### ISSUE TITLE
Feature: Relax the constraints of the PodDNSConfig

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#100622]
#### What would you like to be added:

Relax the constraints of the PodDNSConfig

#### Why is this needed:

The limit of the number of DNS search paths and length of the DNS search list has been removed from libc.
xref: https://github.com/kubernetes/kubernetes/issues/100582

#### Implementation plan
- [ ] Confirm various DNS resolvers
  - [x] `glibc 2.17-323`
  - [x] `glibc 2.28`
  - [x] `musl 1.22`
  - [x] `pure go 1.10 resolver`
  - [x] `pure go 1.16 resolver`
- [ ] 1.22: Prepare to relax the constraints of the PodDNSConfig - https://github.com/kubernetes/kubernetes/pull/100583
- [ ] 1.23: Relax the constraints unconditionally

**Comment by gjkim42** [comment]
The issue will be handled by https://github.com/kubernetes/enhancements/issues/2595

/close
