### ISSUE TITLE
[Umbrella] Fix KEP link

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#101008]
``` 
grep -nr '/enhancements/keps/' * | grep -v '^vendor' | grep -v '/README.md' | grep -v '.json' | grep -v '.pb.go' | grep -v '.proto' | grep -v 'generated'
```

- [ ] OWNERS_ALIASES:581:  # conformance aliases https://git.k8s.io/enhancements/keps/sig-architecture/20190412-conformance-behaviors.md
#101009
- [x] pkg/apis/core/types.go:2835:	// More info: https://git.k8s.io/enhancements/keps/sig-network/0007-pod-ready%2B%2B.md
~#100996~ #99391
- [x] pkg/kubelet/pod/mirror_client.go:85:	// See http://git.k8s.io/enhancements/keps/sig-auth/20190916-noderestriction-pods.md
#101011
- [x] pkg/kubelet/config/flags.go:92:	fs.MarkDeprecated("redirect-container-streaming", "Container streaming redirection has been removed from the kubelet as of v1.20, and this flag will be removed in v1.22. For more details, see http://git.k8s.io/enhancements/keps/sig-node/20191205-container-streaming-requests.md")
#101037
- [x] staging/src/k8s.io/api/core/v1/types.go:3122:	// More info: https://git.k8s.io/enhancements/keps/sig-network/0007-pod-ready%2B%2B.md
#99391
- [x] staging/src/k8s.io/api/core/v1/types.go:3129:	// More info: https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md
~#101014~ #99391
- [x] staging/src/k8s.io/api/node/v1beta1/types.go:36:// https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md
#99391
- [x] staging/src/k8s.io/api/node/v1alpha1/types.go:34:// https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md
#99391

```
grep -nr 'github.com/kubernetes/enhancements/' * | grep -v '^vendor' | grep -v '/README.md' | grep -v '/issues/' | grep -v '/pull/'  | grep -v '.json' | grep -v '.pb.go' | grep -v '.proto' | grep -v 'generated'
```

- [x] CHANGELOG/CHANGELOG-1.8.md:1434:[scalability validation report]: https://github.com/kubernetes/enhancements/tree/master/release-1.8/scalability_validation_report.md
#102860
- [x] CHANGELOG/CHANGELOG-1.14.md:943:kubernetes/enhancements: [kep](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/0029-20180918-kubeadm-phases-beta.md)
~#101140~ #102860
- [x] pkg/ssh/ssh.go:53: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] pkg/volume/util/metrics.go:41: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go:27: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/legacy-cloud-providers/gce/token_source.go:46: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/endpoints/filters/metrics.go:31: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:57: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go:29: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/storage/value/metrics.go:36: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/metrics.go:36: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/storage/cacher/metrics.go:26: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/audit/metrics.go:35: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [x] staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go:38: * ALPHA stability level https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes)
#101046
- [ ] test/conformance/testdata/ineligible_endpoints.yaml:108:  link: https://github.com/kubernetes/enhancements/blob/f16c4c7f1c9e28a3cc4bb4d0e6503efea2ae7987/keps/sig-api-machinery/20190228-priority-and-fairness.md
#101138
- [ ] test/conformance/testdata/ineligible_endpoints.yaml:111:  link: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md
#101138

Some needs to be regenerated `make update`

**Comment by KofClubs** [comment]
/assign
I shall fix `staging/src/k8s.io/api/core/v1/types.go`.

**Comment by lojies** [comment]
/assign
i'm working in `pkg/kubelet/pod/mirror_client.go`

**Comment by ThinkMo** [comment]
pkg/kubelet/config/flags.go
staging/src/k8s.io/api/node/v1beta1/types.go
staging/src/k8s.io/api/node/v1alpha1/types.go

/assign

**Comment by ThinkMo** [comment]
> > pkg/kubelet/config/flags.go
> > staging/src/k8s.io/api/node/v1beta1/types.go
> > staging/src/k8s.io/api/node/v1alpha1/types.go
> > /assign
> 
> i have create a pr for
> `staging/src/k8s.io/api/node/v1beta1/types.go`
> `staging/src/k8s.io/api/node/v1alpha1/types.go`

i see #101018, you need  ```make update```

**Comment by BodilessSleeper** [comment]
/assign
fixing pkg/kubelet/config/flags.go

**Comment by youhonglian** [comment]
/assign
test/conformance/testdata/ineligible_endpoints.yaml

**Comment by learner0810** [comment]
/assign
CHANGELOG/CHANGELOG-1.8.md:1434

**Comment by david99world** [comment]
/assign
CHANGELOG/CHANGELOG-1.19.md@1274

**Comment by david99world** [comment]
/assign
CHANGELOG/CHANGELOG-1.14.md:943

**Comment by zhanghe9702** [comment]
/assign 
test/conformance/testdata/ineligible_endpoints.yaml:108,111

**Comment by youhonglian** [comment]
> /assign
> test/conformance/testdata/ineligible_endpoints.yaml:108,111

Sorry, already assigned

**Comment by niulechuan** [comment]
/assign
i will take pkg/apis/core/types.go

**Comment by wangyysde** [comment]
/assign
staging/src/k8s.io/api/core/v1/types.go:
staging/src/k8s.io/api/core/v1/types.go

**Comment by pacoxu** [comment]
#101011 \ #101037 \ #99391 is merged. Most KEP links are fixed. You may scan it again.
#99391 fixed most of them.

**Comment by tech-geek29** [comment]
/assign

I will work on `CHANGELOG/CHANGELOG-1.8.md:1434:[scalability validation report]`
