### ISSUE TITLE
Remove usage of deprecated klog flags from Kubernetes Org repos

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#106050]
Klog specific flags are deprecated as part of https://github.com/kubernetes/enhancements/issues/2845

All references to deprecated flags in k8s codebase should be removed or migrated to go-runner. This issue will track the work related on it.

What needs to be done:
* Check all occurrences of deprecated flag names and verify if they are affected
  * Affected cases are those where this flag is passed to K8s binary using component-base binary (kube-apiserver, kube-scheduler, kube-controller-manager, kube-proxy, etc)
* Propose reasonable migration path depending on flag used
  * --log-file should use go-runner 
  ...
* Apply migration in file  

List of files to be migrated based on [search](https://cs.k8s.io/?q=%22log-dir%7Clog-file%7Cone-output%7Cstderrthreshold%7Clog-file-max-size%7Cskip-log-headers%7Cadd-dir-header%7Cskip-headers%7Clog-backtrace-at%22&i=nope&files=&excludeFiles=%5C.md%24%7C.*vendor%2F&repos=kubernetes-client/.github,kubernetes-client/c,kubernetes-client/csharp,kubernetes-client/gen,kubernetes-client/go,kubernetes-client/go-base,kubernetes-client/haskell,kubernetes-client/java,kubernetes-client/javascript,kubernetes-client/perl,kubernetes-client/python,kubernetes-client/python-base,kubernetes-client/ruby,kubernetes-csi/.github,kubernetes-csi/cluster-driver-registrar,kubernetes-csi/csi-driver-host-path,kubernetes-csi/csi-driver-image-populator,kubernetes-csi/csi-driver-iscsi,kubernetes-csi/csi-driver-nfs,kubernetes-csi/csi-driver-nvmf,kubernetes-csi/csi-driver-smb,kubernetes-csi/csi-lib-fc,kubernetes-csi/csi-lib-iscsi,kubernetes-csi/csi-lib-utils,kubernetes-csi/csi-proxy,kubernetes-csi/csi-release-tools,kubernetes-csi/csi-test,kubernetes-csi/docs,kubernetes-csi/driver-registrar,kubernetes-csi/external-attacher,kubernetes-csi/external-health-monitor,kubernetes-csi/external-provisioner,kubernetes-csi/external-resizer,kubernetes-csi/external-snapshotter,kubernetes-csi/kubernetes-csi.github.io,kubernetes-csi/lib-volume-populator,kubernetes-csi/livenessprobe,kubernetes-csi/node-driver-registrar,kubernetes-csi/volume-data-source-validator,kubernetes-sigs/alibaba-cloud-csi-driver,kubernetes-sigs/apiserver-builder-alpha,kubernetes-sigs/apiserver-network-proxy,kubernetes-sigs/application,kubernetes-sigs/aws-ebs-csi-driver,kubernetes-sigs/aws-efs-csi-driver,kubernetes-sigs/aws-encryption-provider,kubernetes-sigs/aws-fsx-csi-driver,kubernetes-sigs/aws-iam-authenticator,kubernetes-sigs/aws-load-balancer-controller,kubernetes-sigs/azuredisk-csi-driver,kubernetes-sigs/azurefile-csi-driver,kubernetes-sigs/blob-csi-driver,kubernetes-sigs/boskos,kubernetes-sigs/cli-experimental,kubernetes-sigs/cli-utils,kubernetes-sigs/clientgofix,kubernetes-sigs/cloud-provider-azure,kubernetes-sigs/cloud-provider-baiducloud,kubernetes-sigs/cloud-provider-huaweicloud,kubernetes-sigs/cluster-addons,kubernetes-sigs/cluster-api,kubernetes-sigs/cluster-api-provider-aws,kubernetes-sigs/cluster-api-provider-azure,kubernetes-sigs/cluster-api-provider-digitalocean,kubernetes-sigs/cluster-api-provider-gcp,kubernetes-sigs/cluster-api-provider-ibmcloud,kubernetes-sigs/cluster-api-provider-openstack,kubernetes-sigs/cluster-api-provider-packet,kubernetes-sigs/cluster-api-provider-vsphere,kubernetes-sigs/cluster-capacity,kubernetes-sigs/cluster-proportional-autoscaler,kubernetes-sigs/cluster-proportional-vertical-autoscaler,kubernetes-sigs/contributor-playground,kubernetes-sigs/controller-runtime,kubernetes-sigs/controller-tools,kubernetes-sigs/cri-tools,kubernetes-sigs/custom-metrics-apiserver,kubernetes-sigs/dashboard-metrics-scraper,kubernetes-sigs/descheduler,kubernetes-sigs/discuss-theme,kubernetes-sigs/downloadkubernetes,kubernetes-sigs/etcdadm,kubernetes-sigs/execution-hook,kubernetes-sigs/external-dns,kubernetes-sigs/gateway-api,kubernetes-sigs/gcp-compute-persistent-disk-csi-driver,kubernetes-sigs/gcp-filestore-csi-driver,kubernetes-sigs/gluster-block-external-provisioner,kubernetes-sigs/gluster-file-external-provisioner,kubernetes-sigs/go-open-service-broker-client,kubernetes-sigs/image-builder,kubernetes-sigs/ingress-controller-conformance,kubernetes-sigs/instrumentation-tools,kubernetes-sigs/ip-masq-agent,kubernetes-sigs/iptables-wrappers,kubernetes-sigs/kind,kubernetes-sigs/krew,kubernetes-sigs/krew-index,kubernetes-sigs/kube-batch,kubernetes-sigs/kube-storage-version-migrator,kubernetes-sigs/kubebuilder,kubernetes-sigs/kubebuilder-declarative-pattern,kubernetes-sigs/kubebuilder-release-tools,kubernetes-sigs/kubefed,kubernetes-sigs/kubespray,kubernetes-sigs/kui,kubernetes-sigs/kustomize,kubernetes-sigs/legacyflag,kubernetes-sigs/lwkd,kubernetes-sigs/mdtoc,kubernetes-sigs/metrics-server,kubernetes-sigs/minibroker,kubernetes-sigs/multi-tenancy,kubernetes-sigs/nfs-ganesha-server-and-external-provisioner,kubernetes-sigs/nfs-subdir-external-provisioner,kubernetes-sigs/node-feature-discovery,kubernetes-sigs/node-feature-discovery-operator,kubernetes-sigs/poseidon,kubernetes-sigs/prometheus-adapter,kubernetes-sigs/promo-tools,kubernetes-sigs/reference-docs,kubernetes-sigs/release-notes,kubernetes-sigs/scheduler-plugins,kubernetes-sigs/secrets-store-csi-driver,kubernetes-sigs/security-profiles-operator,kubernetes-sigs/service-catalog,kubernetes-sigs/sig-storage-lib-external-provisioner,kubernetes-sigs/sig-storage-local-static-provisioner,kubernetes-sigs/sig-usability,kubernetes-sigs/sig-windows-samples,kubernetes-sigs/sig-windows-tools,kubernetes-sigs/slack-infra,kubernetes-sigs/structured-merge-diff,kubernetes-sigs/vsphere-csi-driver,kubernetes-sigs/wg-policy-prototypes,kubernetes-sigs/windows-gmsa,kubernetes-sigs/windows-testing,kubernetes-sigs/yaml,kubernetes-sigs/zeitgeist,kubernetes/.github,kubernetes/api,kubernetes/apiextensions-apiserver,kubernetes/apimachinery,kubernetes/autoscaler,kubernetes/cli-runtime,kubernetes/client-go,kubernetes/cloud-provider,kubernetes/cloud-provider-alibaba-cloud,kubernetes/cloud-provider-aws,kubernetes/cloud-provider-openstack,kubernetes/cloud-provider-sample,kubernetes/cloud-provider-vsphere,kubernetes/cluster-bootstrap,kubernetes/code-generator,kubernetes/committee-security-response,kubernetes/community,kubernetes/component-helpers,kubernetes/contributor-site,kubernetes/controller-manager,kubernetes/cri-api,kubernetes/csi-api,kubernetes/csi-translation-lib,kubernetes/dashboard,kubernetes/dns,kubernetes/enhancements,kubernetes/examples,kubernetes/funding,kubernetes/gengo,kubernetes/git-sync,kubernetes/ingress-gce,kubernetes/ingress-nginx,kubernetes/k8s.io,kubernetes/kompose,kubernetes/kops,kubernetes/kube-aggregator,kubernetes/kube-controller-manager,kubernetes/kube-openapi,kubernetes/kube-proxy,kubernetes/kube-scheduler,kubernetes/kube-state-metrics,kubernetes/kubeadm,kubernetes/kubectl,kubernetes/kubelet,kubernetes/kubernetes,kubernetes/kubernetes-template-project,kubernetes/legacy-cloud-providers,kubernetes/metrics,kubernetes/minikube,kubernetes/mount-utils,kubernetes/node-api,kubernetes/node-problem-detector,kubernetes/noderesourcetopology-api,kubernetes/org,kubernetes/perf-tests,kubernetes/pod-security-admission,kubernetes/publishing-bot,kubernetes/release,kubernetes/repo-infra,kubernetes/sample-apiserver,kubernetes/sample-cli-plugin,kubernetes/sample-controller,kubernetes/sig-release,kubernetes/sig-security,kubernetes/sig-testing,kubernetes/steering,kubernetes/system-validators,kubernetes/test-infra,kubernetes/utils,kubernetes/website) logtostderr and alsologtostderr are not included in search as they no longer need to be set with klogv2

kubernetes/kops
* [x] https://github.com/kubernetes/kops/issues/12663

kubernetes/kubernetes
* [x] [cluster/gce/gci/configure-helper.sh](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/gci/configure-helper.sh) - konnectivity-server is not affected as it uses klog directly
* [x] [cluster/gce/gci/configure-kubeapiserver.sh](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/gci/configure-kubeapiserver.sh) - unrelated
* [x] [cluster/gce/manifests/cluster-autoscaler.manifest](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/manifests/cluster-autoscaler.manifest) - cluster autoscaler is not affected as it uses klog directly
* [x] [cluster/gce/manifests/kube-apiserver.manifest](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/manifests/kube-apiserver.manifest) - uses go-runner
* [x] [cluster/gce/manifests/kube-controller-manager.manifest](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/manifests/kube-controller-manager.manifest) - uses go runner
* [x] [cluster/gce/manifests/kube-scheduler.manifest](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/manifests/kube-scheduler.manifest) - uses go runner
* [x] [cluster/gce/util.sh](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/util.sh) - https://github.com/kubernetes/kubernetes/issues/106101
* [x] [cluster/gce/windows/k8s-node-setup.psm1](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/gce/windows/k8s-node-setup.psm1) - containerd is not affected
* [x] [cluster/log-dump/logexporter-daemonset.yaml](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cluster/log-dump/logexporter-daemonset.yaml) - logexporter is not affected
* [x] [cmd/kubeadm/app/apis/kubeadm/validation/validation.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cmd/kubeadm/app/apis/kubeadm/validation/validation.go) - unrelated
* [x] [cmd/kubeadm/app/kubeadm.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/cmd/kubeadm/app/kubeadm.go) - mark hidden
* [x] [pkg/volume/glusterfs/glusterfs.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/pkg/volume/glusterfs/glusterfs.go) - glusterfs is unaffected
* [x] [staging/src/k8s.io/apiserver/pkg/server/options/audit.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/staging/src/k8s.io/apiserver/pkg/server/options/audit.go) - comment
* [x] [staging/src/k8s.io/component-base/cli/globalflag/globalflags_test.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/staging/src/k8s.io/component-base/cli/globalflag/globalflags_test.go) - flag tests.
* [x] [staging/src/k8s.io/component-base/logs/logs.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/staging/src/k8s.io/component-base/logs/logs.go) - flag definition
* [x] [staging/src/k8s.io/component-base/logs/options_test.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/staging/src/k8s.io/component-base/logs/options_test.go) - flag tests
* [x] [test/e2e_node/node_problem_detector_linux.go](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/test/e2e_node/node_problem_detector_linux.go) - unrelated
* [x] [test/kubemark/resources/hollow-node_template.yaml](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/test/kubemark/resources/hollow-node_template.yaml) - https://github.com/kubernetes/kubernetes/issues/106103
* [x] [test/kubemark/resources/start-kubemark-master.sh](https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/test/kubemark/resources/start-kubemark-master.sh) - unrelated

kubernetes/autoscaler
* [x] [charts/cluster-autoscaler/values.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/charts/cluster-autoscaler/values.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-multiple-asgs.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-multiple-asgs.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/bizflycloud/manifest/cluster-autoscaler.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/bizflycloud/manifest/cluster-autoscaler.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/brightbox/examples/config.rb](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/brightbox/examples/config.rb) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/exoscale/examples/cluster-autoscaler-run-on-control-plane.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/exoscale/examples/cluster-autoscaler-run-on-control-plane.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog/klog.go](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog/klog.go) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [cluster-autoscaler/cloudprovider/ionoscloud/examples/cluster-autoscaler-standard.yaml](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/cluster-autoscaler/cloudprovider/ionoscloud/examples/cluster-autoscaler-standard.yaml) - cluster autoscaler is unaffected as it uses klog directly
* [x] [vertical-pod-autoscaler/pkg/admission-controller/Dockerfile](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/vertical-pod-autoscaler/pkg/admission-controller/Dockerfile) - vpa-admission-controller is unaffected as it uses klog directly
* [x] [vertical-pod-autoscaler/pkg/recommender/Dockerfile](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/vertical-pod-autoscaler/pkg/recommender/Dockerfile) - vpa-recommender is unaffected as it uses klog directly
* [x] [vertical-pod-autoscaler/pkg/updater/Dockerfile](https://github.com/kubernetes/autoscaler/blob/c4b56ea56136681e8a8ff654dfcd813c0d459442/vertical-pod-autoscaler/pkg/updater/Dockerfile)  - vpa-updater is unaffected as it uses klog directly

kubernetes/test-infra
* [x] [config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml) - benchmarkunit is unaffected
* [x] [config/jobs/kubernetes/test-infra/test-infra-canaries.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/config/jobs/kubernetes/test-infra/test-infra-canaries.yaml) - benchmarkunit is unaffected
* [x] [config/jobs/kubernetes-sigs/structured-merge-diff/structured-merge-diff-ci.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/config/jobs/kubernetes-sigs/structured-merge-diff/structured-merge-diff-ci.yaml) - benchmarkunit is unaffected
* [x] [config/jobs/kubernetes-sigs/structured-merge-diff/structured-merge-diff-presubmits.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/config/jobs/kubernetes-sigs/structured-merge-diff/structured-merge-diff-presubmits.yaml) - benchmarkunit is unaffected
* [x] [gubernator/view_logs.py](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/gubernator/view_logs.py) - unrelated
* [x] [images/builder/main.go](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/images/builder/main.go) - unrelated 
* [x] [logexporter/cluster/logexporter-daemonset.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/logexporter/cluster/logexporter-daemonset.yaml) - logexporter is unaffected
* [x] [logexporter/cmd/main.go](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/logexporter/cmd/main.go) - unrelated
* [x] [pkg/benchmarkjunit/main.go](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/pkg/benchmarkjunit/main.go) - unrelated flag definiton
* [x] [pkg/benchmarkjunit/prowjob_example.yaml](https://github.com/kubernetes/test-infra/blob/bbbf3af5a092f7d0d2bc3b3feea443d538909a1c/pkg/benchmarkjunit/prowjob_example.yaml) - benchmarkunit is unaffected

kubernetes-sigs/reference-docs
* [x] [gen-compdocs/generators/gen_kube_docs.go](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/gen-compdocs/generators/gen_kube_docs.go) - mark hidden
* [x] [gen-kubectldocs/generators/v1_5/kubectl.yaml](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/gen-kubectldocs/generators/v1_5/kubectl.yaml) - old k8s version
* [x] [gen-kubectldocs/generators/v1_6/kubectl.yaml](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/gen-kubectldocs/generators/v1_6/kubectl.yaml)- old k8s version
* [x] [gen-kubectldocs/generators/v1_7/kubectl.yaml](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/gen-kubectldocs/generators/v1_7/kubectl.yaml) - old k8s version
* [x] [gen-kubectldocs/generators/v1_8/kubectl.yaml](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/gen-kubectldocs/generators/v1_8/kubectl.yaml) - old k8s version
* [x] [kubectl.yaml](https://github.com/kubernetes-sigs/reference-docs/blob/0c18683146785c22292aef91998b5c92f6eda58b/kubectl.yaml)

kubernetes/release
* [x] [cmd/gcbuilder/cmd/root.go](https://github.com/kubernetes/release/blob/179dff8f4f6dfde254508aedbe6eb3c32fa0029f/cmd/gcbuilder/cmd/root.go) - gcbuilder is unaffected
* [x] [cmd/krel/cmd/announce_build.go](https://github.com/kubernetes/release/blob/179dff8f4f6dfde254508aedbe6eb3c32fa0029f/cmd/krel/cmd/announce_build.go) - unrelated
* [x] [images/build/go-runner/go-runner.go](https://github.com/kubernetes/release/blob/179dff8f4f6dfde254508aedbe6eb3c32fa0029f/images/build/go-runner/go-runner.go) - go runner

kubernetes-sigs/apiserver-network-prxoy
* [x] [examples/kubernetes/konnectivity-server.yaml](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/a007c42f6c9d06ff869da5b93c428546658c414e/examples/kubernetes/konnectivity-server.yaml) - konnectivity-server is not affected as it uses klog directly
* [x] [examples/kubernetes/konnectivity-test-client.yaml](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/a007c42f6c9d06ff869da5b93c428546658c414e/examples/kubernetes/konnectivity-test-client.yaml) - konnectivity-server is not affected as it uses klog directly

kubernetes-sigsa/controller-runtime
* [x] [internal/testing/controlplane/testdata/fake-1.19-apiserver.sh](https://github.com/kubernetes-sigs/controller-runtime/blob/c73b143dc50358328b9153329b3b570b1a0e5623/pkg/internal/testing/controlplane/testdata/fake-1.19-apiserver.sh) - old k8s version
* [x] [pkg/internal/testing/controlplane/testdata/fake-1.20-apiserver.sh](https://github.com/kubernetes-sigs/controller-runtime/blob/c73b143dc50358328b9153329b3b570b1a0e5623/pkg/internal/testing/controlplane/testdata/fake-1.20-apiserver.sh) - old k8s version

kubernetes-sigs/node-feature-discovery
* [x] [deployment/components/worker-config/nfd-worker.conf.example](https://github.com/kubernetes-sigs/node-feature-discovery/blob/347b16daeae440999845a22ed0e835125e1003f0/deployment/components/worker-config/nfd-worker.conf.example) - comment
* [x] [deployment/helm/node-feature-discovery/values.yaml](https://github.com/kubernetes-sigs/node-feature-discovery/blob/347b16daeae440999845a22ed0e835125e1003f0/deployment/helm/node-feature-discovery/values.yaml) - comment

kubernetes-sigs/node-feature-discovery-operator
* [x] [build/assets/worker/04_worker_cm.yaml](https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/92c4a2460f01a0f8e2cf852896d854f31ebfee1e/build/assets/worker/04_worker_cm.yaml) - comment
* [x] [config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml](https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/92c4a2460f01a0f8e2cf852896d854f31ebfee1e/config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml) - comment

kubernetes-sigs/service-catalog
* [x] [cmd/svcat/plugin/manifest.go](https://github.com/kubernetes-sigs/service-catalog/blob/03094167e4de72116cdfa246ef33b429db948941/cmd/svcat/plugin/manifest.go) - unrelated
* [x] [pkg/webhookutil/tester/decoder.go](https://github.com/kubernetes-sigs/service-catalog/blob/03094167e4de72116cdfa246ef33b429db948941/pkg/webhookutil/tester/decoder.go) - unrelated

kubernetes/minikube
* [x] [hack/release_notes.sh](https://github.com/kubernetes/minikube/blob/3a17f863ba08ea808b379052a12539213a29a51e/hack/release_notes.sh)  - pullsheet is not affected
* [x] [hack/update_contributions.sh](https://github.com/kubernetes/minikube/blob/3a17f863ba08ea808b379052a12539213a29a51e/hack/update_contributions.sh) - pullsheet is not affected

kubernetes/sig-release
* [x] [releases/release-1.22/release-notes/maps/pr-101449-map.yaml](https://github.com/kubernetes/sig-release/blob/0b151c32a5daa28410dae7175ac41b5ba9cd623d/releases/release-1.22/release-notes/maps/pr-101449-map.yaml) - release notes
* [x] [release-1.22/release-notes/release-notes-draft.json](https://github.com/kubernetes/sig-release/blob/0b151c32a5daa28410dae7175ac41b5ba9cd623d/releases/release-1.22/release-notes/release-notes-draft.json) - release notes

kubernetes-sigs/aws-iam-authenticator
* [x] [hack/changelog.py](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/f58cdd79570346aeb4c9c196b87605c567e5c9a8/hack/changelog.py) - unrelated

kubernetes/cloud-provider-azure
* [x] [tests/kubemark/templates/hollow-node.yaml](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/99678f0fff5b49fdc1fdcaadb50b116777d43d78/tests/kubemark/templates/hollow-node.yaml) - https://github.com/kubernetes/kubernetes/issues/106103

kubernetes-sigs/cluster-addons
* [x] [installer/cmd/installer/flag.go](https://github.com/kubernetes-sigs/cluster-addons/blob/a8622ef8b343e3b511ecc2058c2b15058b481ddb/installer/cmd/installer/flag.go) - mark hidden

kubernetes-sigs/cluster-proportional-autoscaler
* [x] [charts/cluster-proportional-autoscaler/templates/deployment.yaml](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/84a3b6968fd47e25a9ba5039ee29b47219b7e9c4/charts/cluster-proportional-autoscaler/templates/deployment.yaml) - cluster-proportional-autoscaler is not affected as it uses glog

kubernetes-sigs/descheduler
* [x] [cmd/descheduler/app/options/options.go](https://github.com/kubernetes-sigs/descheduler/blob/50f9513cbb3a0eee4e6134ba09aaa7e9a4a09add/cmd/descheduler/app/options/options.go) - flag definition

kubernetes-sigs/kube-batch
* [x] [cmd/kube-batch/main.go](https://github.com/kubernetes-sigs/kube-batch/blob/86b2ba217ad76340221fdc9b4ec16f3209dbff7e/cmd/kube-batch/main.go) - flag definition

kubernetes-sigs/kubefed
* [x] [scripts/sync-up-helm-chart.sh](https://github.com/kubernetes-sigs/kubefed/blob/224fe9501b0709fb2999451339d7e756a8a94e9f/scripts/sync-up-helm-chart.sh) - https://github.com/kubernetes-sigs/kubefed/issues/1470

kubernetes-sigs/multi-tenacy
* [x] [incubator/virtualcluster/cmd/manager/main.go](https://github.com/kubernetes-sigs/multi-tenancy/blob/5fa490746bf88e611248bf4b65a01a9365193ea9/incubator/virtualcluster/cmd/manager/main.go) - flag definition

kubernetes-sigs/release-notes
* [x] [src/assets/release-notes-1.22.0-beta.0.json](https://github.com/kubernetes-sigs/release-notes/blob/e87801f40c7435fee21203587589531fa185d210/src/assets/release-notes-1.22.0-beta.0.json) - release notes

kubernetes/cloud-provider-aws
* [x] [hack/changelog.py](https://github.com/kubernetes/cloud-provider-aws/blob/59ae724ba8a09ca5b6266a8452e937e3e99a6953/hack/changelog.py) - unrelated

**Comment by serathius** [comment]
@pohly One problem with proposing deprecating klog flags in component-base is that there are multiple components that don't use go-runner. Kubernetes core components already have go-runner available and are using them default manifests. For components like cluster-autoscaler and kube-proxy we might need to do additional work.

**Comment by pohly** [comment]
From the description:

> Affected cases are those where this flag is passed to K8s binary using component-base binary (kube-apiserver, kube-scheduler, kube-controller-manager, kube-proxy, etc)

This "using component-base" needs to be removed. We are deprecating klog in *all* of Kubernetes, not just in some binaries.

**Comment by serathius** [comment]
We are not yet deprecating klog, as we don't have replacement ready yet. For now we are deprecating klog specific features that are enabled via it's flags. We need to avoid wrong messaging to prevent confusion. 

We are deprecating klog specific flags in Kubernetes Org projects, but should not affect:
* projects just using klog

**Comment by pohly** [comment]
> We are not yet deprecating klog

True. I simplified too much. The earlier PR described it correctly ("All klog flags except for `-v` and `-vmodule` are deprecated.").

**Comment by serathius** [comment]
All points on the list were addressed.
