### ISSUE TITLE
CRD Validation Expression Language to beta

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#106465]
### What would you like to be added?

Promote Expression Language validation for CRD to beta.

KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language

Expression Language validation for CRD is available in alpha in 1.23 release(https://github.com/kubernetes/kubernetes/issues/105745). In order to promote it to beta, the required work needs to be done:
- [ ] Resolve topic of what support we should provide for access to the previous versions of object (ie. 'oldSelf' feature)
- [ ] x-kubernetes-int-or-string is upgraded to use a union type of just int or string, not a dynamic type (CEL go support is planned in lates 2021)
- [ ] CEL numeric comparison issue is resolved (e.g. ability to compare ints to doubles) (https://github.com/google/cel-spec/issues/54)
- [ ] Understanding of upper bounds of CPU/memory usage and appropriate limits set to prevent abuse.
- [ ] Build-in macro/function library is comprehensive and stable (any changes to this will be a breaking change)
- [ ] [Reduce noise of invalid data messages reported from cel.UnstructuredToVal](https://github.com/kubernetes/kubernetes/issues/106440)
- [ ] [Benchmark cel.UnstructuredToVal and optimize away repeated wrapper object construction](https://github.com/kubernetes/kubernetes/issues/106438)

### Why is this needed?

Validating CRD with webhooks is painful, it could be greatly improved by adding expression language validation.
This issue lists the required work before graduating the feature to beta.

/sig api-machinery
/wg api-expression

cc @jpbetz
