### ISSUE TITLE
[Umbrella Issue] Integration framework: reduce goroutine leakage

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#108483]
The integration framework runs an apiserver and sometimes other components before each test execution, however, the shutdown is not clean and is leaving a lot of goroutines orphan that keep accumulation between different runs.

Some orphan goroutines are connections to etcd, and since the etcd process is shared for all test, we don't know if this can cause contention and flakiness on the job.

We are logging the number of goroutines leaked per test binary execution,  it is important if we can reduce them and more important we don't regress and this number keeps growing. This issue will record the state as today for reference:

```
grep "number of goroutine" junit_20220303-074418.stdout  | sed -r 's/.*test\/(.*),.*after ([[:digit:]]+).*/\1:\t\2/' | sort -k 2,2 -n
integration/dryrun":	201
integration/tls":	202
integration/scale":	228
integration/events":	250
integration/storageversion":	682
integration/serving":	801
integration/apiserver/podlogs":	987
integration/configmap":	1007
integration/defaulttolerationseconds":	1007
integration/network":	1007
integration/objectmeta":	1007
integration/secrets":	1007
integration/storageclasses":	1007
integration/ttlcontroller":	1007
integration/cronjob":	1024
integration/kubelet":	1219
integration/examples":	1282
integration/apiserver/tracing":	1541
integration/disruption":	1751
integration/namespace":	2005
integration/endpoints":	2009
integration/apiserver/admissionwebhook":	2897
integration/garbagecollector":	2972
integration/apimachinery":	2999
integration/evictions":	3014
integration/quota":	3029
integration/apiserver/flowcontrol":	3101
integration/certificates":	3634
integration/serviceaccount":	3995
integration/node":	4072
integration/client":	4158
integration/statefulset":	4212
integration/etcd":	4501
integration/apiserver/certreload":	4879
integration/metrics":	4991
integration/pods":	5987
integration/endpointslice":	7010
integration/service":	9084
integration/dualstack":	13975
integration/replicationcontroller":	14109
integration/deployment":	14241
integration/volumescheduling":	14290
integration/volume":	15019
integration/daemonset":	16076
integration/replicaset":	19133
integration/job":	21023
integration/apiserver":	21076
integration/auth":	28066
integration/controlplane":	30394
integration/apiserver/apply":	39148
integration/scheduler":	68597

```

**Comment by aojea** [comment]
hmm, not doing better https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/109031/pull-kubernetes-integration/1508893646152273920/

```
grep "number of goroutine" junit_20220329-200738.stdout  | sed -r 's/.*test\/(.*),.*after ([[:digit:]]+).*/\1:\t\2/' | sort -k 2,2 -n
integration/controlplane/audit":	204
integration/events":	210
integration/scale":	229
integration/dryrun":	232
integration/tls":	244
integration/storageversion":	673
integration/serving":	758
integration/controlplane/transformation":	841
integration/apiserver/podlogs":	1003
integration/configmap":	1023
integration/defaulttolerationseconds":	1023
integration/network":	1023
integration/objectmeta":	1023
integration/secrets":	1023
integration/storageclasses":	1023
integration/ttlcontroller":	1023
integration/cronjob":	1040
integration/kubelet":	1294
integration/examples":	1329
integration/apiserver/tracing":	1570
integration/disruption":	1900
integration/namespace":	2038
integration/endpoints":	2042
integration/apimachinery":	3049
integration/evictions":	3062
integration/quota":	3079
integration/garbagecollector":	3080
integration/apiserver/admissionwebhook":	3147
integration/apiserver/flowcontrol":	3151
integration/apiserver/openapi":	3242
integration/certificates":	3654
integration/serviceaccount":	4062
integration/node":	4139
integration/client":	4168
integration/statefulset":	4312
integration/etcd":	4568
integration/apiserver/certreload":	4963
integration/metrics":	5075
integration/pods":	6088
integration/endpointslice":	7128
integration/service":	10337
integration/volumescheduling":	13285
integration/dualstack":	14212
integration/replicationcontroller":	14346
integration/deployment":	14478
integration/volume":	15273
integration/daemonset":	16347
integration/apiserver":	18484
integration/replicaset":	19455
integration/job":	23405
integration/auth":	28633
integration/controlplane":	29746
integration/apiserver/apply":	39796
integration/scheduler":	78957
```

**Comment by kerthcet** [comment]
I'll take the scheduler part for a deep investigate.

**Comment by aojea** [comment]
### Current status:

For people that want to get access to the stack traces, just apply this patch, so the framework will dump the output of the goroutines after each execution:

```
diff --git a/test/integration/framework/etcd.go b/test/integration/framework/etcd.go
index a0128352ed6..39d3c2ab186 100644
--- a/test/integration/framework/etcd.go
+++ b/test/integration/framework/etcd.go
@@ -196,6 +196,9 @@ func EtcdMain(tests func() int) {
        }
        after := runtime.NumGoroutine()
        klog.Infof("unexpected number of goroutines: before: %d after %d", before, after)
+       buf := make([]byte, 1<<16)
+       runtime.Stack(buf, true)
+       fmt.Printf("%s", buf)
        os.Exit(result)
 }
```

- [x] Apiserver was shutting down the listener before the hooks could finish, hence the controllers couldn't shutdown gracefully since there was no http server https://github.com/kubernetes/kubernetes/pull/108033
- [ ] The storage cacher doesn't differentiate between not read and stopping https://github.com/kubernetes/kubernetes/pull/108414 - Missing integration test reproducing the issue, only reproduced with unit tests
- [ ] admission plugins can't shutdown gracefully - https://github.com/kubernetes/kubernetes/issues/108388 - there is a PR addressing

However, most of the contributions to goroutines leaks are grpc connections that are related to the storage cleanup, there is also a TODO in the code
https://github.com/kubernetes/kubernetes/blob/c6153a93d0528a3dc6be9dedc2602f140081688d/cmd/kube-apiserver/app/testing/testserver.go#L106-L111

and an open issue https://github.com/kubernetes/kubernetes/issues/49489

I've also tried to reduce the number of connections between storage and etcd, right now, each Storage creates an independent conection to etcd, but sharing the etcd client doesn't work https://github.com/kubernetes/kubernetes/pull/105826

**Comment by wojtek-t** [comment]
I think I made some progress with it.
I was playing with ttlcontroller test (as it's fairly simple one for the playground and I'm familiar with it, but symptoms in many tests are exactly the same)

In https://github.com/kubernetes/kubernetes/pull/109284 I actually managed to reduce amount of leaked goroutines from 1023 to 85. It's not mergable in this state, but it clearly shows that destroy functions for storage are not called in integration tests.
I will try to dig deeper into those and clean this up - but I think the above clearly shows where the problem is.

@liggitt - FYI ^^

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/109292 is out for review and it's making most of the job here

There are still leftovers, but those are mostly oneof's here and there - we should address them independently.

**Comment by wojtek-t** [comment]
And a bit more longerterm cleaner approach is in https://github.com/kubernetes/kubernetes/pull/109303

**Comment by wojtek-t** [comment]
> integration/ttlcontroller":	1007

With https://github.com/kubernetes/kubernetes/pull/109854 we're down to 14.
I admit that this is one of the simplest tests, but apiserver shutdown is pretty clean once that PR merges.

**Comment by aojea** [comment]
@wojtek-t a leftover for the storage cleanup in

https://github.com/kubernetes/kubernetes/blob/d0832102a7017e83bf47a5137b690e52f19c267c/staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing/testserver.go#L82-L93

**Comment by wojtek-t** [comment]
Re comment above - yeah, I'm aware, we need to clean it up.

FTR:
```
> grep "number of goroutine" junit_20220510-181507.stdout  | sed -r 's/.*test\/(.*),.*after ([[:digit:]]+).*/\1:\t\2/' | sort -k 2,2 -n
integration/configmap":	14
integration/defaulttolerationseconds":	14
integration/network":	14
integration/secrets":	14
integration/storageclasses":	14
integration/ttlcontroller":	14
integration/scheduler/extender":	24
integration/namespace":	29
integration/cronjob":	31
integration/endpoints":	31
integration/scheduler/taint":	34
integration/apimachinery":	36
integration/serviceaccount":	47
integration/evictions":	49
integration/metrics":	58
integration/quota":	66
integration/pods":	69
integration/node":	124
integration/apiserver/flowcontrol":	137
integration/scheduler/scoring":	145
integration/dualstack":	149
integration/volume":	236
integration/volumescheduling":	246
integration/scheduler/preemption":	265
integration/statefulset":	297
integration/daemonset":	308
integration/replicationcontroller":	311
integration/scheduler/filters":	364
integration/job":	383
integration/scheduler":	401
integration/replicaset":	410
integration/scale":	418
integration/tls":	418
integration/controlplane/audit":	419
integration/dryrun":	424
integration/events":	425
integration/deployment":	443
integration/apiserver/openapi":	456
integration/service":	539
integration/scheduler/plugins":	623
integration/pvc":	828
integration/serving":	835
integration/storageversion":	1074
integration/apiserver/podlogs":	1238
integration/apiserver/certreload":	1325
integration/controlplane/transformation":	1337
integration/examples":	1441
integration/apiserver/tracing":	1498
integration/auth":	1584
integration/apiserver":	1827
integration/apiserver/apply":	1904
integration/kubelet":	2217
integration/disruption":	2326
integration/controlplane":	2618
integration/etcd":	2671
integration/garbagecollector":	3093
integration/certificates":	3158
integration/apiserver/admissionwebhook":	3189
integration/client":	4426
```

**Comment by aojea** [comment]
awesome, we are several order  of magnitud better

**Comment by wojtek-t** [comment]
Looking further into it, in different tests I'm seeing a lot of goroutines with the top of the stacktrace like this:
```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*ready).wait(0xc001af1500)
```

https://github.com/kubernetes/kubernetes/pull/108414 should hopefully address those once it merges...
@aojea ^^

**Comment by wojtek-t** [comment]
OK - I think I have now the biggest thing contributing factor to the remaining tests, although I don't yet fully understand it and don't know how exactly to fix it.

The main problem is basically that TestServer is not finishing its shutdown:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/testing/testserver.go#L114

So what exactly is happening is:
- we run TryDown the TestServer there: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/testing/testserver.go#L114
- this underneath is triggering run of PreShutdown hooks:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L517
- in the meantime ShutdownInitated signal is signaled:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L457
- as part of running preshutdown hooks, the bootstrap controller is stopping endpoint reconciler:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/controller.go#L225
- and then as part of doReconcile, the GET requests hangs forever: https://github.com/kubernetes/kubernetes/blob/c50579afb1c3fbb2b83007bba6e8d285436d5dc9/pkg/controlplane/reconcilers/lease.go#L187

By adding time.Sleep(5s) (didn't try smaller values TBH) before the ShutdownInitiated is signalled, the TestServer is shutting clearly:
https://github.com/kubernetes/kubernetes/pull/109284/files#diff-68eb390e148644c38174960be4d103c0e377e71eb540aa8c395f7d2278363973R461

Obviously that's not a solution, but I'm wondering why the GET request mentioned above is hanging forever when ShutdownInitiate is signaled and what we can do with this.
@aojea - thoughts?


[The easiest repro is to run:
```
make test-integration WHAT='k8s.io/kubernetes/test/integration/service -run=Test_UpgradeService'
```

Adding this sleep basically reduces the number of leaked routines from O(1000) to O(20).]

**Comment by aojea** [comment]
I thought that the reconciler hangs because of https://github.com/kubernetes/kubernetes/issues/108483#issuecomment-1123611572

**Comment by wojtek-t** [comment]
> I thought that the reconciler hangs because of https://github.com/kubernetes/kubernetes/issues/108483#issuecomment-1123611572

Not in this place - here the usual GET request hangs - I will keep looking over the next days.

**Comment by wojtek-t** [comment]
> why the request actually hangs forever instead of finishing with some error...

OK - I understand now and the above isn't really true.
The request wasn't really hanging forever. What was happening is that it was being rejected by the WaitGroup handler:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go#L55
and retried by the client-go internals...

So I guess from that perspective setting non-zero ShutdownDelayDuration actually makes sense..
@aojea @p0lyn0mial - thoughts? ^^

**Comment by p0lyn0mial** [comment]
mhm, not sure why setting `ShutdownDelayDuration` should help. 

In general, the server shout stop listening and the HTTP std library should instruct the client's stack to tear down the underlying TCP connection. 

In that case, the client-go should fail on dialing and stop retrying releasing the server.

 thoughts?

**Comment by wojtek-t** [comment]
> mhm, not sure why setting ShutdownDelayDuration should help.

It's that with ShutdownDelay, the "stopCh" is signaling PreShutdown hooks (that still want to do some work, including API calls) and if we immediately start rejecting that, they will not be able to do that work...

**Comment by wojtek-t** [comment]
Discussed a bit more offline - I'm going to investigate blocking closing the waitGroup filter on preshutdown hooks. Will try to send a PR in upcoming days.

**Comment by wojtek-t** [comment]
We're getting there - this is where we are now:
```
integration/apiserver/tracing":	8
integration/network":	8
integration/scheduler/preemption":	9
integration/events":	10
integration/job":	12
integration/scheduler/taint":	14
integration/service":	15
integration/evictions":	16
integration/apimachinery":	18
integration/apiserver/openapi":	18
integration/client":	18
integration/certificates":	21
integration/storageversion":	21
integration/serviceaccount":	23
integration/controlplane/transformation":	27
integration/quota":	40
integration/volumescheduling":	43
integration/node":	44
integration/garbagecollector":	45
integration/serving":	62
integration/volume":	71
integration/controlplane":	104
integration/apiserver/flowcontrol":	119
integration/disruption":	134
integration/apiserver":	199
integration/auth":	232
```

I have a bit more in my local branch to upstream, but I need to clean them up and may not have time in the next week or so.

**Comment by aojea** [comment]
where are we standing today?

**Comment by wojtek-t** [comment]
Getting close:
```
wojtekt@wojtekt-l:~/Downloads$ grep "number of goroutine" junit_20220719-054236.stdout  | sed -r 's/.*test\/(.*),.*after ([[:digit:]]+).*/\1:\t\2/' | sort -k 2,2 -n
integration/apiserver/tracing":	8
integration/auth":	12
integration/service":	15
integration/client":	17
integration/serviceaccount":	23
integration/apiserver":	25
integration/controlplane/transformation":	27
integration/serving":	62
```

**Comment by wojtek-t** [comment]
A bit more coming soon.

**Comment by wojtek-t** [comment]
This is where we are now:
```
wojtekt@wojtekt-l:~/Downloads$ grep "number of goroutine" junit_20220720-044401.stdout  | sed -r 's/.*test\/(.*),.*after ([[:digit:]]+).*/\1:\t\2/' | sort -k 2,2 -n
integration/apiserver/tracing":	8
integration/controlplane/transformation":	9
integration/service":	15
integration/serviceaccount":	23
integration/serving":	62
```

I understand some of them (though fixing is potentially non-trivial) and need to understand the others (in particular serving).
And we should prevent regressions by failing if we have more leaking goroutines - will be looking at that over upcoming weeks.

**Comment by wojtek-t** [comment]
OK - so here is where we are (with the current check set to not leaking more than 4 goroutines):

```
integration/apiserver/tracing":	8
integration/serving":	8
integration/controlplane/transformation":	9
```

Comparing to the first comment in this issue - that looks like a significant improvement :)

Here is the summary of I think the remaining goroutines in the above files:

- [ ] integration/apiserver/tracing:  
   The goroutines are coming from otel exporter (in particular grpc layer). It seems that something is not closed, although required digging deeper into otel exporter.
- [ ] integration/serving: 
   The goroutines are coming from the failure case: https://github.com/kubernetes/kubernetes/blob/18ce801beac34489f313d6b1223a1a5f07200cb6/test/integration/serving/serving_test.go#L339
     And they basically are coming from the fact that Queue when created is spawning a goroutine:
     https://github.com/kubernetes/kubernetes/blob/18ce801beac34489f313d6b1223a1a5f07200cb6/staging/src/k8s.io/client-go/util/workqueue/queue.go#L63
     which is only shutdown on Shutdown() call. But Shutdown in all controllers is only called in defer of controllers of the `Run` function that is actually not being run in failure cases.
      The actual queue that is problematic here is coming from here:     https://github.com/kubernetes/kubernetes/blob/18ce801beac34489f313d6b1223a1a5f07200cb6/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_serving_content.go#L66
- [ ] testing/integration/controlplane/transformation
   The goroutines are coming from the fact that we're not closing the kms transformer (grpc goroutines) that is being created.
   We basically create a grpc service and never close that:
https://github.com/kubernetes/kubernetes/blob/18ce801beac34489f313d6b1223a1a5f07200cb6/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L245
   Fixing would probably require changing transformer interfact to implement Close method or sth like that.

**Comment by wojtek-t** [comment]
@dashpole - can you please help with the apiserver/tracing test mentioned in https://github.com/kubernetes/kubernetes/issues/108483#issuecomment-1195714805

**Comment by dashpole** [comment]
@wojtek-t looking

**Comment by dashpole** [comment]
Opened #113545 to try fixing the goroutine leak.

**Comment by wojtek-t** [comment]
It seems the fix worked fine - I'm marking the tracing as fixed - thanks @dashpole 

I'm also trying to fix couple other smaller things.

**Comment by wojtek-t** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/113669 as a final step. With that PR we're in good enough shape that I'm going to close this issue as further improvements would have negligible impact.
