### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Tracking TODO items to address pre-beta, at beta, GA, and GA+1

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#109547]
### What would you like to be added?

This enhancement tracks various TODO items from alpha to GA for the In-Place Pod Vertical Scaling feature.
To find pending TODO items in the k/k repo, do:
```bash
git grep TODO | grep InPlacePodVerticalScaling
```

TODOs not tracked in code:
- [ ] Add and expose a helper function to get a pod's resource requirements and allocations for use by metrics, kubectl describe, etc

### Why is this needed?

These were TODO items found during review of PR https://github.com/kubernetes/kubernetes/pull/102884/ and it was agreed they should not block alpha. Most need to be handled before Beta, and a few need to be addressed at GA/GA+1.

```[tasklist]
### Tasks
- [ ] pkg/apis/core/validation/validation.go:5071 - Drop this var once InPlacePodVerticalScaling goes GA and featuregate is gone.
- [ ] pkg/kubelet/container/helpers.go:128 - Remove this in GA+1 and make HashContainerWithoutResources to become Hash.
- [ ] pkg/kubelet/container/runtime.go:301 - Remove this in GA+1 and make HashWithoutResources to become Hash.
- [ ] pkg/kubelet/kubelet.go:1962 - Investigate doing this in HandlePodUpdates + periodic SyncLoop scan
- [ ] pkg/kubelet/kubelet.go:2588 - Can we recover from checkpoint failure in some way? Investigate
- [ ] pkg/kubelet/kubelet.go:2847 - Can we recover from checkpoint update failure in some way? Investigate
- [ ] pkg/kubelet/kubelet.go:2855 - Can we recover from resize status checkpoint failure in some way? Investigate
- [ ] pkg/kubelet/kubelet_pods.go:2107 - Update this to include extended resources in addition to CPU, memory, ephemeral storage. Add test case for extended resources.
- [ ] pkg/kubelet/kuberuntime/helpers_linux.go:63 - Address issue that sets min req/limit to 2m/10m before beta ( See: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r662552642 )
- [ ] pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go:867 - Add unit tests for cgroup v1 & v2
- [ ] pkg/kubelet/kuberuntime/kuberuntime_manager.go:662 - Figure out best way to get enforceMemoryQoS value (parameter kubelet should know which containers it is managing #4 below) in platform-agnostic way
- [ ] pkg/scheduler/internal/queue/scheduling_queue.go:1074 - Fix this to determine when a pod is truly resized down (might need oldPod if we cannot determine from Status alone)
- [ ] test/e2e/node/pod_resize.go:85 - Can we optimize this?
- [ ] test/e2e/node/pod_resize.go:334 - Is there a better way to determine this?
- [ ] test/e2e/node/pod_resize.go:500 - Remove this check once base-OS updates to containerd>=1.6.9
- [ ] pkg/kubelet/cm/cgroup_manager_linux.go:645 - Support memory request in getCgroupMemoryConfig
- [ ] pkg/kubelet/cm/cgroup_manager_linux.go:731 - Support memory request in setCgroupMemoryConfig
```

**Comment by tallclair** [comment]
/triage accepted

Updated list of TODOs:

- [ ] [pkg/apis/core/validation/validation.go:5071](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/apis/core/validation/validation.go#L5071) -  Drop this var once InPlacePodVerticalScaling goes GA and featuregate is gone.
- [ ] [pkg/kubelet/cm/cgroup_manager_linux.go:645](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/cm/cgroup_manager_linux.go#L645) -  Add memory request support
- [ ] [pkg/kubelet/cm/cgroup_manager_linux.go:731](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/cm/cgroup_manager_linux.go#L731) -  Add memory request support
- [ ] [pkg/kubelet/container/helpers.go:128](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/container/helpers.go#L128) -  Remove this in GA+1 and make HashContainerWithoutResources to become Hash.
- [ ] [pkg/kubelet/container/runtime.go:301](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/container/runtime.go#L301) -  Remove this in GA+1 and make HashWithoutResources to become Hash.
- [ ] [pkg/kubelet/kubelet.go:1962](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet.go#L1962) -  Investigate doing this in HandlePodUpdates + periodic SyncLoop scan
- [ ] [pkg/kubelet/kubelet.go:2588](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet.go#L2588) -  Can we recover from this in some way? Investigate
- [ ] [pkg/kubelet/kubelet.go:2847](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet.go#L2847) -  Can we recover from this in some way? Investigate
- [ ] [pkg/kubelet/kubelet.go:2855](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet.go#L2855) -  Can we recover from this in some way? Investigate
- [ ] [pkg/kubelet/kubelet_pods.go:2107](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet_pods.go#L2107) -  Update this to include extended resources in
- [ ] [pkg/kubelet/kuberuntime/helpers_linux.go:63](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kuberuntime/helpers_linux.go#L63) -  Address issue that sets min req/limit to 2m/10m before beta
- [ ] [pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go:867](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go#L867) -  Add unit tests for cgroup v1 & v2
- [ ] [pkg/kubelet/kuberuntime/kuberuntime_manager.go:662](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L662) -  Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
- [ ] [pkg/scheduler/internal/queue/scheduling_queue.go:1074](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/scheduler/internal/queue/scheduling_queue.go#L1074) -  Fix this to determine when a
- [ ] [test/e2e/node/pod_resize.go:85](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/test/e2e/node/pod_resize.go#L85) -  Can we optimize this?
- [ ] [test/e2e/node/pod_resize.go:334](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/test/e2e/node/pod_resize.go#L334) -  Is there a better way to determine this?
- [ ] [test/e2e/node/pod_resize.go:500](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/test/e2e/node/pod_resize.go#L500) -  Remove this check once base-OS updates to containerd>=1.6.9

@esotsal would you mind updating the issue description to merge it with this list?

**Comment by vinaykul** [comment]
@tallclair @esotsal I've converted it to task list, please review. For the checkpoint failure TODOs, I want to toss out the node-local checkpointing code entirely and rely on podStatus as source of truth. (Please see https://github.com/kubernetes/kubernetes/pull/119665)
@ndixita Does it still make sense to support setting memory request?

**Comment by HirazawaUi** [comment]
> * [ ]  [pkg/kubelet/container/runtime.go:301](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/container/runtime.go#L301) -  Remove this in GA+1 and make HashWithoutResources to become Hash.
> * [ ]  [pkg/kubelet/kubelet.go:1962](https://github.com/kubernetes/kubernetes/blob/99129ed5ebbf435e65e7416f166558e37b1aac4d/pkg/kubelet/kubelet.go#L1962) -  Investigate doing this in HandlePodUpdates + periodic SyncLoop scan

With the merge of https://github.com/kubernetes/kubernetes/pull/124220 I think the both issues have been addressed.

**Comment by esotsal** [comment]
> @esotsal would you mind updating the issue description to merge it with this list?

Unfortunately @tallclair I am not allowed to modify issue description :-( , perhaps better to assign @vinaykul for this or close this issue and use https://github.com/orgs/kubernetes/projects/178 instead to track TODOs ?

**Comment by vinaykul** [comment]
> > @esotsal would you mind updating the issue description to merge it with this list?
> 
> Unfortunately @tallclair I am not allowed to modify issue description :-( , perhaps better to assign @vinaykul for this or close this issue and use https://github.com/orgs/kubernetes/projects/178 instead to track TODOs ?

I've updated it. I don't suppose there is a way to transfer ownership of issue, is there? (I can periodically keep it updated as bandwidth permits, but let's use the project board for most current info)

**Comment by esotsal** [comment]
> [test/e2e/node/pod_resize.go:334](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/pod_resize.go#L334) - Is there a better way to determine this?  => please check [here](https://github.com/kubernetes/kubernetes/pull/124296/files#diff-34fce4fbd28cee8beb8b899502e790a18a8d72ea70be9e786715f647d58c61b3R60)
> [test/e2e/node/pod_resize.go:85 ](https://github.com/kubernetes/kubernetes/blob/63bc33181436cf90c626efe90d0dd9dfb97aabc2/test/e2e/node/pod_resize.go#L85)- Can we optimize this? => please check [here](https://github.com/kubernetes/kubernetes/pull/124296/files#diff-34fce4fbd28cee8beb8b899502e790a18a8d72ea70be9e786715f647d58c61b3R83)
> [test/e2e/node/pod_resize.go:500](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/pod_resize.go#L500) - Remove this check once base-OS updates to containerd>=1.6.9  ==> please check [here](https://github.com/kubernetes/kubernetes/pull/124296/files#diff-34fce4fbd28cee8beb8b899502e790a18a8d72ea70be9e786715f647d58c61b3R94)

With the merge of [#124296 ](https://github.com/kubernetes/kubernetes/pull/124296) we can update test/e2e accordingly, and close those three TODOs i believe

**Comment by iksaif** [comment]
Is there a plan for https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-resourceFieldRef ? I guess this would work only for files?

**Comment by tallclair** [comment]
Action item: scrub the list of open TODOs, and file separate issues for any that should be addressed before going to beta.

**Comment by natasha41575** [comment]
/assign

I will go through these shortly and file separate issues for any that need to be addressed before GA

**Comment by natasha41575** [comment]
Remaining list of TODOs:
```
$ git grep TODO | grep InPlacePodVerticalScaling
pkg/apis/core/validation/validation.go: // TODO: Remove this after GA+3 releases of InPlacePodVerticalScaling
pkg/kubelet/allocation/allocation_manager.go:                   // TODO(vinaykul,InPlacePodVerticalScaling): Can we recover from this in some way? Investigate
pkg/kubelet/cm/cgroup_manager_linux.go: //TODO(vinaykul,InPlacePodVerticalScaling): Add memory request support
pkg/kubelet/kubelet_pods.go:                    // TODO(tallclair,vinaykul,InPlacePodVerticalScaling): Investigate defaulting to actuated resources instead of allocated resources above
pkg/kubelet/kuberuntime/helpers_linux.go:// TODO(vinaykul,InPlacePodVerticalScaling): Address issue that sets min req/limit to 2m/10m before beta
pkg/kubelet/kuberuntime/kuberuntime_manager.go: //TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
```

I think at this point, there is a small enough number of these that it is better to track as separate issues and close this one. Filed these:
- https://github.com/kubernetes/kubernetes/issues/133537
- https://github.com/kubernetes/kubernetes/issues/133538
- https://github.com/kubernetes/kubernetes/issues/133539

I'm going to look a bit more into the last 3, not sure yet if they are still relevant.

**Comment by esotsal** [comment]
@natasha41575 

Please add https://github.com/kubernetes/enhancements/issues/5294  in the TODOs for GA ( this KEP replaced an old issue )

**Comment by natasha41575** [comment]
Thanks @esotsal, I added it to the project board but marked it as post-GA. AFAIK (@pravk03 can correct me if I'm wrong), we aren't intending to drive that one in 1.35 and I don't consider it GA blocking

**Comment by esotsal** [comment]
> Thanks [@esotsal](https://github.com/esotsal), I added it to the project board but marked it as post-GA. AFAIK ([@pravk03](https://github.com/pravk03) can correct me if I'm wrong), we aren't intending to drive that one in 1.35 and I don't consider it GA blocking

Plan was to be in v1.35 , @ffromani , @tallclair , @Chunxia202410 to comment  

https://github.com/kubernetes/kubernetes/issues/127262  which was closed to be added on the KEP was for GA that was the original plan as discussed in sig node almost one year ago. What has changed?

**Comment by natasha41575** [comment]
> > Thanks [@esotsal](https://github.com/esotsal), I added it to the project board but marked it as post-GA. AFAIK ([@pravk03](https://github.com/pravk03) can correct me if I'm wrong), we aren't intending to drive that one in 1.35 and I don't consider it GA blocking
> 
> Plan was to be in v1.35 , [@ffromani](https://github.com/ffromani) , [@tallclair](https://github.com/tallclair) , [@Chunxia202410](https://github.com/Chunxia202410) to comment
> 
> [#127262](https://github.com/kubernetes/kubernetes/issues/127262) which was closed to be added on the KEP was for GA that was the original plan as discussed in sig node almost one year ago. What has changed?

_This_ issue is just tracking the commented TODOs in the current implementation, so I'd like to move the static cpu / memory discussion over to https://github.com/kubernetes/enhancements/issues/5294. I have written up my reply in a comment here: https://github.com/kubernetes/enhancements/issues/5294#issuecomment-3192469607.

**Comment by natasha41575** [comment]
I took a look at the last 3 today:

```
pkg/kubelet/kubelet_pods.go:                    // TODO(tallclair,vinaykul,InPlacePodVerticalScaling): Investigate defaulting to actuated resources instead of allocated resources above
pkg/kubelet/kuberuntime/helpers_linux.go:// TODO(vinaykul,InPlacePodVerticalScaling): Address issue that sets min req/limit to 2m/10m before beta
pkg/kubelet/kuberuntime/kuberuntime_manager.go: //TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
```

> pkg/kubelet/kubelet_pods.go:                    // TODO(tallclair,vinaykul,InPlacePodVerticalScaling): Investigate defaulting to actuated resources instead of allocated resources above

I think this is still a valid issue. I filed https://github.com/kubernetes/kubernetes/issues/133629 to track this.

> pkg/kubelet/kuberuntime/helpers_linux.go:// TODO(vinaykul,InPlacePodVerticalScaling): Address issue that sets min req/limit to 2m/10m before beta

This was tracked, addressed, and fixed in https://github.com/kubernetes/kubernetes/issues/114123. I'll create a PR to remove the TODO. 

> pkg/kubelet/kuberuntime/kuberuntime_manager.go: //TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way

This one appears to be related to the memoryQoS feature, which is in alpha and indefinitely stalled. I don't think we need to fix this one unless memoryQoS starts moving forward.

I think with that, we can close this one and use the new issues to track whatever is remaining.

/close
