### ISSUE TITLE
[Tracking Issue] Preparing sample-cli-plugin as a public template

### ISSUE THREAD

**Issue by Dentrax** [kubernetes/kubernetes#110841]
### What would you like to be added?

/kind feature
/sig cli

Prepare sample-cli-plugin as a public template:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-cli-plugin

* [ ] `.gitignore` (https://github.com/kubernetes/kubernetes/pull/110842)
* [ ] `.goreleaser.yml` (https://github.com/kubernetes/kubernetes/pull/110844)
* [ ] `.golangci-lint.yml` (https://github.com/kubernetes/kubernetes/pull/110843)
* [ ] `docs/`
* [ ] `.github/`
*  * [ ] dependabot (https://github.com/kubernetes/kubernetes/pull/110847)
*  * [ ] ISSUE + PR Templates (https://github.com/kubernetes/kubernetes/pull/110846)
*  * [ ]  workflows: `test` + `codeql` + `release` (https://github.com/kubernetes/kubernetes/pull/110848)
* [ ]  [.krew.yaml](krew.sigs.k8s.io/) (https://github.com/kubernetes/kubernetes/pull/110845)
* [ ] [just](https://github.com/casey/just) or [make](https://man7.org/linux/man-pages/man1/make.1.html) file
* * [ ] build: go build (ldflags for version)
* * [ ] test: unit + integrations
* * [ ] fmt: format checking
* * [ ] lint: linters
* * [ ] krew: test + build + send a pr to krew using [Automating plugin updates](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)
* [ ] Move the `ns` example into `examples` folder
* [ ] Make README more like how-to-start guide
* [ ] Rename repository to `kubectl-plugin-scaffolding`
* [ ] Change repository to [Public Template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

Easy instructions to build new plugin from scratch:
1. Click `Use this template` button
2. Clone the forked repository and cd into it
3. Build the plugin using the make command:

cc @eddiezane @kubernetes/sig-cli @developer-guy

### Why is this needed?

As we have discussed the idea at https://github.com/kubernetes/kubectl/issues/1138, creating a tracing issue to make this repository a public template.
