### ISSUE TITLE
Umbrella issue tracking Alpha impl. of KEP 3521 (Pod Scheduling Readiness)

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#113269]
This issue tracks all coding work to accomplish [KEP 3521](https://github.com/kubernetes/enhancements/issues/3521).

- [x] Introduce a new Pod API field `schedulingGates` #113274
    - [x] Pod API definition, feature gate, codegen, validation, and drop disabled fields
    - [x] disallow binding a Pod carrying non-nil schedulingGates
    - [x] disallow creating a Pod with non-nil nodeName and non-nil schedulingGates
    - [x] if needed, adds a `{type:PodScheduled, reason:WaitingForGates}` condition upon pod creation
    - [x] new literal SchedulingPaused in the STATUS column of `k get pod`
- [x] Scheduler logic #113275
    - [x] API, Codegen, UT for Enqueue extension point
    - [x] Add EnqueuePlugin to Scheduler Framework
    - [x] Implement EnqueuePluign in scheduler queue
    - [x] Implementation of DefaultEnqueue plugin
    - [x] Metrics
 - [x] Integration tests #113442

/sig scheduling
/kind feature

**Comment by Bryce-Soghigian** [comment]
Do you need help with any of this work?

**Comment by Huang-Wei** [comment]
All work for Alpha has been merged. Close the issue.
