### ISSUE TITLE
CEL in Admission Control Tracking

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#113440]
### What would you like to be added?

This is the tracking issue for the work goes in CEL in Admission Control([KEP]: https://github.com/kubernetes/enhancements/issues/3488)

- Kubernets 1.26 tracking
  - [x] Add feature gate: https://github.com/kubernetes/kubernetes/pull/112792
  - [x] Add API for ValidatingAdmissionPolicy and ValidatingAdmissionBinding(https://github.com/kubernetes/kubernetes/pull/112883)
  - [x] escalation/authz checks on policy paramKind / policyBinding paramRef raised in (https://github.com/kubernetes/kubernetes/pull/112883#discussion_r1007146284)
  - [x] where generateName is applied relative to mutating and validating admission (https://github.com/kubernetes/kubernetes/pull/112883#discussion_r1001076753)
  - [x] https://github.com/kubernetes/kubernetes/pull/112858
  - [x] https://github.com/kubernetes/kubernetes/pull/113349
  - [x] https://github.com/kubernetes/kubernetes/pull/112994
  - [x] https://github.com/kubernetes/kubernetes/pull/113314
  - [x] https://github.com/kubernetes/kubernetes/pull/113312

### Why is this needed?

For tacking the work properly

/triage accepted
/sig api-machinery
/assign @cici37

**Comment by cici37** [comment]
/close 
The feature has been successfully added in 1.26 as alpha and promoted to beta in 1.28
