### ISSUE TITLE
Umbrella issue tracking Beta impl. of KEP 3521 (Pod Scheduling Readiness)

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#113608]
This issue tracks all coding work to accomplish https://github.com/kubernetes/enhancements/issues/3521 as beta.

```[tasklist]
# Code changes
- [ ] #115815
- [ ] #115821
- [ ] #115583
- [ ] #115083
- [ ] #115569
- [ ] #116201
- [ ] #116201
```

```[tasklist]
# Docs update
- [ ] https://github.com/kubernetes/website/pull/39773
- [ ] https://github.com/kubernetes/website/pull/39509
- [ ] https://github.com/kubernetes/website/pull/40647
- [x] k/community: scheduler framework
```

**Comment by Huang-Wei** [comment]
It's for a future release that promotes PodSchedulingReadiness to beta.

**Comment by ahg-g** [comment]
Based on https://github.com/kubernetes/enhancements/pull/3840#discussion_r1097619928; we need to change validation to never permit nodeName and schedulingGates to be populated simultaneously, *regardless of feature enablement*. This applies to update, create and bind.

Current we do it conditional of the feature gate.

**Comment by lianghao208** [comment]
/assign 
assign for Optimization on places of calling addToActiveQ

**Comment by Huang-Wei** [comment]
@lianghao208 feel free to work on

> Evaluate the necessity of enforcing the scheduling gate as a https://github.com/kubernetes/kubernetes/pull/113274#discussion_r1013376569

It's better to enforce the naming format to avoid chances of duplication, as well as to know which components add a gate by first sight.

**Comment by lianghao208** [comment]
assign for enforcing the naming format of scheduling gate

**Comment by lianghao208** [comment]
assign for doc update k/website: [pod-lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)
