### ISSUE TITLE
[Umbrella] Skip Filter plugins when coupled PreFilter plugin returns `Skip` status

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#114399]
### What would you like to be added?

It's spawned from https://github.com/kubernetes/kubernetes/issues/107556.

After https://github.com/kubernetes/kubernetes/pull/114125 gets merged, the scheduler skips the plugin in Filter, if that plugin return `Skip` in PreFilter. In other words, the plugin can return `Skip` when it doesn't do anything on Pod's scheduling.

For example, if the pod doesn't have any inter-pod affinity, the inter-pod affinity plugin PreFilter can return Skip, and the scheduler won't run the inter-pod affinity plugin Filter. 

Here, I just listed all filter plugins, **not all of them may not need to return Skip in PreFilter though.** Assignee, please make sure your plugin really needs to return `Skip` or not.
Please feel free to assign what you'd like to work on. And please comment in this issue before starting to work on so that we can avoid many people from working on the same thing!

- [x] InterPodAffinity @sanposhiho https://github.com/kubernetes/kubernetes/pull/114889
- [x] NodeAffinity @sanposhiho https://github.com/kubernetes/kubernetes/pull/114125
- [x] NodeName @1978629634 https://github.com/kubernetes/kubernetes/pull/114386
- [ ] NodePorts @tangwz  https://github.com/kubernetes/kubernetes/pull/118271
- [x] NodeResourceFit @tangwz (no need to implement)
- [x] NodeUnschedulable @sivchari (no need to implement)
- [x] CSILimits @tangwz https://github.com/kubernetes/kubernetes/pull/115398
- [x] nonCSILimits @tangwz https://github.com/kubernetes/kubernetes/pull/115398
- [ ] TopologySpread @utam0k https://github.com/kubernetes/kubernetes/pull/117683
- [x] TaintToleration (no need to implement) @sivchari https://github.com/kubernetes/kubernetes/pull/114405
- [x] VolumeBinding @kidddddddddddddddddddddd https://github.com/kubernetes/kubernetes/pull/114897
- [x] VolumeRestriction @kidddddddddddddddddddddd https://github.com/kubernetes/kubernetes/pull/114898
- [x] VolumeZone @kidddddddddddddddddddddd https://github.com/kubernetes/kubernetes/pull/114896

### Why is this needed?

The scheduler can know which plugins it really needs/doesn't need to run to get the scheduling result.
It'd contribute to the scheduling performance.

/sig scheduling
/assign

**Comment by 1978629634** [comment]
👍

**Comment by kidddddddddddddddddddddd** [comment]
`VolumeZone` can use `skip` when pod has no topology labels.
`VolumeRestriction` can use `skip` when pod has no volumes?
And also, since we're optimizing `volumebinding` in [#114098,](https://github.com/kubernetes/kubernetes/pull/114098) I think I can do this for `volumebinding` in that pr.

I'll handle these three plugins after #114125 being merged.
/assign

**Comment by sanposhiho** [comment]
@Bryce-Soghigian will work on Topology Spread.

**Comment by sivchari** [comment]
I'll handle the `TaintToleration` plugin.
/assign

**Comment by utam0k** [comment]
I have interested in InterPodAffinity. Can I try it? I'm a very newer around that code.

**Comment by sanposhiho** [comment]
👍 

/assign @utam0k

**Comment by tangwz** [comment]
I'm working on NodeResourceFit now,I'm interested in it.

/assign

**Comment by sivchari** [comment]
@sanposhiho 
Please assign me to NodePorts and NodeUnschedulable.

**Comment by kerthcet** [comment]
/retitle [Umbrella] Skip Filter plugins when coupled PreFilter plugin returns `Skip` status

**Comment by utam0k** [comment]
@sanposhiho Sorry, but I can't find the time to try this PR:sob: Please allow me to unassign.

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/pull/114125 now got merged.

**Comment by Bryce-Soghigian** [comment]
ok we can get started on the work now then

**Comment by sivchari** [comment]
Hi, @sanposhiho 
NodePorts and NodeUnschedulable depend on a Node info when a pod is scheduled to any node. So, the both isn't effective to apply Skip status to kube-scheduler. wdyt ?

**Comment by sanposhiho** [comment]
@sivchari 
For `NodeUnschedulable`, agree. Marked it as done.
But, for `NodePorts`, it can return Skip when no container has `Ports`.

**Comment by tangwz** [comment]
@sanposhiho I think `NodeResourceFit` does not need to implement too.

**Comment by sanposhiho** [comment]
@tangwz Thanks, agree with that. Marked `NodeResourceFit` as done.

**Comment by sanposhiho** [comment]
Hey, I created the much similar ticket for PreScore/Score. 
Please consider working on it if you're interested! :)
https://github.com/kubernetes/kubernetes/issues/115745

Some plugins support both Filter and Score; for them, I'm thinking it'd be nice if the same person could work on the same plugin in Score/PreScore as well. (because probably the implementation will be much similar to the PreFIlter/Filter)

**Comment by sanposhiho** [comment]
Does anyone get interested in taking over this one? (TopologySpread)
https://github.com/kubernetes/kubernetes/pull/114535

**Comment by utam0k** [comment]
@sanposhiho Can I take it?

**Comment by sanposhiho** [comment]
@utam0k 
Thanks, just assigned it to you!

**Comment by tangwz** [comment]
> Any volunteer to take over #115318 from @sivchari?

@sanposhiho assign to me.

**Comment by sanposhiho** [comment]
@sivchari 
Are you OK to abandon https://github.com/kubernetes/kubernetes/pull/115318?
