### ISSUE TITLE
expose some metrics from HPA controller

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#115639]
### What would you like to be added?

Currently, HPA controller doesn't have any metrics in it.

- `horizontal_scaling_attempt_duration_seconds`: How long does the HPA controller take to complete reconcile one HPA object?
  - Probably equals the execution time of [`reconcileAutoscaler`](https://github.com/kubernetes/kubernetes/blob/9b09d0600a69a2eb36b0d136465ccc3c179dacdb/pkg/controller/podautoscaler/horizontal.go#L677). 
  - Has these labels:
    - `error`: should be `true` or `false`.
- `metrics_computation_duration_seconds`: How long does each metric type take to compute the ideal replica num. 
  - Probably equals the execution time around [here](https://github.com/kubernetes/kubernetes/blob/9b09d0600a69a2eb36b0d136465ccc3c179dacdb/pkg/controller/podautoscaler/horizontal.go#L400-L434).
  - Has these labels:
    -  `metric_type`: should be one of `Resource`, `Pods`, `Object`, `ContainerResource`, and `External`.
    - `error`: should be `true` or `false`. 

Please comment if any other ideas.

### Why is this needed?

In the PRR for any new features, we need to provide a way to enable admins to know if a feature is being used.
That's the initial motivation for this. 

But, of course, we can discuss the metrics from other perspective as well; HPA is the critical component for the service reliability, and end-users want to make sure if something wrong/unexpected happens carefully.

**Comment by pbetkier** [comment]
I generated a list of interesting metrics independently and arrived at a similar list. Here's my input:

Reconciliation health metrics:

* `reconciliation_duration_seconds` (Histogram) – the time it takes to reconcile a single HPA.
  - label `error` with values: `none`, `spec`, `internal`
* `reconciliations_total` (Counter) – the number of HPA reconciliations split by result.
   - label `error` with values: `none`, `spec`, `internal`
* `metric_computation_duration_seconds` (Histogram) – the time it takes to produce a single metric recommendation.
   - label `error` with values: `none`, `spec`, `internal`
   - label `metric_type` with values `Resource`, `Pods`, `Object`, `ContainerResource`, `External`
* `metric_computation_total` (Counter) – the number of metric recommendations split by result.
   - label `error` with values: `none`, `spec`, `internal`
   - label `metric_type` with values `Resource`, `Pods`, `Object`, `ContainerResource`, `External`
* `time_since_last_reconciliation_duration_seconds` (Histogram) – the elapsed time since the last reconciliation for each of the HPAs.
   - no labels
   - use case: notice scalability problems where the controller is not able to fulfil the expected reconciliation interval (15s); help find stuck HPAs
   - implementation: for simplicity can we emit values at the beginning of an HPA reconciliation ("previously reconciled X ago") as opposed to really tracking time since last reconciliation.
* `reconciliation_phase_duration_seconds` (Histogram)
   - label `phase` with values `compute_metric_recommendations`, `compute_final_recommendation`, `actuate`
   - use case: pinpoint performance problems found in `reconciliation_duration_seconds
   - optional for now: can derive from logs if we start logging more
* `metric_computation_phase_duration_seconds` (Histogram)
   - analogous to `reconciliation_phase_duration_seconds`
   - optional for now: can derive from logs if we start logging more

State metrics:

* `objects_count` (Gauge) – the current number of controlled HPA objects.
   - no labels
   - note: could query api server instead
* `metric_specs_count` (Gauge) – the number of metrics specs in the currently controlled HPA objects.
   - label `metric_type` with values `Resource`, `Pods`, `Object`, `ContainerResource`, `External`
   - note: could query api server instead

Notes:

* I'm opting for `reconciliation` instead of `scaling_attempt`, because scaling attempt is not clear to me if it's about the whole process or only new recommendation actuation.
* I think it's useful to turn `error` labels into enums, it's a different problem if an HPA spec is wrong vs. if HPA controller fails to compute due to a bug.
* I don't yet know how to cleanly handle situation where there is a partial error, e.g. when HPA spec has multiple metric specs, one of the metric computations fails, but since a different metric recommendation says scale-up we actuate a scale-up. Is it a success or an error? I assume it's `error: none` in `reconciliations_total` and `error: spec/internal` in `metric_computation_total`, but it may be confusing.
* I think there's a whole bunch of useful metrics to add regarding recommendation explanations (why given recommendations are produced, what is recommendation history) for HPA users, besides metrics for cluster admins that we're proposing now. I know that @pbeschetnov wants to work on recommendation observability soon.

**Comment by sanposhiho** [comment]
Thanks @pbetkier. Looks good overall. 

---

> reconciliations_total: (Counter) – the number of HPA reconciliations split by result.

It'd be great if this metric has the label which means how the HPA behaves finally on that reconcilation_loop. Probably something like:
- label `action` with values: `none`, `scale_down`, `scale_up`.

Then, the cluster admin can know the tendency of the resource demand on the cluster and utilize it to determine the cluster size.

I'm thinking the same label _may_ be good to add to `reconciliation_duration_seconds` as well, but not sure if there is a usecase to know the reconciliation performance on the specific action, either of scaling down or scaling up.

> I don't yet know how to cleanly handle situation where there is a partial error, e.g. when HPA spec has multiple metric specs, one of the metric computations fails, but since a different metric recommendation says scale-up we actuate a scale-up. Is it a success or an error? I assume it's error: none in reconciliations_total and error: spec/internal in metric_computation_total, but it may be confusing.

Good point.
It may be good to solve with the above `action` label; if HPA controller fails to calculate some metrics, but still can scale up by other metrics, then it emits `reconciliations_total` with `error: internal or spec` and `action: scale_up`.

**Comment by sanposhiho** [comment]
> I think there's a whole bunch of useful metrics to add regarding recommendation explanations (why given recommendations are produced, what is recommendation history) for HPA users, besides metrics for cluster admins that we're proposing now. I know that @pbeschetnov wants to work on recommendation observability soon.

👍 

Regarding that point, I'd like to see something like:
- `desired_replica` (Histogram): The scaling history of each HPA object.
  - labels: `namespace`, `hpa_name`
  - usecase: see how the HPA objects scale up/down workloads.
  - alternative for now: track the replica number of the target replicasets (or etc) directly. 
- `metric_proposed_replica` (Histogram): The proposed replica number from each metric in the HPA object.
  - labels: `namespace`, `hpa_name` (+ TODO: something to indicate specific metric in the HPA object.)
  - usecase: Users can see which metric recommends what replica number.
- `metric_proposed_replica_change_ratio` (Histogram): The proposed change ratio from each metric in the HPA object.
  - labels: `namespace`, `hpa_name` (+ TODO: something to indicate specific metric in the HPA object.)
  - usecase: Users can see which metric often/less affects the scaling decision and consider adjusting the resource request for resource utilization optimization. Also, for the cluster admin, this metric may be useful to adjust appropriate tolerance.

**Comment by pbetkier** [comment]
Another corner case to think of already: what happens in `reconciliations_total ` when we have an HPA with 2 metrics: one metric computation reports `spec` error and the other reports `internal` error. Reconciliation should report both `spec` and `internal` label values, which is currently not possible. I guess as a workaround we could report `internal` with the assumption that it's a higher priority than `spec`. Another option is splitting `error` label into `has_spec_error` and `has_internal_error` but I'd prefer to avoid it.

**Comment by sanposhiho** [comment]
> I guess as a workaround we could report internal with the assumption that it's a higher priority than spec. Another option is splitting error label into has_spec_error and has_internal_error but I'd prefer to avoid it.

The first idea looks fine.
If people want to know the number of `spec` errors exactly, then they can know it from `metric_computation_total`.

**Comment by pbetkier** [comment]
Let's bring @mwielgus and @gjtempleton to this discussion since we need to have the metrics implemented by mid March to graduate HPA on Container Resource metrics to beta. Or at least implement a core subset of them.

**Comment by sanposhiho** [comment]
Thanks @pbetkier. 
Let me list the high priority ones from the container resource metrics graduation PoV:

- [ ] `reconciliation_duration_seconds`: users need to confirm the container resource metric doesn't increse the whole time of scaling.
- [ ] `metric_computation_duration_seconds`:  users need to confirm the container resource metric doesn't take long time compared to other metrics.
- [ ] `metric_computation_total`: users need to confirm no much error occurrence on the container resource metric. Also, operators can determine how many the container metrics are actually in use by HPAs.

These are must-to-have to meat the requirements from the production readiness review.

**Comment by sanposhiho** [comment]
@pbetkier @mwielgus @gjtempleton 

I opened the PR for `reconciliation_duration_seconds` and `reconciliations_total`. Probably, we can discuss them there based on the actual implementation. PTAL when getting a chance 🙏 

https://github.com/kubernetes/kubernetes/pull/116010

**Comment by dgrisonnet** [comment]
@sanposhiho do you think we can close this issue now? I am seeing a bunch of PRs merged.

**Comment by sanposhiho** [comment]
There are some other metrics that were discussed here but not implemented yet; that's the reason this PR is still open.
Let me summarize the current state and update the issue description later.

**Comment by sanposhiho** [comment]
Here's the list of all metrics that are _mentioned_ here. 
(note that they're just ideas; it doesn't mean we agree to implement all of them)

- [x] reconciliations_total: Number of reconciliation of HPA controller. (https://github.com/kubernetes/kubernetes/pull/116010)
- [x] reconciliation_duration_seconds: The time(seconds) that the HPA controller takes to reconcile once. (https://github.com/kubernetes/kubernetes/pull/116010)
- [x] metric_computation_duration_seconds: The time(seconds) that the HPA controller takes to calculate one metric. (https://github.com/kubernetes/kubernetes/pull/116326)
- [x] metric_computation_total: Number of metric computations. (https://github.com/kubernetes/kubernetes/pull/116326)
- [ ] time_since_last_reconciliation_duration_seconds (Histogram): the elapsed time since the last reconciliation for each of the HPAs. ([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1426061241))
- [ ] reconciliation_phase_duration_seconds (Histogram) ([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1426061241))
- [ ] reconciliation_phase_duration_seconds (Histogram) ([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1426061241))
- [ ] desired_replica (Histogram): The scaling history of each HPA object. ([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1427024592))
- [ ] metric_proposed_replica (Histogram): The proposed replica number from each metric in the HPA object. ([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1427024592))
- [ ] metric_proposed_replica_change_ratio (Histogram): The proposed change ratio from each metric in the HPA object.([discussion](https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1427024592))


---

@dgrisonnet I have a question; should these↓ kind of metrics for state of objects be implemented in https://github.com/kubernetes/kube-state-metrics, not in HPA controller directly?

> objects_count (Gauge) – the current number of controlled HPA objects.
metric_specs_count (Gauge) – the number of metrics specs in the currently controlled HPA objects.
https://github.com/kubernetes/kubernetes/issues/115639#issuecomment-1426061241

**Comment by dgrisonnet** [comment]
@sanposhiho So the thing about kube-state-metrics is that it is not native to Kubernetes so although it is very widely used, you can't expect all the Kubernetes users to have it running. If you feel that a metric is important to have by default and that its cardinality is reasonable, I would recommend adding the metric here.

From what I can tell, the two metrics you mentioned should have a fairly low cardinality so it should be fine to have in the HPA controller.

To mention some other drawbacks from kube-state-metrics:
1. would require aggregating data to compute the counts (could be expensive and will not be available by default to kube-state-metrics users)
2. will be less precise than the HPA controller since it relies on the data exposed by the kube-apiserver, so two layers above the HPA controller

**Comment by sanposhiho** [comment]
Got it, that makes sense.

**Comment by rexagod** [comment]
@sanposhiho Are you still planning to work on this?

**Comment by sanposhiho** [comment]
No, you/anyone can pick it up if needed.

/unassign

**Comment by omerap12** [comment]
We’ve made good progress over the past couple of months.
@sanposhiho / @dgrisonnet, do you think we can close this issue, or are there additional metrics we should implement?
