### ISSUE TITLE
Implement node autoscaler for GCE

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#11748]
Implement node autoscaler for GCE on a base of cloud autoscaler for MIG.

## Milestones 
- [x] Move nodes of GCE kubernetes to MIG #7799
- [x] Fix problem with update of external services when nodes are changed #6292
- [x] Custom metrics:
  - [x] Implement new custom utilization metrics in heapster/cadvisor
  - [x] Ensure the correct version of heapster/cadvisor is used in kubernetes
- [x] Modify kube-up/kube-down scripts so that the autoscaler will be created #11742
- [x] Implement e2e tests:
  - [x] Test for cluster resize #8243
  - [x] Test custom metrics autoscaling #11685 
  - [ ] Test kube-up/kube-down scripts
- [x] Write user doc about autoscaling nodes

**Comment by jszczepkowski** [comment]
@piosz

**Comment by jszczepkowski** [comment]
CC @fgrzadkowski

**Comment by jszczepkowski** [comment]
The feature is done, e2e tests are passing.
