### ISSUE TITLE
Remove ability to re-enable serving deprecated APIs

### ISSUE THREAD

**Issue by carlory** [kubernetes/kubernetes#117659]
Built-in beta API versions have a maximum lifetime of 9 months or 3 minor releases (whichever is longer) from introduction to deprecation, and 9 months or 3 minor releases (whichever is longer) from deprecation to removal.

prerelease-lifecycle-gen:

- [x] autoscalingapiv2beta1.SchemeGroupVersion // deprecate in 1.22, remove in 1.25 #117661
- [x] autoscalingapiv2beta2.SchemeGroupVersion // deprecate in 1.23, remove in 1.26 #117661
- [x] batchapiv1beta1.SchemeGroupVersion      // deprecate in 1.21, remove in 1.25 #117662 
- [x] discoveryv1beta1.SchemeGroupVersion      // deprecate in 1.21, remove in 1.25 #117664
- [x] eventsv1beta1.SchemeGroupVersion        // deprecate in 1.22, remove in 1.25 #117665 
- [x] policyapiv1beta1.SchemeGroupVersion      // deprecate in 1.22, remove in 1.25 #117666
- [x] storageapiv1alpha1.SchemeGroupVersion     // deprecate in 1.19, remove in 1.24 #117667
- [x] storageapiv1beta1.SchemeGroupVersion     // deprecate in 1.19, remove in 1.27 #117667

/assign

**Comment by carlory** [comment]
all tasks are done.
