### ISSUE TITLE
[UMBRELLA] OpenAPI is very expensive

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#118136]
### What would you like to be added?

# Short description

OpenAPI v2 is very expensive, specifically when installing a lot of CRDs. I'm opening this issue to track what's going on and the work that we've been doing, are doing, or planning to do to improve the situation.

Right now, there's mostly three dimensions that are interesting:
1. OpenAPI v2 is not lazy, and aggregates the information from CRDs on a very regular basis
2. OpenAPI is subtly called by various processes in kubectl which probably shouldn't exist. Once the OpenAPI v2 is lazy, then we should definitely make sure we have as few calls as possible to it.
3. Some processes are very slow in the OpenAPI v2. These have mostly been fixed.

# Existing issues and pull-requests

## OpenAPI v2 is not lazy
```[tasklist]
- [x] https://github.com/kubernetes/kube-openapi/pull/371
- [x] https://github.com/kubernetes/kubernetes/pull/116445
- [ ] https://github.com/kubernetes/kubernetes/pull/118212
- [ ] Issue missing for CRD controller not being lazy
```

## OpenAPI v2 is being used
```[tasklist]
- [x] https://github.com/kubernetes/kubernetes/pull/115324
- [x] https://github.com/kubernetes/kubernetes/pull/114439
- [x] https://github.com/kubernetes/kubernetes/pull/115119
- [x] https://github.com/kubernetes/kubernetes/pull/114294
- [ ] We need to create a few issues for the things that are still pulling the OpenAPI in kubectl.
```

## OpenAPI v2 processing is slow

That is mostly done, 
```[tasklist]
- [x] https://github.com/kubernetes/kube-openapi/issues/324
- [x] https://github.com/kubernetes/kube-openapi/issues/315
- [x] https://github.com/kubernetes/kube-openapi/pull/368
- [x] https://github.com/kubernetes/kube-openapi/pull/361
- [x] https://github.com/kubernetes/kube-openapi/pull/339
- [x] https://github.com/kubernetes/kube-openapi/pull/325
- [x] https://github.com/kubernetes/kube-openapi/pull/319
- [ ] https://github.com/kubernetes/kubernetes/pull/118204
- [ ] We need to create an issue for openapi v3 serialization
```

## Misc
```[tasklist]
- [x] https://github.com/kubernetes/kubernetes/pull/114191
```

cc @sttts @Jefftree 

### Why is this needed?

We need to be able to create more CRDs on Kubernetes clusters than we can today. Schema is the main limitation of most of the memory allocated, in-use memory and almost certainly of processing time (though that's usually harder to measure since you need to measure WHILE the cpu is being used).

**Comment by sttts** [comment]
@Jefftree what is still to do here?

**Comment by Jefftree** [comment]
Lazy OpenAPI: https://github.com/kubernetes/kubernetes/pull/118212
kubectl remove default v2 pulling: https://github.com/kubernetes/kubernetes/pull/120707
V3 serialization: https://github.com/kubernetes/kube-openapi/pull/416

All the tasks listed above are complete. Marking this as done
/close
