### ISSUE TITLE
Add serial e2e tests for `SidecarContainers`

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#119014]
https://github.com/kubernetes/kubernetes/pull/116429#discussion_r1247437996

> I would like a node serial e2e test that adds a restartable init container, waits for it to be initialized, stops the kubelet, and then:
> 
> * causes the restartable init container to exit, starts the kubelet, verifies the restartable init container is started
> * (if we have the machinery) removes all but the last init container, starts the kubelet, and verifies the pod is not re-initialized
> * (if we have the machinery) removes all but the last init container (which should be restartable), starts the kubelet, and verifies the restartable init container is not restarted and than no other init containers are started.
> 
> I know we can do the first one, I assume we can do something slightly CRI specific to purge specific containers.

/assign
```[tasklist]
### Tasks
- [x] Add serial e2e tests w/o SidecarContainers feature https://github.com/kubernetes/kubernetes/pull/119019
- [x] Merge SidecarContainers PR https://github.com/kubernetes/kubernetes/pull/116429
- [x] Add the test-infra job for serial e2e tests w/ SidecarContainers feature https://github.com/kubernetes/test-infra/pull/30281
- [ ] Add serial e2e tests w/ SidecarContainers feature
```
