### ISSUE TITLE
Dynamic resource allocation: refactoring overall flow of prepare/unprepare resources

### ISSUE THREAD

**Issue by TommyStarK** [kubernetes/kubernetes#119469]
- [ ]  Implement a clean way to determine which API the gRPC server supports
   Proposal:
        - detect version in a lazy way, i.e. on the first real call and only set the version if the call succeeds
        - better approach could be to specify supported API version at the plugin registration time but it implies deeper changes as it affects devices plugins and csi plugins
- [ ]  Avoid falling back to `v1alpha2` API on every call
- [ ] Update end-to-end tests using KIND
- [ ] Update dra e2e node tests
```[tasklist]
### Tasks
```

**Comment by bart0sh** [comment]
> Update end-to-end tests using KIND
Do you mean fix failing tests or add new ones?

**Comment by TommyStarK** [comment]
I mean both

**Comment by bart0sh** [comment]
Thanks for the explanations. btw, dra e2e node tests doesn't use kind. are you planning to update them?

**Comment by TommyStarK** [comment]
I forgot about the dra e2e node tests. IMHO we should also look at them. I've updated the issue accordingly. I know this is going to be a big amount of work but I do think it's necessary.

**Comment by bart0sh** [comment]
/close
The issue is fixed by https://github.com/kubernetes/kubernetes/pull/120099
