### ISSUE TITLE
kmsv2: follow-ups from KDF based nonce extension

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#119563]
/assign
/sig auth
/triage accepted
/milestone v1.29
```[tasklist]
### Tasks
- [ ] Seed rotation: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1267336920
- [ ] integration test that this dynamically takes effect: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1248315533
- [x] integration test with old AES GCM data recorded and new KDF data recorded: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1248315660 -> #120370
- [ ] Doc SIV: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1267300901
- [ ] AEAD: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1261626758
- [ ] Rand bytes: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1270688260 and https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1268520912
- [ ] Birthday math: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1268505548
- [ ] Drop encrypted prefix: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1271002510
- [ ] Switch on type: https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1271003797 and https://github.com/kubernetes/kubernetes/pull/118828#discussion_r1271005273
- [x] Changelog: https://github.com/kubernetes/kubernetes/pull/118828#issuecomment-1649433462 -> #119693
- [x] Update docs to describe new feature gate -> https://github.com/kubernetes/website/pull/42312
```

**Comment by zelenushechka** [comment]
Hello @enj ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by zelenushechka** [comment]
Hello @enj. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and we want to ensure that each PR has a chance to be merged and issues can be addressed.
Is this issue still targeting the 1.29 release?
