### ISSUE TITLE
[StructuredAuthn]: follow-ups from alpha implementation

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#121553]
/assign
/sig auth
/triage accepted

```[tasklist]
### Tasks
- [ ] Making username required: https://github.com/kubernetes/kubernetes/issues/121329
- [ ] Using generics: https://github.com/kubernetes/kubernetes/pull/121078#discussion_r1367380846
- [ ] Ability to specify variables for CEL: https://github.com/kubernetes/kubernetes/pull/121078#discussion_r1372152672
- [ ] Dumping claims in extra: https://github.com/kubernetes/kubernetes/pull/121078#discussion_r1372180760
```
