### ISSUE TITLE
Upgrade etcd to version 3.5.10

### ISSUE THREAD

**Issue by mzaian** [kubernetes/kubernetes#121610]
```[tasklist]
### Tasks
- [x] update build etcd image to 3.5.10-0 etcd: Build image 3.5.10 #121567 @mzaian
- [x] update etcd version to 3.5.10 etcd: Update to version 3.5.10 #121566 @mzaian
- [x] update image promotion for etcd 3.5.10-0 Image promotion for etcd 3.5.10-0 https://github.com/kubernetes/k8s.io/pull/6032 @mzaian
- [x] upgrade etcd deps to v3.5.10 bump etcd newest version: v3.5.10 #121573 @tukwila
```
**Why is this needed?**
Update etcd to version 3.5.10 See release: [v3.5.10](https://github.com/etcd-io/etcd/releases/tag/v3.5.10).
