### ISSUE TITLE
KEP-4222: CBOR encoding alpha requirement tracking

### ISSUE THREAD

**Issue by benluddy** [kubernetes/kubernetes#122921]
### What would you like to be added?

Requirements for https://kep.k8s.io/4222:

As we check these off, please add links to the tests.

- [x] Test: Decoding a map containing duplicate keys into a Go map produces an error: https://github.com/kubernetes/kubernetes/pull/123436
- [x] Test: Decoding a map containing duplicate keys into a Go struct produces an error: https://github.com/kubernetes/kubernetes/pull/123436
- [x] Test: Decoding a map into a Go struct matches `json` field tag names case-sensitively: https://github.com/kubernetes/kubernetes/pull/123436
- [x] Test: When decoding a map into a Go struct, a case-insensitive match between a key and a `json` field tag name is treated the same as no match: https://github.com/kubernetes/kubernetes/pull/123436
- [x] Test: Encoding a struct with duplicate field names (`json` tag names) does not result in a map containing duplicate keys: https://github.com/kubernetes/kubernetes/pull/123626 (discussed at [March 6 2024 api-machinery biweekly](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.xzja5vbnkhk2) and agreed on matching the encoding/json behavior, with addition of parallel test cases for the json serializer)
- [x] Test: Roundtripping preserves the distinction between integers and floating-point numbers
    - [x] subtests for (u)int{64,32,16,8} and float{64,32} in TestRoundtrip of https://github.com/kubernetes/kubernetes/pull/123267
    - [x] Still need tests for the distinction being maintained when decoding into `map[string]interface{}` https://github.com/kubernetes/kubernetes/pull/123536
    - [x] missing case covering `uint64(math.MaxUint64)` because it would overflow int64. Kube JSON cannot roundtrip this, either: `uint64(math.MaxUint64)` -> JSON `18446744073709551615` -> `float64(1.8446744073709552e+19)` -> JSON `18446744073709552000` -> `json: cannot unmarshal number 18446744073709552000 into Go value of type uint64`: this was discussed in the apimachinery biweekly on march 6 and agreed to reject rather than decode to float64: https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.xzja5vbnkhk2
- [x] Test: Decoding a text string containing an invalid UTF-8 sequence produces an error
    - [x] subtest in TestDecode of https://github.com/kubernetes/kubernetes/pull/123267
- [x] Test: Pooled buffers should not grow and be retained forever: https://github.com/kubernetes/kubernetes/pull/125676
- [x] Test: Decoding into a Go interface{} stores only either `nil` concrete values or concrete values of type `bool`, `string`, `int64`, `float64`, `[]interface{}`, or `map[string]interface{}` (no special treatment of tagged content producing `time.Time`, `math/big.Int`, etc.): https://github.com/kubernetes/kubernetes/pull/125068
  - [x] fixme: "decoding cbor data tagged with 0 produces time.Time instead of RFC3339 timestamp string": https://github.com/kubernetes/kubernetes/pull/125424
  - [x] fixme: "decoding cbor data tagged with 1 produces time.Time instead of RFC3339 timestamp string"
    - [x] tagged unsigned integer: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged float16: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged float32: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged float64: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged unsigned integer, year beyond 9999: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged negative integer: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged negative float16: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged negative float32: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged negative float64: https://github.com/kubernetes/kubernetes/pull/125424
    - [x] tagged Inf: https://github.com/kubernetes/kubernetes/pull/125423
    - [x] tagged -Inf: https://github.com/kubernetes/kubernetes/pull/125423
    - [x] tagged NaN: https://github.com/kubernetes/kubernetes/pull/125423
  - [x] fixme: "decoding cbor data tagged with 2 produces big.Int instead of []byte": https://github.com/kubernetes/kubernetes/pull/125420
  - [x] fixme: "decoding cbor data tagged with 3 produces big.Int instead of []byte": https://github.com/kubernetes/kubernetes/pull/125420
  - [x] fixme: "cbor data with simple value 23 should throw an error": https://github.com/kubernetes/kubernetes/pull/125421
  - [x] fixme: "unrecognized simple values should be rejected": https://github.com/kubernetes/kubernetes/pull/125421
- [x] Test: Conformance to CBOR specification
  - [x] All CBOR examples in RFC 8949 Appendix A roundtripped in https://github.com/kubernetes/kubernetes/pull/123268
  - [x] fixme: "decoding bigint to interface{} must not produce math/big.Int": https://github.com/kubernetes/kubernetes/pull/125420
  - [x] fixme: "decoding negative bigint to interface{} must not produce math/big.Int": https://github.com/kubernetes/kubernetes/pull/125420
  - [x] fixme: "the undefined simple value should not successfully decode as nil": https://github.com/kubernetes/kubernetes/pull/125421
  - [x] fixme: "simple values other than false, true, and null should be rejected": https://github.com/kubernetes/kubernetes/pull/125421
  - [x] fixme: "simple values other than false, true, and null should be rejected": https://github.com/kubernetes/kubernetes/pull/125421
  - [x] fixme: "decoding of tagged time into interface{} must produce RFC3339 timestamp compatible with JSON, not time.Time": https://github.com/kubernetes/kubernetes/pull/125424
- [x] Test: Conformance tests demonstrated to run against a non-Go Kubernetes client language: https://github.com/kubernetes/enhancements/pull/4923
- [x] Test: Go strings that are not valid UTF-8 sequences can be roundtripped through CBOR without error
    - [x] subtest in TestRoundtrip of https://github.com/kubernetes/kubernetes/pull/123267
- [x] Test: Decoding a map into a Go struct produces a strict decoding error if the map contains a key that does not correspond to JSON tag name of one of the struct's fields
  - [x] Subtest of TestDecode in https://github.com/kubernetes/kubernetes/pull/122881
- [x] Test: Roundtripping preserves the distinction between absent, present-but-null, and present-and-empty for slices and maps
  - [x] subtest in TestRoundtrip of https://github.com/kubernetes/kubernetes/pull/123267
  - [x] Still need tests for the distinction being maintained when decoding into `map[string]interface{}`: https://github.com/kubernetes/kubernetes/pull/123536
- [x] Test: `runtime.RawExtension`: Re-encoding preserves the original raw bytes: https://github.com/kubernetes/kubernetes/pull/125629
- [x] Test: `runtime.RawExtension`: Decoding JSON-in-CBOR, JSON-in-Protobuf, CBOR-in-JSON, and CBOR-in-Protobuf is supported: https://github.com/kubernetes/kubernetes/pull/125629
- [x] Test: Fuzz: For all native types, native-to-JSON-to-unstructured and native-to-CBOR-to-unstructured is identical: https://github.com/kubernetes/kubernetes/pull/122832
  - [x] cover aggregator types: https://github.com/kubernetes/kubernetes/pull/125570
  - [x] cover apiextensions types: https://github.com/kubernetes/kubernetes/pull/125570
  - [x] todo: enable for types using RawExtension: https://github.com/kubernetes/kubernetes/pull/125629
  - [x] todo: enable for types using []byte: https://github.com/kubernetes/kubernetes/pull/125419
- [x] Test: Fuzz: Decoding does not allocate an inordinate number of bytes: https://github.com/kubernetes/kubernetes/pull/124761
- [x] Test: Fuzz: Roundtrip JSON-to-CBOR-to-JSON and CBOR-to-JSON-to-CBOR: https://github.com/kubernetes/kubernetes/pull/127862
- [x] Test: Fuzz: Roundtrip through implementations in at least some of the non-Go client languages: https://github.com/kubernetes/enhancements/pull/4923
- [x] Test: Integration: Response content-type negotiation works and honors indicated preference (Protobuf > CBOR > JSON): https://github.com/kubernetes/kubernetes/pull/128267
- [x] Test: Integration: Get, list, watch, update, delete, deletecollection, apply, and scale support CBOR using dynamic and generated clients for all native types
  - [x] Streaming support in Serializer implementation: https://github.com/kubernetes/kubernetes/pull/126105
  - [x] Tests using dynamic client for all resources: https://github.com/kubernetes/kubernetes/pull/128243
  - [x] Tests using generated client: https://github.com/kubernetes/kubernetes/pull/128323
  - [x] Patch handler accepts CBOR apply: https://github.com/kubernetes/kubernetes/pull/128273
  - [x] Apply integration test coverage (dynamic + generated): https://github.com/kubernetes/kubernetes/pull/128273
    - [x] Dynamic client supports CBOR apply: https://github.com/kubernetes/kubernetes/pull/128273
    - [x] Generated clients support CBOR apply: https://github.com/kubernetes/kubernetes/pull/128273
  - [x] TODO: Dynamic client watch integration test coverage: https://github.com/kubernetes/kubernetes/pull/128491
- [x] Alpha: Test: Integration: Request content-type falls back to JSON for life of RESTClient: https://github.com/kubernetes/kubernetes/pull/128497
- [x] Custom Resource Storage: https://github.com/kubernetes/kubernetes/pull/128322
  - [x] Test: Integration: Custom resources storage encoding is CBOR with API server feature gate enabled
  - [x] Test: Integration: Custom resources storage encoding is JSON with API server feature gate disabled
  - [x] Test: Integration: Mixed CBOR and JSON encodings in storage for a single custom resource can be retrieved with feature gate disabled
- [x] Support nondeterministic encoding for responses: https://github.com/kubernetes/kubernetes/pull/125678/
  - [x] Implement NondeterministicEncoder on serializer: https://github.com/kubernetes/kubernetes/pull/125678
- [x] Test: Integration: Client feature gate can force clients otherwise configured with a CBOR request encoding to use JSON: https://github.com/kubernetes/kubernetes/pull/128323
- [x] Test: Integration: Client feature gate can change the default request encoding to CBOR for clients with no explicitly configured encoding: https://github.com/kubernetes/kubernetes/pull/128323
- [x] Dynamic client supports CBOR behind client-side gates https://github.com/kubernetes/kubernetes/pull/128243
- [x] Generated clients support CBOR behind client feature gates: https://github.com/kubernetes/kubernetes/pull/128323
- [x] Remove test-only feature gate and client feature gate instances and introduce regular feature gates: https://github.com/kubernetes/kubernetes/pull/128539
- [x] Serving Codecs wired to apiserver feature gate, integration test wiring removed: https://github.com/kubernetes/kubernetes/pull/128503
  - [x] Integration test: storage encoding of all built-in types should be Protobuf https://github.com/kubernetes/kubernetes/pull/128590
  - [x] Watch responses use the application/cbor-seq media type: https://github.com/kubernetes/kubernetes/pull/128501
- [x] Test: E2E: Request and response content-type negotiation with 1.17 sample API server: https://github.com/kubernetes/kubernetes/pull/128641

### TODOs
Tracks debt built up as we merged.  If there were some edges that didn't work, we want to avoid losing track of those, while unlocking as much as possible.

- [x] https://github.com/kubernetes/kubernetes/pull/122881 leaves debt
    - [x] IntDecConvertSignedOrFail errors on overflow, JSON will try to fall back to float64. Discussed in [March 6 2024 api-machinery biweekly](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.xzja5vbnkhk2) and decided to continue returning an error for this case instead of imitating JSON's fallback to float64.
    - [x] UnstructuredList implementation of SetUnstructuredContent is not identical to what unstructuredJSONScheme does: https://github.com/kubernetes/kubernetes/pull/124775
    - [x] Should Inf/-Inf/NaN be supported? Current Protobuf will encode this, but JSON will produce an error
      - [x] Discussed in [March 6 2024 api-machinery biweekly](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.xzja5vbnkhk2): Match JSON behavior here, error on encode and decode: https://github.com/kubernetes/kubernetes/pull/125423
    - [x] [DefaultMapType isn't set properly by DecOptions, set it again here until the bugfix is adopted](https://github.com/kubernetes/kubernetes/commit/e305e773bbfe8c5bdf9c57881a875e168b004b8c#diff-2416853adc0c25daf3c828489f3d37bed401dbb5df4ce277c61f43719f63f7d6R773)
    - [x] Missing test case that demonstrates list encode/decode.  Probably covered above, but indicating just in case: https://github.com/kubernetes/kubernetes/pull/124775
- [x] Handle typed CR clients using custom json Marshaler/Unmarshaler implementations: https://github.com/kubernetes/kubernetes/pull/125748
  - [x] Enforce the same check on args to Marshal and Unmarshal https://github.com/kubernetes/kubernetes/pull/128462
- [x] Add Unstructured field accessor(s) that handle coercion of numeric values to a specific type, e.g. "NestedNumberAsFloat": https://github.com/kubernetes/kubernetes/pull/127838
- [x] Decoder unit test verifies that the "self-described CBOR" tag is accepted without changing the result: https://github.com/kubernetes/kubernetes/pull/124799
- [x] Go byte arrays marshal to CBOR array of integers, not byte string: https://github.com/kubernetes/kubernetes/pull/125418
- [x] Implementations of `encoding.BinaryMarshaler` or `encoding.BinaryUnmarshaler` are not used during encoding or decoding: https://github.com/kubernetes/kubernetes/pull/125422
- [x] Decode allocation fuzz target covers unstructured typed.  built-in go types are excluded because we don't know of a tool to generate fuzzed cbor bytes that will actually be usefully decoded and the coverage would end up checking custom marshallers and not the cbor library itself
- [x] Add beta requirement to opt out of automatic transcoding of RawExtension and FieldsV1 to JSON for Kubernetes components: https://github.com/kubernetes/enhancements/pull/4758

### Why is this needed?

The requirements tracked here originate from the KEP alpha criteria.

**Comment by jiahuif** [comment]
/assign @benluddy 
For this is a TODO list
/triage accepted

**Comment by deads2k** [comment]
I think we're at alpha!

@benluddy would you do the honor of `/close`?
