### ISSUE TITLE
Improve kubelet's scalability and performance

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#12540]
Kubelet incurs high pod management overhead due to constant polling container states and sub-optimal implementation details (relevant issues reported by users:  #10451, #12099, #12082). This is an umbrella issue to improve Kubelet's scalability and performance by lowering such an overhead. 

I will update this issue with more progress soon.

**Comment by lleszczu** [comment]
@yujuhong If you need help with testing / developing this I will be happy to help :)

**Comment by yujuhong** [comment]
@lleszczu, thanks for offering help! I am still at the phase of writing design doc and building prototypes. I will update the issue soon for the details.

**Comment by yujuhong** [comment]
I've written a proposal to better handle discovering container state changes.
 1. The first part of the proposal adds a pod lifecycle event generator to avoid periodic polling that hammers docker. See #12802 
 2. The second part of the proposal integrates a pod cache to store the container/pod states. See #12810

Sub-issues to be created later.

Besides the proposal above, there are other low-hanging fruits that we can get to for v1.1:
 - #12691 to trigger pod worker individually on pod spec changes.
 - Rate-limit containers creation/deletion to handle batch creation/deletion (issue-to-be-created).

**Comment by yujuhong** [comment]
PRs for the event generator: #13571, #13990

**Comment by yujuhong** [comment]
UPDATE: I was distracted by release-1.1 issues and general kubelet debugging and resource usage issues. I plan to return and finish my WIP PRs.

Here is a TODO list (which may be updated from time to time to include more details and progress): 

**[P1] Pod lifecycle event generator (PLEG)**
*Proposal #12802*: Leverage the container runtime event stream to replace existing periodic polling of container states.
*Expectation*: Significantly lower kubelet's and docker’s resource usage; improves reliability; also lower the response time to container events.
 - [ ] [Prerequisite]: Pod workers will only react to events/changes. Decouple all proactive tasks from pod syncs and eliminate reliance on periodic syncing in kubelet components.
   - [ ] A separate prober handling liveness/readiness checks: (#12866 by @timstclair)
   - [ ] Status manager should not rely on period syncs to repopulate pod statuses (PR: #16223 by @timstclair)
   - [ ] Handle sync errors in pod workers (PR #15264)
   - [ ] Move pastActiveDeadline check out to the main sync loop
   - [x] Trigger pod workers independently on pod spec changes (#12691)

- [ ] Implement a generic PLEG and switch both docker and rkt to use it (WIP PR: #13571)
- [ ] Implement a docker-specific PLEG and switch docker to use it (WIP PR: #13990)
- [ ] Benchmark docker event stream


**[P1] Resource usage and performance benchmark/monitoring/dashboard**
Evaluate, monitor resource usage and performance of kubelet under different workloads, and detect any regression.
 - [ ] Create realistic workloads (e.g., w/ and w/o probing)
 - [ ] Create a performance dashboard #15554
 - [ ] Record relevant performance metrics in Prometheus #15554
 - [ ] Extend resource usage tracking test in e2e to fail tests if the usage is beyond the limit.
 - [ ] [Optional]: allow using cadvisor mock for benchmarking #16296



**[P2] Add an in-memory runtime pod cache**
*Proposal #12810*: The cache will be populated by PLEG upon changes and will store all relevant pod/container states
*Expectation: Further reduce requests to the container runtime; also provide a centralized place to retrieve pod/container information*
 - [ ] [Prerequisite]: Record and check expectations in pod workers to ensure a consistent view when syncing
 - [ ] [Optional]: Restructure SyncPods to facilitate expectation recording and improve code readability (#12826)
 - [ ] Integrate a pod cache with the event generator

**Comment by yujuhong** [comment]
@dchen1107, @Random-Liu, FYI, I updated the TODO list in the comment above.

**Comment by Random-Liu** [comment]
Wow! Nice~

**Comment by yifan-gu** [comment]
@yujuhong Thanks :)

**Comment by dchen1107** [comment]
Very nice. Both p1 items listed in https://github.com/kubernetes/kubernetes/issues/12540#issuecomment-152625606 in our 1.2 roadmap already. Thanks!

**Comment by yujuhong** [comment]
Closing this as we've met our v1.2 goals. Will open a new issue when we want further improvement.
