### ISSUE TITLE
[Umbrella Issue] Compatibility Version Feature Gate Port

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#126926]
With the introduction of Compatibility Version, feature gates must be created with both their current version as well as historical versions and when they transitioned to alpha/beta/GA.

Current status:
- [x] https://github.com/kubernetes/kubernetes/pull/126878
- [x] https://github.com/kubernetes/kubernetes/pull/126791
- [x] https://github.com/kubernetes/kubernetes/pull/127672
- [x] https://github.com/kubernetes/kubernetes/pull/127200
- [x] https://github.com/kubernetes/kubernetes/pull/127670

Outstanding Issues:
- [ ] https://github.com/kubernetes/kubernetes/issues/126893
- [x] https://github.com/kubernetes/kubernetes/issues/127159
- [x] https://github.com/kubernetes/kubernetes/issues/127160

**Reference**:

All features in kube_features:
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go

must be transitioned to here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/versioned_kube_features.go

Feature gate definitions start on Line 1013
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L1013

Total features as of Kubernetes v1.31: 157 features

We have 120 features strictly through kube_features, 35 features through apiserver, 2 features through apiextensions-apiserver

KEP reference for feature gate changes: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/4330-compatibility-versions#changes-to-feature-gates

https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/4330-compatibility-versions#feature-gating-changes

/sig api-machinery
/triage accepted
/cc @jpbetz @Aaron-Prindle

**Comment by aaron-prindle** [comment]
Should https://github.com/kubernetes/kubernetes/issues/126893 also be added to the TODO list or is doing that still TBD/potentially-not-a-requirment?

**Comment by Jefftree** [comment]
> Should #126893 also be added to the TODO list above or is the work in that issue still TBD/potentially-not-a-requirement?

Good point, let's add it for tracking and we can remove it later if it's deemed not a requirement

**Comment by tengqm** [comment]
Shall we sort the feature gate names in alphabeta order?

**Comment by tengqm** [comment]
BTW, DynamicResourceAllocation was introduced in v1.26.

**Comment by Jefftree** [comment]
This is now completed. https://github.com/kubernetes/kubernetes/issues/126893 is a separate issue that shouldn't be needed to be coupled with feature porting. 

> Shall we sort the feature gate names in alphabeta order?

> BTW, DynamicResourceAllocation was introduced in v1.26.

Both of these should have been fixed.
