### ISSUE TITLE
scheduler: more fine-grained QHints

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#127405]
/kind feature
/sig scheduling
/assign

We had a problematic internal feature called `preCheck` (https://github.com/kubernetes/kubernetes/issues/110175).

preCheck prevented us from implementing a fine-grained QHint because it could cause the scenarios like the following:
1. Node with un-ready taint is created.
2. Because Node has taint, this `Node/Add` event isn't delivered to QHints because preCheck filters it out.
3. When Node is ready and the taint is removed, preCheck forwards this Node event to the scheduling queue. However, it's Node/Update (UpdateNodeTaint), not Node/Add.
4. Plugins that actually want to move Pods via Node/Add couldn't get Node/Add at (2), hence has to subscribe `Node/Update` to catch (3) instead, and handle it like `Node/Add`.

Now, it's disabled finally when QHint is enabled (https://github.com/kubernetes/kubernetes/pull/127109), and we can improve QHints to filter out events more accurately.

```[tasklist]
### Tasks
- [x] https://github.com/kubernetes/kubernetes/pull/127220
- [x] go thru all plugins and list up which QHints can be improved. @sanposhiho
- [x] InterPodAffinity  @googs1025 https://github.com/kubernetes/kubernetes/pull/127470
- [x] NodeAffinity @dom4ha https://github.com/kubernetes/kubernetes/pull/127444
- [x] NodeResourceFit @dom4ha https://github.com/kubernetes/kubernetes/pull/127473
- [x] NodeUnschedulable @googs1025 https://github.com/kubernetes/kubernetes/pull/127450
- [x] PodTopologySpread @googs1025 https://github.com/kubernetes/kubernetes/pull/127478
```

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/issues/127405 removes all non-necessary Node/Update events when QHint is enabled.
I'll go thru all plugins and check which can be improved. Then, probably will need some help from the community to make an actual improvement.

**Comment by sanposhiho** [comment]
> I'll go thru all plugins and check which can be improved.

- InterPodAffinity
- NodeAffinity
- NodeResourceFit
- NodeUnschedulable
- PodTopologySpread

**Comment by sanposhiho** [comment]
@dom4ha maybe you want to pick up some? (I heard you were looking for a good starter task.)

cc @alculquicondor @macsko

**Comment by googs1025** [comment]
/cc

If possible, I would like to help.

**Comment by sanposhiho** [comment]
@googs1025 Thanks, please go ahead. Just leave a comment about which one you'll work on before starting (so that many people won't work on the same one)

**Comment by googs1025** [comment]
> @googs1025 Thanks, please go ahead. Just leave a comment about which one you'll work on before starting (so that many people won't work on the same one)
thanks. I want to confirm the requirements. Do I need to optimize the code of the following plugins?

**Comment by googs1025** [comment]
I think the focus should be on optimizing the isSchedulableAfterNodeChange method, right?

**Comment by dom4ha** [comment]
@sanposhiho Sure, I'm looking into it. Will let you know which plugin I can start with once I get a sufficient understanding.

**Comment by omerap12** [comment]
If possible, I would like to help :)

**Comment by sanposhiho** [comment]
@omerap12 Thanks, feel free to give it a tackle. 
(But, also note that it's not a beginner-friendly issue, as you don't see `good-first-issue`. It surely requires a certain level of understanding around the scheduler and specifically requeueing process.)

**Comment by dom4ha** [comment]
@sanposhiho thanks for the example. I think the overall idea is clear to me, so let me start looking into specific plugins now. I will get back to you once I have some specific questions

**Comment by dom4ha** [comment]
Let me tackle NodeAffinity plugin first.

**Comment by googs1025** [comment]
/assign 
NodeUnschedulable plugins

**Comment by dom4ha** [comment]
@sanposhiho started working on NodeResourceFit

**Comment by omerap12** [comment]
Gave my best shot :)

**Comment by googs1025** [comment]
InterPodAffinity plugins . I can also give it a try :)

**Comment by googs1025** [comment]
Sorry for the late post, I'm working on the InterPodAffinity PodTopologySpread plugin :sweat:

**Comment by googs1025** [comment]
Maybe there are other areas that need improvement in the plugin. I will check and browse in the next few days to confirm whether there are similar improvements needed and sort them out.

**Comment by sanposhiho** [comment]
Closing this as we merged all the necessary PRs. Thanks for all the effort, everyone! 🎉 

/close
