### ISSUE TITLE
[Umbrella] Make client-go lighter and easier to consume

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#127888]
### Description

The current structure of client-go, with its dependencies on k8s.io/api and k8s.io/apimachinery present some significant challenges:

* **Dependency bloat:** projects end up pulling in a large number of transitive dependencies, increasing binary size and potentially leading to conflicts.
* **Versioning headaches:** Updating client-go often necessitates updating the dependent projects as well, which can be complex and time-consuming, especially with the need for coordinated releases.
* **Tight coupling:** This structure creates tight coupling between client-go and the underlying API definitions, making necessary to update the clients to be able to use the new API types.

### How to repro

Using the workqueue example https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/workqueue and creating a new project, after doing `go mod tidy` the go.mod file looks like:

<details>
<summary>go.mod</summary>

```
module client-go-example

go 1.23

require (
        k8s.io/api v0.31.1
        k8s.io/apimachinery v0.31.1
        k8s.io/client-go v0.31.1
        k8s.io/klog/v2 v2.130.1
)

require (
        github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
        github.com/emicklei/go-restful/v3 v3.11.0 // indirect
        github.com/fxamacker/cbor/v2 v2.7.0 // indirect
        github.com/go-logr/logr v1.4.2 // indirect
        github.com/go-openapi/jsonpointer v0.19.6 // indirect
        github.com/go-openapi/jsonreference v0.20.2 // indirect
        github.com/go-openapi/swag v0.22.4 // indirect
        github.com/gogo/protobuf v1.3.2 // indirect
        github.com/golang/protobuf v1.5.4 // indirect
        github.com/google/gnostic-models v0.6.8 // indirect
        github.com/google/go-cmp v0.6.0 // indirect
        github.com/google/gofuzz v1.2.0 // indirect
        github.com/google/uuid v1.6.0 // indirect
        github.com/imdario/mergo v0.3.6 // indirect
        github.com/josharian/intern v1.0.0 // indirect
        github.com/json-iterator/go v1.1.12 // indirect
        github.com/mailru/easyjson v0.7.7 // indirect
        github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
        github.com/modern-go/reflect2 v1.0.2 // indirect
        github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
        github.com/spf13/pflag v1.0.5 // indirect
        github.com/x448/float16 v0.8.4 // indirect
        golang.org/x/net v0.26.0 // indirect
        golang.org/x/oauth2 v0.21.0 // indirect
        golang.org/x/sys v0.21.0 // indirect
        golang.org/x/term v0.21.0 // indirect
        golang.org/x/text v0.16.0 // indirect
        golang.org/x/time v0.3.0 // indirect
        google.golang.org/protobuf v1.34.2 // indirect
        gopkg.in/inf.v0 v0.9.1 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
        k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340 // indirect
        k8s.io/utils v0.0.0-20240711033017-18e509b52bc8 // indirect
        sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
        sigs.k8s.io/structured-merge-diff/v4 v4.4.1 // indirect
        sigs.k8s.io/yaml v1.4.0 // indirect
)
```
</details>

and its size is 

```
ls -lah main
-rwxr-x--- 1 aojea primarygroup 51M Oct  6 08:41 main
```

### Proposal

* **Modularization:** Breaking down client-go into smaller, more focused modules would allow users to import only the functionalities they need, reducing dependency bloat and improving maintainability.
* **Generic clients and Versioned APIs:** Providing generic clients that can use versioned API clients would enable users to target specific Kubernetes versions without being forced to update the entire client-go library.
* **Reducing dependencies:** eliminate unnecessary dependencies within client-go and its related projects.

#### k8s.io/api

Ideally this should be a self contained module without dependencies,  but it depends on apimachinery for the generated code and registering the types

https://github.com/kubernetes/kubernetes/blob/7b28a115ba04651bc31aa1d7089abbd67ec5c067/staging/src/k8s.io/api/go.mod#L3-L13

It requires `k8s.io/apimachinery` because of:

* schema
```
register.go:     "k8s.io/apimachinery/pkg/runtime"
register.go:     "k8s.io/apimachinery/pkg/runtime/schema"
zz_generated.deepcopy.go:        runtime "k8s.io/apimachinery/pkg/runtime"
```
* metav1
```
register.go:     metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
zz_generated.deepcopy.go:        v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```

* utils for types

```
"k8s.io/apimachinery/pkg/util/validation"
zz_generated.deepcopy.go:  intstr "k8s.io/apimachinery/pkg/util/intstr"
resource/v1alpha3/types.go:     "k8s.io/apimachinery/pkg/util/validation"
```

**NOTE** This validation can be easily avoided and it seems is only to match a constant  (cc: @pohly )

https://github.com/kubernetes/kubernetes/blob/7b28a115ba04651bc31aa1d7089abbd67ec5c067/staging/src/k8s.io/api/resource/v1alpha3/types.go#L186

#### k8s.io/apimachinery

This is the more tricky, and it is bringing a lot of dependencies

https://github.com/kubernetes/kubernetes/blob/7b28a115ba04651bc31aa1d7089abbd67ec5c067/staging/src/k8s.io/apimachinery/go.mod#L3-L33

#### k8s.io/client-go

These module contains all the generated code, the typed clients and the dynamic client. Thanks to @skitt we already have  [Generics to share code in client-go](#121439 )

In addition to the dynamic client we could have a Generic client, that will be able to work with different versions of k8s.io/api, allowing users to work with skew between k8s.io/client-go and  k8s.io/api, though this requires a very high bar on these modules to avoid breaking clients and provide stability across the ecosystem.

https://github.com/kubernetes/kubernetes/blob/7b28a115ba04651bc31aa1d7089abbd67ec5c067/staging/src/k8s.io/client-go/go.mod#L3-L37

#### Tasks

- [ ] remove unnecessary dependencies, per example, testing frameworks only offer cosmetic benefits but bring dependencies, despite they are not used to build the binary the make more noisy the dependency tree https://github.com/kubernetes/kubernetes/pull/127876
- [ ] consolidate, per example,  we have our own fork of go-yaml https://github.com/kubernetes-sigs/yaml/pull/76 so we can switch all the dependencies to it to have just one path and also avoid possible code drifting
- [ ] stricter rules for client-go and apimachinery exported code, @pohly  already has setup a job as optional https://github.com/kubernetes/test-infra/pull/33579
- [ ] 

### References

*  #124380 
*  #106846
* [Analyzing Go Binary Sizes](https://blog.howardjohn.info/posts/go-binary-size/)

#### Notes

I don't create a KEP because there are a considerable number of dimensions in this problem, so as first step I just want to gather feedback and take a more iterative approach, there are things like dependency pruning that can be worked out without a KEP, once we reach a point we need to implement some user facing change I will open the corresponding KEP

/area code-organization
/sig architecture
/sig api-machinery

**Comment by aojea** [comment]
Tagging some of the people I know will be interested/impacted
/cc @deads2k @liggitt @dims @fedebongio @jpbetz @BenTheElder @thockin @pohly @alvaroaleman @howardjohn

**Comment by pohly** [comment]
Here's one more thought: `k8s.io/client-go` contains lots of loosely connected packages. Would it make sense to break it apart into smaller modules?

If a simple Go client doesn't need `k8s.io/client-go/tools/record`, it shouldn't depend on `github.com/golang/groupcache/lru`.

I'm aware that this raises challenges for our publishing bot because we don't want to change the import paths. For example, if `k8s.io/client-go/tools/record` was its own module, where to we publish the code? Can `k8s.io/client-go/tools/record` redirect to `github.com/kubernetes/client-go-tools-record` or does `github.com/kubernetes/client-go` have to become a multi-module repository?

Can Go handle the transition of a package into its own module? For v0.31.0, `k8s.io/client-go/tools/record` has to be found as package in `client-go`. For a future release, it would have to be found as module.

**Comment by pohly** [comment]
> Here's one more thought: k8s.io/client-go contains lots of loosely connected packages. Would it make sense to break it apart into smaller modules?

Let me take this one step further: if we don't do this, how much can we really reduce the dependencies of client-go? It doesn't help to remove a dependency from e.g. `k8s.io/api` if `k8s.io/client-go` then still depends on that same dependency through something else. For example, how useful is https://github.com/kubernetes/kubernetes/issues/127889 for `client-go`? It will still depend on `apimachinery`.

**Comment by aojea** [comment]
> It will still depends on `apimachinery`.

that is the thing, if it does not depend on apimachinery, or if apimachinery is lighter,  or if we break apimachinery in smaller modules, ....

**Comment by pohly** [comment]
I agree that it makes sense to simplify.

But removing a dependency on "bar" from "foo" should not be based on the argument that it's being done to remove "bar" from the client-go dependency tree unless there really is a plan how that can be achieved.

**Comment by aojea** [comment]
why not, everything that removes dependencies that are not necessary helps

**Comment by pohly** [comment]
If some package becomes cleaner because it avoids some dependency, that's fine. But if it becomes more complex and client-go still depends on "bar", then it's a net loss.

**Comment by aojea** [comment]
> If some package becomes cleaner because it avoids some dependency, that's fine. But if it becomes more complex and client-go still depends on "bar", then it's a net loss

absolutely, goal is simplifying across the stack ,  as soon as things require more design and consensus we need a KEP with details ... but per example, since we have now a fork of go-yaml https://github.com/kubernetes-sigs/yaml/pull/76 we can switch all the dependencies to it to have just one path and also avoid possible code drifting ... things like this can help to reduce the problem scope

**Comment by skitt** [comment]
Related to simplifying across the stack, there are a number of in-progress transitions or duplications of code/effort in the tree. They don’t get much attention, and we tend to frown upon “blanket deprecation” PRs, but I do think it would be good to make progress on some of them, especially if they can help reduce dependency trees. For example, `k8s.io/utils/pointer` to `k8s.io/utils/ptr` (not significant here because it’s the same dependency); or `k8s/io/apimachinery/pkg/util/sets` and `k8s.io/utils/set` (client-go currently uses the former; the two aren’t quite equivalent, see https://github.com/kubernetes/utils/pull/294 in particular).

**Comment by skitt** [comment]
> Can Go handle the transition of a package into its own module? For v0.31.0, `k8s.io/client-go/tools/record` has to be found as package in `client-go`. For a future release, it would have to be found as module.

In my experience it works reasonably well. In theory, when a module is split out, the “main” module must declare a dependency on the new module, so that existing users aren’t broken on upgrades; but that defeats the purpose if the goal is to simplify dependency trees. `go get` usually figures out what’s going on as long as it doesn’t run into ambiguous imports.

**Comment by skitt** [comment]
#127889 makes me wonder if we could move parts of apimachinery that meet k8s.io/utils’ requirements to k8s.io/utils? apimachinery has a big set of dependencies, k8s.io/utils has a minimal set and is supposed to keep it that way. For example, all of apimachinery validation could be moved to k8s.io/utils if we move validation/fields, errors and sets too (for sets, replace it with k8s.io/utils sets).

Put another way, we’ve ended up with two repositories of dependency-less utilities in k8s.io, apimachinery and sets, sometimes with duplicates. I think it would help this overall endeavour if we decided where these should live.

**Comment by skitt** [comment]
Consolidating on sigs.k8s.io/yaml doesn’t help with the dependency tree, but it does improve consistency. See #127901

**Comment by howardjohn** [comment]
From my POV there are two aspects to 'light' -- low dependencies (less chance of dep hell, less licenses, etc), and smaller size (impacting final binary size which impacts end users).

WRT to the smaller size, a very substantial portion of this is due to basically any import of `client-go` bringing in **everything** in istio.io/api; you cannot just import `core/v1` for example. This requires pretty deep changes throughout a lot of things - the schema, setting up the base client stuff, etc. Somehow fixing this would cut binary sizes in half, even for packages that actually depend on a large number of APIs.

(Unfortunately, even in an optimal package layout, if you depend on the tiny ConfigMap you also depend on the huge Pod)

**Comment by howardjohn** [comment]
> From my POV there are two aspects to 'light' -- low dependencies (less chance of dep hell, less licenses, etc), and smaller size (impacting final binary size which impacts end users).
> 
> WRT to the smaller size, a very substantial portion of this is due to basically any import of `client-go` bringing in **everything** in istio.io/api; you cannot just import `core/v1` for example. This requires pretty deep changes throughout a lot of things - the schema, setting up the base client stuff, etc. Somehow fixing this would cut binary sizes in half, even for packages that actually depend on a large number of APIs.
> 
> (Unfortunately, even in an optimal package layout, if you depend on the tiny ConfigMap you also depend on the huge Pod)

To make this more concrete, this example https://github.com/howardjohn/k8s-client-go/blob/e0023d6daa2795430e532f5813108f8087ec2014/generics/example/main.go#L19 (which compiles) is 9.8Mb stripped, 15M unstripped. With an import of `k8s.io/client-go/kubernetes` its instead 30M/44M.

FWIW in a not-direct comparison, using kube-rs (rust), it is more like 7.6M/11M.

**Comment by BenTheElder** [comment]
> From my POV there are two aspects to 'light' -- low dependencies (less chance of dep hell, less licenses, etc), and smaller size (impacting final binary size which impacts end users).

One other aspect we're looking for is ease of switching Kubernetes API versions specifically, ideally the transport layer etc is pretty stable and you should be able to quickly adopt and implement custom behaviors for the new types without needing to update _any_ mess of dependencies, just a package with the types.

I've been thinking a bit about how we might approach this and avoid breaking anyone at the same time.

> Here's one more thought: k8s.io/client-go contains lots of loosely connected packages. Would it make sense to break it apart into smaller modules?

I would go a step further actually: some of this should be in non-staged libraries that are actually versioned and developed with stable consumption in mind in their own repos, rather than being "staged" out as unstable v0.x

But I think the first step is making it easier to consume the API types, with which you could bring your own client or skew the client (and use dynamic or a new generic API).

If I read https://github.com/kubernetes/kubernetes/issues/127888#issuecomment-2397384464 right, I think alvaro is roughly advocating for that part at least as well, and I have recently floated the concept to a few people (like antonio) who seem to agree.

We're in the middle of enhancements freeze right now and will probably all have more bandwidth for this soon, possibly even at KubeCon?

**Comment by dims** [comment]
With v1.34.0-alpha.3, the size dropped from 51 MB to 36 MB!
```
> ls -latrh m
-rwxr-xr-x@ 1 dsrinivas  staff    36M Jul 15 10:12 m
```

**Comment by dims** [comment]
```
❯ grep k8s.io go.mod
        k8s.io/api v0.34.2
        k8s.io/apimachinery v0.34.2
        k8s.io/client-go v0.34.2
        k8s.io/klog/v2 v2.130.1
        k8s.io/kube-openapi v0.0.0-20250710124328-f3f2b991d03b // indirect
        k8s.io/utils v0.0.0-20250604170112-4c0f3b243397 // indirect
        sigs.k8s.io/json v0.0.0-20241014173422-cfa47c3a1cc8 // indirect
        sigs.k8s.io/randfill v1.0.0 // indirect
        sigs.k8s.io/structured-merge-diff/v6 v6.3.0 // indirect
        sigs.k8s.io/yaml v1.6.0 // indirect
❯ ls -lah main
-rwxr-xr-x@ 1 dsrinivas  staff    37M Nov 28 19:40 main
```
