### ISSUE TITLE
Tracking: archive cloud-provider-sample repository and remove references

### ISSUE THREAD

**Issue by elmiko** [kubernetes/kubernetes#128294]
This issue is being created to help track the archiving of the github.com/kubernetes/cloud-provider-sample repository. During discussion at the [23 October SIG Cloud Provider office hours](https://www.youtube.com/watch?v=aXFkqfRMqd0), we decided that we would like to move forward with archiving this repository to reduce confusion about external cloud controller manager development.

The cloud-provider-sample repository was created 6 years ago with the intention of containing a sample implementation of the external cloud controller manager. Since then, the repository has not received any updates and a new sample has been created in the cloud-provider repository (see https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cloud-provider/sample)

As we would like to close the sample repository, and we do not feel it is appropriate to carry this issue on the cloud-provider repository, we are opening this issue to help us track the progress.

TODO
- [x] Update the cloud-provider-sample readme to indicate archive status (https://github.com/kubernetes/cloud-provider-sample/pull/15)
- [ ] Issue created on kubernetes/org to archive the repository
- [x] Update readme in new sample directory to indicate relationship with staging repository
- [ ] Update readme in cloud-provider repository to highlight the sample location
- [ ] cloud-provider-sample archived
- [x] Email sent to kubernetes-dev mailing list

/sig cloud-provider
/kind cleanup

**Comment by elmiko** [comment]
cc @bridgetkromhout @cheftako

**Comment by elmiko** [comment]
i wrote "kubernetes-dev" for the mailing list, but perhaps it only needs to be announced on the sig-cloud-provider list.
