### ISSUE TITLE
Compute resource metrics roadmap

### ISSUE THREAD

**Issue by mvdan** [kubernetes/kubernetes#14081]
As a means to keep track of what I am doing so that it is clear to others. 

* [x] Write proposal - #11951
* [x] Add apiserver experimental nodeMetrics resource endpoint - #12952
* [x] Write nodeMetrics resource endpoint client interface - also #12952
* [x] Add `util.Duration` type required to index time windows by duration - #14096
* [x] Add Heapster experimental nodeMetrics endpoint (to be used as data source) - kubernetes/heapster#549
* [x] Write program to periodically pipe metrics from a heapster to apiserver - kubernetes/heapster#549
* [x] Write rc config to run apiserver, etcd, heapster and the program above - kubernetes/heapster#549
* [ ] Make `kubectl` show resource metrics on nodes for cpu and memory

Extra steps to improve efficiency and move some of the workload to the kubelets:

* [x] Add instantaneous cpu metrics to cadvisor - google/cadvisor#861
* [ ] Improve kubelet metrics APIs (#12483)

CC @vishh

**Comment by vishh** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
If we add metrics to existing kubectl commands, such as describe pods, we need them to fail gracefully/silently in the case that the experimental metrics API is not enabled/present.

**Comment by mvdan** [comment]
Updated progress since the bridge between heapster and apiserver is now done, as well as the rc config. I'm pushing all of those to https://github.com/kubernetes/heapster/pull/549 too.

**Comment by vishh** [comment]
@mvdan: Can you publish your draft PRs that resolves some of the pending work items? I'm referring to the metrics service with a secondary api server, kubectl changes, etc.

**Comment by vishh** [comment]
Closing this issue since @piosz has picked up this effort.
