### ISSUE TITLE
Cover horizontal pod autoscaler controller with tests

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#14108]
- [x] add unittests for the controller #14034
- [x] add unittests for heapster metric client #14414
- [x] add e2e tests for autoscaling replication controllers #14811
- [ ] add e2e tests for autoscaling deployments

**Comment by jszczepkowski** [comment]
Closing this issue in favor of  #15474.
