### ISSUE TITLE
Tracking issue for 1.0/1.1 upgrade & version skew testing

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#14778]
(cc @quinton-hoole @mikedanese)

This is the consolidated tracking bug for upgrade & version skew testing for the transition from 1.0 to 1.1.

List of in-flight bugs, to be updated as things change:

- [x] P0: Fix GKE upgrade tests, and get them into the critical builds #13602
- [ ] P1: Fix GCE upgrade tests, and get them into the critical builds #14674
- [x] P1: Create sustainable testing for GKE & GCE upgrades and version skew #14771
- [ ] Discussion: Version skewed e2e tests #3334 (this is an old issue that should be closed as part of this effort)

**Comment by ihmccreery** [comment]
The following bugs have been submitted for failing tests (I'll update this list as I file more):

- [ ] Kubectl e2e tests leave resources running after stop during upgrade #15112

**Comment by davidopp** [comment]
@ihmccreery can you give an update on the status of this issue?

**Comment by ihmccreery** [comment]
This is just a tracking issue; see referenced issues for statuses.  Once #13602 is done, we can knock this down to a P1, unless we decide that #14674 should also be P0.

**Comment by lavalamp** [comment]
There is version skew in kubectl, does that belong in this tracking issue? https://github.com/kubernetes/kubernetes/issues/15702

**Comment by ihmccreery** [comment]
No, we decided that was distinct enough that it belongs in its own world.

**Comment by ihmccreery** [comment]
We've gotten v1.1.1 out, so I'm going to close this tracking bug, (the more specific bugs remain open,) in favor of #17263.
