### ISSUE TITLE
What do we do with 1.0 tests that fail when run against 1.1?

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15116]
This is a problem we're going to run into as we're running 1.0 e2e tests against 1.1 clusters, (which we do because we need to make sure that 1.1 clusters still operate the way 1.0 clusters did).  If a test fails, but the failure is due to a bad test rather than a problem in 1.1, what do we do?

For example, Services/Nodeport e2es are failing on upgrade due to change in error message.  They fail when running 1.0 e2es against a HEAD master (in jobs kubernetes-upgrade-gke-step3-e2e-old and kubernetes-upgrade-gke-step5-e2e-old):

-  Kubernetes e2e suite.Services should check NodePort out-of-range
```
Expected
    <string>: Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: invalid value '53127', Details: provided port is not in the valid range
to equal
    <string>: Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: invalid value '53127': provided port is not in the valid range
```

- Kubernetes e2e suite.Services should prevent NodePort collisions

```
Expected
    <string>: Service "nodeport-collision2" is invalid: spec.ports[0].nodePort: invalid value '31641', Details: provided port is already allocated
to equal
    <string>: Service "nodeport-collision2" is invalid: spec.ports[0].nodePort: invalid value '31641': provided port is already allocated
```

@ixdy @quinton-hoole Any ideas about how to fix this?  This definitely isn't a regression, but it's probably not a good idea to just disable these tests.  My best thought is to cherry-pick the 1.1 test changes into 1.0, and somehow pull these tests HEAD of the 1.0 branch.  That's a lot of mucking around though, and I'm not sure it's worth it.

For now, I think we should punt on these specific tests until we have a better idea of how widespread this kind of version-skew problem is going to be.

**Comment by ihmccreery** [comment]
(This is part of #14778)

**Comment by quinton-hoole** [comment]
@ihmccreery Yes, I think that's the right thing to do.  
I can't think of any other sensible choices than that. 
And definitely don't disable the tests for anything other than this specific version skew upgrade test run.   We definitely want them to be running continuously in the non-version-skewed case.

**Comment by ihmccreery** [comment]
Relevant stuff:

- [ ] Tests are failing because they don't take into account Graceful termination ([comment](https://github.com/kubernetes/kubernetes/issues/14674#issuecomment-151868744)).
- [ ] Tests are failing because of a test change in how we have BYO images (see #16427).
- [ ] API change (see #15948).
- [ ] Error message change (see #16434).

**Comment by davidopp** [comment]
@ihmccreery I believe all four issues you mentioned above have had fixes merged.

**Comment by davidopp** [comment]
Sorry, I misunderstood, your list wasn't a list of stuff to fix, it was examples of where we cherrypicked into 1.0. Never mind. :)

**Comment by ihmccreery** [comment]
This has been resolved via #19608 etc.
