### ISSUE TITLE
DaemonSet: requirements for graduation to beta and then to v1

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15310]
Forked from #14326

Before DaemonSet graduates from experimental:
- [x] It needs to adopt the more general selector, as discussed in #341. This would be very hard to change later.

Before DaemonSet reaches v1beta1, I'd like to see:
- [x] Rolling update as a service, similar in spirit to Deployment (#1743). For now, pod template updates are forbidden. However, DaemonSet should be declarative and should perform rollouts when its template is modified. I envision DaemonSet creating pod template resources behind the scenes instead of ReplicationController resources.
- [x] Revert #17318

Before DaemonSet reaches v1, I'd like to see:
- [ ] Either integration into the node controller in order to integrate with node lifecycle, such as creation before other pods can be scheduled and implicit forgiveness behavior (#1574), or use of initializers and finalizers (#3585) to achieve the same

@davidopp @mikedanese

**Comment by erictune** [comment]
@polvi as mentioned last week, DaemonSet can be used to start a process on every machine in a cluster, thus simplifying setup of things like monitoring and local-storage-daemons.   Documented at https://github.com/kubernetes/kubernetes/blob/ba89c98fc7e892e816751a95ae0ee22f4266ffa5/docs/admin/daemons.md

**Comment by erictune** [comment]
That is a good list of changes that you have thought of.

The best way to find changes that we haven't thought of yet is to use the feature ourselves.
I propose it doesn't graduate from beta until we are using it as part of the kube-up process.
I'll file an issue to that effect.

**Comment by erictune** [comment]
Filed #15324

**Comment by brendandburns** [comment]
I disagree.  If we think it is feasible for KubeUp, then it should _definitely_ be in beta.  If its useful for us, its useful for customers.

**Comment by erictune** [comment]
You have said that before it is beta, we need to be pretty sure we aren't going to change anything.  I don't think that we get to that level of sureness without actually using the interface ourselves.

**Comment by erictune** [comment]
Also, see description in #15324 about how to stage the work.

**Comment by erictune** [comment]
I might be misquoting @brendandburns, but we have definitely talked about a bar for beta stability internally, and I don't see how we reach that bar without using the feature in earnest.

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by bgrant0607** [comment]
DaemonSet won't be ready in 1.1.

In addition to the other issues mentioned, we need to think about interplay between DaemonSet updates and node upgrades.

**Comment by mikedanese** [comment]
We need to revert and fix #17318 before graduation.

**Comment by davidopp** [comment]
We need to fix #16967 (via #12744) before graduation.

**Comment by davidopp** [comment]
> Either integration into the node controller in order to integrate with node lifecycle, such as creation before other pods can be scheduled and implicit forgiveness behavior (#1574), or use of initializers and finalizers (#3585) to achieve the same

Proposal for how to do this (depends on #18263  being implemented)
1. Admission controller intercepts Node object creation and adds a taint "node being configured" 
2. DaemonSet controller automatically adds toleration for "node being configured" taint to all pods it creates
3. When all DaemonSets that should schedule onto the node have started, the taint is removed

(3) is the only tricky step. One idea is that we could have NodeController iterate through all DaemonSet objects, figure out which ones should result in a pod on the given node (due to label selectors not all daemons are supposed to run on all nodes), and when all of those are running remove the taint. 

This doesn't require moving DaemonSet controller into NodeController.

Of course this is all related to https://github.com/kubernetes/kubernetes/issues/3885#issuecomment-146002375

**Comment by mml** [comment]
For the implicit forgiveness part, the idea is that all DaemonSet-managed pods implicitly forgive the node going unreachable, but not any other type of node deletion or cascading delete event.

Correct?

**Comment by davidopp** [comment]
> For the implicit forgiveness part, the idea is that all DaemonSet-managed pods implicitly forgive the node going unreachable, but not any other type of node deletion or cascading delete event.

Yeah, this is just addressing what happens when NodeController deletes pods because the NodeReady  became False or Unknown. But did you have something specific in mind when you said "other type of node deletion or cascading delete event" ?

**Comment by mml** [comment]
I can't think of a cascading delete that would result in deleting a node, but if the admin manually deletes a node with kubectl, we'd still delete the pod, right?

Also to be clear, I'm not planning to do this by exposing the Forgiveness concept anywhere in the API (it's not well-enough formed yet), but just by hardcoding this behavior into the NodeController when the pod in question is DaemonSet-managed.

**Comment by mikedanese** [comment]
We still need to revert #16478 and #17318

@davidopp is anyone working on #12744? Do we need to pick this up?

**Comment by bgrant0607** [comment]
#20232 (drain shouldn't kill daemons) is also needed.

**Comment by bgrant0607** [comment]
Plan for 1.2:

* remove update-related fields from the API (comment them out in at least extensions/v1beta1/types.go)
* permit DaemonSet to be updated but not automatically propagate those changes to pods, as with ReplicationController
* finish the other planned behavioral fixes mentioned above
* enable DaemonSet by default and declare it beta

There would be no rolling-update implementation, but the user could implement a simple shell loop to kill all the daemon pods and the DaemonSet would then replace them. Since implicit forgiveness for daemons has been implemented, this approach isn't nearly as unsafe as it is for ReplicationController.

We can add rolling updates in 1.3 without breaking compatibility by adding the behavior I proposed above as the default update strategy.

cc @madhusudancs

**Comment by davidopp** [comment]
I assume "the behavior I proposed above" means updating the PodTemplate would roll out the update one node at a time? Is it possible to also add pause/resume, revision history, rollback, and status in 1.3?

**Comment by bgrant0607** [comment]
@davidopp "The behavior I proposed above" means updating the pod template would not roll out the update.

**Comment by davidopp** [comment]
My understanding is that everything is done here for 1.2, so I'm moving to next-candidate.

**Comment by madhusudancs** [comment]
@davidopp yeah, everything proposed for 1.2 is done.

**Comment by erictune** [comment]
Can someone summarize what remains to be done for GA?

**Comment by bgrant0607** [comment]
Re. GA:

* Update orchestration
* Coordination with node lifecycle (including node upgrades)
* Guaranteed scheduling

**Comment by lukaszo** [comment]
Is anyone working on Update orchestration? If not, me(or someone from team kubernetes/mirantis) can work on it. Does it require creating a spec?

**Comment by mikedanese** [comment]
@lukaszo yes a proposal would be a good place to start as the feature is pretty involved. There have been a couple attempts to implement this that have not succeeded.

**Comment by lukaszo** [comment]
@mikedanese Can you describe these attempts? I only saw one one kubectl side.

**Comment by mikedanese** [comment]
I feel like there were two kubectl and one server side. Server side one here: https://github.com/kubernetes/kubernetes/pull/19627

**Comment by piosz** [comment]
@bgrant0607 @erictune can me make sure that before going to GA someone (fluentd or node-problem-dectector) will actually use this for a quarter or two, to make sure that for example upgrades are handled properly?

**Comment by bgrant0607** [comment]
@piosz I agree. I don't want to rush any of the controller APIs to GA. I wish Job hadn't been rushed to GA.

**Comment by liggitt** [comment]
cc @kow3ns

**Comment by bgrant0607** [comment]
DaemonSet is v1.
cc @kow3ns @janetkuo
