### ISSUE TITLE
Replace swagger-ui by our static api reference docs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#15915]
List of issues with swagger-ui (kubernetes.io/third_party/swagger-ui/):
* Very slow (https://github.com/swagger-api/swagger-ui/issues/1455)
* XSS issues (https://github.com/swagger-api/swagger-ui/issues/830)

List of issues we need to fix with static api reference docs (http://kubernetes.io/v1.0/api-ref.html), before we can eliminate swagger-ui:
- [x] gen-swagger-doc should read local swagger spec rather than reading the spec from github (https://github.com/kubernetes/kubernetes/issues/15905)
- [x] Add a test that verifies that the reference docs are updated (https://github.com/kubernetes/kubernetes/issues/14069)
- [ ] cross links dont work when generated docs are viewed using htmlpreview (https://github.com/kubernetes/kubernetes/issues/15910), making them useless on HEAD. Note that they work fine on kubernetes.io, making them usable for release docs.
- [x] Add an api-ref README (https://github.com/kubernetes/kubernetes/issues/16049)
- [x] Disable /swagger-ui on api server (https://github.com/kubernetes/kubernetes/pull/23025)

Other issues (not blocking the migration):
- [x] Ignore last updated timestamp changes https://github.com/kubernetes/kubernetes/issues/16121

cc @caesarxuchao @bgrant0607

**Comment by bgrant0607** [comment]
SGTM

**Comment by lavalamp** [comment]
@bgrant0607 Is this really needed for 1.2?

**Comment by bgrant0607** [comment]
@lavalamp If the swagger-ui doesn't show the resources in new API groups I think we should remove it.

**Comment by nikhiljindal** [comment]
Swagger-ui should display the new API groups fine once we have updated the swagger spec on kubernetes.io.

The slowness and XSS issues mentioned originally will remain.

**Comment by lavalamp** [comment]
@nikhiljindal Can we just remove this? Or update it. Need to get the XSS off of our site.

**Comment by caesarxuchao** [comment]
I checked the subtask that we've finished and we still have two issues left. I assigned #16049 to myself. #15910 seems to be intrinsic to htmlpreview and is unsolvable.

I think the api-references docs have covered most functionalities of swagger-ui, so we can remove swagger-ui if it still has its problems.

**Comment by lavalamp** [comment]
I would vote for removal at this point.

**Comment by lavalamp** [comment]
Kicking out. This doesn't need to go into our release, it's just on our website.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/23080 fixes this
