### ISSUE TITLE
Job: requirements for graduation to stable 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15985]
- [x] task queue example (#15982)
- [x] parallelism greater than completions (#18876)
- [x] Delete pods when delete (#16255)
- [X] Generating a unique label by default #12298

Not blocking: Indexed Job (#14188), and other issues listed in #14186

**Comment by erictune** [comment]
- Delete pods when delete (#16255)

**Comment by erictune** [comment]
- Excessive 409s. Self-conflict in controller manager. #16134

**Comment by erictune** [comment]
* task queue example (#15982)

**Comment by erictune** [comment]
- [Delete a Job can't cleanup the completed pods it created #16255

**Comment by erictune** [comment]
@bgrant0607 is Controllers-v2 really a graduation-to-stable requirement for jobs?  Seems pretty ambitious.

**Comment by bgrant0607** [comment]
@erictune The v2 features are not. I just wanted to think a little bit about any would result in breaking changes that couldn't be handled by API versioning. If I can't find time, I wouldn't block on it.

**Comment by davidopp** [comment]
>  either do Indexed Job (#14188) or decide not to do it

I assume you mean "decide not to do it for 1.2" -- I think we definitely we want to do it in a general sense.

**Comment by erictune** [comment]
Put up a proposal for Indexed Job in issue #18260.

**Comment by erictune** [comment]
Job would benefit from automatically generating a unique label by default #12298

This should maybe be in for graduation, or at least ensure we can add later without API breakage.

**Comment by pikeas** [comment]
Is bumping docker to 1.8.x or 1.9.x on deck for 1.2? It was flagged for the 1.1 milestone as a P1, but there's very little movement on the relevant open issues, and 1.2 is on its fourth alpha.

**Comment by erictune** [comment]
Closed by #18876

**Comment by erictune** [comment]
Based on experience with supporting several users in the last week, I now think it is essential to add Job "generating a unique label by default #12298".  After more thought, I think the best way to add is with a breaking API change, which I will explain in that issue.  That means that Job needs one more change before graduation.  Reopening.  I plan to have this in by end of week.

**Comment by erictune** [comment]
## Status update

Moving job to new api group (batch) turned out to be much more complex than expected.  Worked with @lavalamp @caesarxuchao @nikhiljindal and copied work of @piosz to do this.  Many side issues came up along the way.

I have a change pending which is based on #20501.  Need @lavalamp to review #20501 as any review comments in there will affect the PR I am preparing.

Once Job is moved to batch, there will be another PR that changes the Job API to have the new selector generation.  Since last update, selector generation has been designed (described here: https://github.com/kubernetes/kubernetes/blob/master/docs/design/selector-generation.md).

A plan for conversion from extensions/v1beta1 to batch/v1 was proposed, but is under discussion (https://github.com/kubernetes/kubernetes/pull/21354).

I've worked out the plan to deprecate extensions/v1beta1.Job (https://github.com/kubernetes/kubernetes/issues/20951#issuecomment-183144882)

I'm trying hard to get Job-in-batch/v1 for friday's cut, but it is going to be pretty close.

Also, I am out sick, so things are going slower than usual.

**Comment by lavalamp** [comment]
#20501 is merged now. :)

**Comment by erictune** [comment]
Yep, working on rebase.  Also have fuzzer and testapi related errors I cannot figure out.  May ask for help.

**Comment by erictune** [comment]
Latest is in #21434

**Comment by erictune** [comment]
A big chunk merged: #21434
One more, smaller PR in progress.

**Comment by erictune** [comment]
Last PR is #21776
