### ISSUE TITLE
Release mechanics issues

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16773]
Now that #16102 is in, I'm consolidating #15483 and #13339 here, since they're mostly the same work at this point.  There's a lot of stuff, but it's mostly one-liners, wording changes, etc.

Remaining work:

  - [x] `build-official-release.sh` doesn’t work for prereleases (#16865)
  - [x] Add note to output of `release/cut-official-release.sh` to do stuff in a separate window or tab, like we have in `release/build-official-release.sh`
  - [x] `release/cut-official-release.sh` and `release/build-official-release.sh` should use `mktemp`. (#16865)
  - [x] clarify when GitHub releases should be marked as latest release versus pre-release (#16930)
  - [x] Docs in release language need to point to branch, not tag, per @bgrant0607 (#16930)
  - [x] we should probably just never call a release “Candidate"; it's confusing what's a candidate and what's not (#16930)
  - [x] use ./ notation for ./release/build-release.sh (#16930)
  - [x] `push-official-release.sh` doesn’t work for prereleases (#16919)
    - Note that `kube::release::gcs::verify_release_gt` doesn't know how to compare with pre-releases, so it needs to look a lot more like `kube::release::gcs::verify_ci_ge`, (and we should consider collapsing them somehow).

Lower priority or bigger issues:

  - [x] Not doing any release notes for beta, since it’s not clear from where we’d start them.
    - Yup, I don't think this is a problem.
  - [x] `release/latest-1` and `release/latest-1.0` didn’t get updated to 1.0.7; we should investigate why and fix it.
    - I believe this was just an artifact of our tooling not being used.  As long as we follow instructions in the future, we should be good.
  - [x] “Copying release artifacts to gs://kubernetes-release/ci/v1.2.0-alpha.3/“ sometimes hangs, maybe when `gcloud` isn't up-to-date?  This needs further investigation.
    - Filed #16936.
  - [x] There should be a review process built into releasing beyond just the dry-run.
    - Filed #16934.
  - [x] `push-official-release.sh` doesn’t check for a valid CI version until after publication, when trying to do version comparison; it should fail fast if it's trying to push a version that's not valid, instead of uploading and then complaining.
    - Filed #16937.

@quinton-hoole @fgrzadkowski FYI

**Comment by ihmccreery** [comment]
Another lower priority thing that may be worth doing:

- [ ] Move tooling to kubernetes/contrib repo

**Comment by ihmccreery** [comment]
I'm closing this as other issues exist for the stuff that hasn't been done.
