### ISSUE TITLE
Develop Deployment UX equivalent to kubectl rolling-update

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#17168]
Forked from https://github.com/kubernetes/kubernetes/issues/12143

Now that we have deployment resource, we should use that in kubectl rolling-update, instead of maintaining duplicate client side logic.

cc @ironcladlou @janetkuo @bgrant0607

**Comment by janetkuo** [comment]
My plan on this: 

To replace the client logic, in `kubectl rolling-update`, the given rc will be labeled with Deployment's UniqueLabelKey (looks like `deployment.kubernetes.io/podTemplateHash=2189917884`), and then a deployment for this rc with desired template will be generated, and then deployment will finished the rest of the logic. 

If the deployment and the label is already there, just update the deployment's template. 

To rollback, just update the deployment's template to the old rc's. 

After rolling-update, do we need to clean up the generated deployment?

**Comment by nikhiljindal** [comment]
The user experience should not change:
* We should print out scaling up/down events as we do now (We can watch for events and display them)
* The deployment process should stop if users press ctrl C. (Not sure how will we do this)
* The controller should not make any more changes once the process ends (Delete the deployment when deployment.status.replicas=deployment.status.updatedReplicas=deployment.spec.replicas)

IIRC, @bgrant0607 had also suggested that we can introduce a new `kubectl rolling-update deployment` command and define a new experience there.

**Comment by kargakis** [comment]
> The deployment process should stop if users press ctrl C. (Not sure how will we do this)

Setup a listener for SIGINT (https://golang.org/pkg/os/signal/#Notify)

> The controller should not make any more changes once the process ends (Delete the deployment when deployment.status.replicas=deployment.status.updatedReplicas=deployment.spec.replicas)

Wouldn't it be more appropriate to set the deployment as inert (first we have to actually support inert) instead of deleting it?

> IIRC, @bgrant0607 had also suggested that we can introduce a new kubectl rolling-update deployment command and define a new experience there.

I think this wouldn't be a new command, but rolling-update could support handling deployments.

**Comment by kargakis** [comment]
> I think this wouldn't be a new command, but rolling-update could support handling deployments.

Hm, this is the issue in question:) Maybe you are referring to something else... Nvmd

**Comment by janetkuo** [comment]
Another candidate is `kubectl deploy`.

**Comment by kargakis** [comment]
> Another candidate is kubectl deploy.

cc: @ironcladlou 

`kubectl deploy` would also be helpful in kicking inert deployments.

**Comment by kargakis** [comment]
@janetkuo did you start working on this? I think you need to use the resource builder with ResourceNames for the first  argument (we currently do a simple [GET](https://github.com/kubernetes/kubernetes/blob/a5100ef05726237e4e1f44997852963c955b608c/pkg/kubectl/cmd/rollingupdate.go#L175)) so we will be able to continue supporting current behavior
```
$ kubectl rolling-update nginx-1 -nginx-2 --image=nginx:v2
```
but also support flows like 
```
$ kubectl rolling-update deployment/nginx --image=nginx:latest
```
Thoughts?

**Comment by janetkuo** [comment]
Per earlier discussion with @nikhiljindal and @bgrant0607, to support legacy rolling-update behavior with deployment is hard, and instead we can introduce deployment somewhere else, such as `kubectl deploy`. What's more, `kubectl rolling-update` doesn't take resource type (it assumes the only resource for rolling-update is rc), so it's another thing to think about if we want to add deployment to rolling-update.

**Comment by janetkuo** [comment]
We'll have a proposal for this.

**Comment by krmayankk** [comment]
Mainly regarding Deployment history, here are a few more things i need clarification on.

--What is the timeline for getting the deployment history implemented. I need to make something work in the next two months so if this is taking longer than that i would start implementing it on my own.
--for any resource and for Deployment in particular, the way i understand is that resourceVersion is the version of the observed state of the resource and not the desired state. For the desired state of the resource, the versioning is generation, which it seems like is not implemented yet for Deployment resource. Please confirm. 

--For deployment version proposal here https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deploy.md#deployment-version, i don't understand why we are depending on annotations in Replication Controller to track deployment history. RC can be deleted, except the one actively servicing the active pods, i would imagine keeping the deployment history in the deployment object itself may be as annotations. RC is just a construct that is brought up to handle rolling updates if there is only a single RC otherwise it uses an old RC. Thoughts ?Everytime a deployment is successful we can add a annotation to the deployment object and may be use the second highest version or the specified version to roll back. Please help me understand.

**Comment by janetkuo** [comment]
@krmayankk I answered your question on google group. Here I paste my answers:

1. This will be included in release 1.2.
2. You're right. generation isn't implemented yet for Deployment.
3. The RCs won't be deleted when you do deployment rolling updates. The replicas of old RCs will only be set to 0. These RCs, which include podTemplate copied from deployment, are seen as snapshots of different versions of the deployment. We want to decouple an object and the objects it creates (a replication controller and its pods is another example). Imagine that a deployment is deleted and then re-created. The deployment will still be able to observe existing RCs and know its deployment history.

**Comment by kargakis** [comment]
> The RCs won't be deleted when you do deployment rolling updates.

Depends on the cleanup policy: https://github.com/kubernetes/kubernetes/pull/19590

**Comment by janetkuo** [comment]
Summarize related PRs:

**Deployment API**:
- [ ] Rollback
  - [ ] Add version information to deployments (#19581)
  - [ ] Add deployments/rollback subresource & add rollback logic to deployment controller (#19686)
- [ ] Pause/inert deployment (#18901)
- [ ] Perm-failed deployment (#19343)

**kubectl**:
- [ ] kubectl rollout (#19882)
  - [ ] kubectl rollout undo (#19835) *(depends on rollback #19581 & #19686)*
  - [ ] kubectl rollout history (#19893) *(depends on rollback #19581 & #19686)*
  - [ ] kubectl rollout pause *(depends on pause #18901)*
  - [ ] kubectl rollout resume *(depends on pause #18901)*
  - [ ] kubectl rollout status
  - [ ] kubectl rollout retry *(depends on perm-failed #19343)*

**Comment by kargakis** [comment]
I can probably do `rollout pause` and `rollout resume` after the pause PR is merged. @bgrant0607 

I will also do `rollout retry` later once perm-failed is in.

**Comment by kargakis** [comment]
rollout pause/resume PR: https://github.com/kubernetes/kubernetes/pull/20087

**Comment by bgrant0607** [comment]
This is done enough for 1.2, so moving to next milestone.

The main outstanding feature for parity IMO is "kubectl set image".

**Comment by bgrant0607** [comment]
There's a separate issue for set, and I'd like to wait for user feedback re. status, so closing.
