### ISSUE TITLE
Switch to use `GroupVersion` in APIs and structs

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#17216]
Switching to use the new `GroupVersion` type will make our code flows much easier to read and debug as we try to determine which information is contained in particular strings.  Choosing a single struct field or interface method and chasing ripples out one or two levels produces a pull of moderate size that is pretty easy to review and easy to rebase as other changes go in.  After we think we've gotten the big items done, we can start chasing `.String()` and `.ParseGroupVersion` references down to eliminate them.

I'm lifting the a starting list from https://github.com/kubernetes/kubernetes/pull/17185, but I think we should break it down by particular fields and/or methods.  Some may make sense to work at the same time, but 

Inflight:
- [x] `StatusDetails` should contain group and version @deads2k https://github.com/kubernetes/kubernetes/pull/18526

Remaining:
- [ ] NewNotFound, NewForbidden
- [ ] `thirdPartyResourceDataMapper`
- [ ] FuzzerFor
- [ ] RESTScope in the apiserver needs to have a internal GVK to convert to
- [ ] scale.get
- [ ] fakeclient.action

Unnecessary due to other pulls:
- [x] pkg/client/unversioned/clientcmd/api/types.go, `Config.APIVersion`, `Cluster.APIVersion` @janetkuo was working on this separately
- [x] `api.Scheme.AddFieldLabelConversionFunc` @smarterclayton's encoder work
- [x] pkg/conversion/meta.go, `UpdateVersionAndKind()` @smarterclayton's encoder work
- [x] ConvertFieldLabel @smarterclayton's encoder work
- [x] ConvertToVersion @smarterclayton's encoder work
- [x] pkg/runtime/scheme.go, `Recognizes()`, `EncodeToVersion()` @smarterclayton's encoder work
- [x] SetVersionAndKind @smarterclayton's encoder work
- [x] generateConvertMeta @smarterclayton's encoder work
- [x] InternalVersion @smarterclayton's encoder work
- [x] fromScope @smarterclayton's encoder work
- [x] pkg/conversion/encode.go, `EncodeToVersion()` @smarterclayton's encoder work
- [x] pkg/api/meta/interfaces.go, `{TypeInterface|MetadataAccessor}.{APIVersion|SetAPIVersion}`; pkg/api/meta/meta.go, `genericAccessor` @smarterclayton's encoder work

Followup:
- [ ] pkg/api/types.go, `ObjectFieldSelector.APIVersion`, `TypeMeta.APIVersion` - uncertain
- [ ] pkg/runtime/types.go, `TypeMeta.APIVersion` - uncertain
- [ ] prevent parsing empty groups unless the version is v1.  This will cleanup tests.
- [ ] swagger spec files aren't qualified in /api/swagger-spec
- [ ] stop abbreviating `gvk`.  https://github.com/kubernetes/kubernetes/pull/18379#discussion_r47100949

Completed:
- [x] InterfacesFor @deads2k https://github.com/kubernetes/kubernetes/pull/18370
- [x] CodecFor @deads2k https://github.com/kubernetes/kubernetes/pull/18373
- [x] NewObject @deads2k https://github.com/kubernetes/kubernetes/pull/18379
- [x] `ClientCache.ClientForVersion` @deads2k https://github.com/kubernetes/kubernetes/pull/18384
- [x] `ClientCache.ClientConfigForVersion` @deads2k https://github.com/kubernetes/kubernetes/pull/18384
- [x] admission.NewAttributesRecord @deads2k https://github.com/kubernetes/kubernetes/pull/17972
- [x] pkg/apiserver/apiserver.go, `APIGroupVersion.Version` `APIGroupVersion.ServerGroupVersion` @deads2k #17227
- [x] requestScope @deads2k - https://github.com/kubernetes/kubernetes/pull/17956
- [x] `NewDefaultRESTMapper` @deads2k https://github.com/kubernetes/kubernetes/pull/17327
- [x] `DefaultRESTMapper.Add` @deads2k https://github.com/kubernetes/kubernetes/pull/17327
- [x] `RESTMapper.GroupForResource` @deads2k https://github.com/kubernetes/kubernetes/pull/17335
- [x] ObjectTyper @deads2k https://github.com/kubernetes/kubernetes/pull/17796
- [x] pkg/client/unversioned/helper.go, `Config.APIVersion` @deads2k https://github.com/kubernetes/kubernetes/pull/17316
- [x] pkg/client/unversioned/restclient.go, `RESTClient.apiVersion`, `RESTClient.APIVersion()` @deads2k #18022
- [x] `NewRESTClient` @deads2k https://github.com/kubernetes/kubernetes/pull/18022
- [x] Request.apiVersion @deads2k https://github.com/kubernetes/kubernetes/pull/18022
- [x] `testapi.Default.GroupAndVersion()` @deads2k https://github.com/kubernetes/kubernetes/pull/17982
- [x] `testclient.ObjectRetriever` @deads2k https://github.com/kubernetes/kubernetes/pull/17432
- [x] `objects.Kind`
- [x] `RESTMapper.RESTMapping` @deads2k https://github.com/kubernetes/kubernetes/pull/17232
- [x] `registered.RegisteredVersions` @deads2k https://github.com/kubernetes/kubernetes/pull/17319
- [x] `Scheme.KnownTypes` @deads2k  https://github.com/kubernetes/kubernetes/pull/17515
- [x] `Scheme.ObjectVersionAndKind` @deads2k
- [x] `GroupMeta.GroupVersion`, ``GroupMeta.GroupVersions`, `GroupMeta.InterfacesFor` @caesarxuchao #17326
- [x] remove `GroupMeta.Version`, `GroupMeta.Group` @caesarxuchao #17326
- [x] `Decoder` @deads2k https://github.com/kubernetes/kubernetes/pull/17432
- [x] pkg/conversion/scheme.go, `Scheme.versionMap`, `Scheme.typeToVersion`
- [x] pkg/runtime/interface.go, every methods that have `version string` as input. [updated]
- [x] DataVersionAndKind
- [x] pkg/kubectl/explain.go, `GetSwaggerSchema()` @deads2k https://github.com/kubernetes/kubernetes/pull/18024
- [x] `DescriberFor` @deads2k https://github.com/kubernetes/kubernetes/pull/17798
- [x] `ScalerFor` @deads2k https://github.com/kubernetes/kubernetes/pull/17798
- [x] `NewVersionedPrinter` @deads2k https://github.com/kubernetes/kubernetes/pull/18024
- [x] `OutputVersion` @deads2k https://github.com/kubernetes/kubernetes/pull/18024
- [x] `OutputVersionMapper` @deads2k https://github.com/kubernetes/kubernetes/pull/18024
- [x] all `SchemeGroupVersion` variables should be made correct.
- [x] allow `queryToObject` to properly fall back to external unversioned.

@liggitt @caesarxuchao

**Comment by deads2k** [comment]
@liggitt  are you willing to help review this work?  There will be a lot of it.

**Comment by liggitt** [comment]
> @liggitt are you willing to help review this work? There will be a lot of it.

Sure, @caesarxuchao and I can probably tag team on individual PRs

**Comment by deads2k** [comment]
I think that in the end, we shouldn't have any calls to `.String` and `.ParseGroupVersion`.  That will allow us to find and stomp all the ripples as we start by converting at the edges.

**Comment by caesarxuchao** [comment]
Sounds right. Thank you! I'll take the latest package today.

**Comment by caesarxuchao** [comment]
@deads2k I hope you don't mind I updated the list with one new entry (search for "[updated]"). May I add entries into the list as I find more?

**Comment by deads2k** [comment]
> @deads2k I hope you don't mind I updated the list with one new entry (search for "[updated]"). May I add entries into the list as I find more?

please do.

**Comment by caesarxuchao** [comment]
Sorry I was working on other things last Friday. I will work on refactoring the `latest` package today.

**Comment by bgrant0607** [comment]
There's a high bar for touching TypeMeta. What is the specific change to TypeMeta that is proposed and what is the compelling justification?

**Comment by caesarxuchao** [comment]
@bgrant0607 
We are passing around the "group/version" and "version" string in our code base and it's hard to reason whether a string should be "group/version" or "version" only. Hence we are going to pass a GroupVersion struct around instead.

TypeMeta.APIVersion is the root of all "group/version" string, so we are going to change it from a string to unversioned.GroupVersion:
```
type TypeMeta struct {
	Kind		string    `json:"kind,omitempty"`
	APIVersion	unversioned.GroupVersion `json:"apiVersion,omitempty"`
}
```
There will be no change to the on-wire format as we've made a special marshalling function for it: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/group_version.go#L88

**Comment by deads2k** [comment]
> There's a high bar for touching TypeMeta. What is the specific change to TypeMeta that is proposed and what is the compelling justification?

I consider all the other points higher priority.  Is that the only sticking point?  If so, I'd be in favor of splitting `TypeMeta` into its own issue so the rest of this issue can move ahead.

**Comment by caesarxuchao** [comment]
@deads2k, in one of the above PRs, you split internal types according to their groups when registered to the Scheme. It just occurred to me this *perhaps* will cause problems to the unversioned types in pkg/api/unversioned/. Specifically, we currently register them to "", https://github.com/kubernetes/kubernetes/blob/master/pkg/api/register.go#L73, shall we register them to other groups' internal as well?

**Comment by deads2k** [comment]
> Specifically, we currently register them to "", https://github.com/kubernetes/kubernetes/blob/master/pkg/api/register.go#L73, shall we register them to other groups' internal as well?

I don't think we'll have trouble, but if we do, I think we want to resolve the problem by allowing cross group dependencies.  It is very useful to be able to depend upon other types in other groups.

**Comment by caesarxuchao** [comment]
@deads2k, I'm refactoring the discovery API to use the GorupVersion struct, specifically this field: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/types.go#L347.

**Comment by deads2k** [comment]
> @deads2k, I'm refactoring the discovery API to use the GorupVersion struct, specifically this field: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/types.go#L347.
> 
> The ripple should be small, so I plan to directly change the type definition.

I definitely agree in principle that the field should be strongly typed.  I'm not sure we want to use the same `GroupVersion` to indicate kind and resource metadata as we want to include in API types.  It makes our dependency chain a little unusual to look at down in the scheme and conversion layers.  The direct dependency on any API type down in a `Codec` feels strange.

@smarterclayton In your encoding work, did you also come to the conclusion that we want one `GroupVersion` type for handling metadata descriptions and a separate one for representing the concept in serialized types?

**Comment by caesarxuchao** [comment]
I think @smarterclayton feels the same way: https://github.com/kubernetes/kubernetes/pull/17515#issuecomment-160832323

I agree we should have runtime#GroupVersion and unversioned#GroupVersion. I'm uncertain where is the boundary though.

**Comment by smarterclayton** [comment]
I think we want to keep field serialization format totally separate from
our internal types.  Field serialization objects will have protobuf and
json serializers on them - over time they will accumulate other things that
make them unsuited to be passed around as generic typers.

My goal is to move all type aware code out of the conversion package.  At
that point, only runtime scheme knows about objectversionkind.  Unversioned
would stop being a dependency of conversion, and instead the direction
would flip the other way (our api objects have a dependency on runtime/,
the way it used to be)

**Comment by deads2k** [comment]
made it! :)

**Comment by caesarxuchao** [comment]
@deads2k Thanks!

Should we change TypeMeta.APIVersion to type GroupVersion?

**Comment by liggitt** [comment]
I'm not sure that would be worth the ripples.

**Comment by smarterclayton** [comment]
I would prefer we do this in 1.3 or later.  It's not required for
correctness, and isn't really going to improve internal code quality.
