### ISSUE TITLE
Add support for disk accounting 

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#17331]
Based on #16889 

This issue tracks support for basic disk accounting in kubernetes. Specific work-items are as follows:
## Core Features
- [x] du works today. Use du for all the categories and ensure that it works on both on aufs and overlayfs - [cAdvisor [#962](https://github.com/google/cadvisor/pull/962)]
- [ ] Add device mapper support - [cAdvisor [#959](https://github.com/google/cadvisor/issues/959)]
- [x] Track disk usage of localhost volumes in kubelet. [kubernetes [19741](https://github.com/kubernetes/kubernetes/pull/19741)]
- [x] Define a disk manager module in kubelet that will serve as a source of disk usage information for the rest of the kubelet. [kubernetes [19741](https://github.com/kubernetes/kubernetes/pull/19741)]
- [x] Ensure that the kubelet metrics APIs (`/stats/summary`) exposes the disk usage information. Add an integration test. [kubernetes [19932](https://github.com/kubernetes/kubernetes/pull/19932)]
- [x] Maintain references to originally created Volumes instead of generating from scratch #19741
- [x] Support caching fs metrics in the MetricsProvider #19741
- [x] Expose disk usage information through heapster  
## Clean up items
- [x] Eagerly cache the fs disk results in the resource analyzer.  [kubernetes [19741](https://github.com/kubernetes/kubernetes/pull/19741)]
- [ ] Permanently cache ReadOnly fs metrics in the Volume object. Volume objects are re-created on updates
- [x] Add Fs metric support for Secrets [kubernetes [19741](https://github.com/kubernetes/kubernetes/pull/19741)]
- [ ] Performance test metrics api 
- [ ] Disambiguate metrics error from "not supported" #20676
- [ ] Prevent expensive metrics collection for a pod from impacting other pods collection and kubelet performance #20675
- [ ] Disambiguate pod volume stats are "empty" from "not yet available" #20679
## Nice to haves
- [ ] volumes that wrap other volumes should delegate
- [ ] Expose disk usage via kubedash (stretch).

**Comment by vishh** [comment]
@pwittrock: Can you keep this issue updated periodically?

**Comment by LongTu** [comment]
@vishh Hi, I was trying to work on this issue. 
1. Do you know what is the json schema of disk usage information? Is it like: struct {nodeName string, usage uint64}? May I put it in /pkg/kubelet/cadvisor/types.go?
2. For the  (/apis/metrics/v1beta1) to expose disk usage information, Is there any document/examples to do it? (it seems that the src code already have pkg/apis/componentconfig/v1alpha1, but when i do a "curl localhost:8080/api/componentconfig/v1alpha1" from k8s master node,  the response says "the server could not find the requested resource". Is it because this endpoint was turned down somewhere in the config/code?)

**Comment by vishh** [comment]
cc @pwittrock

**Comment by timothysc** [comment]
Is this really targeted for v1.2?  /cc @kubernetes/rh-storage

**Comment by vishh** [comment]
@timothysc: Yes. @pwittrock and I are working on this.

@LongTu:

> 1. Do you know what is the json schema of disk usage information? Is it like: struct {nodeName string, usage uint64}? May I put it in /pkg/kubelet/cadvisor/types.go?
https://github.com/google/cadvisor/pull/1035

2. For the (/apis/metrics/v1beta1) to expose disk usage information, Is there any document/examples to do so? (it seems that the src code already have pkg/apis/componentconfig/v1alpha1, but when i do "curl localhost:8080/api/componentconfig/v1alpha1" from k8s master node, the response says "the server could not find the requested resource". Is it because this endpoint was turned off somewhere in the config/code?)

Metrics API on the API server is still a WIP. Until that is available, we will expose disk metrics via kubelet and heapster APIs. 

If you'd like to help out, I'd suggest picking up adding support for computing container's write layer usage with devicemapper and btrfs in cAdvisor.

**Comment by dchen1107** [comment]
@vishh and @pwittrock I am closing the issue for 1.2 milestone since

* Overlayfs support was in cAdvisor library
* new kubelet metrics APIs (/stats/summary) exposes the disk usage information already.  

Thanks!

**Comment by vishh** [comment]
@dchen1107: We are using this issue to track some of the pending cleanup work. Let's keep it open until all the work-items mentioned above are resolved.

**Comment by dchen1107** [comment]
Ok, in this case, I removed 1.2 milestone from this one.
