### ISSUE TITLE
[Proposal] Make Kubernetes run on ARM devices

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#17981]
**Edited to reflect current status**
Since Kubernetes is written in Go, it's possible to add support for ARM devices like Raspberry Pi.
I have done this, it's published here: https://github.com/luxas/kubernetes-on-arm
And it would be great to merge this to mainline k8s.

This work focuses on making it **easier for other architectures too**, like `arm64` and `ppc64le`

TODO:
 - [x] Upgrade to ~~`go1.5`~~ `go1.6`: #22149
 - [x] Compile ARM binaries on every CI build and for every release. #19769!
 - [x] Compile ARM64 and ppc64le binaries on every CI build and build images for every release. #22149
 - [x] Use the `gcr.io/google_containers/binary-arch:version` names for images. Discussions: #19061, #23059, #23009
 - [x] Make `etcd` cross-platform: #19216 
 - [x] Add a `gcr.io` flannel image that uses `quay.io/coreos/flannel:version` for `amd64` and cross-compile for other architectures. #21617 
 - [x] Merge the PR that pushes docker images (including `hyperkube`) when releasing. #19061
 - [x] Edit the `hyperkube` Makefile to support ARM. #21617 
 - [x] Make `skydns`,  `kube2sky` and `exechealthz` cross-platform. #19376, https://github.com/kubernetes/contrib/pull/646
 - [x] Add a k8s-in-docker deployment (like #13901) that supports multiple architectures https://github.com/kubernetes/kube-deploy/pull/12
 - [x] Update `docker-multinode` instructions: #18894
 - [x] Update `docker` guide to support other architectures also. https://github.com/kubernetes/kubernetes.github.io/pull/407
 - [x] Write a multiarch proposal #26863 
 - [x] Build `dashboard` for ARM (`gcr.io/google_containers/kubernetes-dashboard-arm`)
 - [x] Make `pause` totally cross-platform (and written in C). #23059, #23009
 - [x] Be able to detect server platform #19905
 - [x] Label nodes with os/arch #23684

Status of multiarch images:
Get docker-multinode working:
 - gcr.io/google_containers/hyperkube, **fixed for all** #21617, #22149
 - gcr.io/google_containers/etcd, **fixed for all** #19216, #22149
 - gcr.io/google_containers/flannel, **fixed for all** #21617, #22149
   - Depends on `gcr.io/google_containers/debian-iptables`, **fixed for all** #21617
 - gcr.io/google_containers/pause, **fixed for all** #23009

Get DNS working:
 - gcr.io/google_containers/kube2sky, **fixed for all** #19376
 - gcr.io/google_containers/skydns, **fixed for all** #19376
 - gcr.io/google_containers/exechealthz **fixed for all** https://github.com/kubernetes/contrib/pull/646

Docker wrapped Kubernetes binaries:
 - gcr.io/google_containers/kube-proxy, **fixed for all** #21617, #22149
 - gcr.io/google_containers/kube-apiserver, **fixed for all** #19769, #22149
 - gcr.io/google_containers/kube-controller-manager, **fixed for all** #19769, #22149
 - gcr.io/google_containers/kube-scheduler, **fixed for all** #19769, #22149
 - gcr.io/google_containers/kubelet, doesn't really exist yet: #19177

I worked with the dashboard team, and it has had multiarch support from the first release.
I'm maybe gonna add multiarch support for official heapster too, now when it has reached v1.
On [kubernetes-on-arm](http://bit.ly/1U5nBgx), I already have heapster, influxdb and grafana nicely running as a cluster addon.

> Things to have in mind:
>  - All binaries have to be compiled for ARM, and therefore a common naming structure is important
>    - @brendandburns has already proposed this as `binary-ARCH:VERSION`, which is logical
>    - Also, `etcd` and `flannel` should be built. `etcd` is already in `cluster/images/etcd`, maybe `flannel` could be included there also? Pushed to `gcr.io/google_containers/flannel`
>  - One big question is how they should be compiled
>    - It might be possible to compile ARM images on a `amd64` machine.
>      - https://github.com/dweinstein/dockerfile-qemu-arm-chroot
>      - https://github.com/moul/docker-binfmt-register
>      - https://github.com/golang/go/issues/13024 `go1.5.2` is probably going to support `qemu`
>    ~~- Cross-compilation doesn't work AFAIK, because e.g. `hyperkube` needs to be built dynamically, and one can't build ARM docker images on `amd64`~~
>  - ~~Also all docker images must be compiled on ARM (except those `FROM scratch`)~~
>  - Base docker images have to be chosen
>  - One deployment method that would fit well for Raspberry Pis is `k8s-in-docker`
>    - I'm using a `k8s-in-docker`-like setup combined with `systemd` services. I've also written a `kube-config` script that handles the whole process.
>    - https://github.com/kubernetes/kubernetes/pull/13901
>  - Bugs and patches
>    - ~~Sometimes, things fail (randomly) on ARM.~~
>    - Example: https://github.com/kubernetes/kubernetes/issues/17060
>    - Often, it's easy to patch. ~~But there should be a specific place for ARM patches.~~
>  - GOARM values
>    - It's difference between `armv6` and `armv7` when compiling. We will have to set `ENV GOARM=6` when we compile the images, so e.g. `Raspberry Pi 1` is supported.
> Outdated tasks:
>  - Use `qemu` emulation for `hyperkube` and `flannel` cross-building `Makefile`s. #21617 
>    - Related: https://github.com/resin-io-projects/armv7hf-debian-qemu

I thought about making a proposal earlier, and now when #17629 was merged, it might be time

/cc
@dalanlan (`k8s-in-docker` interest)
@resouer (`k8s-in-docker` interest)
@guybrush (`k8s-in-docker` interest)
@davidopp (who was involved in #17629)
@roberthbailey (who was involved in #17629)
@zmerlynn (who was mentioned in #17629)
@DieterReuter (interested in Raspberry Pi things)

**Comment by luxas** [comment]
I've digged into this a little bit more, and here are the results: 
 - `hyperkube` **must** be compiled dynamically, I tested it and it exited if it was built statically:
```
Error: failed to create kubelet: cAdvisor is unsupported in this build
failed to create kubelet: cAdvisor is unsupported in this build
```
 - `armbuild/debian`, which is the image currently used for ARM, doesn't work on ARMv6
   - the reason why `armbuild` fails is probably because the packages are built for ARMv7
   - the other option would be `resin/rpi-raspbian` which is a very good debian image
 - Now I may run any ARM docker image on my `amd64` machine. This is very interesting.
   - I'm using moul's binfmt-register. However, it should only be able to run and compile binaries with go 1.5.2 or newer.
   - If we use this method, we could compile the binaries dynamically for ARM on a `amd64` machine.
   - Some drawbacks though:
     - We can't use the normal `kube-build:cross` method as it is right now. It just cross-compiles statically. So just adding `linux/arm` to server platforms in `hack/lib/golang.sh` won't work.
     - Only the go base image must be built on a real ARM machine. That's because, using `qemu` we can't compile `go1.4.3`, which is required for `go1.5.2`. The chicken-or-egg problem.
   - So if we create a `gcr.io/google_containers/golang-arm:v1.5.2` (maybe with some other prefix) and build that on a ARM machine, we could build all binaries on `amd64`

So here are some questions for you to answer
 - Should I start working on a `WIP: Kubernetes on ARM` PR?
 - Is it acceptable to include `flannel` in `cluster/images` and maybe build them there? The same method as `skydns`...
 - Is using `qemu` for building ARM things OK?
 - Should ARMv6 be supported? That would be great. You've already set `GOARM=5` in `kube-build:cross`
 - Could we switch `armbuild/debian` for `resin/rpi-raspbian` or some other ARMv6 compatible image?

**At least I would like to discuss these things**
Just say if you don't want this functionality at this time in Kubernetes
Personally, I don't think it's that good to promote usage of k8s on Pis on your blog when you have to hack things for it to work (on the other hand, it's very fun :smile:)

**Comment by ihmccreery** [comment]
@brendandburns I know you were working on some Pi stuff; want to chime in here?

**Comment by luxas** [comment]
Yes #17629
> I thought about making a proposal earlier, and now when #17629 was merged, it might be time

@ihmccreery At least, should I start writing on the ARM docs?
E.g. about what's different with ARM and what needs to be customized.

There are lots of folks who want this, and since 1st Oct, things like [my project](https://github.com/luxas/kubernetes-on-arm) or self-made hacks are the only way of doing this.
Lets do this!

**Comment by ihmccreery** [comment]
Assigning to @brendandburns to advise.

**Comment by brendandburns** [comment]
@luxas I have a working Raspberry PI cluster and have built a bunch of ARM binaries for various pieces.  I'm happy to advise and review the PRs..

We can keep this open as a tracking issue.  Please assign the PRs to me.

**Comment by luxas** [comment]
@brendandburns Are you OK with using `resin/rpi-raspbian` instead for `armbuild/debian` for `ARMv6` compability?
And how about including `flannel` besides `etcd` in `cluster/images`?

**Comment by luxas** [comment]
@brendandburns Great news! I've been able to compile all kubernetes binaries on my `amd64` laptop.
This makes ARM building a lot easier and faster, and the ARM binaries works on both `ARMv6` and `ARMv7` (aka RPi 1 and 2)

The code is [here](https://gist.github.com/luxas/e319b314f22b18243b1d) and it uses `golang:1.5.2` as the base image. I could test if it also works with `golang:1.4-cross`, which you are using today.

`hyperkube` and `flannel` is built **dynamically** for ARM on `amd64` thanks to some libraries [described here](https://wiki.debian.org/CrossToolchains)

I also think it would be possible to build ARM docker images on `amd64` (only images with `COPY` works today) using `qemu`
Here is a blog post about that: https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

WDYT?

**Comment by ihmccreery** [comment]
cc @david-mcmahon

**Comment by bgrant0607** [comment]
Quite a few people have made K8s run on Raspberry Pi:
http://blog.kubernetes.io/2015/11/creating-a-Raspberry-Pi-cluster-running-Kubernetes-the-shopping-list-Part-1.html
https://raspberrypicloud.wordpress.com/2015/08/11/how-to-kubernetes-multi-node-on-raspberry-pi-2s/
http://www.jinkit.com/k8s-on-rpi/
https://github.com/skippbox/k8sonpi
https://github.com/andrewpsuedonym/Kubernetes-Arm-Binaries

**Comment by luxas** [comment]
Yes, I know. (Cool, the jinkit blog post is about my project)
I'm one of them: https://github.com/luxas/kubernetes-on-arm (on Github since 1st Oct). 
The difference is that my project has the most features with addons, sd card writing, `kube-config` and such.
But it would be best if we could get this into k8s mainline.
#19376 would be a great next step to merge

**Comment by luxas** [comment]
Yay, major milestone! #19769 was merged :)
And k8s is now easily buildable for `arm64` and `ppc64le` if one uses `go1.5.2` or higher since #19712 and #20546

**Comment by luxas** [comment]
Again, a major milestone was merged for cross-platform Kubernetes: #21617
When the `v1.3.0-alpha.2` release is out, one is able to run Kubernetes on ARM by following the [`docker`](http://kubernetes.io/docs/getting-started-guides/docker/) guide.

**Comment by coryjamesfisher** [comment]
@luxas Thanks so much for the work you and the others have put into this. I was smacking my head against the wall trying to get Kubernetes running on a rpi 3 last night using the guide... Then I saw your comment this morning so I changed the k8 version number to the latest alpha and everything just works :) Thank you thank you thank you :)

**Comment by luxas** [comment]
@david-mcmahon How is the release note writing process for v1.3 managed? 
It would be really great to mention a few words about the new non-business-supported architectures in the v1.3 release notes, ideally both on the blog and in the changelog.
WDYT? Please respond when you're seeing this and if you want me to write a short summary, just ping me

**Comment by roberthbailey** [comment]
Release notes are handled in a few chunks. There are the auto-generated notes from github labels that are bundled up since the last release. And there are hand-curated release notes, which this falls under. Please write up what you'd like to see and send it to @david-mcmahon

**Comment by luxas** [comment]
@david-mcmahon Did you get my email message I sent some days ago?

**Comment by david-mcmahon** [comment]
@luxas Yes and I replied.

**Comment by luxas** [comment]
Yes, thanks!
Looking forward to see the full release notes for v1.3 :smile:

**Comment by luxas** [comment]
For everyone interested, arm binaries has been released for kubernetes since v1.2.

For v1.2.x, use my project kubernetes-on-arm v0.7.0
For v1.3.x, use docker-multinode or kubernetes-on-arm v0.8.0
For v1.4.x, use kubeadm

You may also read https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multi-platform.md

I consider this work done since a while ago thanks to the linked PRs above.
Still, there are work to do mentioned in the proposal, but the original issue `Make Kubernetes on ARM devices` has worked "officially" since v1.2.x, which is more than a half year ago, so closing this issue
