### ISSUE TITLE
Tracking Issue Storage Layer Cleaning.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#18542]
The work for isolating storage is complete, but there are a series of follow on items for completeness:
- [x] Cleanup: remove etcd references that have proliferated through the code #17546
- [ ] Test example, for in-memory data store 
- [ ] Documentation on howto add a new data store
- [ ] Requirements for different resource objects (write latency, durability, watch/triggers etc.) 
- [x] Create new store integration that meets requirements of resource object(s). 

/cc @kubernetes/sig-scalability @abhgupta

**Comment by wojtek-t** [comment]
Thanks for writing this down @timothysc 

Regarding requirements - the thing that we can't forget about is Watch - we can't use storage that doesn't support that...

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by timothysc** [comment]
So this was originally around the etcd3 work, which has long since been done.  closing.
