### ISSUE TITLE
Tracking Issue HA endpoint annotation locking 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#18553]
Below is the list of follow up items per HA discussion with @mikedanese @bgrant0607 @davidopp as action items post #16830 
- [ ] better defaulting and validation
- [ ] add useful observational stats in the leader record
  - [x] number of master transitions
- [ ] e2e test
- [ ] #18386
- [x] scheduler and controller-manager integration
- [ ] delete podmaster
- [ ] update HA docs (no fencing, etc.)

**Comment by mikedanese** [comment]
A subset of these should get done before v1.2.

**Comment by davidopp** [comment]
@mikedanese are you working on this? It's marked as 1.2 milestone.

**Comment by bgrant0607** [comment]
@timothysc @mikedanese Is this issue obsolete?

**Comment by timothysc** [comment]
yeah.. closing.
