### ISSUE TITLE
[User Story] 3x Number of Pods Per Node

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#19094]
- [x] Hung docker daemon yet kubelet remains in 'Ready' status - https://github.com/kubernetes/kubernetes/issues/17525
- [x] RFC: Determine the scalability goal for v1.2 kubelet - https://github.com/kubernetes/kubernetes/issues/16943
- [ ] Evaluate the benefits of adopting docker event stream - https://github.com/kubernetes/kubernetes/issues/16831
- [ ] Container garbage collection should define MinAge as age since the container termination - https://github.com/kubernetes/kubernetes/issues/13562
- [x] Some thoughts about the pod/container abstraction in kubelet -  https://github.com/kubernetes/kubernetes/issues/12619
- [x] Improve kubelet's scalability and performance -  https://github.com/kubernetes/kubernetes/issues/12540
- [X] Kubelet using expensive /containers/json?all=1 call - https://github.com/kubernetes/kubernetes/issues/17959
- [ ] Change scheduling complexity from O(containers) to O(nodes) - https://github.com/kubernetes/kubernetes/issues/18831

**Comment by goltermann** [comment]
@aronchick I'm pushing this out of v1.2.  We've achieved the 100 pods per node goal, though not via closing each of these subissues.

**Comment by yujuhong** [comment]
I am closing this. The work was done in 1.2, and the rest of the open issues in the lists are not that relevant.
