### ISSUE TITLE
Unit tests are EXTREMELY flaky lately

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19167]
It's bad. kubertest-test-go suite failed 5 consecutive times because of it.

@thockin @davidopp @brendandburns @bgrant0607 @dchen1107 @fgrzadkowski @wojtek-t @nikhiljindal @aronchick

Known Issues:
- [x] pkg/master #19141 (fixed by @wojtek-t in #19195)
- [x] pkg/util/wait #19067 (maybe fixed by @wojtek-t in #19196)
- [ ] pkg/storage/etcd, pkg/registry/generic/etcd #18928
- [x] pkg/apiserver #19176
- [ ] pkg/client/record/event_test.go #19151
- [ ] k8s.io/kubernetes/contrib/mesos/pkg/runtime #19186
- [x] pkg/util/wait: #19223
- [ ] pkg/client/unversioned/portforward #19230
- [ ] plugin/pkg/scheduler/factory #19229
- [ ] pkg/storage #19254
- [ ] pkg/client/record #19268

**Comment by smarterclayton** [comment]
Also https://github.com/kubernetes/kubernetes/issues/19176

**Comment by wojtek-t** [comment]
And also: https://github.com/kubernetes/kubernetes/issues/19151
[Looking into that issue, I think I've seen a different failure coming from that package]

**Comment by thockin** [comment]
This needs to be a drop-everything situation.  It's really bad.

**Comment by wojtek-t** [comment]
Agree - I already fixed some of them and debugged some, but there is more to be done here.

**Comment by wojtek-t** [comment]
And also: https://github.com/kubernetes/kubernetes/issues/19223

**Comment by thockin** [comment]
Appreciate your work on them, I know you disappear soon.

On Fri, Jan 1, 2016 at 1:40 AM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
It seems that we are on much better shape now.
The biggest issue responsible for 90%+ of all flakes now is #18928 - and I think that we should temporarily fix by by merging #19187 - it seems that although it's pretty ugly hack, it seems to solve the problem (I tested it 20+ times on Jenkins and it never failed on that race - before it was failing within 5 runs).

**Comment by timothysc** [comment]
@gmarek - 

1.5 seems to be exposing a number of behavioral oddities in jenkins, but does anyone know why *no one* can seem to repro many of the cases locally.

**Comment by gmarek** [comment]
At least for some of those issues the answer is load. Plus I don't think we found any jenkins oddity yet - all things were genuine bugs in tests.

**Comment by davidopp** [comment]
These tracking issues are really hard to deal with as (1) they go stale quickly, and (2) it's never clear who to assign them to if we've decided to parallelize investigating the individual failures. Can we close this issue and just rely on the kind/flake label for tracking?

**Comment by wojtek-t** [comment]
+1 - I agree that having individual issues is better (note that we already have them - this is just spanning 5+ different existing issues)
