### ISSUE TITLE
AWS kube-up should mirror GCE kube-up

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20643]
The AWS kube-up and the GCE kube-up diverged over time as GCE added functionality.  We should try to get them working similarly - I am going to try to get this into 1.2.

In particular, I want to make sure that:

1. Node and master reboot work properly on AWS (some reports that they sometimes don't)
1. In place upgrade works properly on AWS
1. We build secrets & certs as part of kube-up, paving the way for HA master
1. We run salt on each of the nodes, ending the dependency on salt-master and making for a faster boot
1. kube-push works properly on AWS (less important?)

The completed PoC is in #19799.

Steps:

- [x] Start extracting shared functionality out of cluster/gce/util.sh -> cluster/common.sh (done #19776)
- [x] Extract out certificate builder function into common.sh (#20642)
- [x] Change AWS instance-boot script to share script with GCE, likely by using override-method hack for the moment (in progress; cleaning up #19799)

**Comment by paralin** [comment]
I can start testing this and providing PRs if you are interested.

**Comment by justinsb** [comment]
Initial work here is done:  kube-up on master re-uses much of the GCE infrastructure!

We still need to verify:
* rebooting master node works great
* kube-push (although I think even on GCE we use a different script now?)
* in place upgrades (probably via the e2e tests)

@paralin please feel free to test - I'm reasonably sure kube-up works for normal scenarios, but those 3 remaining tasks are important (and are sorted easiest to hardest)

**Comment by paralin** [comment]
I'll have a look at this. Our prod code under Kubernetes runs on GCE, but we still use AWS for some existing services. Will try spinning up some clusters and report back.

Might not be able to get that done for a few days though.

**Comment by davidopp** [comment]
ping

**Comment by justinsb** [comment]
The work here is done, I believe (at least enough to cut the branch).  There are still some open PRs that need to land, and lots more testing to be done.

**Comment by davidopp** [comment]
@justinsb Can you list the relevant PRs so we know when we can close this or at least downgrade it to P2? Thanks!

**Comment by justinsb** [comment]
Two issues: kube-push doesn't work, and in-place upgrade.  Going to close this and open dedicated issues.
