### ISSUE TITLE
v1.0 upgrades to v1.2: outstanding issues

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21699]
This is just an overview of outstanding issues, many of which should be straightforward-ish cherry picks.

- v1.2 Kubectl against v1.0 cluster
  - [x] **Kubectl client Kubectl run deployment should create a deployment from an image [Conformance]** is failing (should be resolved with #21423).
- v1.0 e2es against a v1.2 master
  - [ ] **Events should be sent by kubelets and the scheduler about pods scheduling and running** (same as #19724, just a name change)
  - [ ] **MaxPods Validates MaxPods limit number of pods that are allowed to run** (same as #19724, just a name change)
  - [ ] **DNS should provide DNS for the cluster** (#19726, just a forward-incompatible test)
  - [ ] **Services should check NodePort out-of-range** (same as #19723, just an error message change)
  - [ ] **Services should prevent NodePort collisions** (same as #19723, just an error message change)
- v1.2 e2es against a v1.2 cluster, after upgrade
  - [x] **Deployment paused deployment should be ignored by the controller** failing (flake, see #21698)
  - [ ] **HPA tests** failing (should be the same as #20925, might have to backport some configs)

**Comment by ihmccreery** [comment]
A lot of these issues are going to be tough to solve, because v1.0 doesn't have any semver capabilities.  I'm skeptical that we want to put engineering effort into adding that extra dependency for a release that's so far out of date. cc @roberthbailey

**Comment by ihmccreery** [comment]
Okay, I'm ~confident that none of the outstanding issues are release blockers.  The question now is just if we want to get a good signal going forward that v1.0 clusters work upgraded to and version-skewed with v1.2.  Like I said above, that would take a lot of engineering effort, so I'm not to worried, and I definitely don't think it's a release blocker.

**Comment by ihmccreery** [comment]
There are a few v1.2 tests failing on v1.2 clusters after upgrading from v1.0:

- [x] Kubectl client Kubectl apply should apply a new configuration to an existing RC (#22996?)
- [ ] Services should be able to up and down services (#23060)
- [ ] Services should serve multiport endpoints from pods [Conformance] (#23060)
- [x] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ... (#20925; HPA light tests are passing, and the node size is configured wrong—will fix tests soon)

**Comment by ihmccreery** [comment]
Closing as obsolete.
