### ISSUE TITLE
Master Metrics API

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#23376]
This is na umbrella issue for Master Metrics API effort which will provide resource usage metrics for pods and nodes through the API server. The list of working items contains:
- [x] proposal with types definition #24253
- [x] add types to `metrics` api group https://github.com/kubernetes/heapster/pull/1151
- [x] add support for types/operations in Heapster https://github.com/kubernetes/heapster/pull/1152, https://github.com/kubernetes/heapster/pull/1161, https://github.com/kubernetes/heapster/pull/1163
- [x] migrate HPA (and possible other components) to use new types #25768
- [ ] [optional] figure out a way (possibly a hacky one) to proxy request to Heapster from api server and implement it
- [ ] [optional] migrate HPA to use Master Metrics API instead of querying Heapster directly
- [ ] [optional] implement kubectl top #11382

Providing generic mechanism for 3rd party api providers in api server is out of the scope of this effort.

**Comment by piosz** [comment]
cc @davidopp @erictune @fgrzadkowski @mwielgus

**Comment by vishh** [comment]
@piosz: Since the basic control plane metrics don't have to be persisted in etcd, have you considered pushing metrics directly to a secondary API server from the kubelet? 
If we were to store metrics only in memory, and also support batch updates from individual nodes to update metrics for all the pods in a node at once, would that work?
cc @davidopp

**Comment by erictune** [comment]
Allowing for the type of flexibility that @vishh was a reason I pushed for the summary metrics to only be point-in-time and not historical (i.e. you can restart an in-memory server and not worry about losing history).

**Comment by piosz** [comment]
This is one of possible solution. I'd like to define scope and requirements first and then think about the design.

**Comment by nikhiljindal** [comment]
This looks like something that Ubernetes can use as well.
We need cluster level metrics in ubernetes to make scheduling decisions for each cluster.
For now, we are planning to get metrics from each node in the cluster and then aggregate them together in a controller. We can switch to this new API whenever it is ready.

@kubernetes/sig-cluster-federation

**Comment by vishh** [comment]
@nikhiljindal Is there a relevant ubernetes issue?

**Comment by huangyuqi** [comment]
Hi, @vishh , I am working on Ubernetes recently.
In ubernetes' design, metrics(CPU/MEM) in cluster level need to be collected, and used to make scheduling decisions.
In my experience, the heapster has `Cluster-level Metrics`, like this:

```
/api/v1/model/metrics/: Returns a list of available cluster-level metrics.
/api/v1/model/metrics/{metric-name}?start=X&end=Y: Returns a set of (Timestamp, Value) 
pairs for the requested cluster-level metric, between the time range specified by start and end
```

So, @nikhiljindal , In my opinion , current heaspter can match our require about the cluster metrics. How do you think?

**Comment by nikhiljindal** [comment]
@vishh There wasnt any issue specific to getting metrics for ubernetes. It was touched upon at https://github.com/kubernetes/kubernetes/pull/23430#issuecomment-202768265.

I have filed one just now: https://github.com/kubernetes/kubernetes/issues/23614

@huangyuqi I will copy your comment there. We can discuss it further there.

**Comment by davidopp** [comment]
> For now, we are planning to get metrics from each node in the cluster and then aggregate them together in a controller.

I highly recommend you not do this. I'll follow up on the other issue.

**Comment by piosz** [comment]
All required steps are done, so closing the issue.

**Comment by pwittrock** [comment]
@piosz

Would you provide an update on the status + ETA for the documentation for this feature as well as add any PRs as they are created?

Not Started / In Progress / In Review / Done

Expected Merge Time:

Thanks
@pwittrock

**Comment by pwittrock** [comment]
@piosz If there are no user facing changes in v1.3 for this, then we do not need to document it.  If it changes existing user-facing behavior / apis or adds new user-facing capabilities to Kubernetes, we should document somewhere on the kubernetes.io site.

It sounds like there are no user-facing changes for Kuberenetes v1.3 for this issue.  Is that correct?

**Comment by piosz** [comment]
That's true.

**Comment by smarterclayton** [comment]
Which issue will we use to track the metrics API being available as a first class api?  Should we discuss this in the next @kubernetes/sig-api-machinery call?

**Comment by quinton-hoole** [comment]
cc: @mwielgus re: Federation cross-cluster load-based scheduling.

**Comment by piosz** [comment]
I will send a proposal and create an issue with work plan.

**Comment by piosz** [comment]
I created an issue #31784 for the further work
