### ISSUE TITLE
Kubelet: Switch to Docker engine-api and add timeout for all docker calls

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#23563]
From the first release of Kubernetes, we have been using [go-dockerclient](https://github.com/fsouza/go-dockerclient). It is reliable and updated frequently. However, we still met some problems when using it:
* **No operation timeout.** Functions in go-dockerclient don’t have timeout. Once the Docker daemon hangs, these caller will also hang forever. (Related issues: #9896, #13934, #21029, #21821, #22259 etc.)
* **No compatibility guarantee.** It's not official Docker client. After each Docker release, community people gradually find and fix compatible issues. (Related issue: #19720 etc.).
* **Missing features.** Some wanted features are not supported by go-dockerclient yet. (Related issue: image pull progress #19077 etc.)

Docker [engine-api](https://github.com/docker/engine-api) is the official Golang client for the Docker remote api. It has **cancellable operations**(All the functions use [Context](https://golang.org/x/net/context)), **official support**(The Docker CLI itself is relying on it) and **the same feature set with Docker CLI**. So, we decided to switch to docker engine-api.

[`DockerInterface`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L58) is an abstract interface containing a subset functions of go-dockerclient. Kubelet uses it whenever talking to docker. To switch to engine-api, we must refactor all the functions in `DockerInterface` which will touch a lot of code.
To avoid a huge refactoring in one PR, we'll split the refactoring into several steps:
- [x] Implement the original `DockerInterface` with the engine-api. [#23506]
- [x] Refactor the functions in the DockerInterface one by one, and add unit test for complex functions [#24748]:
  - [x]	ListContainers [#23699]
  - [x] InspectContainer [#23699]
  - [x] CreateContainer [#23699]
  - [x] StartContainer [#23699]
  - [x] StopContainer [#23699]
  - [x] RemoveContainer [#23699]
  - [x] InspectImage [#23800]
  - [x] ListImages [#23800]
  - [x] PullImage [#23800]
  - [x] RemoveImage [#23800]
  - [x] Logs [#23907]
  - [x] Version [#23907]
  - [x] Info [#23907]
  - [x] CreateExec [#23907]
  - [x] StartExec [#23907]
  - [x] InspectExec [#23907]
  - [x] AttachToContainer [#23907]
- [x] Add timeout and timeout handling in all docker calls. [#24918]
  - [ ] https://github.com/kubernetes/kubernetes/issues/25356#issuecomment-217974344 Add kubelet flag making the image pulling timeout configurable.
- [ ] Optional: Leverage the image pull progress information and other new features of engine-api if any.

/cc @kubernetes/sig-node

**Comment by resouer** [comment]
Nice to have this! :+1:

**Comment by resouer** [comment]
Image related is ready in #23800, except `PullImage`

**Comment by MHBauer** [comment]
I'd like to help with this effort. It looks like most of the work is done for the various endpoints, but I will look at the PRs and help review them.

**Comment by Random-Liu** [comment]
@MHBauer Thanks a lot! Really appreciate your help~ :)

**Comment by derekwaynecarr** [comment]
@Random-Liu - I think we need to set ShmSize now when using docker engine-api for create container.  see: https://github.com/kubernetes/kubernetes/issues/24588  , let me know thoughts and I will send a PR.

**Comment by dchen1107** [comment]
I think this is done.

**Comment by Random-Liu** [comment]
@dchen1107 Yeah, the only thing left is "Add kubelet flag making the image pulling timeout configurable." @wojtek-t Do we still need that? If so, I can add it soon. :)
