### ISSUE TITLE
Loadbalancing umbrella issue

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24145]
A non-comprehensive list ordered by an approximation of priority. Mostly for documentation and reducing bus factor:
- [ ] Source IP Preservation for external LB services (#28647)
- [x] Run ingress controller as static pod on master (https://github.com/kubernetes/kubernetes/issues/23663)
- [ ] Fix beta limitations ([gce](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md), [nginx](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#limitations))
- [ ] Improve e2es (write a single generic E2E for nginx/aws/gce)
- [x] Let different controllers co-exist AKA ingress claims (https://github.com/kubernetes/kubernetes/issues/24393, https://github.com/kubernetes/kubernetes/issues/30151)
- [ ] Finish other controllers: AWS (https://github.com/kubernetes/contrib/issues/346), Haproxy (https://github.com/kubernetes/contrib/pull/206), F5 (https://github.com/kubernetes/contrib/issues/12)
- [ ] L4 in Ingress - SSL proxy, SNI etc (https://github.com/kubernetes/kubernetes/issues/23291, https://github.com/kubernetes/kubernetes/issues/19333, https://github.com/kubernetes/kubernetes/pull/25821)
- [x] Health checks - just scrape endpoints for http readiness? (https://github.com/kubernetes/contrib/issues/325, b/27217458)
- [ ] Cert generation (https://github.com/kubernetes/kubernetes/issues/19899, https://github.com/kubernetes/kubernetes/issues/23482)
- [ ] External DNS integration
- [ ] Rewrite/redirect rules (lot of context on https://github.com/kubernetes/contrib/issues/679)
- [ ] Client Affinity and algorithms (we already do this [through annoations](https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L56))
- [ ] Type=LoadBalancer spins up internal lb (https://github.com/kubernetes/kubernetes/issues/23791)
- [ ] DoS protection (https://github.com/kubernetes/kubernetes/issues/30088)
- [ ] Traffic splitting (https://github.com/kubernetes/kubernetes/issues/25485)  
- [ ] TLS to backend (https://github.com/kubernetes/kubernetes/issues/32928)
- [ ] Soak tests (https://github.com/kubernetes/kubernetes/issues/37335)

@kubernetes/goog-cluster

**Comment by sputnik13** [comment]
created https://github.com/kubernetes/kubernetes/issues/27294 to address sharing of IPs, hostnames, and other "things" in an Ingress

**Comment by pires** [comment]
Who's responsible for updating this issue? For instance, the first item in the list is fixed.

**Comment by girishkalele** [comment]
Adding to this list

#28647 Source IP Preservation for external LB services.

**Comment by nvnobelen** [comment]
@pires Just tested 1.4-alpha2 for issue #10921/#28467: Does not work in alpha2 as expected (or do I misinterpret the state "closed" here as something is really in the branch):

Log output in an nginx container:

```
174.6.xx.xx 1 0.000 [12/Aug/2016:21:01:25 +0000]  "GET /favicon.ico HTTP/1.1" 404 199 "http://104.154.234.227/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36" "-" "-"
10.240.0.7 2 0.000 [12/Aug/2016:21:01:25 +0000]  "GET / HTTP/1.1" 200 4 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36" "-" "-"

```

Source info/bug report in https://github.com/kubernetes/kubernetes/issues/30531

**Comment by bprashanth** [comment]
@nvnobelen source ip was never preserved for ingress traffic through services.Type=LoadBalancer. That's what https://github.com/kubernetes/kubernetes/issues/24145#issuecomment-233007696 is about. For *intra* cluster traffic through the service vip, you should see the right source ip of the pod in nginx logs, if that doesn't work it's a regression (https://github.com/kubernetes/kubernetes/issues/27110). If you're using a hostPort pod, you may get source ip, this is a live bug (https://github.com/kubernetes/kubernetes/issues/29742), but you will get the right source ip in the case that matters most (outside cluster -> node ip:hostport).

**Comment by sandys** [comment]
@bprashanth is there a bug to preserve source ip for nginx based ingress controllers ? i see lots of bugs in different cases.. but not for nginx ingress.

**Comment by pires** [comment]
@thockin can we have an owner for this issue?

**Comment by ccatlett2000** [comment]
Is there an issue for source IP preservation on non-GCE clusters?

**Comment by bprashanth** [comment]
It needs to be dealt with on a case by case basis (eg https://github.com/kubernetes/kubernetes/issues/35758)

**Comment by thockin** [comment]
This issue is sort of a collector, not really actionable.  We should
probably close it and move info to docs and discrete bugs/FRs.

**Comment by InAnimaTe** [comment]
Any updates on this? Has it been merged to docs or discrete bugs?

Additionally, unless I'm reading this wrong, it seems SNI Passthrough (L4 in Ingress) is at least somewhat [done](https://github.com/kubernetes/contrib/issues/1854#issuecomment-256623830).

**Comment by pires** [comment]
The L4 Ingress proposal was closed due to inactivity. The _somewhat done_ you mention is just a workaround for nginx controller.

**Comment by bowei** [comment]
I'm going to close this bug in favor the individual pieces that are planned and in progress.

/close
