### ISSUE TITLE
Test Flakes and merge throughput: umbrella

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24753]
One of the most frustrating things about developing on Kubernetes right now is the amount of time it takes to get PRs through the queue and merged. The primary thing that slows that down at the moment is flaky tests. I believe this is a process/culture problem. Several times now, we've stopped development work to fix tests; we need solutions that keep the tests green in steady state, not ones that make us oscillate between flaky & emergency fixes.

This umbrella issue will track at a high level the things we intend to change to improve this situation. I'll file individual issues for each with much more complete specification-- some of these are big topics in their own right.
- [x] [Individual test owners](https://github.com/kubernetes/kubernetes/issues/24754)
- [x] [Measure flake rate of each test](https://github.com/kubernetes/kubernetes/issues/24758)
- [x] [Automatic flake assignment](https://github.com/kubernetes/kubernetes/issues/24755)
- [ ] [Dashboard for test owner stats](https://github.com/kubernetes/kubernetes/issues/24759)
- [ ] [Expand the integration test framework](https://github.com/kubernetes/kubernetes/issues/24760)
- [x] [Tolerate nonzero flake rates (maybe)](https://github.com/kubernetes/kubernetes/issues/24761)
- [ ] [Measure time spent by PRs in the submit queue](https://github.com/kubernetes/kubernetes/issues/24762)
- [ ] [Measure % of API surface area used in tests.](https://github.com/kubernetes/kubernetes/issues/24763)
- [x] [Nag flaky test assignees](https://github.com/kubernetes/kubernetes/issues/31291)

(I will keep the above list up to date if good ideas show up in the comments on this issue.)

Exit criteria for this issue to be considered resolved (feel free to debate these in the comments-- I will keep this up to date, too):
- [ ] [Presubmit requirements](https://github.com/kubernetes/kubernetes/issues/27578)
- [ ] [Postsubmit requirements](https://github.com/kubernetes/kubernetes/issues/27579)
- [ ] [Flake fix SLO requirements](https://github.com/kubernetes/kubernetes/issues/27580)
- [ ] [Retest succeeds 95% of the time](https://github.com/kubernetes/kubernetes/issues/27581)

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by eparis** [comment]
I know this isn't the right place really, but is there a way to find the 'most failed unresolved test'? Find the issue with the most # references from other PRs?

**Comment by spxtr** [comment]
> I know this isn't the right place really, but is there a way to find the 'most failed unresolved test'? Find the issue with the most # references from other PRs?

I have the start of something along those lines in https://github.com/kubernetes/test-infra/pull/30. It will show the last 24 hour's flakiest tests in merge-blocking suites, and it won't be difficult to make it also show the last week's.

The most references from other PRs (invoked with `@k8s-bot test this issue: #`) might be interesting as well.

**Comment by david-mcmahon** [comment]
One way to distinguish flakes from real issues is to re-test at the same hash when an error occurs and verify that it reproduces N times.  So it's not one failure that gates the submit queue but N identical failures.  This relatively simple and easy test/change will likely increase the submit queue throughput significantly.  Flakes can still bubble down and and be collected for metrics or followup as needed, but not gate the crowded submit queue.

I set up something like this on another team with great success, though it was only gating notifications, not submissions.   Still worth considering though.  N should be determined based on what we know about the level of flakiness so far.  Some flakes may still reproduce N times, but the number should be far less than those that are flaky <N.

**Comment by lavalamp** [comment]
ref https://github.com/kubernetes/contrib/pull/1006

**Comment by lavalamp** [comment]
I'm planning to implement a variant of what @david-mcmahon says: I'll make the submit queue ignore failures in the blocking jobs as long as: a) the prior two runs got test results and b) the failed tests from each are a disjoint set. @eparis stop me if that sounds problematic.

**Comment by lavalamp** [comment]
The obvious next step is to autofile issues for such tests, we'll see how much time I find.

**Comment by lavalamp** [comment]
https://github.com/kubernetes/contrib/pull/1011

**Comment by lavalamp** [comment]
This has been running overnight now, but unfortunately, all of the failures have been of the sort that prevents the cluster from starting, or is in some step that doesn't make it to a JUnit file. So it hasn't done anything yet.

**Comment by lavalamp** [comment]
This would save some merge queue time: https://github.com/kubernetes/contrib/issues/1016

**Comment by lavalamp** [comment]
@david-mcmahon So it turns out that this doesn't help that much so far. Part of the reason is that the flakes happen on the incoming PR, and I'm checking only head. It still requires that the tests on the PR pass before a merge.

**Comment by lavalamp** [comment]
Another item that would help: https://github.com/kubernetes/contrib/issues/1020

**Comment by david-mcmahon** [comment]
@lavalamp In the implementation I set up, we always verified against head and gated only notifications.  That worked well, but this is different.
With a submit queue we actually want to vet each PR as it comes through before allowing it to submit.

Unless we modify the submit queue to retest the same PR looking for flakes vs. consistency, we won't get the benefit of automating with this retest mode.

**Comment by lavalamp** [comment]
Start on autofiling issues: https://github.com/kubernetes/contrib/pull/1021

Submit queue doesn't wait long enough: https://github.com/kubernetes/contrib/pull/1022

**Comment by eparis** [comment]
I just got an e-mail from github support that they added an API to be able to view when a PR referenced a given PR. Which means we should today at least have the API information to be able to tell how many times people requested a retest for a given issue...

**Comment by bgrant0607** [comment]
cc @grodrigues3

**Comment by bgrant0607** [comment]
The test health exit criteria doc from last year:
https://docs.google.com/document/d/1jnGRrZymgnXoVUNnZVER_TOKH_Z11VvsKxlLxU1gg0A/edit#heading=h.7oial9h5tzpi

**Comment by bgrant0607** [comment]
Data I'd like to see:
* Average test failure rate for the submit queue over multiple sliding time windows (e.g., day, week, month, quarter)
* Number of test failures hit per PR at 50th, 80th, 95th, 99th, 100th percentiles
* Failure ratio of each test and test suite over multiple sliding time windows
* Average time to failure of the soak test(s) over multiple sliding time windows

**Comment by spxtr** [comment]
> Number of test failures hit per PR at 50th, 80th, 95th, 99th, 100th percentiles

This one is a little tricky because failures in PRs are usually a good thing. I wrote [a quick script](https://github.com/kubernetes/test-infra/blob/master/experiment/flakedetector.py) to find cases where the same suite fails and passes for a single commit in a PR. For the last day, it gives the following output:
```
Certain flakes from the last day:
16/167	(10%)	pull-kubernetes-kubemark-e2e-gce
13/167	(8%)	pull-kubernetes-e2e-kops-aws
8/156	(5%)	pull-kubernetes-e2e-gce
8/160	(5%)	pull-kubernetes-e2e-gce-non-cri
8/162	(5%)	pull-kubernetes-e2e-gce-etcd3
7/160	(4%)	pull-kubernetes-e2e-gce-gci
7/177	(4%)	pull-kubernetes-unit
2/176	(1%)	pull-kubernetes-node-e2e-non-cri
1/176	(1%)	pull-kubernetes-e2e-gke-gci
1/175	(1%)	pull-kubernetes-node-e2e
1/207	(0%)	pull-kubernetes-bazel
1/176	(1%)	pull-kubernetes-e2e-gke
0/175	(0%)	pull-kubernetes-verify
0/28	(0%)	pull-kubernetes-cross
Chance that a PR hits a flake: 37%
```
It would be nice if we could see this data change over time.

**Comment by luxas** [comment]
@spxtr What about if I first send a truly broken PR (let's say I missed a `,` in the end of the list => compilation error)
That would show up in this statistic, right? Which might not be a flake

**Comment by euank** [comment]
@luxas 

> the same suite fails and passes for a single commit in a PR

If it was a true error the suite would have at no point passed, so it wouldn't show up in that statistic.
If the PR were updated, it would change the commit.

**Comment by luxas** [comment]
Argh, didn't read properly. I missed _for a single commit_, sure then this makes a lot of sense :+1:

**Comment by bgrant0607** [comment]
@kubernetes/sig-testing-feature-requests PTAL and decide whether this is still needed

**Comment by nikhita** [comment]
> @kubernetes/sig-testing-feature-requests PTAL and decide whether this is still needed

bump

**Comment by BenTheElder** [comment]
We're doing more but not all of this yet. Not sure if we still need this @fejta @spiffxp
