### ISSUE TITLE
Implement export functionality server-side for all resources

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#24855]
The machinery added in https://github.com/kubernetes/kubernetes/pull/17483 is currently used only by services. Not sure if I miss any other resource but most don't (and should since the client functionality is already in place: https://github.com/kubernetes/kubernetes/pull/18101). 

issues/gaps with current implementation:

- [ ] export is not implemented for list (https://github.com/kubernetes/kubernetes/issues/41880 )
- [ ] export does not remove self links (https://github.com/kubernetes/kubernetes/issues/33767 https://github.com/kubernetes/kubernetes/issues/57898)
- [ ] export service doesn't know intent, sometimes drops a port that was desired (https://github.com/kubernetes/kubernetes/issues/28551)

**Comment by AdoHe** [comment]
@kargakis in this PR #22285, I just add service export implementation. You may take a look. Besides do we really need to support export all resources?

**Comment by kargakis** [comment]
@AdoHe yes, we need to support exporting of most if not all resources.

**Comment by AdoHe** [comment]
Also as what export suggests, we should stripped of cluster-specific information from exported resources.

**Comment by kargakis** [comment]
@AdoHe right, have a look in the way we currently do export in Openshift: https://github.com/openshift/origin/blob/ba78a93546bb876693276b44b2baf5b0b41f6910/pkg/cmd/cli/cmd/exporter.go#L60-L250

**Comment by AdoHe** [comment]
Just add this to my to do list, will open a PR asap.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
I'd like to couple this to the server side representation of resources (https://github.com/kubernetes/community/pull/123) since not all exports are born equal (there are likely cases where export needs to be parameterized).  This is a pre-req for generic extension servers, but it's slightly less important than get and describe on the server in many cases.

**Comment by seh** [comment]
Perhaps this comment belongs over on #33241, or maybe a fresh issue, but I noticed that if I run _kubectl get --export=true_ against a pluralized resource name, summoning a _v1.List_ of objects, then the `--export=true` flag has no effect. It only works when running _kubectl get_ against a singular named resource. That is,
```shell
kubectl get serviceaccounts --export=true
```
has no observable effect, but
```shell
kubectl get serviceaccount default --export=true
```
does.

**Comment by yue9944882** [comment]
Hi folks, any updates on this thread? @liggitt @soltysh

**Comment by liggitt** [comment]
> Hi folks, any updates on this thread? @liggitt @soltysh

not really, getting server-side printing and alternate representations completed is a higher priority for api-machinery currently.

it's a bit unclear what the goals of the server-side export function are. there are several opposing use cases that tend to get grouped together under the "export" heading:
* export for import to another namespace (remove all references to the source namespace)
* export for import to the same namespace in another cluster (remove assigned fields like service IP)
* export for import to the same namespace in the same cluster 

it doesn't make sense to spend a lot of effort on export until it is resolved what the feature actually is, and which of those (if any), we intend to support

**Comment by bgrant0607** [comment]
I agree that other flavors of export might be desirable. For instance, I could imagine someone just wanting to export the applied configuration rather than the full desired state.

One thing that would be useful for export and also for dry run and client-side generation would be to make fields like metadata.creationTimespamp and status omitempty in the json tags.

**Comment by bgrant0607** [comment]
Another question is whether we should version export functionality if we're going to make changes to it, much as we're discussing for strategic merge patch formats.

**Comment by deads2k** [comment]
> I agree that other flavors of export might be desirable. For instance, I could imagine someone just wanting to export the applied configuration rather than the full desired state.

We've considered this a few times since then and ended up coming back around to avoiding export and instead just getting the resource as it exists today.  The transformations could then be done client-side and at some later date.  Doing it this way allows a single retrieval to be used for different purposes and allows an "export" to be done before deciding how you may later use it.

**Comment by ST-DDT** [comment]
Now that the export function is deprecated, I assume that the issues won't need fixing either...
might as well close this issue. Or is there hope that we get some replacement feature?

**Comment by liggitt** [comment]
> Now that the export function is deprecated, I assume that the issues won't need fixing either...
> might as well close this issue.

correct, closing
/close

> Or is there hope that we get some replacement feature?

If we do, it will start with a KEP

**Comment by ameyaagashe** [comment]
closing issue for a buggy switch is fine but do we have an alternative approach? We need for an on-prem to Managed Kubernetes Service Migration. --export or anything better would have been handy...
