### ISSUE TITLE
Umbrella issue for various swagger related improvements

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#25716]
Summarizing all our swagger related issues here:

Improving the spec:
- [ ] Represent Enum types: right now, we represent them as strings and put the possible values in comments. Want to represent them as enum types and use the list of valid values for validation: https://github.com/kubernetes/kubernetes/issues/24562
- [x] Represent strategic merge patch policy in swagger: https://github.com/kubernetes/kubernetes/issues/24560 (need to figure out how to represent it)
- [x] Fix the return type for /versions: https://github.com/kubernetes/kubernetes/issues/17176 (super simple one line change)
- [x] *versioned.Event model should not be a pointer: https://github.com/kubernetes/kubernetes/issues/24240 (looks like a bug in go-restful)
- [x] Get swagger spec validation to pass: https://github.com/kubernetes/kubernetes/issues/16748 (requires change to swagger-tools most probably)
- [x] Figure out a way to represent IntOrString: We represent them as string right now which fails when we return int: https://github.com/kubernetes/kubernetes/issues/14190
- [x] Fix responseModel for pods/log: https://github.com/kubernetes/kubernetes/issues/14071
- [ ] Document all possible status codes and returned object types: https://github.com/kubernetes/kubernetes/issues/6167
- [x] Represent maps as maps (right now we represent them as `"type": "object"` which is the generic type we use for all our custom types): https://github.com/kubernetes/kubernetes/issues/4700 (requires moving to 2.0)
- [x] Represent unversioned.Time correctly in swagger spec: https://github.com/kubernetes/kubernetes/issues/2968 (should be a simple change)
- [x] intOrString #2971
- [ ] deletion response is incorrect #30537

Making it easy to use:
- [x] Serve it as JSON at kubernetes.io: https://github.com/kubernetes/kubernetes/issues/15571
- [x] Validate on each commit to ensure valid spec at HEAD: https://github.com/kubernetes/kubernetes/issues/5356

Doing things on top of spec:
- [ ] Generate client libraries in multiple languages: We can use client-gen swagger tool to use the swagger to spec to auto generate client libraries in multiple languages: https://github.com/kubernetes/kubernetes/issues/22405

Advanced:
- [x] Move to swagger spec 2.0: https://github.com/kubernetes/kubernetes/issues/13414 (we are using go-restful to generate swagger spec 1.2 right now).
- [ ] Move all internal components to use OpenAPI (swagger spec 2.0): https://github.com/kubernetes/kubernetes/issues/38637

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by nikhiljindal** [comment]
Other people who have shown interest in fixing swagger related stuff: @AdoHe @paralin @whitlockjc

**Comment by Pensu** [comment]
@nikhiljindal I would like to take something up. Let me know if there is anything I can help with.

**Comment by paralin** [comment]
I don't have much time to work on this right now unfortunately, but as a heavy user of the Kube API within my code I'm very interested in any improvements that happen here.

**Comment by bgrant0607** [comment]
Add representable validation properties (min, max, etc.): #8116

We need a way to represent strategic-merge-patch policies and merge keys.
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#strategic-merge-patch

There were some issues mentioned here: https://github.com/kubernetes/kubernetes/issues/9097#issuecomment-156011847

There are also issues with the API documentation itself: #19680

**Comment by nikhiljindal** [comment]
@Pensu Great! Almost all of the issues mentioned above are unassigned right now. Please feel free to pick any!
You can reply "I am working on this issue" when you start working on any of them (so that others know that you are working).

**Comment by bgrant0607** [comment]
For features that aren't supported in jsonschema/swagger/openapi currently, we should develop our own extensions where we can. Unrecognized fields should be ignored by other tools.

https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md
http://swagger.io/specification/#vendorExtensions

**Comment by brendandburns** [comment]
As we push deeper into client code generation, the gaps in Swagger start biting us worse and worse...

In particular in strongly typed languages, the lack of oneOf support mean that many operations are incorrectly documented and thus fail when called from client libraries.

**Comment by mbohlool** [comment]
@brendandburns oneof is supported in OpenAPI v3.0. We should be able to leverage that, right?

Also adding optional parameters to API calls make generated client backward incompatible, that is not a swagger issue but a swagger-codegen issue. I filed [this](https://github.com/kubernetes-client/java/issues/93) and will promote it to a swagger-codegen issue after getting some feedback.

**Comment by brendandburns** [comment]
I think the challenge is that go-restful doesn't currently support oneOf even if OpenAPI does, we'll need to update go-restful too.

--brendan

Microsoft Give is happening in October!
Participate at https://aka.ms/give

________________________________

**Comment by mbohlool** [comment]
and `go-restful` is not an active project. It would be challenging to add things to it. Hopefully by the time we support OpenAPI v3, we also deprecate swagger 1.2 and then we don't need go-restful and can replace it with our router.

**Comment by mbohlool** [comment]
still some issues remains here.

**Comment by vosmith** [comment]
Has anyone started a PR for this?

**Comment by roycaihw** [comment]
openapi v3 spec requirement: https://github.com/kubernetes/kubernetes/issues/79472
openapi v3 support KEP: https://github.com/kubernetes/enhancements/pull/1263

**Comment by thockin** [comment]
Should this old issue be closed?

**Comment by lmktfy** [comment]
> Should this old issue be closed?

Yes.
