### ISSUE TITLE
Adding support for QoS cgroup Hierarchy and Pod level resource management in Kubelet

### ISSUE THREAD

**Issue by dubstack** [kubernetes/kubernetes#27204]
This PR adds support for pod level cgroups and is the first step towards improving Quality Of Service. 
I plan to use this issue to track progress of the work on adding support for QoS Cgroup hierarchy. 
### Short Introduction

We will have have a unified cgroup hierarchy with pod level cgroups for better resource management. The cgroup hierarchy would have top level cgroups for the three Quality of Service(QoS) classes Guaranteed, Burstable and BestEffort. Pods (and their containers) belonging to a QoS class will be grouped under these top level QoS cgroups. And all containers in a pod would be nested under the pod cgroups.

The features I intend to implement are covered in greater detail in the following proposal: #26751 
### High level requirements
- Do not break existing users. Ideally, there should be no changes to the Kubernetes API semantics.
- Support multiple cgroup managers - systemd, cgroupfs, etc.
### Work items
- [x] Finalize and submit Pod resource management proposal for the project #26751
- [x] Refactor qos package to be used globally throughout the codebase #27749 #28093
- [x] Add interfaces for CgroupManager and CgroupManagerImpl which implements the CgroupManager interface and creates, destroys/updates cgroups using the libcontainer cgroupfs driver. #27755 #28566
- [x] Inject top level QoS Cgroup creation in the Kubelet and add e2e tests to test that behaviour. #27853
- [x] Add PodContainerManagerImpl Create and Destroy methods which implements the respective PodContainerManager methods using a cgroupfs driver. #28017
- [x] Have docker manager create container cgroups under pod level cgroups. Inject creation and deletion of pod cgroups into the pod workers. Add e2e tests to test this behaviour. #29049
- [ ] Add a NodeCapacityProvider which would be used both by the Kubelet and ContainerManager
- [x] Add support for updating policy for the pod and QoS containers. Add e2e tests to test this behaviour. #29087
- [ ] Reconcilation loop that ensures pod cgroups on the cgroup mount are of pods which are known to be not terminated by the Kubelet
- [ ] Add top level scheduler check to ensure that pod can be scheduled on the node by estimating left over resources on the node.
- [x] Add a systemd implementation for the above Cgroup Manager interface
- [ ] Log Basic metrics of cgroup creation/ deletion
### Rollout Plan
- This feature will be opt-in in v1.5 and an opt-out in v1.6. 
- Ideally we would want to have all the sub features to be completed for v1.5.
- We would recommend users to drain their nodes and opt-in, before switching to v1.6, which will result in a no-op when v1.6 kubelet is rolled out.

I will keep all my future PR's related to this proposal tied to this issue. 
cc @kubernetes/sig-node @dchen1107 @vishh @ronnielai @derekwaynecarr @Random-Liu @yujuhong

**Comment by Random-Liu** [comment]
@dubstack Good job~~ :)

**Comment by derekwaynecarr** [comment]
We need to ensure this is functional using both the systemd and cgroupfs
docker drivers.  They expect different input.

**Comment by vishh** [comment]
@dubstack Make it explicit that this feature will be opt-in and requires all the sub-features mentioned above to be completed for v1.4.

**Comment by dubstack** [comment]
Yes I will expand on the description to more elaborately cover my work.

**Comment by yifan-gu** [comment]
Notes for support this with rkt:

Since rkt is spawned by systemd already, I think we can specify the [Slice](http://man7.org/linux/man-pages/man5/systemd.cgroup.5.html) to be one of the qos classes, and then the process in the rkt pods will all be put into the slice, (the slice will be created by systemd if not existed already).

Need to check how this affects the cgroup discovery of rkt pods though

cc @kubernetes/sig-rktnetes

**Comment by vishh** [comment]
Can `rkt` instead accept a pod level cgroup that kubelet provides and use
that instead?

**Comment by euank** [comment]
Right now it can't, but we could probably add something akin to `cgroup-parent`.. though we could also just as easily use `cgexec` from whatever non-systemd process spawns rkt.

However, so long as rktnetes has a hard dependency on systemd anyways, it seems like we could have systemd use the pod-level cgroup as the parent and just abstract that implementation detail away suitably so it has the same interface.

Do you have a specific concern / reason you think rkt should support that directly itself rather than whatever launches that (be it the kubelet now or the client/server server portion later)?

**Comment by vishh** [comment]
We'd like to keep QOS policies within Kubelet to make sure that the core
features of k8s works the same way across deployments. This aligns with the
new Container Runtime Interface as well.

**Comment by euank** [comment]
Right, so the interface expresses QoS in the form of saying "here's your parent cgroup under which all containers must run" and then that happens. Why does it matter if that's done via rkt the runtime doing it or rktnetes the abstraction over rkt doing it?

I think you misunderstood what I said; I'm not saying that kubelet doesn't create a pod level cgroup and hand it off to the kubelet -> rktnetes -> rkt abstraction, I'm just asking why it matters if it's rktnetes vs rkt that actually drops the pod into that cgroup.

**Comment by vishh** [comment]
> Right, so the interface expresses QoS in the form of saying "here's your parent cgroup under which all containers must run" and then that happens. Why does it matter if that's done via rkt the runtime doing it or rktnetes the abstraction over rkt doing it?

Honestly, it doesn't matter. If there are plans on moving rkt to the new CRI, rkt will have to place pods within the cgroups created by kubelet.

> I think you misunderstood what I said; 

Quite likely :) Thanks for your patience!

> I'm not saying that kubelet doesn't create a pod level cgroup and hand it off ( flowing as kubelet -> rktnetes -> rkt ). I'm just asking why it matters if it's rktnetes vs rkt that actually drops the pod into that cgroup.

What is the difference between `rktnetes` vs `rkt`? As long as pods are running in the cgroups that kubelet created, nothing else matters, at-least for this specific issue/feature.

**Comment by euank** [comment]
@vishh circling back; I was distinguishing `rkt` the container runtime from `rktnetes` the CRI implementation that turns kubelet requests, including `CgroupParent` into something for `rkt` to do.
The semantic issue I was taking here is that @yifan-gu's comment meant that `rktnetes` can set a cgroup parent that kubelet provides and `rkt` will then nest under it happily without any changes to `rkt` itself.

I think we're on the same page and the difference is just semantic / runtime preference for where this logic should live.

**Comment by vishh** [comment]
FYI: As of now all the cgroups logic is being added to container manager
(`cm`) package in kubelet. Changing the current architecture requires more
thought.

**Comment by dims** [comment]
@vishh : move this from v1.5 to v1.6 please?

**Comment by dims** [comment]
@vishh This needs to be triaged as a release-blocker or not for 1.5

**Comment by resouer** [comment]
@davidopp > Add top level scheduler check to ensure that pod can be scheduled on the node by estimating left over resources on the node.

How can we achieve this? I mean, it seems scheduler has no knowledge of pod level cgroup values, unless we modify pod spec to support it.

**Comment by davidopp** [comment]
@resouer I'm actually not sure what this work item means. I originally thought this proposal didn't require any scheduler changes, but now I'm not sure. Maybe @dubstack or @vishh can explain that comment?

From a scheduling perspective, all we care about is that the amount of resources in the "request" translates into resources that are guaranteed to the container/pod on the node. Best-effort pods are a non-issue since request==0 by definition. It seems that Guaranteed pods are not handled any differently from today in the proposal, so that should also be a non-issue. So the remaining question is whether Burstable is still guaranteed to get its "request." Because all Burstable pods live under a single cgroup, it seems all the Burstable are collectively restricted to whatever the size of that cgroup is. Is the Bu cgroup size dynamically updated when a new Bu pod is scheduled onto a node?

It's possible the comment was talking about system-reserved and kube-reserved, but it seems we should be able to account for those by simply excluding them from NodeStatus.Allocatable.

**Comment by davidopp** [comment]
I got clarification from @vishh and @dchen1107, and the statement "Add top level scheduler check to ensure that pod can be scheduled on the node by estimating left over resources on the node" should say "Add Kubelet admission control check to ensure pod can be scheduled on the node taking into account resources that are technically free but are still being cleaned up (reclaimed) on the node so not yet truly available"

Regrading my (unrelated) question about Burstable being able to get its "request" (in the long-term plan for cgroup hierarchy) the answer was that the top-level Burstable cgroup would be continually updated to allow for the sum of the requests of the Burstable pods running underneath it.

**Comment by resouer** [comment]
@davidopp Thanks for explanation! But how pod level cgroup contribute to `taking into account resources that are technically free but are still being cleaned up`?

**Comment by resouer** [comment]
And top level qos containers update seems not implemented yet: https://github.com/kubernetes/kubernetes/issues/39913

**Comment by davidopp** [comment]
> how pod level cgroup contribute to taking into account resources that are technically free but are still being cleaned up

Yeah, I think these things are orthogonal.

**Comment by resouer** [comment]
> And top level qos containers update seems not implemented yet.

Answer from @vishh 
We do not plan on updating top level cgroups as of now. Let's first complete and roll out pod level cgroups and the overall cgroup hierarchies. There is no urgent need to update top level cgroups.

**Comment by derekwaynecarr** [comment]
@vishh @resouer - we have been working on updating qos level cgroups, we can discuss if that should roll out separately or be off by default similar to what was done thus far for pod cgroup.

**Comment by resouer** [comment]
Thanks Derek. Personally I agree we can roll out it separately (unless it has already been finished). Then together with other tasks depends on it (e.g. use pod cgroup values to fill default resources in downwardapi).

Other tasks I'm not sure are: `Add a NodeCapacityProvider ...` and `Reconcilation loop that ensures pod cgroups ...`. Especially the later, are they should be included in this rollout? Or they are not urgent either.

**Comment by derekwaynecarr** [comment]
I find the presence of this issue being open confusing for multiple reasons.  Primary reason is that I will open a document that outlines the proposal for rolling out the feature that is up-to-date, and secondary reason is that the issue author is no longer active in the project in this area.

**Comment by derekwaynecarr** [comment]
To summarize pertinent parts of the meeting held with @vishh and @sjenning for awareness:

1. We intend to rollout Node Allocatable and pod level cgroups together. @derekwaynecarr is working on a rollout plan for pod level cgroups. @vishh will add the plan for node allocatable to it or post a separate plan.
1. QoS level cgroup settings for memory are intended to be made available for v1.6 (turned off by default). @sjenning  is working on it.   Enabling qos level settings for memory impacts overcommit.  Enabling the feature would drive the kubelet to run a sync loop to try and reach desired state of inducing memory pressure on lower qos workloads to try to reserve memory for guaranteed workloads.  It would not guarantee availability of memory before admitting the workload.  QoS level cgroup settings for cpu requests are intended to be enabled in v1.6 by default.  Node allocatable is intended to also be enforced at the root level cgroup for the k8s workload.
1. @dashpole and @sjenning  is working on making pod deletions safe by deleting volumes and pod level cgroups. This prevents scheduler from over committing nodes. The latency to free up resources will be higher once disk is added as a resource.

**Comment by davidopp** [comment]
When pod-level cgroups are implemented, will there still be container-level cgroups?

**Comment by vishh** [comment]
Yes. There will still be container level cgroups to enforce container level
requests and limits.

On Sat, Jan 21, 2017 at 7:23 PM, David Oppenheimer <notifications@github.com

**Comment by jingxu97** [comment]
After pod-level cgroups is available, I think it would be nice to add pod-level resource request/limit in API. I can image in some use cases, users do not know or don't care the resource request/limit for each individual container, they only need to set a pod-level request/limit based on e.g., quota they can use. Also with only container-level resource enforcement, if one container's limit is exceeded, the whole pod gets evicted even through there should be enough resources for the pod as a whole.
Should we continue this work on supporting pod-level resources?
Ref: https://groups.google.com/forum/#!topic/kubernetes-users/VMCftsSYgBI
