### ISSUE TITLE
Once final 1.3.0 is available, verify cluster/gce/upgrade.sh works to upgrade to that version

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#27764]
There seem to multiple issues with cluster/gce/upgrade.sh script.
- [x] cluster-name.txt file doesn't exists: fixed by #27763
- [x] the script has unbound variable errors: fixed by #27771
```
./cluster/gce/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/common.sh: line 572: KUBE_MANIFESTS_TAR_URL: unbound variable
./cluster/gce/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/common.sh: line 572: KUBE_MANIFESTS_TAR_HASH: unbound variable
```
- [x] master is not ready after upgrade: fixed by #27846
- [x] nodes are not ready after upgrade: fixed by #27824

@piosz @gmarek @davidopp @roberthbailey @mikedanese @kubernetes/goog-gke

**Comment by piosz** [comment]
Unbound variables issue can be workarounded by upgrading to local binaries. I'm checking whether it works.

cc @jszczepkowski @mwielgus

**Comment by wojtek-t** [comment]
It can be workarounded for testing, but this is a blocker for release in my opinion.

**Comment by piosz** [comment]
Totally agree. I can confirm that upgrade using local variables work for me.

**Comment by piosz** [comment]
There is yet another issue: after upgrade master becomes not ready. @gmarek is trying to fix it.

**Comment by wojtek-t** [comment]
@piosz - this seems to be the third issue from first post.
I'm also looking into it now. In fact I'm testing a possible fix.

**Comment by piosz** [comment]
Yep. Just wanted to emphasize this.

**Comment by wojtek-t** [comment]
And there is another problem, that nodes after upgrade are not getting ready. I though it's the same, but it may be a different fix.

But to clarify, the problem is that kubelet doesn't have --api_servers flag set at all.

**Comment by wojtek-t** [comment]
I got to the point where I have this flag is set, but it seems we have incorrect certificates:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:fix_master_ready?expand=1

**Comment by piosz** [comment]
Regarding problem with broken nodes in the new instance template I can see metadata field `configure-sh` instead of `startup-script`.

**Comment by piosz** [comment]
It seems that `upgrade.sh` tries to upgrade my nodes to gci instead of debian. Is this by design?

@dchen1107 @andyzheng0831 Which image are we using for 1.3 for nodes?

**Comment by gmarek** [comment]
I tried another approach to what @wojtek-t did - I just removed few cases from the if statement. It didn't work, so there must be some other thing that drives addition of `kubelete_api_servers` Kubelet flag.

More context to what @piosz said: originally we have a debian image with startupscript set. After `upgrade -N` we see a new template with a `configure-sh` and lines such as 
```
cp "${dst_dir}/kubernetes/gci-trusty/gci-configure-helper.sh" "${KUBE_HOME}/bin/configure-helper.sh"
```

I tried adding 
```
if [[ "${OS_DISTRIBUTION}" == "gci" ]]; then
    OS_DISTRIBUTION="debian"
fi
```
to the upgrade script, but it didn't help.

**Comment by piosz** [comment]
@gmarek it won't help since you want to have appropriate script to be included in mig template. You should try to export local env var OS_DISTRIBUTION=debian

**Comment by gmarek** [comment]
I don't want to do that, as if I set it locally before running script, the master will be using debian as well.

**Comment by piosz** [comment]
You can upgrade master first, then set env variable and upgrade nodes.

**Comment by gmarek** [comment]
yeah - that's the perfect flow. I think that setting it in the script before template creation should be enough.

**Comment by andyzheng0831** [comment]
For question in https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-227462767: Currently the master branch head uses gci-dev-53-8467-0-0 image. But this will be automatically updated when we cut a new release image. You can find the image in use via "gcloud compute images list --project google-containers | grep gci-dev-53"

@piosz @gmarek From the above comments I am not clear about two things: (1) Are you testing upgrade from ComtainerVM-based cluster to GCI-based cluster? (2) What are the steps you use? Maybe I can reproduce and take a look.

**Comment by gmarek** [comment]
@andyzheng0831 - we were testing ordinary `gce/upgrade.sh` for Nodes, which seems to be trying to update nodes to GCI. To reproduce just run `gce/upgrade.sh -N v1.3.0-beta.1`

**Comment by andyzheng0831** [comment]
Does it mean I need to first create a cluster (nodes on GCI or containerVM does not matter), and then run that upgrade.sh to upgrade nodes to GCI?

We switched master from ContainerVM to GCI but never declare nodes on GCI as default. Why mark this issue as P0? P0 looks to me like a release blocker

**Comment by gmarek** [comment]
It's for upgrade tests, and upgrades doesn't seem to be working for now.

**Comment by andyzheng0831** [comment]
The upgrade test is new to me, so please provide detailed information for me to reproduce it. Do I need to first create a cluster using kube-up.sh, with nodes on ContainerVM? What version of k8s should I use? And then try to upgrade nodes to GCI, with a certain setting to use GCI as nodes image?

**Comment by gmarek** [comment]
- create a cluster from v1.2 branch (basically checkout v1.2, build it and deploy it)
- try to upgrade it to v1.3 (switch to the head/v1.3 branch, try running upgrade script)

**Comment by piosz** [comment]
What I did:
```
git checkout v1.2.4
hack/dev-build-and-up.sh
git checkout master
cluster/gce/upgrade.sh -M v1.3.0-beta.1
# wait some time, master becomes not ready
cluster/gce/upgrade.sh -N v1.3.0-beta.1
# the update never succees
```

**Comment by roberthbailey** [comment]
@piosz -- did you re-build binaries after checking out the master branch?

**Comment by piosz** [comment]
It doesn't matter - I'm using pre-built binaries from release v1.3.0-beta.1. I was also trying upgrade to local binaries with option `-l` and then after changing branch to master I invoked `make clean && make quickrelease`

**Comment by roberthbailey** [comment]
Ah. In that case, for step 1 you could also do `curl https://get.k8s.io | bash` to create the cluster at the latest release version.

**Comment by piosz** [comment]
I need to have cluster in v1.2.4 instead of the latest one.

**Comment by roberthbailey** [comment]
1.2.4 is the latest stable version:

```
$ curl https://get.k8s.io | bash
...
Saving to: 'kubernetes.tar.gz'

kubernetes.tar.gz               100%[======================================================>] 473.69M  28.9MB/s   in 16s    

2016-06-21 11:32:00 (29.8 MB/s) - 'kubernetes.tar.gz' saved [496696744/496696744]

Unpacking kubernetes release v1.2.4
Creating a kubernetes on gce...
...
```

**Comment by piosz** [comment]
Oh I see. Thanks!

**Comment by roberthbailey** [comment]
Saves you the build step, which should speed up the testing cycle. :)

**Comment by piosz** [comment]
This seems to be related https://github.com/kubernetes/kubernetes/issues/26183

**Comment by andyzheng0831** [comment]
@piosz the issue you mentioned is not a blocker for functionality. @wonderfly logged it just for improving some logic in setting up master and node distro. I am following the information in above comments to reproduce it and check where is wrong.

**Comment by andyzheng0831** [comment]
In https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-227521367, "-M" and "-N" are used, which means do not upgrade master or node. So, what is the real thing we are trying to do? Upgrade both master and nodes, or upgrade master only, or upgrade nodes only? Or you meant that neither upgrade master only nor nodes only works?

**Comment by gmarek** [comment]
Upgrade procedure is that we first upgrade master only (and everything should work), then we update nodes (and everything should still work).

**Comment by andyzheng0831** [comment]
Here is what I did and found:
1. git checkout v1.2.4
2. hack/dev-build-and-up.sh
3. git checkout master
4. make release-skip-tests quick-release
5. cluster/gce/upgrade.sh -M v1.3.0-beta.1
Wait for a while after the above step, I can see "Cluster validation succeeded". So, upgrading master works fine.

6. cluster/gce/upgrade.sh -N v1.3.0-beta.1
In step 6, I expect that nodes should still use ContainerVM after being upgraded. But actually a GCI node template is created and ContainerVM-based node group uses that template. This is why nodes initialization do not work.

I think the problem is in the node template creation logic. I am reading the script to figure out how to fix it.

**Comment by andyzheng0831** [comment]
OK, I find what is wrong. See this line https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#l214, since the OS_DISTRIBUTIONS is gci, it sources cluster/gce/gci/helper.sh, and that is the reason why it creates a GCI-based node group template. Now, see this block https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#l750-755, you will understand why the hybrid cluster works fine when we run kube-up.sh.

I am making a fix now.

**Comment by piosz** [comment]
I can confirm that #27824 fixed nodes upgrade. So it seems the only remaining problem is not ready master.

**Comment by wojtek-t** [comment]
I'm looking into it now.

**Comment by wojtek-t** [comment]
This is now fixed.

We will verify end-to-end that the script works now and I will close this bug if so later today.

**Comment by piosz** [comment]
There is yet another issue with cluster upgrade, though it's not a blocking one. I filled https://github.com/kubernetes/kubernetes/issues/27852.

The upgrade seems to work as for now and we are planning to test it.

**Comment by wojtek-t** [comment]
Together with @piosz we independently verified that the upgrade works after those 4 fixes.

There is one remaining bug (which doesn't seem to be a blocker for me) and @piosz already filed a separate issue for it.

So I'm closing this one.

**Comment by piosz** [comment]
copy/paste of @janetkuo's https://github.com/kubernetes/kubernetes/issues/23004#issuecomment-227957864:

Upgrading master from 1.2.4 to 1.3.0-beta.2 failed :( 
My new master never respond to API requests...

I first did `curl https://get.k8s.io | bash` and then `cluster/gce/upgrade.sh -M v1.3.0-beta.2`. 

From HEAD:  
```console
➜ kubernetes(master)$ cluster/gce/upgrade.sh -M v1.3.0-beta.2
Your active configuration is: [default]

Project: kuber-3
Zone: us-central1-b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38796  100 38796    0     0   130k      0 --:--:-- --:--:-- --:--:--  130k
== Upgrading master to 'https://storage.googleapis.com/kubernetes-release/release/v1.3.0-beta.2/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==
Using master: kubernetes-master (external IP: 146.148.35.19)
Enter passphrase for key '/usr/local/google/home/xxxx/.ssh/google_compute_engine': 
Deleted [https://www.googleapis.com/compute/v1/projects/kuber-3/zones/us-central1-b/instances/kubernetes-master].
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/kuber-3/zones/us-central1-b/instances/kubernetes-master].
NAME               ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
kubernetes-master  us-central1-b  n1-standard-1               10.240.0.2   146.148.35.19  RUNNING
== Waiting for new master to respond to API requests ==
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

I retried for several times (create a new project, shut down the cluster and then restart) but it still didn't work.

**Comment by gmarek** [comment]
@janetkuo were you running upgrade script from head or from the released version?

@wojtek-t @piosz - I think that we should cherry pick our fixes.

**Comment by wojtek-t** [comment]
After reverting the PR: #27924 it seems to work again.

**Comment by zmerlynn** [comment]
Can you please diagnose this failure a little more? I'm out and the PR you
reverted is a hard ship blocker for GKE. @roberthbailey

**Comment by zmerlynn** [comment]
I'm on mobile, but I suspect what's going on here is that the upgrade script is invalidly using the GCI helper.sh script from the current repo rather than a versioned GCS one. This would cause the same subprime. If that's the case, please fix that (it's bad) and re-revert.

**Comment by zmerlynn** [comment]
(If what I said were true, you'd be able to upgrade to the latest CI build, just not a beta build before that. That's a failure of the upgrade script, not my PR.)

**Comment by wojtek-t** [comment]
@andyzheng0831 @wonderfly - since this seems to be GCI-related, can one of you please fix it?

**Comment by zmerlynn** [comment]
In the meantime, please re-revert the PR and test using CI versions. This is an `upgrade.sh` failure, which is a poorly supported mechanism.

**Comment by wojtek-t** [comment]
@zmerlynn - actually it's not poorly supported - having this script working is a release blocker.

**Comment by zmerlynn** [comment]
I'm arguing that it's been poorly supported for months and you ran across a
bug in the script. The GCI helper scripts have to be versioned in the same
way the salt tar is, for upgrade - they are synonymous. If your goal is to
support upgrade.sh, please re-revert the PR and fix the upgrade script.

**Comment by gmarek** [comment]
@zmerlynn - it will be much easier for you or GCI folks to fix this, as we don't really know the context. @davidopp

**Comment by andyzheng0831** [comment]
I am reading through the new comments and see if I can reproduce and make a fix

**Comment by gmarek** [comment]
Repro is simple - revert a revert and try upgrading the master from 1.2 to 1.3.

**Comment by davidopp** [comment]
@zmerlynn - I agree ith Marek and Wojtekt that the right people to fix this are the GCI folks.

Just to be clear, we are not talking about kube-push.sh, which indeed has been broken for many months. We're talking about cluster/gce/upgrade.sh, which worked until the change mentioned above (that was just reverted). Having cluster/gce/upgrade.sh work is a hard ship blocker for 1.3.

**Comment by alex-mohr** [comment]
I propose that backward-looking which-component-is-at-fault isn't productive.  Let's focus on getting this fixed for 1.3.

Zach @zmerlynn  is OOO on vacation today and tomorrow, so he's unavailable.  

The functionality in #27924 is also a hard release blocker for 1.3.

**Comment by andyzheng0831** [comment]
@davidopp @alex-mohr I can take an initial investigation. If it is in GCI config, I can make a fix. If it is outside of GCI config scope, I can try best to point it out where it is and then we may find a suitable person to fix it.

**Comment by zmerlynn** [comment]
To be clear, fixing anything in #27924 is also a non-starter. The GCI config here is actually not to blame, it's the `upgrade.sh` path pulling the wrong set of helper scripts.

**Comment by andyzheng0831** [comment]
Wait a minute, I think I already fixed the problem of pulling wrong set of helper script in #27824.

And I just tried but cannot reproduce the issue. My master can successfully upgrade from 1.2.4 to 1.3.0-beta.1, using the following steps including reverting #27924

- git checkout v1.2.4
- hack/dev-build-and-up.sh
- git checkout master
- git reset --hard 5094333
- make release-skip-tests quick-release
- cluster/gce/upgrade.sh -M v1.3.0-beta.1

**Comment by gmarek** [comment]
That's a wrong PR you reverted. You should reapply #27924

**Comment by davidopp** [comment]
BTW before anyone LGTMs any further PRs related to this issue -- either un-reverting #27924, or changing upgrade.sh, or whatever, **PLEASE PLEASE PLEASE** verify that it did not re-break upgrade.sh.

The procedure we've been using to verify upgrade.sh is
```
curl https://get.k8s.io | bash
# do something
# from HEAD, compiled
cluster/gce/upgrade.sh -M v1.3.0-beta.2
# check something
cluster/gce/upgrade.sh -N v1.3.0-beta.2
# check something
```

A reasonable "do something" is to bring up the [guestbook example](https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook) and "check something" is to verify you can use the guestbook service.

Here are the detailed notes on what was done in the upgrade testing for guestbook:

```
curl https://get.k8s.io | bash
// from 1.2 branch
// add: “type: LoadBalancer” line to frontend-service.yaml
kubectl create -f examples/guestbook
// waited until service has load balancer
// created some messages in guestbook
===============================
// from head
cluster/gce/upgrade.sh -M v1.3.0-beta.2
// checked if all pods are running without restarts
// checked if messages exists in guestbook and added new
===============================
cluster/gce/upgrade.sh -N v1.3.0-beta.2
// checked if all nodes are ready
// checked if all pods are running (all of them were actually recreated)
// checked if guestbook is responsive (also during upgrade)
// All message disappeared, but pods don’t have PDs, so that’s expected.
```

**Comment by wojtek-t** [comment]
Even verifying that the master itself and ndoes are up is a good test (it wasn't the case before we reverted the PR)

**Comment by andyzheng0831** [comment]
@gmarek @wojtek-t please give more detail about master branch. Which commit should I reset to?

**Comment by maisem** [comment]
#27961 should help make upgrade.sh better.

**Comment by wojtek-t** [comment]
@andyzheng0831 - I don't understand your question. THis is the PR that broke the upgrade:
https://github.com/kubernetes/kubernetes/pull/27840
You should simply reapply it to break upgrade.

**Comment by andyzheng0831** [comment]
I meant that the current master head does not have this issue because that change #27840 was reverted. OK, I think revert master branch to the commit f9d1737 which adding the PR #27840 should be able to show the issue. Let me try it.

**Comment by maisem** [comment]
I am testing #27961 with zachs PR #27840.

**Comment by maisem** [comment]
These are the steps I followed.
1. git checkout release-1.2
2. cluster/kube-up.sh
3. git checkout <branch_with_27840>
4. cluster/gce/upgrade.sh -N v1.3.0-beta.2 (this worked presumably because it is running container-vm)
5. cluster/gce/upgrade.sh -M v1.3.0-beta.2

This is the error on the master
 cp: cannot stat '/home/kubernetes/kubernetes/kubernetes-src.tar.gz': No such file or directory

The file is present at /home/kubernetes/kubernetes-src.tar.gz.

@andyzheng0831 - what does KUBE_HOME point to in GCI?

**Comment by andyzheng0831** [comment]
KUBE_HOME="/home/kubernetes" (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#l929)

The error you saw is what I was concerned when reviewing #27840. (https://github.com/kubernetes/kubernetes/pull/27840#issuecomment-227819525)

**Comment by maisem** [comment]
Upgrading to the latest CI seems to work fine.
`cluster/gce/upgrade.sh -M v1.4.0-alpha.0.674+890ac5fdfea522` 

Going to spin up a new cluster at 1.2.4 and verify this.

**Comment by andyzheng0831** [comment]
I know where is wrong. First of all, it is nothing wrong with GCI config. Try to download the v1.3.0-beta.2 tarball https://storage.googleapis.com/kubernetes-release/release/v1.3.0-beta.2/kubernetes-server-linux-amd64.tar.gz and take a look. There is no kubernetes-src.tar.gz file in it. @zmerlynn's PR  #27840 is in v1.3.0-beta.2, but there is something missing in the release scripts. That is why we see the error "cp: cannot stat '/home/kubernetes/kubernetes/kubernetes-src.tar.gz': No such file or directory"

Next step: find someone to check the release scripts for the missing part about kubernetes-src.tar.gz file.
This is not an issue about GCI.

**Comment by maisem** [comment]
Upgrading the master worked.
`cluster/gce/upgrade.sh -M v1.4.0-alpha.0.674+890ac5fdfea522`

Upgrading the nodes also worked.
`cluster/gce/upgrade.sh -N v1.4.0-alpha.0.674+890ac5fdfea522`

So what @andyzheng0831 said is correct. There is an issue with v1.3.0-beta.2. If we upgrade to HEAD everything seems to be working fine.

The action now is to reapply #27840 and then to merge #27961 once its LGTM'd.

**Comment by andyzheng0831** [comment]
One thing I have to point it out: #27961 is not really a fix to this particular issue. It is an improvement to the hack such as in #27824, so it does not fix any breakage. By splitting OS_DISTRIBUTION into two variables, people can better control and understand the hybrid clusters. For this upgrade breakage, please check the release scripts. Do not wait for #27961. Based on our previous experience, changing such fundamental env variable is very risky and most likely we will breakage someone. I don't hope people misunderstand that #27961 is a fix to this issue and consider it as a release blocker for 1.3.0.

**Comment by zmerlynn** [comment]
There's nothing wrong with the release scripts for `beta.2`. The release changed after that to include the src tar, hence my comment about the helper scripts themselves needing to be versioned.

**Comment by andyzheng0831** [comment]
Ah, I think I put some wrong information in my previous comment https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-228194465. Zach's change is not in v1.3.0-beta.2 as you can verify the file https://github.com/kubernetes/kubernetes/blob/v1.3.0-beta.2/cluster/gce/gci/configure.sh. But after upgrade, the config code in use is not really v1.3.0-beta.2. So, what @zmerlynn said is correct. The versioning problem.

Does anyone know how to make the config scripts to be versioned?

**Comment by alex-mohr** [comment]
Is there release blocker to re-add the -src-tar and re-test upgrades against head (or a beta.3 if that's useful)?  Or is making the config scripts versioned absolutely required to cut a release?  I talked briefly with @maisem and it seems the former is the case?

**Comment by maisem** [comment]
I agree with @alex-mohr, we shouldn't care about v1.3.0-beta.2 as an upgrade target as upgrading to HEAD works.

Created #27985 to reapply #27840.

**Comment by davidopp** [comment]
> an upgrade target as upgrading to HEAD works

Just to be clear -- what we really care about is that upgrading to the 1.3 release that we will be cutting tomorrow works, from a 1.2 cluster.

**Comment by zmerlynn** [comment]
It needs to be a high priority item to correct this. As I mentioned above, the helper scripts for GCI are equivalent to the Salt tar for CVM, and we change those without much concern. I agree with an expedient path that doesn't care for now, but if in e.g. 1.3.1 someone makes a change to a GCI config script, it may get run incorrectly against a 1.3.0 tarball to downgrade. It's a narrow case, but it's there.

**Comment by andyzheng0831** [comment]
A question (may be stupid). Like GCI's scripts, the ContainerVM's script configure-vm.sh is uploaded to instance as metadata. It also has the versioning issue, right?

**Comment by zmerlynn** [comment]
There's actually a TODO on the OSS script to always point to the GCS path, IIRC. `configure-vm.sh` does much less, though, because it hands off to Salt. (And on GKE we always load the right URL.)

**Comment by piosz** [comment]
Regarding https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-228205618
This is not true. To logic for upgrading to HEAD and pre-built version is different. We should care about upgrading to v1.3.0-beta.2 and we can probably care less about upgrade to HEAD.

**Comment by alex-mohr** [comment]
@piosz In this case, "HEAD" meant v.1.4.0-alpha and thus presumably went through the pre-built version path?
https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-228196070

**Comment by piosz** [comment]
@alex-mohr sorry, I thought it was with flag `-l`. Otherwise I agree it's not a big difference.

**Comment by alex-mohr** [comment]
We believe this is now fixed, but I'm renaming and would like to leave it open to have someone explicitly verify that it works with the official 1.3.0 release after it comes out.

**Comment by davidopp** [comment]
Yes, good idea, I was just thinking the same thing during the meeting. :)

**Comment by alex-mohr** [comment]
Maisem volunteered to pick this up unless you're desperate to own it @davidopp .

Also, if there's another beta of 1.3, we could do this then.

**Comment by davidopp** [comment]
No, I'm happy to have @maisem do it.

**Comment by maisem** [comment]
Upgrading the master to v1.3.0-beta.2.224+27e212baad161c fails. Well it doesn't complete.

Trying v1.3.0-beta.3.

**Comment by maisem** [comment]
Upgrading to v1.3.0-beta.3 works, will do one last verification when we cut v1.3.0.

**Comment by maisem** [comment]
Upgrading from 1.2.5 to 1.3.0 works!
All the addons are running as well.

Closing this issue.
