### ISSUE TITLE
Release tarballs are too big

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#28435]
The Kubernetes 1.3 release tarball is 1.4G.  That is insane.  While we know that much of this is due to the fact that we include all architectures, it make kubernetes feel heavier than it is.

Much of the space is the fact that 4 server platforms are now created and packaged with everything else.  Each target is a ~325M tarball.  These tarballs include both individual binaries along with Docker images that include those binaries.  They include kubectl (which is available naked in the release).

We also have 9 copies of kubectl for various targets totaling 450MB.

Things we can do to slim this down:
- [x] Start building release tars per-architecture.  Either include non-arch specific stuff in every tar or break that out too. (#28629, owner?)
- [ ] Finish transition to hyperkube and deprecate the individual binaries.  . We could move the individual binaries into a different tar for those that still need them.  For `amd64` hyperkube is 132M uncompressed and 26M compressed.  This means we could go from a 350M compressed tar for the amd64 target down to 26M. (#16508, owner?)
- [ ] Have the ability to build the Docker images on the fly.  It should be easy to automate (as part of the binary) creating a Dockerfile, referencing the running binary and driving docker.  `hyperkube admin create-container-image` could do this. We could also support `hyperkube admin create-container-image --aci` and `hyperkube admin create-container-image --docker --just-dockerfile`. (#28630, owner?)
  - I understand that gzip does a decent job of de-duping stuff here.  But the uncompressed footprint balloons and looks bad.
- [ ] Break out kubectl as a separate download from the server components.  `gcloud` already ships it separately.  The user cases here differ dramatically. (#28631, owner?)
- [ ] Reevaluate all of our targets.  Do we really need 32bit Windows? (#28632, owner?)
- [x] Why are the federation targets new binaries? They add 150M uncompressed for amd64. (I don't know enough to say here but could these be folded in to hyperkube?  I'm guessing they could.) (#28633, @madhusudancs)
- [x] Don't ship binaries that we don't really need.  We included `kubemark` here.  No end users will actually use that.  This is 100M uncompressed. (#28635, owner?)

Also related: #27444 (Builds are taking too long)

**Comment by spxtr** [comment]
```
$ du -sh server/bin/*
99M		server/bin/federation-apiserver
4.0K	server/bin/federation-apiserver.docker_tag
100M	server/bin/federation-apiserver.tar
57M		server/bin/federation-controller-manager
4.0K	server/bin/federation-controller-manager.docker_tag
58M		server/bin/federation-controller-manager.tar
132M	server/bin/hyperkube
105M	server/bin/kube-apiserver
4.0K	server/bin/kube-apiserver.docker_tag
106M	server/bin/kube-apiserver.tar
95M		server/bin/kube-controller-manager
4.0K	server/bin/kube-controller-manager.docker_tag
97M		server/bin/kube-controller-manager.tar
54M		server/bin/kubectl
48M		server/bin/kube-dns
103M	server/bin/kubelet
101M	server/bin/kubemark
49M		server/bin/kube-proxy
4.0K	server/bin/kube-proxy.docker_tag
178M	server/bin/kube-proxy.tar
57M		server/bin/kube-scheduler
4.0K	server/bin/kube-scheduler.docker_tag
58M		server/bin/kube-scheduler.tar
```

If the point of the release is for end-users to turn up a kubernetes cluster, do they even need the binaries? Why not just give them the image?

I also think it makes sense to split the release up by server architectures.

@david-mcmahon

**Comment by justinsb** [comment]
Some previous discussion here: https://github.com/kubernetes/kubernetes/issues/9253  Apparently some of the duplication is/was for CoreOS?

Although kube-up uses this tarball, there's no need to: the expanded files are also available for direct download (kubectl, kubelet), and gcr.io has all the images.

**Comment by david-mcmahon** [comment]
cc @robertbailey

**Comment by roberthbailey** [comment]
So I just came across this (while downloading the 1.3.0 binaries) and I agree that this is completely ridiculous. We need an owner for this issue for 1.4.

**Comment by thockin** [comment]
@david-mcmahon Can we stick you with this for 1.4?

**Comment by alex-mohr** [comment]
I think this falls under @david-mcmahon and the release infra area, so proactively assigning -- David, let us know if you disagree.

I think this is also interesting to install, because downloading a 1.4GB tarball that extracts to 3+GB is a relatively sad install process.

There may be short-term expedient things we could do, e.g. building multiple tar balls with only linux x86-64 or srcs while still supporting the one-big-ball, in addition to hyperkube-style minified builds.

**Comment by mikedanese** [comment]
We explode those tars in GCS. We should document how to pull specific pieces of the release.

https://gist.github.com/mikedanese/d3eed580c7f0a0e5c13534220f88eb5a

**Comment by david-mcmahon** [comment]
This looks like a huge meta-issue with several solutions affecting many areas of the product.

If we all agree on @jbeda 's suggestion solutions, each should be broken out into their own bug (grouped where appropriate) and assigned. 

Many of these solutions potentially have product/user/usability ramifications and need the attention of the area owner(s).

I'll make a first pass at the original list.  Others feel free to add/update.

**Comment by david-mcmahon** [comment]
I am unlikely to have the bandwidth to drive this further this quarter or before 1.4.  Area leads should be assigning the subtasks @jbeda identified and I filed issues for to get this done before 1.4.   @thockin @mikedanese @davidopp @luxas @quinton-hoole @alex-mohr.  Please cc anyone I've missed.

**Comment by pwittrock** [comment]
@david-mcmahon @jbeda @alex-mohr  I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here, move it back and provide daily updates to this issue.

**Comment by ixdy** [comment]
Let's plan to make this a high-priority item for 1.5? I will own it.

**Comment by luxas** [comment]
Great! We can probably remove windows/386 then...

**Comment by ixdy** [comment]
Another curiosity: our "server" tarballs include the kubernetes src tarball. Is there a good reason to be doing that?

**Comment by ixdy** [comment]
It looks like we do this explicitly, per https://github.com/kubernetes/kubernetes/pull/27830 https://github.com/kubernetes/kubernetes/pull/27840 and https://github.com/kubernetes/kubernetes/pull/27985.

**Comment by jbeda** [comment]
Happy to help attack this for 1.5.

As for the source tarballs -- those PRs are where it happened but there is no _why_ there.  @zmerlynn -- do you have the reasoning there?

**Comment by zmerlynn** [comment]
Yes, it was a legal requirement that the source, and not just a link to the source, appear on the machine.

**Comment by jbeda** [comment]
@zmerlynn -- can you give a bit more context? Where does this legal requirement come from? Which machines?

Obviously if I'm installing k8s on my own VM/hardware there is no need to have the source on that same machine.  GCE runs VMs where the linux kernel code isn't on the machine.  This is a bit confusing for me.

**Comment by zmerlynn** [comment]
If you want to talk further about this, I recommend we schedule time with our lawyers rather than continuing on this thread. I implemented what was requested after several back and forths, after trying to get by with just a link to the source (which is what's present in 1.2).

That said, if someone wants to take the time to plumb the separate download into GKE and handle the changes in the startup script so this doesn't have to be in every server tarball (where it's not actually a huge component), it will satisfy the same requirements. The route I chose was actually minimizing the number of URLs we hit, which is minorly important operationally for us, but it's not so important that I can live without it.

**Comment by jbeda** [comment]
Sounds like it is a sore spot.  As it isn't the biggest problem now, I'm guessing we can leave it for later.  I don't get it but... lawyers.

**Comment by justinsb** [comment]
Just closed #9253 as a dup, opened almost exactly a year before this, where I complained:

> kubernetes-server-linux-amd64.tar.gz is 71 MB; that seemed bigger than I remember it being.

Ah, the good old days!  Looking forward to issue 48888 around July of 2017, where someone complains that a 28GB .tar.gz is unacceptable.

**Comment by ixdy** [comment]
#9253 describes a slightly different issue, which still exists; we include several of the server binaries twice in each arch tarball.

**Comment by luxas** [comment]
@ixdy IIUC, kubemark will be moved to perf-tests, right?
That will be an improvement to remove that one from the tarball at least

**Comment by ixdy** [comment]
@luxas yes, though it's already been pulled out of the server tarballs into the test tarball with https://github.com/kubernetes/kubernetes/pull/33409

**Comment by dims** [comment]
@ixdy work on this will move to 1.6? (This needs to be triaged as a release-blocker or not for 1.5)

**Comment by dims** [comment]
@ixdy work on this will move to 1.6? (This needs to be triaged as a release-blocker or not for 1.5)

**Comment by luxas** [comment]
If I understand correctly, @ixdy has already made some improvements by splitting the monotarball out to one tarball per arch.

But I think there's work left to do, so moving to v1.6

**Comment by ethernetdan** [comment]
@ixdy can this be closed?

**Comment by liggitt** [comment]
pre-existing for 1.6, not a release blocker

**Comment by roberthbailey** [comment]
Is anyone from @kubernetes/sig-release-feature-requests working on this feature request?

**Comment by enisoc** [comment]
Since 1.6 or so, we've had separate per-arch tarballs, and the main one is only a few MB with a script to download only the arch you're running on. I haven't heard any complaints about tarball size since then.

**Comment by roberthbailey** [comment]
Should we close this then?

**Comment by jbeda** [comment]
Close enough.  I'm closing it. Victory is ours!
