### ISSUE TITLE
Node E2E: Prep for node conformance test.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#29081]
For https://github.com/kubernetes/kubernetes/issues/30122.

In 1.4, we plan to provide part of the node e2e test to the user as the node conformance test.

Later, we'll have a comprehensive roadmap about this, after finalizing with the team @kubernetes/goog-node @kubernetes/sig-node 

But before that, to prepare for the node conformance test, there are several working items we should do to improve the **test coverage and the reliability** of the test framework.
- [x] https://github.com/kubernetes/kubernetes/pull/28807 #29536 #29806 Make it possible to share test case between e2e test and node e2e.
  * This makes it much easier to improve the test coverage.
  * Ideally, all node e2e compatible e2e test should be shared between the 2 test suites.
  - [ ] Add image white list. [Related issue: https://github.com/kubernetes/kubernetes/issues/29155]
- [x] #29806 #29807 #29809 #29814 Consolidate existing e2e and node e2e test, and move them into the shared diretory.
  * This directly improves the test coverage.
- [x] https://github.com/kubernetes/kubernetes/pull/29020 Start namespace controller in node e2e test framework. [Related issue https://github.com/kubernetes/kubernetes/issues/28320]
  * This makes it easier to improve the test coverage.
    * Originally the automated namespace cleanup is not enabled in node e2e, becaue of lack of namespace controller. When migrating test from e2e to node e2e, we have to carefully take care of the cleanup. 
    * After this, we can directly migrate test from e2e, and the test framework will automatically handle cleanup as what it has done in the e2e test.
  * This makes the test framework more reliable.
  * This also improves the user experience if we provide the node conformance test to the user.
- [x] https://github.com/kubernetes/kubernetes/pull/29092 Run node e2e test in parallel. [Related issue https://github.com/kubernetes/kubernetes/issues/26215]
  * This makes it easier to improve the test coverage.
    * Most tests are time consuming. Now all node e2e tests run sequentially. As we improve the test coverage, the test duration will increase quickly.
    * In fact most time the test is just sleeping and waiting for specific state. Parallelize the tests could significantly decrease the test duration.
  * This also improves the user experience if we provide the node conformance test to the user.

More working items: TBD

XRef https://github.com/kubernetes/kubernetes/issues/28408, because kubelet verify is considered to be a subset of node conformance test.

**Comment by Random-Liu** [comment]
This one is done, close it. :)
