### ISSUE TITLE
CRI implemention in kubelet (with in-process docker integration)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29478]
This issue tracks TODOs for the client-side implementation of CRI in kubelet, as well as the in process docker integration via CRI (#31459). 
- [x] Support [pull `qps` and `burst` for image pulling](https://github.com/kubernetes/kubernetes/blob/007257a5adac832d276af10cbe0c617e6189f04a/pkg/kubelet/dockertools/docker.go#L120). I think we should extract the logic `dockerPuller` for the new runtime to use. (#33228)
- [x] [encoding lifecycle hooks](https://github.com/kubernetes/kubernetes/blob/007257a5adac832d276af10cbe0c617e6189f04a/pkg/kubelet/dockertools/docker_manager.go#L573) (#33389)
- [x] Calculate OOM score. (#33443)
- [x] Handle custom pod infra container image (and credentials). (#33488)
- [x] Support setting environment variables for pod sandboxes (original PR for the feature #20719)
  - The feature is used exclusively by the mesos framework. Opened an issue to discuss how mesos should integrate with CRI. https://github.com/kubernetes-incubator/kube-mesos-framework/issues/34
- [x] Instrument the [interfaces](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/services.go) (#35489)
- [x] Image pulling progress (done by using `kube_docker_client` directly
- [x] Version cache (#34332)
- [x] Save port name in docker via labels for PortMappings
- [x] AppArmor #22159 (#33500)
- [x] Seccomp support (#33500)
- [x] Support apparmor/seccomp: dockershim completed, need docs in CRI #34819.
- [x] Use RepoDigest for image ID (#33014, https://github.com/kubernetes/kubernetes/pull/34380) 
- [x] sysctl #27180 (#34830)
- [x] Move runtime cgroup management down to dockertools/dockershim (#33980)
- [x] Container logging #34376 #35348 #34858
- [x] ImageStats in CRI #33048
- [x] Support pod/container security context features: #34811
    - Add/drop capabilities (api being discussed in #33614, #35910)
    - [SELinux relabel](https://github.com/kubernetes/kubernetes/blob/007257a5adac832d276af10cbe0c617e6189f04a/pkg/kubelet/dockertools/docker_manager.go#L481); API discussion in #33139

======= TODOS AFTER 1.5 =============
- [ ] Sandbox resource requirements: depends on pod level cgroup #31546
- [ ] Make [pod_container_deletor](https://github.com/kubernetes/kubernetes/blob/e067f7548f6975c34d0e3cc5fb3b893ba11146c8/pkg/kubelet/pod_container_deletor.go) sandbox-friendly. 
- [ ] [Nvidia gpu support](https://github.com/kubernetes/kubernetes/blob/007257a5adac832d276af10cbe0c617e6189f04a/pkg/kubelet/dockertools/docker_manager.go#L587) **claimed by @feiskyer**
- [ ] *Docker v1.10  support
- [ ] **ShmSize support #34928

Backward compatibility with containers created by non-CRI enabled kubelet. This includes (but not limited to) the following tasks. 
**Need a complete assessment of all changes required before diving into implementation**
- [ ] Listing containers without filters (to see old containers).
- [ ] Distinguish between annotations and labels from older containers (https://github.com/kubernetes/kubernetes/issues/29252#issuecomment-239526039) 

*TBD items that may be dropped later.
**Features with WIP PRs.
# 

Related issues:
- Migrate docker to using the new runtime interface #29252
- Previous kuberuntime issue #31458

/cc @feiskyer @Random-Liu

**Comment by Random-Liu** [comment]
Known compatible issues with docker 1.9 and docker 1.10:
- [ ] `seccomp=unconfined` is added in docker 1.11, for **docker <=1.10**, it should be `seccomp:unconfined`. This will cause error `failed to create a sandbox for pod "XXX": Error response from daemon: Invalid --security-opt: "seccomp=unconfined"` (See https://github.com/docker/docker/issues/24810)
- [ ] Using filter with empty engine-api version is not compatible with **docker 1.9**. Filter type of docker engine-api is changed in docker 1.10 (See https://github.com/docker/engine-api/issues/171). Docker engine api has fixed this based on client version https://github.com/docker/engine-api/pull/174. However, in our code, we [don't set client version](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L376), so that docker client won't work properly. This should be fixed, because this may cause even more problems in the future.

**Comment by feiskyer** [comment]
There is also an item above with same concern: which version of kubelet should backward to?

> add huge chunk of code to ensure backward compatibility (i.e., kubelet can track older containers). This includes, but not limited to, listing containers without filters (to see old containers). Still updating.

**Comment by Random-Liu** [comment]
@feiskyer I think that part means that on old containers there are no labels, and we can't do filter. Not exactly the same problem. :)

**Comment by yujuhong** [comment]
> Whether do we care about docker <=1.10 for CRI? I think at least we may want to care docker 1.10.

I think we'll most likely drop support for docker 1.9 in the next release, so let's cross that out from our list. 
For 1.10, we should try o support it if possible. /cc @dchen1107

**Comment by Random-Liu** [comment]
Claim `encoding lifecycle hooks`. :)

**Comment by Random-Liu** [comment]
Claim `Nvidia gpu support`. :)

**Comment by resouer** [comment]
Will help `version cache (one of my own commits)`, `custom pod infra image`, `env for pod sandbox`.

**Comment by Random-Liu** [comment]
Claim `Instrument the interfaces`.

**Comment by Random-Liu** [comment]
@yujuhong By `Image pulling progress`, do you mean report image pulling progress in log? If so, it's in kube_docker_client, and should have already been supported if we keep using kube_docker_client.

**Comment by yujuhong** [comment]
> @yujuhong By Image pulling progress, do you mean report image pulling progress in log? If so, it's in kube_docker_client, and should have already been supported if we keep using kube_docker_client.

I think so. I probably wrote that before deciding to use kube_docker_client directly. Updated the original post to reflect the current status.

**Comment by feiskyer** [comment]
Claims gpu and sysctl

**Comment by feiskyer** [comment]
cc/ @kubernetes/sig-node

**Comment by Crazykev** [comment]
Claims these two:
1. `Listing containers without filters (to see old containers).`
2. `Distinguish between annotations and labels from older containers`

**Comment by feiskyer** [comment]
"Support pod/container security context features"  is addressed at #34811.

**Comment by feiskyer** [comment]
@yujuhong Some more features not tracked here:

- [ ] Sandbox resource requirements: depends on pod level cgroup #31546
- [ ] Container logging #34376
- [ ] ImageStats in CRI #33048
- [ ] Support add or drop capabilities in dockershim.
- [ ] Support apparmor/seccomp: dockershim completed, need docs in CRI.

**Comment by yujuhong** [comment]
> Claims these two:
> 1. Listing containers without filters (to see old containers).
> 2. Distinguish between annotations and labels from older containers

@Crazykev thanks for offering to help! We don't have a clear picture of what's missing in supporting old k8s containers. It'd be great if you can start from /checkingtesting the new CRI integration with the old containers and see what would need to be added to support them. After gathering all the items, we can assess how much work is needed, and how we want to approach it. Thanks!

**Comment by yujuhong** [comment]
> @yujuhong Some more features not tracked here, please adds them to the list.

Included in the list. Thanks!

**Comment by Random-Liu** [comment]
Another potential thing needs to support once it gets approved, just track here https://github.com/kubernetes/kubernetes/pull/34928.

**Comment by dims** [comment]
@Random-Liu @yujuhong This needs to be triaged as a release-blocker or not for 1.5

**Comment by yujuhong** [comment]
I think we've finished all 1.5 requirements. Closing this one and will file a new issue for the remaining work targeted for 1.6
