### ISSUE TITLE
Node Conformance Test Planning

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#30122]
# Background

**Node Conformance Test** is a test suite testing whether the node meets the minimum requirement of Kubernetes. it is aimed to validate whether a node is qualified to join the Kubernetes cluster, so as to:
- **Help user bring their own nodes into the cluster.** The user should make sure their nodes can pass node conformance test before bringing them into the cluster.
- **Help the third party vendor bake and verify their Kubernetes node image.** The image vendor should make sure their image could pass the node conformance test.
- **Help define NodeSpec(https://github.com/kubernetes/features/issues/56).**
  - NodeSpec is the specification of a qualified node. A node which meets the specification should be able to join the Kubernetes cluster. However, because people may run kubelet in many different environments - different hardware, OS distro, init system, runtime, configuration etc., it's hard to give a exhaustive and accurate specification for now.
  - Node conformance test can help us approach the goal. Instead of providing and validating the specification,  it treats the node as a blackbox and validates the node by running a set of functionality test. This can partially achieve the goal of NodeSpec, and as people run node conformance test in more and more environment, we will understand more environment and eventually get the NodeSpec.
# UX

Ideally, after users set up their nodes, including:
- Kubelet
- Container runtime
- CNI
- Other dependencies (See [build cni and kubelet debian packages](https://github.com/kubernetes/release/pull/35) for more information)

They just need to **run one command**, then it will automatically:
- Download the node conformance test package
- Test the entirety of the the node environment setup
- Generate test result
- Cleanup the package if needed.
# Plan

Currently, we've already got [node e2e test](https://github.com/kubernetes/kubernetes/blob/fe3dda1aeb788805df8b75381252daa9e5ad5690/docs/devel/e2e-node-tests.md), which is continuously running as both pre- and post- submit tests by the Kubernetes project.

**Conformance test is part of node e2e test.** So in Kubernetes 1.4, we plan to package and provide the node e2e test suite to the user as the node conformance test.
By default it should only run conformance test. However, if needed user can also run specific test to test some advanced functionality.

To achieve the goal, there are several things need to be done:
- [x] #29081 **Improve node e2e test coverage.** Currently, the node e2e still doesn't have enough test coverage yet. In the current cluster e2e, there are quite a few test could be run on the node level, for 1.4 we should at least enable all those tests in node e2e.
- [x] #29081 **Improve node e2e test framework.** There are some issues of current node e2e framework, such as running test sequentially #26215, not cleaning up properly after test running #28320 etc. These issues are acceptable in our test infrastructure, but are not acceptable for the user. For 1.4, we should fix these issues.
- [x] #30174 **Separate node conformance test framework from node e2e framework.** Node e2e is currently running as kubelet ci test, so except for running test, the framework also sets up kubelet. However, for node conformance test, user should have already set up the node and installed kubelet. We should separate out the test logic from node e2e framework.
- [x] #30174 **Package node conformance test suite.** For easy distribution and adoption, we'll package the node e2e test suite including all dependencies as a docker image. Users only need to run a `docker run`, `rkt run` etc. to test their node.
- [x] [Doc](https://docs.google.com/spreadsheets/d/1yib6ypfdWuq8Ikyo-rTcBGHe76Xur7tGqCKD9dkzx0Y/edit?usp=sharing) **Define conformance test.** We should define which tests are conformance, which are not.
- [ ] **Add node conformance CI test.** We should add CI test to avoid new features or tests breaking node conformance test.
- [ ] [Optional] Add node conformance test into Kubernetes release process. Ideally, each Kubernetes release should have corresponding node conformance test, we should release node conformance test with Kubernetes.
- [ ] [Optional] #28408 Define preliminary NodeSpec and implement Kubelet verify.

@dchen1107 @vishh 
/cc @kubernetes/sig-node @kubernetes/sig-testing

**Comment by timothysc** [comment]
@jayunit100 engage por favor. 

/cc @ncdc.

**Comment by yujuhong** [comment]
Does the test use the kubelet that's already installed on the node (i.e., testing the entirety of the the node environment setup) or does it come with its own binaries? It's not very clear from the description what the test workflow is..

**Comment by Random-Liu** [comment]
@yujuhong It should test the kubelet that's already installed on the node. I'll update the description to make it more clear. :)

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @Random-Liu (or move to 1.6?)

**Comment by Random-Liu** [comment]
@dims This is 1.5. And it's done except a CI test. Will close this one when the test is done.

**Comment by dims** [comment]
Awesome. I'll mark it as non-release-blocker then @Random-Liu

**Comment by Random-Liu** [comment]
@dims SGTM. :)

**Comment by dchen1107** [comment]
I filed an separate issue #37252 to track the rest of integration of node conformance test with our ci and release process. But I think as node conformance test framework itself, we can close this issue.

**Comment by dchen1107** [comment]
@Random-Liu is going to update kubernetes/features#84 with the latest updates for 1.5 release including the documentation.
