### ISSUE TITLE
Integrate docker with kubelet via CRI

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#31459]
Meta issue: #28789

This issue tracks the progress of docker integration via CRI.

The initial CRI server-side implementation for docker is in the [`pkg/kubelet/dockershim`](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/dockershim) package. We chose to let the code remain in the kubelet codebase to help with the migration. It will also not go through grpc/protobuf until the features are completed.

For 1.5, we aim to have a functional docker integration.
- [x] **P0** Feature parity
  - [x] Pass node conformance e2e test (https://github.com/kubernetes/kubernetes/issues/33189)
  - [x] Pass cluster e2e test (https://github.com/kubernetes/kubernetes/issues/33189) (host port support has been dropped for the integration in 1.5)
- [x] **P0** Reliability and regression-proof
  - [x] Set up node e2e continuous jenkins builders (https://github.com/kubernetes/kubernetes/pull/33054, https://github.com/kubernetes/test-infra/pull/617)
  - [x] Set up cluster e2e continuous jenkins builders (https://github.com/kubernetes/test-infra/pull/712)
  - [x] Set up per-PR, presubmit builds (https://github.com/kubernetes/kubernetes/pull/34068, https://github.com/kubernetes/test-infra/pull/755)
  - [x] Set up soak e2e builders (https://github.com/kubernetes/test-infra/pull/922)
- [x] **P1** Validate CRI integration via grpc
  - [x] Support switching to using grpc via a kubelet flag (https://github.com/kubernetes/kubernetes/pull/33988)
- [ ] **P2** CRI conformance test (https://github.com/kubernetes/kubernetes/issues/34040)
- [x] **P2** Backward compatibility
  - [x] Support docker v1.10
- [x] **P2** No performance regression
  - [x] Set up node e2e serial builds (https://github.com/kubernetes/kubernetes/pull/34141, https://github.com/kubernetes/test-infra/pull/761)
  - [x] Verify difference latency, resource usage, etc, are within our SLO (https://github.com/kubernetes/contrib/pull/1841)
- [x] **P3** Kubelet in-place upgrade (?)

---

Implementation TODOs: #29478
Current integration CI Node E2E builder (#33189): https://k8s-testgrid.appspot.com/google-node#kubelet-cri-gce-e2e
Current integration CI E2E builder (https://github.com/kubernetes/test-infra/pull/712): https://k8s-testgrid.appspot.com/google-gce#gci-gce-cri
Current presubmit builder:
- `@k8s-bot cri node e2e test this` to trigger node e2e test.
- `@k8s-bot cri e2e test this` to trigger e2e test.
- `@k8s-bot cri test this` to trigger both.

Relevant PRs so far: #29700, #29553, #29580
Relevant issues: #29252

**Comment by Random-Liu** [comment]
Got the first e2e result: `202 Passed | 12 Failed | 0 Pending | 194 Skipped`

**Comment by feiskyer** [comment]
> Got the first e2e result: 202 Passed | 12 Failed | 0 Pending | 194 Skipped
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce-cri/1

Hmm, initcontainers are already addressed in #33363, port-forwarding is not implemented yet, we could deal it same with exec for docker.

**Comment by feiskyer** [comment]
Claims port-forward for docker.

**Comment by Random-Liu** [comment]
Claims attach for docker. Attach is also not implemented in kuberuntime yet. I'll verify with my local cluster even though the change is very small. :) Will send a PR soon after I verify it.

**Comment by Random-Liu** [comment]
I run density test to compare operation latency with grpc/non-grpc integration.
Here is the result: https://docs.google.com/spreadsheets/d/1CK-lq2rERkx50-DXl3QUYLtaTNCIZyaQAezEMTnYJc0/edit?usp=sharing

It turns out that the latency increment is not very significant, for example list_container is increased by 30%.

However, the memory usage is increased by about 30-40%:
![screenshot from 2016-10-27 16 37 23](https://cloud.githubusercontent.com/assets/5821883/19794820/6a26bed8-9c8a-11e6-8d15-c0c88f1ecd0f.png)

I'll run some test to analyze the memory usage increment.

**Comment by dims** [comment]
@yujuhong @Random-Liu This needs to be triaged as a release-blocker or not for 1.5

**Comment by yujuhong** [comment]
We completed all the p0/p1 items. Moving the issue to 1.6 to finish the rest.

**Comment by redbaron** [comment]
is it still planned for 1.6?

**Comment by yujuhong** [comment]
Yes, we just enabled the CRI implementation by default in kubelet last night.

**Comment by redbaron** [comment]
great!  does it mean that `hostPort` feature will work for CNI enabled setups?

**Comment by yujuhong** [comment]
@redbaron unfortunately no. It works for kubenet, but not for CNI. The effort of pushing host port logic down to CNI is tracked in #31307

**Comment by yujuhong** [comment]
Closing this issue since the only thing left is the CRI validation test, which is tracked separately.
