### ISSUE TITLE
Epic: make genericapiserver generic

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#32792]
Here is the board: https://github.com/kubernetes/kubernetes/projects/2
## Todo:
- [ ] reconsider where /healthz lives (now instantiated in the master)
- [ ] make /version customizable without the need to use ldflags
- [ ] unify how optional non-rest routes can be enabled/disabled: probably get rid of `Config.Enable*` variables
- [ ] make api prefix configurable : https://github.com/kubernetes/kubernetes/issues/18991
- [ ] handle handle empty prefixes gracefully
- [ ] move flags install to common place: https://github.com/kubernetes/kubernetes/issues/24062
- [ ] make pkg/apiserver/api_installer.go more generic (or should be made generic)
- cmd/kube-apiserver/app/server.go:
  - [ ] newEtcd should be moved to a genericapiserver/etcd package or something
  - [ ] All the if blocks (`if !apiGroupVersionOverrides["extensions/v1beta1"].Disable {`) should be refactored into something that operates in a loop over a map or something, and moved to the generic apiserver
- [ ] move `pkg/api/requestcontext.go` to `apiserver` package? https://github.com/kubernetes/kubernetes/pull/33164#pullrequestreview-936569
- [x] move `KubernetesServiceNodePort` from genericapiserver to master 
- [x] split `options.ServerRunOptions` into generic and non-generic part
## WIP:
- [x] move non-rest routes into `routes` sub-packages https://github.com/kubernetes/kubernetes/pull/32387
- [x] posthooks for initialization: https://github.com/kubernetes/kubernetes/pull/31529
- turn `genericapiserver.Run()` into `Serve()` as much as possible:
  - [x] https://github.com/kubernetes/kubernetes/pull/33095
  - [ ] reconsider where OpenAPI and swagger endpoints are installed after APIs have been installed (it's now in `Run()`
- [x] make auditing injectable https://github.com/kubernetes/kubernetes/pull/33164#discussion_r79818752
- [x] make handler chains customizable: pre/post authn/authz handlers, secure vs. insecure. Probably replace direct `genericapiserver.Mux` access with this. https://github.com/kubernetes/kubernetes/pull/33164#discussion_r79819350: 
  [![#33365](https://github-shields.com/github/kubernetes/kubernetes/pull/33365.svg)](https://github.com/kubernetes/kubernetes/pull/33365.svg)
- [x] add locking to `genericapiserver.apiGroupsForDiscovery`
- [x] `apiserver.InstallServiceErrorHandler` overwrites the container `ServiceErrorHandler`. But the `apiVersions` passed are only those of one group, not all groups: https://github.com/sttts/kubernetes/blob/1350325037cea3355c9d92bcdfeed08be4c18eac/pkg/genericapiserver/genericapiserver.go#L408: PR fixing this as a side-effect: [![#33368](https://github-shields.com/github/kubernetes/kubernetes/pull/33368.svg)](https://github.com/kubernetes/kubernetes/pull/33368.svg)

Related: minimal routes for an apiserver https://github.com/kubernetes/kubernetes/issues/32678

**Comment by piosz** [comment]
cc @mksalawa

**Comment by sttts** [comment]
Closing as most is addressed or not applicable anymore after k8s.io/apiserver has been introduced.
