### ISSUE TITLE
Tracking: Kubernetes Product Security Response Plan

### ISSUE THREAD

**Issue by philips** [kubernetes/kubernetes#35462]
This is a tracking issue for creating, documenting, and exercising a Kubernetes Product Security Response Plan. The overall goal is to ensure that when a security vulnerability becomes known the entire Kubernetes community has processes, infrastructure, and communication channels to make an organized and responsible response for users.

The document describing the initial implementation of this [plan is here](https://docs.google.com/document/d/1dGzReKkYdRwyj2uYFMeIJbZesnBlhWgCeuSJ9af4gbE/edit#).

Special thanks to the many folks who helped to review and make additions to this document: Kees Cook, Jess Frazelle, Matthew Garrett, Jordan Liggitt, Kurt Seifried, Davanum Srinivas, and many many more.

**Comment by philips** [comment]
Next steps I would like to have completed by KubeCon (Nov 8th and 9th):

- [ ] Cleanup the response doc and try and put the relevant parts into the dev guide and kubernetes home page (I can lead this)
- [ ] Create a private github repo and a private CI system to handle private disclosures (could you lead this @jessfraz?)
- [ ] Create a vendor survey for people to sign-up for embargoed disclosures (I will get advice from @mjg59 and then help put this together)
- [ ] Create a process for adding/removing people from the product security team (@sarahnovotny could you draft this or delegate?)

**Comment by sarahnovotny** [comment]
ack.  will draft something.

**Comment by bgrant0607** [comment]
cc @alex-mohr @eparis

**Comment by philips** [comment]
Got caught up with KubeCon madness. Targeting getting this done this week.

Any progress on the requisite systems @jessfraz?

**Comment by jessfraz** [comment]
I don't have the permissions and pinged a few people I'll reping, sorry for
the delay

On Nov 15, 2016 10:31, "Brandon Philips" <notifications@github.com> wrote:

Got caught up with KubeCon madness. Targeting getting this done this week.

Any progress on the requisite systems @jessfraz
<https://github.com/jessfraz>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35462#issuecomment-260468894>,
or mute the thread

**Comment by philips** [comment]
@jessfraz no worries, I think we were all overly optimistic about the ability to get stuff done before KubeCon :)

**Comment by philips** [comment]
@jessfraz Is there something I can help with externally? @ethernetdan or @calebamiles might be able to pitch in.

**Comment by jessfraz** [comment]
ping @alex-mohr I was told to get your approval :)

**Comment by philips** [comment]
First docs PR is up: https://github.com/kubernetes/kubernetes.github.io/pull/1819

**Comment by philips** [comment]
@sarahnovotny did you get a chance to draft anything re: https://github.com/kubernetes/kubernetes/issues/35462#issuecomment-255966377

**Comment by philips** [comment]
dev docs PR is up https://github.com/kubernetes/kubernetes/pull/37836

**Comment by philips** [comment]
dev docs PR moved to community repo https://github.com/kubernetes/community/pull/126

**Comment by jessfraz** [comment]
Just to update working on test-infra things here: https://github.com/kubernetes/test-infra/pull/1515/files

**Comment by philips** [comment]
@jessfraz what is the status of your test-infra? I am updating the process document now and adding all of the release managers to the security list.

**Comment by jessfraz** [comment]
yeah i gotta force someone on eng-prod to review and probably sit with them to test :) will do next tomorrow if not next week!

**Comment by philips** [comment]
@jessfraz Got it. I have made major improvements to the security process doc. https://github.com/kubernetes/community/pull/126

Hoping to get this merged this week.

**Comment by jessfraz** [comment]
So also along with the CI stuff if we want the bots on that repo we need to
add seats for them, we probably just need the k8s-ci-bot to start and we
can merge manually if all tests pass and skip the merge-bot
And then we might need a couple seats for engprod to help as well

**Comment by philips** [comment]
The security release process doc is merged: https://github.com/kubernetes/community/blob/master/contributors/devel/security-release-process.md

**Comment by philips** [comment]
The PST is drafting something now.

/remove-lifecycle stale
