### ISSUE TITLE
StatefulSet tests 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#36855]
A list of tests for StatefulSet (excluding existing ones). Feel free to extend / update the list:

- [x] Scale StatefulSet up/down #30082 (PR: #32868, #34454)
- [ ] StatefulSet upgrades
  - [x] Manual update (PR: #36849)
  - [ ] Rolling update #28706 (not implemented yet)
- [ ] StatefulSet examples 
  - [x] All existing examples (PR: #36793)
  - [ ] Add as least a non-database example, and a test for it 
  - [x] Enable cluster restart test (PR: #36910)
- [ ] Pod network identity
- [ ] Upgrade of the kubernetes node should keep the petset functioning as intended
- [ ] Rollbacks should occur as expected in case of a network partition and maintain data consistency
- [ ] StatefulSet fencing #31762 
  - [x] Network partition tests for statefulset 
- [ ] Overlapping StatefulSets should fail gracefully (not handled yet, target 1.6)
- [ ] PV/PVC
  - [ ] Delete a pod's PVC, it should come back with the same name (should that emit warning events?)
  - [ ] Delete pods won’t affect PVCs / PVs (unless other delete policies implemented and specified)
- [ ] Check that pods creation timestamps don't overlap 
- [ ] Rollbacks should occur as expected in case of a network partition and maintain data consistency

cc @erictune @foxish @kow3ns @kubernetes/sig-apps

**Comment by foxish** [comment]
Thanks for putting together the list. I think we should clarify/edit a few of these tests mentioned.

* Rolling updates are not implemented, and we're just going to document the manual process with them for the supported StatefulSet examples IIUC.
* Fencing currently has some tests for various controllers (including statefulset) in [test/e2e/network_partition.go](https://github.com/kubernetes/kubernetes/blob/6ea8606c59265c37e2dfc720ff23ebcf7d78d228/test/e2e/network_partition.go). 
*  Rollbacks should occur as expected in case of a network partition and maintain data consistency: I think this one should be moved into the e2e tests we write for charts. IIRC, rollbacks were a concern for mongo, which became an issue in https://github.com/kubernetes/kubernetes/issues/30289#issuecomment-238883607.
* Overlapping StatefulSets should fail gracefully: can we have overlapping StatefulSets? The name is a lock and the pods-names are based on the name.

**Comment by janetkuo** [comment]
> Overlapping StatefulSets should fail gracefully: can we have overlapping StatefulSets? The name is a lock and the pods-names are based on the name.

We find pods with statefulset selector here https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.0/pkg/controller/petset/pet_set.go#L219
Perhaps instead of adding this test, we should update the code to not use selector but use name prefix

**Comment by foxish** [comment]
I agree. Filed issue https://github.com/kubernetes/kubernetes/issues/36859.
