### ISSUE TITLE
[CRI] dockershim networking umbrella issue 

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#37316]
Umbrella issue for tracking CRI networking related tasks for k8s 1.6

- [X] Maintain checkpoints in dockershim. Plus, ensure no resource (IP, hostport) leaks. 
https://github.com/kubernetes/kubernetes/issues/35531

- [X] Support native docker networking 
#38430

- [X] Support hostport in kubenet
https://github.com/kubernetes/kubernetes/issues/35457 

- [x] Enable Traffic Shaping
#41588

- [ ] Now that kubenet works with CRI, make sure other CNI network plugins works too.
https://github.com/kubernetes/kubernetes/issues/28653

**Comment by yujuhong** [comment]
One more item: 
- Support native docker networking

**Comment by resouer** [comment]
@yujuhong docker native networking is a "docker specific" feature, how we properly add it to k8s API? i.e., a filed named "network" only work for docker in pod spec will be wired...

**Comment by freehan** [comment]
@resouer network sig is working on defining the network object. As a first step, we just use the default network mode. See #38430

**Comment by resouer** [comment]
Em, that make sense, I think I must missed something. @freehan, Any existing doc or issue of `network` object handy?

**Comment by freehan** [comment]
@resouer It is still being drafted. see https://github.com/kubernetes/kubernetes/issues/27398#issuecomment-268572492

**Comment by freehan** [comment]
refer: https://github.com/kubernetes/features/issues/54

**Comment by yujuhong** [comment]
@freehan I think this one can be closed.

**Comment by freehan** [comment]
Other CNI network plugins have not been tested with the CRI integration yet. And we are in the process of upgrading libcni (CNI library), calico guys are upgrading stuff and etc...

**Comment by squeed** [comment]
IIRC there were plans to turn kubenet in to a CNI plugin - is there an issue for that? Is that still part of the plan?

**Comment by freehan** [comment]
Turning kubenet into a CNI plugin is a long term plan. I think there is a issue somewhere. That is not a blocker for CRI in 1.6. 

The CNI network plugin related item is mainly about ensuring CNI network plugin works with CRI.

**Comment by squeed** [comment]
Understood, thanks.

**Comment by yujuhong** [comment]
> Other CNI network plugins have not been tested with the CRI integration yet. And we are in the process of upgrading libcni (CNI library), calico guys are upgrading stuff and etc...

I see. I marked this 1.6 to help tracking the issues.

**Comment by dchen1107** [comment]
What is the decision for the last item listed above: Now that kubenet works with CRI, make sure other CNI network plugins works too. Any tests / validation performed? compatible or not? Please note that CRI is enabled by default in OSS k8s. 

cc/ @kubernetes/sig-network-misc

**Comment by dchen1107** [comment]
I punt the last item to 1.7 milestone. But @freehan please do some validation tests with other CNI network plugins, and document the test results asap. This helps the release note too so that we can properly guide the users. 

cc/ @devin-donnelly @calebamiles

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr

**Comment by cmluciano** [comment]
I can test out a few CNI plugins. Are there certain tests cases that should be run through ? @freehan @dchen1107 @yujuhong

**Comment by bowei** [comment]
@cmluciano @yujuhong -- can you document your test process if you are taking this on, I would like to get some idea of what an automated suite will look like

**Comment by yujuhong** [comment]
> @cmluciano @yujuhong -- can you document your test process if you are taking this on, I would like to get some idea of what an automated suite will look like

I don't have enough insight on what CNI plugins to test, but since this issue was re-targeted for 1.7, I think @freehan will be able to provide more input once he's back. 

We don't have a dedicated "networking" test suite, I'd imagine if we had one, it should be either part of the node or cluster e2e suite. In general, the node e2e suite should give you the basic confidence for pod networking (of course the test coverage may not be complete, but that can always be improved).

**Comment by cmluciano** [comment]
Ok i will await freehan's response and start looking at the node e2e suite

**Comment by bboreham** [comment]
The network e2e tests are concentrated in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/networking.go

**Comment by freehan** [comment]
FYI, 
PR https://github.com/kubernetes/kubernetes/pull/42202 is in flight to update cni network plugin to comply with CNI v0.5 spec. 

@cmluciano 
Here are some networking related tests you can start with:
Basic tests for pod-to-pod communication (support both in node and regular e2e): https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/networking.go

More comprehensive tests (only support regular e2e)
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/networking.go
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/serviceloadbalancers.go

**Comment by thockin** [comment]
when do we close this?

**Comment by cmluciano** [comment]
I think this can be closed since the e2e testing of CNI plugins is tracked in https://github.com/kubernetes/kubeadm/issues/218

/assign /close

**Comment by caseydavenport** [comment]
Try as we might, it seems this issue is not destined to be closed.

**Comment by cmluciano** [comment]
:rofl:
