### ISSUE TITLE
Federation e2e improvements

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#37354]
Our federation e2e's require a lot of love.
Filing this as a top level issue to track all the work that needs to be done.

* Reduce the running time:

- [ ] [#40765, #40766, #40767] Run the tests in parallel: All our tests are running serially right now. This was required because we did not have federated namespaces and hence there was no guarantee that each test can run independent of each other. We have recently done a lot of work to ensure that all tests run in their own namespaces. I believe that all tests have been fixed now. Need to ensure that and start running tests in parallel.
- [x] [#40765, #40768] Do not register and unregister cluster in each test case: Again this was required because our tests were not independent of each other. Now that they are, we can register and unregister the clusters once when we bring up and down the federation control plane. No need to do it in each test. This should also help reduce the running time.

* Fix resource leakage:

- [ ] Our e2e tests dont delete all the resources that they create resulting in resource leakage.
Examples:
https://github.com/kubernetes/kubernetes/issues/29335, https://github.com/kubernetes/kubernetes/issues/34060

* More extensive tests

- [ ] Generic tests for when clusters become unready. We do not have any tests at all for this case.
- [ ] Service controller e2e: We know of a lot of cases which are not being tested in our service e2e. Example: https://github.com/kubernetes/kubernetes/issues/27623
- [ ] Run the tests on GKE and AWS

- [ ] We should run federation e2e's as part of tests that run on every PR. Reducing the running time is a blocker for this since tests need to finish in 30 mins to be added there.

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
cc @madhusudancs @mwielgus I have filed this as a top level issue. Feel free to add anything that I missed

**Comment by nikhiljindal** [comment]
Our e2e tests are timing out after 500 mins on Jenkins!! That is crazy.
We need to fix the issues in "reduce the running time" bucket really soon.

**Comment by quinton-hoole** [comment]
Most of the runtime and resource leakage issues have been fixed, and we have pre-submit tests.  Closing this.
