### ISSUE TITLE
kubectl umbrella issue for printers and describers

### ISSUE THREAD

**Issue by fabianofranz** [kubernetes/kubernetes#38768]
### Printers issues

- [x] #38907 kubectl get broken for list 
- [ ] #38779 Update kubectl.GetPrinter to not return both nil for the printer and nil for the error on `wide` format
- [x] #38327 kubectl get -o yaml probably/maybe shouldn't filter pods
- [ ] #36733 kubectl get node(s) should show all node conditions
- [ ] #36304 "kubectl get events" or something else should give a sensible timeline of events
- [x] #34232 Fatal error while running `kubectl get ....`
- [ ] #34146 kubectl / kubernetes not 100% compatible with YAML 1.2
- [ ] #33817 printEventList is only used for watch-only and not for get event list
- [ ] #31943 strange kubectl get output
- [ ] #31344 Bug: Namespaces not shown when querying 3prs across all namespaces
- [ ] #30970 Kubectl panics when getting sorted replica set
- [ ] #29472 WIP: Proposal for moving "printers" (kubectl get) to the server
- [ ] #28754 Add warning for `kubectl get rs` for hidden objects
- [ ] #28551 Possible Bug: `kubectl get svc --export` omits `NodePort`
- [ ] #28190 Feature Request: `kubectl` should output `AGE` as elapsed time in current state
- [ ] #27212 `kubectl get rs` should be ordered better and hide 0 replica ones by default
- [x] #25579 Add software versions to "kubectl get nodes -o wide" output
- [ ] #20374 Kubectl get cluster
- [x] #15853 kubectl get in namespace with no objects returns nothing
- [ ] #15179 `kubectl get pods` behavior differs based on output mode wrt Failed pods
- [ ] #11994 kubectl: no way to list events about a specific object
- [ ] #11338 kubectl get -w doesn't clearly reflect resource deletions
- [ ] #10311 Sort yaml/json fields more helpfully when printing objects
- [ ] #8329 `kubectl get services` should warn the user if the service has no endpoints
- [ ] #36222 Configmap pretty display
- [ ] #30785 kubectl doesn't reflect pod condition
- [ ] #29679 kubectl view commands
- [ ] #29271 kubectl -n should support both `-n namespace/yournamespace` and `-n yournamespace`
- [ ] #14905 JSON output format directive overrides templates
- [ ] #39147 Include more info about deployments in `get -o wide`

### Describers issues

- [ ] #38698 Deployment description lacks basic info
- [ ] #38697 Replica set sizes are messed in the description of a Deployment
- [ ] #37576 How kubectl explain and describe output could be improved for external consumers
- [ ] #32699 GKE: Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
- [ ] #30555 Need to add more information in pv and pvc description
- [ ] #29876 kubectl pod status: describe does not match get
- [ ] #29651 PetSet describer should show the pod template, like RC / D / DS
- [ ] #25353 Kubectl describe doesn't support json output
- [ ] #25251 Stabilize describer outputs
- [ ] #25160 pod status does not reflect 'Reason' codes for failures that one sees when doing kubectl describe pod <podname>
- [ ] #23380 kubectl describe doesn't show annotations
- [ ] #22702 Clarify kubectl get/describe service output
- [ ] #20941 Make kubectl describers and resource printers more consistent
- [ ] #10885 kubectl describe pod does not show events for static pods
- [ ] #10674 kubectl describe - undocumented feature: resources are matched by prefix
- [ ] #4471 Describers should be able to print objects from somewhere besides the server
- [ ] #3731 Need consistent printing for Name, Namespace, etc
- [ ] #32883 kubectl describe should be resilient to errors in fetching related info
- [ ] #13501 printEvent Source to much more cleaner 

### JSONPath issues

- [ ] #37991 Kubectl -o jsonpath throws an error if field is not present in json
- [ ] #36391 JSONpath not drilling down into an RS .spec.template.metadata.name
- [ ] #28678 kubectl JSONPath doesn't allow use of `true` or `false` keywords
- [ ] #27090 kubectl get -o jsonpath does not handle objects with RawExtension
- [ ] #23386 JSONpath fails to return keys containing dots in a map
- [ ] #20352 JsonPath nested condition and multiple conditions are not working
- [ ] #16707 jsonpath template output should be json
- [ ] #15584 jsonpath implementation should support "$" for root in filters
- [ ] #14129 Unable to use kubectl get with a fieldSelector 
- [ ] #12771 JSONPath output needs a quote operator to safely generate arguments
- [ ] #15858 Cannot format a selector with jsonpath

**Comment by fabianofranz** [comment]
@kubernetes/sig-cli @kubernetes/kubectl

**Comment by AdoHe** [comment]
👍 Thanks for @fabianofranz great work. Guess we can go through this one by one.

**Comment by kargakis** [comment]
I've added one more in the printer issues list: https://github.com/kubernetes/kubernetes/issues/39147

**Comment by AdoHe** [comment]
Thanks @kargakis, will take a look.

**Comment by spiffxp** [comment]
/remove-help
I don't think this meets [the criteria for `help wanted`](http://git.k8s.io/community/contributors/devel/help-wanted.md). Please add back via `/help` if I'm incorrect

**Comment by soltysh** [comment]
@juanvallejo we need to check this list and figure out what needs fixing these days.

**Comment by juanvallejo** [comment]
This can be closed in favor of https://github.com/kubernetes/kubernetes/issues/63503

**Comment by spiffxp** [comment]
/close
per above comment
