### ISSUE TITLE
federation: Known issues

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#38893]
Compiling a list of high level known issues that customers should be aware of while deciding to use federation:

- [x] No way to disable specific APIs (#38593)
- [ ] Alpha APIs are enabled by default (https://github.com/kubernetes/kubernetes/issues/44291)
- [ ] No upgrade testing (#38537)
- [x] No kubectl tests (https://github.com/kubernetes/kubernetes/issues/32826)
- [x] Not all e2e tests are green (https://github.com/kubernetes/kubernetes/issues/37105)
- [ ] Unclear auth story (https://github.com/kubernetes/kubernetes/issues/35254)
- [ ] Not all API resources are supported in federation (http://kubernetes.io/docs/user-guide/federation/ lists the supported resources)
- [ ] Need to design HA federation control plane (https://github.com/kubernetes/features/issues/104)

cc @kubernetes/sig-federation-misc

**Comment by nikhiljindal** [comment]
cc @madhusudancs 

Please feel free to add anything that I missed

**Comment by valichek** [comment]
I tried to run federation control plane on aws but got many issues recently.
1. script https://github.com/kubernetes/kubernetes/blob/v1.5.1/federation/deploy/deploy.sh doesn't support `aws` provider
2. Tried to use old way (deploying manifests one by one), got `federation-apiserver`and `federation-controller-manager` running,  but then it resulted to `error in fetching secret: secrets "federation-apiserver-kubeconfig" not found` at `federation-controller-manager` container, no description for this secret found.
3. Couldn't find gcr.io/madhusudancs-containers/federation-charts

**Comment by madhusudancs** [comment]
@valichek Could you try using `kubefed` - http://kubernetes.io/docs/admin/federation/kubefed/?

**Comment by valichek** [comment]
@madhusudancs getting following errors when starting federation services with kubefed
```
Failed to attach volume "pvc-xxxx" on node "xxxx.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-xxxx is not 'available'
```
First time there was a message for ec-2 instance: "One or more volumes attached to this instance is impaired". And volume stuck in attaching. 
When tried again got the same error, but volume have been attached.

**Comment by valichek** [comment]
well, after some time, `apiserver` turned to be running, but not `controller-manager`, 

```
Cloud provider could not be initialized: could not init DNS provider "google-clouddns": 
google: could not find default credentials. 
See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I have check `kubefed` sources and found that `--dns-provider` and many other things are hardcoded and not configurable
https://github.com/kubernetes/kubernetes/blob/04a74570323eae3fc843ca7a6c34c28ada2847a9/federation/pkg/kubefed/init/init.go#L477

**Comment by madhusudancs** [comment]
@valichek 

> I have check kubefed sources and found that --dns-provider and many other things are hardcoded and not configurable
https://github.com/kubernetes/kubernetes/blob/04a74570323eae3fc843ca7a6c34c28ada2847a9/federation/pkg/kubefed/init/init.go#L477

That's an old commit. 

If you want to use AWS Route53 instead of Google Cloud DNS, pass `--dns-provider=aws-route53` to `kubefed init`.

For now, you can also configure everything you want by just editing the deployments directly after running `kubefed init`: `kubectl --context=<host-cluster> --namespace=federation-system edit deployment federation-apiserver` or `kubectl --context=<host-cluster> --namespace=federation-system edit deployment federation-controller-manager`.

We are collecting a list of things we need to make configurable. What else would you like to configure?

**Comment by valichek** [comment]
@madhusudancs well, for now it looks that I need to configure CIDR, I used kube-aws tool to run the cluster, and have following options:
`instanceCIDR: "10.0.16.0/20"`
`serviceCIDR: "10.128.0.0/20"`
`podCIDR: "10.128.16.0/20"`
`dnsServiceIP: 10.128.0.10`

If I understand the config properly, I have to change from `--service-cluster-ip-range=10.0.0.0/16"`
to `--service-cluster-ip-range=10.128.112.0/20/16"`, or should I leave it same as for cluster - `serviceCIDR: "10.128.0.0/20"` ?

And thank you.

**Comment by valichek** [comment]
And `--dns-zone-id` too

**Comment by rbtcollins** [comment]
@madhusudancs Is there a means to move the federation control plane to another cluster? We're trying to avoid in-place upgrades of k8s clusters - should I file a separate bug on kubefed?

**Comment by madhusudancs** [comment]
@valichek `--service-cluster-ip-range` in federation API server does nothing. So just leave the defaults as is. In the next release (v1.6), we are removing that flag from federation.

**Comment by madhusudancs** [comment]
@rbtcollins It is possible, but you have to orchestrate that manually. You just need to start the federation API server and controller manager pods in the new cluster and attach the etcd volume from the old cluster to those pods.

Please feel free to file an issue for `kubefed`. We will look into it when we design/implement HA support for federation control plane via kubefed.

**Comment by quinton-hoole** [comment]
We can update this issue to track all of the remaining GA items.

**Comment by xtophs** [comment]
Because deploy.sh is specific to gce and gke, federation e2e tests run [as documented](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#federation-e2e-tests) cannot run on Azure (or aws).

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#88.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
