### ISSUE TITLE
federation replicasets: known issues

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39986]
Documenting the list of known issues with federation replicasets:

- [ ] `kubectl delete rs` not working as expected: https://github.com/kubernetes/kubernetes/issues/38493, https://github.com/kubernetes/kubernetes/issues/42594.
- [ ] Bug in `kubectl delete rs --cascade=false`: https://github.com/kubernetes/kubernetes/issues/38223
- [ ] Enable federation-apiserver kubectl tests for replicasets: https://github.com/kubernetes/kubernetes/issues/39984.
- [ ] Figure out a path to GA for FederatedReplicaSetPreferences.
- [ ] Verify that rebalancing works and add a test for that: https://github.com/kubernetes/kubernetes/issues/33312
- [ ] Document how rebalancing works: https://github.com/kubernetes/kubernetes.github.io/issues/1362

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-federation-misc @mwielgus 
Feel free to add anything that I missed

**Comment by perotinus** [comment]
I've made some progress on diagnosing the RS kubectl tests (item 2 above) with @madhusudancs's help.

The tests were hanging in deletion and timing out. It appears that this is due to an interaction between the code used in kubectl to check whether the ReplicaSet has been properly scaled down (https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/conditions.go#L60) and the way that the Federation controller plane handles its replica set objects. The FCP does not properly set the Status metadata on the ReplicaSet, which causes the check for whether the RS has been scaled down to fail in a loop, since the observedGeneration of the object is always 0.

This does not usually happen in regular usage because (we believe but have not verified) during reconciliation, the Federated ReplicaSet acquires an observedGeneration from the watched replica set(s) in the cluster(s). The issue can be reproduced (inconsistently: it's racy) against a regular Federated cluster by quickly creating and then deleting a replicaset, before the reconciliation happens. The kubectl tests do not add a cluster to the federation, which means that the status is never properly updated.

There are still more issues to debug, but this will require fixing the federated replicaset controller to be smarter about handling the Status data.

**Comment by nikhiljindal** [comment]
aah thanks for great explanation @perotinus 
I can reproduce the same problem even when I have clusters registered by creating a replicaset with 0 replicas. In this case also, federation does not create any replicas in underlying clusters and hence does not update the status.

**Comment by perotinus** [comment]
Another work item: re-enabling the test disabled in #43654

**Comment by perotinus** [comment]
Another work item: determining how to handle status reporting. We cannot necessarily simply dump the status back into a Kubernetes object: a developer may well want to know how the replicas were distributed among clusters.

**Comment by StevenYCChou** [comment]
interesting in the subjects but also at the same time I felt like @perotinus is the dedicated person working on it. Is it possible to contribute as a supporter around the topic of 1) status reporting and 2) replicas distribution report?

**Comment by nikhiljindal** [comment]
>  a developer may well want to know how the replicas were distributed among clusters

Yes its good to provide this information but am not convinced that it needs to be part of ReplicasetStatus. 
https://github.com/kubernetes/kubernetes/issues/33622 will also enable that.

The kubernetes analogy is ReplicasetStatus does not tell which replicas are running on which node. Users can certainly get that information but not via ReplicasetStatus.

**Comment by perotinus** [comment]
I'm not sure the analogy between clusters and nodes holds here: I think a federation user is more likely to care about scheduling into  clusters than a Kubernetes user is to care about scheduling onto nodes. I guess this is a specific instance of the more general question of "Does a user know/care that a federation is a federation?" We could consider having simple status responses for users who do not know or care that they're interacting with a federation, and more advanced statuses for users who do.

Does #33622 provide enough information for a user to be able to tell that a federated replicaset maps to the replicaset they provided? If there are several replicasets in a cluster, will it be easy to filter for the appropriate ones?

**Comment by madhusudancs** [comment]
In the case of cluster replicasets users don't provide node preferences and thus don't control the distribution of replicas across nodes (node/pod affinity/anti-affinity aside). In the case of federation they do. I think that's a  stronger reason to report cluster-level distribution in a federated replicasets status.

**Comment by quinton-hoole** [comment]
@perotinus I agree.  We should stick to the status fields exposed by the Kubernetes API (which do not include the underlying cluster ReplicaSets, or Pods, or Nodes).

Right now the common thread between the cluster replicasets and the federated replicaset is the namespace+name.  This was mainly to aid human cognition, as opposed to being a good API design. 
 @nikhiljindal we were also planning to add parentrefs? (from the cluster replicasets to the federated replicaset?)  I think we should probably also add labels to correlate them all together (i.e. all cluster replicasets associated with a federated replicaset should share a common label or annotation, which should be derivable from the federated replicaset(s).  e.g. the UID of the federated replicaset.

**Comment by marun** [comment]
@quinton-hoole How would you suggest that 'parentrefs' be implemented?  Is there an existing meta field that could be used, or would it be a field addition?

I was thinking that meta.OwnerReferences could be used, but realized that it is intended as a mechanism to prevent garbage collection before processing by the owner (a resource wouldn't be collected if any OwnerReferences was not empty).  That would complicate manual deletion of a federated resource in a member cluster.

**Comment by quinton-hoole** [comment]
@marun Yes, meta.OwnerReferences was my idea (although I'm not expert on those, I must stress).

I don't think it makes any sense to be able to easily delete federated resources on member clusters (as replacements would simply be created by the federation controller).

How would this be any different from meta.OwnerRefs in Kubernetes?  For example would it not be analogous to manually deleting a Pod that had been created by a (non-federated) ReplicaSet?

Perhaps I'm missing something here...

**Comment by marun** [comment]
@quinton-hoole I was thinking of the case of a cluster leaving the federation but wanting to retain the resources created by the federation control plane.  In such a case I would imagine that the resources should revert to acting like any cluster-created resource vs a federation-created resource.

You're right, though, that it wouldn't be any different from a replicaset-managed pod.  I think it should be enough to document the use of OwnerRefs so that manual remediation would be possible.

**Comment by quinton-hoole** [comment]
@marun Yes, I think that it would be perfectly reasonable to support orderly "seccession" from a Federation, along the lines that you suggest.  For example, when deregistering a cluster from a federation (as one way of expressing "I no longer want this cluster to be part of this federation"), one might methodically remove all of the parent refs to objects in that federation.

**Comment by quinton-hoole** [comment]
Oops, sorry, closed by mistake (and re-opened).

**Comment by perotinus** [comment]
/unassign perotinus

I'm not working on deployments/replica sets at the moment.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#97.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
