### ISSUE TITLE
Federated Deployments: known issues

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39987]
Documenting the list of known issues with federated deployments:

- [ ] Enable federation-apiserver kubectl tests for deployments: https://github.com/kubernetes/kubernetes/issues/39985.
- [ ] Figure out a path to GA for FederatedReplicaSetPreferences.
- [ ] Verify that rebalancing works and add a test for that: https://github.com/kubernetes/kubernetes/issues/33312
- [ ] Document how rebalancing works: https://github.com/kubernetes/kubernetes.github.io/issues/1362
- [ ] Handle rollbacks: https://github.com/kubernetes/kubernetes/issues/37570
- [ ] Update to use apps group version: https://github.com/kubernetes/kubernetes/issues/52123

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-federation-misc @mwielgus
Feel free to add anything that I missed

**Comment by uiansol** [comment]
@nikhiljindal Are this issues still opened? Is someone working in this tasks?

**Comment by nikhiljindal** [comment]
@uiansol Yes all the issues are still open. There are owners for some. 
I dont think anyone is working on #33312 or #33312 but please post on the individual issue if you want to work on any.

**Comment by nikhiljindal** [comment]
cc @perotinus

**Comment by quinton-hoole** [comment]
@nikhiljindal You pasted the same issue number twice above.  Did you mean #33312 and #37570?

**Comment by nikhiljindal** [comment]
@perotinus said he will take up https://github.com/kubernetes/kubernetes/issues/37570

**Comment by perotinus** [comment]
I'm not working on this ATM, so someone else should feel free to take it on.

**Comment by nikhiljindal** [comment]
Added moving to apps group version https://github.com/kubernetes/kubernetes/issues/52123 to the list.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#98.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
