### ISSUE TITLE
federation ingress: known issues

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39989]
Documenting the list of known issues with federated ingress:

Issues that need to be fixed soon:
- [x] Need to create a firewall rule. Users will have to create it manually pre 1.5. Document it. Create it in the test for now and get the tests to turn green (https://github.com/kubernetes/kubernetes/pull/37571). In 1.6, create it automatically in the controller (https://github.com/kubernetes/kubernetes/issues/37306).
- [ ] Verify (add a test) and document that users need to create a static IP themselves (by running `gcloud compute addresses create kubernetes-ingress --global`) for HTTP load balancer.
- [ ] GCP Ingress does not work for clusters in the same zone (https://github.com/kubernetes/kubernetes/issues/47565)
- [ ] Resource leak due to race condition with service controller (https://github.com/kubernetes/kubernetes/issues/52315)

Longer term:
- [ ] Support federated ingress outside GCP. https://github.com/kubernetes/kubernetes/issues/51806

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-federation-misc @madhusudancs @allannaim
Feel free to add anything that I might have missed.

**Comment by clenimar** [comment]
it seems that the two short-term issues have already been fixed.

**Comment by uiansol** [comment]
@nikhiljindal Who is working on Support federated ingress outside GCP? Is there a proposal for this?

**Comment by quinton-hoole** [comment]
@uiansol I'm not aware of anyone currently actively working on it, but Amazon, CoreOS and Ticketmaster have recently done some integration work between Kubernetes Ingress and AWS ALB, that lays some good groundwork to federate on top of this.

https://coreos.com/blog/alb-ingress-controller-intro

I would be happy to write up a design if anyone can offer some developers to implement it.  I don't think that it would require much work to implement federated ingress across multiple AWS-only clusters.  Multi-cloud/hybrid federated ingress is a bit harder, but also doable if anyone is interested enough to implement it.

**Comment by uiansol** [comment]
@quinton-hoole Good to know, we have a "gang of 4" to work. =)
If you write up the design we will be glad to work on that. We have been PM docs and trying to help in some bugs.

**Comment by quinton-hoole** [comment]
@uiansol Great.  I will try to get a design out in the next two weeks.  I have a draft already.

**Comment by gurvindersingh** [comment]
@quinton-hoole wondering if you have any update on the design of having ingress working outside GCP e.g. in baremetal or other cloud providers.

**Comment by henriquetruta** [comment]
hi @quinton-hoole are you still working on this?

**Comment by quinton-hoole** [comment]
@henriquetruta @gurvindersingh Unfortunately I no longer have access to the doc, which I wrote while at Google, and handed over when I left.  I have asked @nikhiljindal To try to track it down, but unfortunately is has not yet been tracked down.  Any updates @nikhiljindal ?

**Comment by gurvindersingh** [comment]
@quinton-hoole thanks for the info and good luck with the new role. I look forward to reading docs one found.

**Comment by mattbates** [comment]
@nikhiljindal @quinton-hoole We'd also be keen to read the design doc (if it can be found) and also perhaps help contribute here too. We're seeing increasing interest in cross-region/cloud federation.

**Comment by quinton-hoole** [comment]
I've moved the discussion to a separate dedicated issue:

https://github.com/kubernetes/kubernetes/issues/51806

**Comment by quinton-hoole** [comment]
Required for federation GA.  Prioritized accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#99.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
