### ISSUE TITLE
Split the federation e2e tests into two separate jobs to make parallel testing possible in at least one of the jobs

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#40765]
Federation e2e tests run in a single e2e job right now. Some of the tests in that job is not parallelizable because they either clobber resources used by other jobs or they need clusters to be registered and/or deregistered on-the-fly. This makes the entire suite slow.

We should split the federation test into two jobs. One job should have all the tests that can be run in parallel. And another job with tests that must be run serially. 

The way we are going to approach this, is by:
- [x] [#40766] Going through all the tests and adding `[Serial]` label to the ones that must be run serially. Anything not labelled with `[Serial]` will be run in the parallel suite.
- [x] [#40767] Creating a new test job to run serial tests.
- [x] [#40768] Moving the cluster registration/deregistration steps from the parallel tests' `BeforeEach/AfterEach` blocks to federation-up.sh

Note: this is an umbrella issue. Individual work items will be tracked in their own issues.

cc @kubernetes/sig-federation-bugs @shashidharatd

**Comment by madhusudancs** [comment]
All the sub-issues listed here are now implemented/fixed.
