### ISSUE TITLE
Federation service controller refactoring

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#41253]
Creating this issue here to manage the multiple pieces involved while doing #40296. I would be breaking that PR into smaller and easily acceptable ones.
### Background:
We have been getting some issues related to federated services because some corner cases are not handled in the controller. Current federated service controller also predates the federated informer framework which handles lot of scenarios compared to earlier ones. So one major improvement would be to use the federated informer for federated service controller.
### Following is the breakup of the tasks
- [x] Write e2e testcases to enhance function coverage which are not handled by current service controller. #27623, #35827 - PR #41254
- [x] Use federated informer. - PR #41258
- [x] Store lb ingress information in Service annotations instead of service cache. Storing lb ingress information in service annotation is better maintainable and does not get lost across service controller restarts. Also this information can be utilized in the future to develop independent controllers to manage service discovery in federation. - PR #41258
- [ ] Handle removing DNS records for federated services, when cluster is unregistered. This would fix leaking DNS records. #29335, #36657
- [x] Segragate DNS related code from service controller to another controller (service-dns controller) to manage DNS records of federated service. - PR #45034
- [x] Enhance the unit tests for both service controller and the new service-dns controller. - PR #41258

cc @kubernetes/sig-federation-bugs @kubernetes/sig-federation-pr-reviews @quinton-hoole @nikhiljindal 
Also request to comment on any suggestion to better handle these task.

**Comment by quinton-hoole** [comment]
@shashidharatd It seems that we can close this issue, as the one remaining item is tracked in #29335, #36657 ?  Re-open if necessary.
