### ISSUE TITLE
NodeController should add NoSchedule taints and we should get rid of getNodeConditionPredicate()

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#42001]
getNodeConditionPredicate() in plugin/pkg/scheduler/factory/factory.go makes our code hard to understand because it hides the node-condition-based filtering in the node lister, which is totally non-obvious.

We should get rid of this function and have NodeController add NoSchedule taints for these situations instead. (Alas, we might not actually be able to get rid of getNodeConditionPredicate() completely until we get rid of the Unschedulable field of PodSpec, but at least we can get rid of all the other code in this function.) If there are pods that should still be able to schedule in any of these situations (e.g. DaemonSet pods?) we should add tolerations in admission control for them (e.g. see pkg/controller/daemon/daemoncontroller.go).

cc/ @kubernetes/sig-scheduling-misc  @kubernetes/sig-cluster-lifecycle-misc 
cc/ @gmarek @kevin-wangzefeng 

**Sub-tasks according to the design doc:**

- [x] Add node taints label and feature flag (#49547)
- [x] In the node controller, taint Nodes according to the Node Condition (#49257)
- [x] In DaemonSet, update DaemonSetController to Tolerant new Taints (#50186)
- [x] In admissionController, add MemoryPressure/DiskPressure toleration for no BestEffort pod (#50180)
- [x] In scheduler, disable the current behaviour of filtering out Nodes. Instead, pods will not be scheduled to tainted nodes if a toleration does not exist in its PodSpec (#50185)
- [x] Add e2e test for this feature (https://github.com/kubernetes/kubernetes/pull/52723)
- [x] Update doc for this feature (https://github.com/kubernetes/kubernetes.github.io/pull/5352)

**Comment by resouer** [comment]
> until we get rid of the Unschedulable field of PodSpec

I think you are referring  Unschedulable field of NodeSpec?

**Comment by resouer** [comment]
Self assigned, I would like to give this a shot.

**Comment by davidopp** [comment]
> I think you are referring Unschedulable field of NodeSpec?

Yes sorry, that was a typo.

**Comment by gmarek** [comment]
@resouer - please CC me to all PRs

**Comment by bgrant0607** [comment]
See also #29178

**Comment by davidopp** [comment]
Note that memory and disk pressure are checked in separate predicates, not in the NodeConditionPredicate. These should be represented as NoSchedule taints too.

https://github.com/kubernetes/kubernetes/blob/e7dfdd5d57b48859811dd4848af5e08b455215b2/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1239

**Comment by davidopp** [comment]
Setting NoSchedule taints corresponding to the node conditions that today cause pods not to schedule onto a node, should also allow us to use tolerations rather than special-case code in the DaemonSet controller (and thereby make it easier to have DaemonSet pods be scheduled by the default scheduler.)

**Comment by davidopp** [comment]
ref/ #42002

**Comment by k82cn** [comment]
Sub-tasks according to the design doc, I'll create PR for them accordingly:

- [ ] In the node controller, taint Nodes according to the Node Condition
- [ ] In DaemonSet, update DaemonSetController to Tolerant new Taints
- [ ] In admissionController, set default toleration seconds with new Taints
- [ ] In scheduler, disable the current behaviour of filtering out Nodes. Instead, pods will not be scheduled to tainted nodes if a toleration does not exist in its PodSpec

**Comment by wanghaoran1988** [comment]
// @mdshuai

**Comment by yastij** [comment]
Currently we already have toleration on dsc for taint related to node problems (e.g NodeNotReady and NodeUnreachable).
But to me ds should respect the new taints (outOfDisk, NodeMemoryPressure etc..), any insights @k82cn @davidopp ?

**Comment by k82cn** [comment]
> But to me ds should respect the new taints (outOfDisk, NodeMemoryPressure etc..), any insights

Yes, it's one of sub-task of this project.
This issue is closed by 'partially fixes' :(, I had updated PRs to 'part of #'.

**Comment by yastij** [comment]
@k82cn - I can handle the dsc tolerations

**Comment by k82cn** [comment]
@yastij , sure, thanks very much :).

**Comment by yastij** [comment]
@k82cn - just saw that you moved node conditions into predicate func, once adding node taiting and the according tolerations to dsc, do we'll still need to have node conditions checking ?

**Comment by gmarek** [comment]
We won't, but it'll take time for us to get there. We'll roll out Tainting as alpha (obviously), later move it to beta and GA in 1.10 at the earliest. We can't remove Condition checking logic before that.

dsc is a daemon set right? New taints are NoSchedule only, so running Pods won't be affected (at least on the control plane level). Kubelet can still decide to evict them based on problem it observes.

**Comment by yastij** [comment]
@gmarek - seems logic for the timeline.

But from @k82cn's sub-tasks

> In DaemonSet, update DaemonSetController to Tolerant new Taints

Since new Taints are NoSchedule Only that's fine, ds shouldn't have toleration for these. Daemon set should respect the new taints when applied and not schedule on these nodes. Or I'm I missing something ?

**Comment by k82cn** [comment]
The task for DS in my mind:
  1. For all DS pods, it should tolerant MemoryPressure & DiskPressure
  1. For critical DS pods, it should tolerant OutOfDisk

And if the taint by condition feature is enabled, we should check OutOfDisk by taints instead of predicates; the refactor is trying to make this simpler :).

**Comment by yastij** [comment]
@k82cn - You're right, I'll send a PR after yours get merged :)

**Comment by jamiehannaford** [comment]
@k82cn Do we have a to do list so folks can help out with https://github.com/kubernetes/community/pull/819? I'd like to help when I get some time.

@gmarek I have a question about timeline. If alpha makes it into v1.8, will I be able to schedule to NotReady nodes (no CNI) if I reference the alpha tolerations? Or do you mean it won't be functional at all until v1.10?

**Comment by gmarek** [comment]
It means you'll need to flip feature gate flag for it to work.

**Comment by k82cn** [comment]
@jamiehannaford , here is the task list: https://github.com/kubernetes/kubernetes/issues/42001#issuecomment-315987635

I'm working on related PRs for them; please ping me when you got time :).

**Comment by derekwaynecarr** [comment]
@k82cn - i anticipate we will also add a CPUPressure condition which will also mean that no BestEffort pod can be scheduled to that node if the kubelet is running with a static cpu assignment policy.

/cc @sjenning

**Comment by gmarek** [comment]
I think it's done (as alpha). @davidopp - do we want to keep this issue open?

**Comment by bsalamat** [comment]
We can close this.
