### ISSUE TITLE
stop serving extensions/v1beta1 and networking.k8s.io/v1beta1 in 1.22

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#43214]
Timeline for already-deprecated extensions types (DaemonSet, Deployment, ReplicaSet, StatefulSet, NetworkPolicy, PodSecurityPolicy):
- 1.14:
  - [x] switch pruning to apps/v1 - https://github.com/kubernetes/kubernetes/pull/72352
  - [x] Update add-on manifests to use new API groups - #72203
  - [x] Update controllers, tests, templates to use new API groups. - https://github.com/kubernetes/kubernetes/pull/70370
  - [x] update addon-manager to prune workload apis in the apps/v1 API group - https://github.com/kubernetes/kubernetes/pull/72940, https://github.com/kubernetes/kubernetes/pull/72978
  - [x] update cluster-proportional-autoscaler to scale via apps/v1 - https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/pull/54
  - [x] update kops to stop using extensions/v1beta1 resources during cluster bringup - https://github.com/kubernetes/kops/issues/6273
  - [x] ensure CI jobs are green when run without serving deprecated types in extensions/v1beta1, apps/v1beta1, apps/v1beta2 - https://github.com/kubernetes/kubernetes/pull/70672 (not intended to merge until 1.16)
  - [x] ack timeline with relevant sigs
    - [x] sig-apps (DaemonSet, Deployment, ReplicaSet, StatefulSet), 2019-03-04 meeting
    - [x] sig-auth (PodSecurityPolicy), 2019-03-06 meeting
    - [x] sig-network (NetworkPolicy), 2019-03-07 meeting
  - [x] announce plans/timeline in community meeting, 2019-03-07 meeting
  - [x] in 1.14 release notes, announce intent to stop serving deprecated types under extensions/v1beta1, apps/v1beta1, apps/v1beta2 by default in v1.16 ([draft](https://docs.google.com/document/d/1PAbK3D6-GorRf_Fi1U_q-Vvt9wM4MMh-qQfiq-dtOTE/edit#bookmark=id.gmpiivhcs9z9))
  - [x] announce plans/timeline in kubernetes-dev (https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc)
- 1.15:
  - [x] keep https://github.com/kubernetes/kubernetes/pull/70672 green
  - [x] re-announce intent to stop serving deprecated types in those three API groups by default
    - https://groups.google.com/d/msg/kubernetes-dev/je0rjyfTVyc/Jfjs4yn8AgAJ
- 1.16:
  - [x] merge https://github.com/kubernetes/kubernetes/pull/70672
  - [x] announce the deprecated types are no longer served by default, describe how to re-enable serving them if required, announce ability to re-enable will be removed in v1.18
- 1.18:
  - [x] remove ability to re-enable serving the deprecated types/API groups - #85903

[Plan for ingress](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md):
- 1.14:
  - [x] replicate Ingress API to networking.k8s.io/v1beta1 - https://github.com/kubernetes/kubernetes/pull/74057
  - [x] announce extensions/v1beta1 Ingress deprecated ([draft](https://docs.google.com/document/d/1PAbK3D6-GorRf_Fi1U_q-Vvt9wM4MMh-qQfiq-dtOTE/edit#bookmark=id.gmpiivhcs9z9))
- 1.15
  - [x] plan v1 improvements
- 1.18
  - [x] execute v1beta1 improvements
    - [x] IngressClass - https://github.com/kubernetes/kubernetes/pull/88509
    - [x] pathType and validation - https://github.com/kubernetes/kubernetes/pull/88587
    - [x] resource backend
- 1.19
  - [x] promote to networking.k8s.io/v1
  - [x] announce networking.k8s.io/v1beta1 Ingress deprecated, to no longer be served in 1.22
- 1.21
  - [x] update all examples and usages to networking.k8s.io/v1
  - [x] update in-org deployments (kube-up, kubeadm, kops, etc) to use networking.k8s.io/v1
- 1.22
  - [x] stop serving extensions/v1beta1 and networking.k8s.io/v1beta1 Ingress 
  - [x] disable serving the extensions/v1beta1 API group

Complete:
- [x] switch kubectl away from using extensions/v1beta1 Deployment rollback function - https://github.com/kubernetes/kubernetes/pull/70039
- [x] Move ReplicaSet, Deployment, Daemonset internal types to apps package - https://github.com/kubernetes/kubernetes/pull/70028
- [x] ~~CustomMetricTarget should migrate to autoscaling (@kubernetes/sig-scalability-feature-requests @mwielgus)~~ appears unused
- [x] ThirdPartyResource should migrate to apiextensions (@kubernetes/sig-api-machinery-misc @deads2k) https://github.com/kubernetes/features/issues/95
- [x] Deployment should migrate to apps (@kubernetes/sig-apps-feature-requests @soltysh) - done in #39683 
- [x] DaemonSet should migrate to apps (@kubernetes/sig-apps-feature-requests @janetkuo)
- [x] ReplicaSet should migrate to apps (@kubernetes/sig-apps-feature-requests)
- [x] PodSecurityPolicy should migrate to policy (@kubernetes/sig-auth-feature-requests @pweil-)
- [x] NetworkPolicy should migrate to network (@kubernetes/sig-network-feature-requests)

**Comment by pweil-** [comment]
@php-coder

**Comment by deads2k** [comment]
> ThirdPartyResource should migrate to ???

`.apiextensions.k8s.io`?  That would give us `ThirdParty.apiextensions.k8s.io`

**Comment by deads2k** [comment]
> PodSecurityPolicy should migrate to ?policy?

How about a peer to rbac under "xxx.authorization.k8s.io" since we're likely to add pre-evaluation endpoints?

**Comment by soltysh** [comment]
@deads2k that sgtm, I didn't have clear answers, so that was just my best guess.

**Comment by timothysc** [comment]
@soltysh There needs to be a long-tailed migration period for this that is not outlined here.  The logistics on deprecating...

**Comment by soltysh** [comment]
@timothysc agreed, I just wanted this out to have a starting point. It'll take much longer to actually get rid of these types. I'm assuming for each of these resources the steps being as follows (those were the steps when I was getting rid of extensions.Jobs):

1. introduce resource X in new api group (just the versioned part) (that has to last at least one release)
2. move the internals to the new api groups (again one release) and deprecate extensions resource
3. actually get rid of the extensions resource

So each will take about 3 releases, the migration will happen during steps 1 and 2, when the resources will be cohabitating. But since there are so many resources and this is cross-sig effort we need this issue out there so that everyone are aware, can comment, and most importantly plan accordingly for the next releases.

**Comment by timothysc** [comment]
@soltysh just a thought here, but this might be a good use case for a github-project b/c it is going to straddle release.

**Comment by thockin** [comment]
Ingress and NetworkPolicy -> network

On Thu, Mar 16, 2017 at 8:24 AM, Timothy St. Clair <notifications@github.com

**Comment by erictune** [comment]
How many releases of overlap do we need between "new group available" and "extensions group is deleted"?  One is an absolute minimum, but 2 seems more civilized.

**Comment by thockin** [comment]
Deprecation policy calls for 1 release for beta, but given the scope of
impact for things like Deployments, I'd agree that 2 is more polite.

**Comment by bgrant0607** [comment]
https://kubernetes.io/docs/deprecation-policy/

**Comment by smarterclayton** [comment]
I'd be ok with 2 - the cost of preserving is not terribly high as long as
we can clearly identify how to transition.  It'll also give us more time to
sort out the implications of a move.

**Comment by bgrant0607** [comment]
We should document that extensions is going away in the code.

I just posted the following to kubernetes-dev and kubernetes-dev-announce

The extensions API "group" was originally created as "experimental" before the full API group mechanism was designed and implemented. It was hastily renamed early on, once the desired distinction between the group and version was clarified. It doesn't support multiple API versions. Though the version is nominally v1beta1, it actually contains some alpha-quality resources as well as beta ones. It also contains a hodgepodge of resources that had nowhere else to go because we couldn't create new groups yet, or at least not sufficiently easily, and didn't have a model for API group evolution. No APIs in that group will ever advance in version within that group. They all need to find new homes in other, more appropriate groups. Please do not add any new APIs to that group.

**Comment by sttts** [comment]
/lifecycle frozen

@soltysh title needs an update. Happy new year! 🎉

**Comment by enisoc** [comment]
FTFY

**Comment by bgrant0607** [comment]
We need to figure out what to do with Ingress

**Comment by soltysh** [comment]
@janetkuo @enisoc @kow3ns I've noticed we still keep internal extensions versions for deployments, replicasets and daemonsets. The same applies for storage version, iow. we store them using the `extensions/v1beta1`. Both of these should move, internals to apps, and storage version to use `apps/v1` accordingly. Does any of you have that planned, I think it's reasonable to address it in 1.10 and start deprecating these resources under extensions as well.

**Comment by enisoc** [comment]
I found a tracker for moving the controller code: https://github.com/kubernetes/kubernetes/issues/55714

I'm not sure if we have one yet for moving the internal and storage versions.

All versions of Deployment, ReplicaSet, StatefulSet, and DaemonSet except apps/v1 are deprecated already as of 1.9. However, we have no concrete plans to remove any of the deprecated versions because there is still a moratorium on removing any API versions: https://github.com/kubernetes/kubernetes/issues/52185.

**Comment by liggitt** [comment]
> there is still a moratorium on removing any API versions: #52185.

I'd recommend we start disabling deprecated resources from being served by default. That leaves the server able to decode objects stored in extensions/v1beta1, and lets clusters that require the deprecated versions to re-enable them with `--runtime-config`, but will push the ecosystem to stop using the deprecated resources.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/58819 to disable serving extensions/v1beta1 network policy by default (deprecated since 1.7)

**Comment by soltysh** [comment]
@enisoc that's fine, but the moratorium is about supporting versions that will be supported in the future. So we need to ensure that stored versions for the aforementioned resources are supported. Iow. we need to move the storage to apps/v1 asap. That's a preliminary step for actual removal of an object. The deprecation should not have happen before that move, so we need to catch up. I'll try to create the necessary PRs next week fixing this. Thanks for information!

**Comment by liggitt** [comment]
> @enisoc that's fine, but the moratorium is about supporting versions that will be supported in the future.

not quite, it's about not removing any types needed to read persisted versions until migration is solved

> So we need to ensure that stored versions for the aforementioned resources are supported. Iow. we need to move the storage to apps/v1 asap.

Agree with this. Opened https://github.com/kubernetes/kubernetes/pull/58854 to do that

**Comment by hzxuzhonghu** [comment]
I can do the work move Ingress to apps.

**Comment by bgrant0607** [comment]
@hzxuzhonghu Please do not move Ingress at this time. And it doesn't belong in apps.

**Comment by hzxuzhonghu** [comment]
I misspell it should be network.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-network-api-reviews

**Comment by bgrant0607** [comment]
We're almost certainly going to make changes to the Ingress API. I don't know that we want to move it before we're ready to do so. That would cause more churn for users.

**Comment by hzxuzhonghu** [comment]
@bgrant0607 So, we have to delay Ingress.

**Comment by ahmetb** [comment]
PR #39683 migrating the Deployment to apps seems to be merged and then reverted. What's the latest status on Deployment?

**Comment by liggitt** [comment]
> PR #39683 migrating the Deployment to apps seems to be merged and then reverted. What's the latest status on Deployment?

deployments are GA in apps/v1 as of 1.9, all existing deployments are accessible via that endpoint, and new/updated deployments are persisted in etcd in that format as of 1.10

**Comment by mourya007** [comment]
@soltysh @liggitt I would like to contribute in this umbrella chain. Let me know If there is anything where I can help out.

**Comment by liggitt** [comment]
the PRs for the 1.14 timeframe are already completed. the next work that will need to be done is [executing on planned improvements to ingress in 1.15](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#115). sig-network would be the right contact for helping with that work

**Comment by mourya007** [comment]
> the PRs for the 1.14 timeframe are already completed. the next work that will need to be done is [executing on planned improvements to ingress in 1.15](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#115). sig-network would be the right contact for helping with that work

Ok, Thanks for the quick clarification.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release.  Please `/milestone clear` if I am incorrect

**Comment by spiffxp** [comment]
I note @liggitt says the PR work is basically done for v1.14? But I see a lot of checkboxes unchecked in the description.

**Comment by liggitt** [comment]
> I see a lot of checkboxes unchecked in the description.

remaining work is comms in sig meetings, community meeting, dev list, and release notes.

**Comment by spiffxp** [comment]
> in 1.14 release notes, announce intent to stop serving deprecated types under extensions/v1beta1, apps/v1beta1, apps/v1beta2 by default in v1.16

This is the only remaining thing I care about from a v1.14 perspective.  Has this landed yet? (FYI @dstrebel @onyiny-ang @jeefy for release notes)

**Comment by liggitt** [comment]
sent to kubernetes-dev in https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc

**Comment by athenabot** [comment]
@liggitt
If this issue has been triaged, please comment `/remove-triage unresolved`.

If you aren't able to handle this issue, consider unassigning yourself and/or adding the `help-wanted` label.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by soggiest** [comment]
Hello, it looks like most of the work for the 1.15 portion has been completed can we move this to 1.16?

**Comment by liggitt** [comment]
yes

/milestone v1.16

**Comment by makoscafee** [comment]
@liggitt Hello! I'm bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by liggitt** [comment]
there is still work in progress for this for 1.16. once that is completed (or deferred), I will move the milestone to 1.17

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by josiahbjorgaard** [comment]
https://github.com/kubernetes/kubernetes/issues/74375

**Comment by liggitt** [comment]
See the description for specific items being worked on in the 1.17 timeframe. When those are complete this will be moved

**Comment by liggitt** [comment]
only the Ingress API remains in the extensions/v1beta1 API group/version, narrowing focus of this to Ingress and adding the sig-network folks working on it

**Comment by cmluciano** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/85903 is merged, do we have any additional steps to be aware of for 1.18?

**Comment by liggitt** [comment]
the main thing for 1.18 is getting the v1 API completed and merged

**Comment by annajung** [comment]
Hello @liggitt  👋 I'm one of the Bug Triage shadows for the 1.18 release. Since this issue is tagged for 1.18, I'd like to check its status. Is this issue intended for milestone 1.18?

Friendly reminder: Code freeze is scheduled for March 5th.

**Comment by liggitt** [comment]
@cmluciano, @robscott, and @bowei have point on the ingress v1 work, I'll defer to them for status on getting that merged in 1.18

**Comment by cmluciano** [comment]
Yes this is intended for 1.18, the major tracking issue is https://github.com/kubernetes/enhancements/issues/1453

**Comment by robscott** [comment]
@liggitt I'm a little confused on what we should be doing for extensions/v1beta1 in 1.18. I'm thinking we should disable the version entirely in 1.18, but I'm not sure since the checklists above don't actually include that step here.

In the 1.14 checklist we have "announce extensions/v1beta1 Ingress deprecated, to no longer be served in 1.18", but we don't have a corresponding bullet point for 1.18. Is that as simple as removing [these lines](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L628-L630)? Since Ingress is the last resource that could be used with extensions/v1beta1, that seems like it would effectively disable `extensions/v1beta1`. The confusion I have is that in the 1.21 checklist there is currently a "disable serving the extensions/v1beta1 API group" item. I'm thinking this actually means "remove extensions/v1beta1 entirely from k/k" and that the disable step should happen earlier in 1.18, is that right?

**Comment by liggitt** [comment]
The timeline has slipped several times since the 1.14 days (originally v1 was planned for 1.14). To avoid making people migrate manifests and clients multiple times, we wanted to overlap keep extensions/v1beta1 available until all supported versions had v1.

**Comment by robscott** [comment]
So if Ingress v1 makes it into 1.18, extensions/v1beta1 can move to being disabled by default?

**Comment by liggitt** [comment]
in Ingress v1 makes it into 1.18, then 1.20 will be the first release in which all supported versions have v1 available (1.18, 1.19, 1.20). It will take significant time to migrate controllers and manifests to v1 across the ecosystem, so planning to disable v1beta1 in 1.21 seems realistic.

**Comment by annajung** [comment]
Hey @robscott @cmluciano checking in again as this issue is marked as `priority/important-soon`. Are you close to completing this for v1.18 release? Another reminder that code freeze is just around the corner! (March 5th).

**Comment by robscott** [comment]
Hey @annajung, we are continuing to make progress on this through this enhancement issue: https://github.com/kubernetes/enhancements/issues/1453. I don't think that progress needs to be tracked separately here though, so feel free to take this issue out the v1.18 milestone.

**Comment by annajung** [comment]
That sounds great, I will remove this from bug triage tracking sheet. Thank you!

/milestone clear

**Comment by liggitt** [comment]
@robscott, were the items for 1.20 completed? Anything remaining to do in 1.21 ahead of removal in 1.22?

**Comment by robscott** [comment]
@liggitt thanks for the reminder! It looks like we missed the items for 1.20 but @cmluciano will tackle them in the 1.21 cycle.

**Comment by robscott** [comment]
@liggitt I missed that we've said we're planning to remove not just extensions/v1beta1 in 1.22, but also networking.k8s.io/v1beta1. This would make it difficult for implementations of Ingress controllers that want to support both 1.18 and 1.22. Would it be reasonable to delay the removal of networking.k8s.io/v1beta1 until 1.23?

**Comment by liggitt** [comment]
> This would make it difficult for implementations of Ingress controllers that want to support both 1.18 and 1.22. Would it be reasonable to delay the removal of networking.k8s.io/v1beta1 until 1.23?

No. Per https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#118, EOL for 1.18 support is 2021-04-30, well before the release of 1.22. A component that wants to continue supporting pre-1.19 versions can:
1. fall back to networking.k8s.io/v1beta1 internally if networking.k8s.io/v1 is unavailable
2. maintain a branch/build that uses networking.k8s.io/v1beta1 for use by pre-1.19 clusters
3.

**Comment by howardjohn** [comment]
Just the perspective of a Ingress controller implementor - I understand the connection to support window here, but in reality we need to meet our users where they are and there is a huge amount of users on unsupported versions (because they get support from cloud providers). Without double checking I would go as far as to say they *majority* of users. Dropping support for all of these users is untenable.

> fall back to networking.k8s.io/v1beta1 internally if networking.k8s.io/v1 is unavailabl

My understanding is that the beta version would be removed in client-go in 1.22, right? So dual support would require using an old client-go

**Comment by liggitt** [comment]
> My understanding is that the beta version would be removed in client-go in 1.22, right? So dual support would require using an old client-go

client-go would still be capable of using the older APIs. Only the serving side is changing in 1.22.

**Comment by howardjohn** [comment]
> > My understanding is that the beta version would be removed in client-go in 1.22, right? So dual support would require using an old client-go
> 
> client-go would still be capable of using the older APIs if speaking to a server that was still serving them. Only the serving side is changing in 1.22.

Ah great,I thought it was removed there too. Supporting both versions should be much easier then. thanks

**Comment by howardjohn** [comment]
@liggitt given the conversion code (like Convert_v1beta1_IngressSpec_To_networking_IngressSpec) is private to kubernetes/kubernetes, it seems are only options are to re-invent (likely incorrectly) the conversion logic or import k/k (which we won't do). Or duplicate all of our code 2x to support both versions. Are there other options?

I am a bit confused how the community of ingress implementations is planning to actually do this.

**Comment by thockin** [comment]
We've never had (much less published) conversion logic for
version-to-version, only version to unversioned (which is NOT a
supported API and *does* have breaking changes) and vice-versa.  As a
client, you can handle multiple versions yourself - either duplicate
your code for both types or convert it to/from your own notion of
internal.

I'm curious how we can make this easier for clients without exposing
our internal API as supported.

**Comment by howardjohn** [comment]
We ended up just copy+pasting all of our Ingress logic

**Comment by bowei** [comment]
+1 to Tim's comment -- we have ended up rewriting the unversioned conversion code ourselves, albeit in a limited hacky manner.

**Comment by yannizhang2019** [comment]
As this issue is still open today, I wonder if the change to stop serving extensions/v1beta1 is going in 1.22? @soltysh

**Comment by liggitt** [comment]
yes, this is resolved in https://github.com/kubernetes/kubernetes/pull/99840

/close
