### ISSUE TITLE
Remove legacy docker integration (a.k.a dockertools/docker_manager.go)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#43234]
We should remove the old implementation and migrate the rest of the utility functions to `pkg/kubelet/dockershim`. 

- [x] Remove DockerManager (PR: #43884).
- [x] Remove --enable-cri and the relevant code (PR: #45194).
- [x] Refactor/move code in dockertools. (PRs: #45199...)

**Comment by yujuhong** [comment]
The dockertools package is gone, closing this issue.

Note that there are still docker references in various places in the repository, as well as tangled docker/kubelet initialization code. Those will be handled in other issues/PRs.

**Comment by yujuhong** [comment]
For the record, relevant PRs:
https://github.com/kubernetes/kubernetes/pull/45667
https://github.com/kubernetes/kubernetes/pull/48742
https://github.com/kubernetes/kubernetes/pull/45314
https://github.com/kubernetes/kubernetes/pull/45299
https://github.com/kubernetes/kubernetes/pull/45307
https://github.com/kubernetes/kubernetes/pull/45292
https://github.com/kubernetes/kubernetes/pull/45199
https://github.com/kubernetes/kubernetes/pull/45194
https://github.com/kubernetes/kubernetes/pull/44061
https://github.com/kubernetes/kubernetes/pull/43884
https://github.com/kubernetes/kubernetes/pull/43883
