### ISSUE TITLE
Support Azure Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by mogthesprog** [kubernetes/kubernetes#43287]
Tracking issue for tracking work on Virtual Machine Scale Set (VMSS) Support in Azure.

I've discussed a little bit with @colemickens and here are some the high level goals for this work:

(edit by @feiskyer and converting it to a list of TODOs)

* [x] Add vmType params to support both VMSS and standard VM type in Azure #55833
* [x] ~~Support concurrent creation of Service Resources~~
* [x] LB Rules + LB Probes +  LB Frontend IP + Public IP #57131
* [x] NSG Rule 
* [x] NIC placement in the LB backend.
* [x] Support "bring your own IP" #42034 
* [ ] PVs (depending on https://github.com/Azure/azure-sdk-for-go/issues/944) #59716

Have we got a tracking issue for the broader azure/v2 cloudprovider? (couldn't find one) We can rename this issue and use this as a tracking issue for the whole package, including the ManagedDisk Support which is apparently already underway (@colemickens knows the details). We can then create issues for tracking individual pieces of work? New here, so i'm not sure how this is usually done.

@brendandburns

**Comment by mogthesprog** [comment]
Early days, but here is the beginning of the work, still aquite a bit to do i think. 
https://github.com/kubernetes/kubernetes/compare/master...mogthesprog:morganj/azure-v2-provider

**Comment by andyzhangx** [comment]
I found managed data disk could  already be attached to vm scale set with managed os disks:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks, I would like to start the work for VMSS support from now.

**Comment by colemickens** [comment]
@andyzhangx ? That supports adding a disk to ALL nodes. There is still no way in Azure to attach a single specific disk to a single instance in a VMSS.

**Comment by feiskyer** [comment]
@colemickens Yep currently, hopefully it will be supported soon.

**Comment by gbowerman** [comment]
Re: attaching disks to specific instances in VMSS, see: https://github.com/Azure/vm-scale-sets/tree/master/preview/disk

**Comment by jdumars** [comment]
@khenidak FYI

**Comment by feiskyer** [comment]
Update: VMSS PV support is pending on https://github.com/Azure/azure-sdk-for-go/issues/944

**Comment by khenidak** [comment]
@feiskyer disk attach per VM (VMSS) is merged on the SDK :-)

@jdumars this a corner stone for v1.10 work -- support for VMSS

**Comment by djsly** [comment]
I will have free cycle next week to test the provider binary on a vanilla
k8s using VMSS @feiskyer <https://github.com/feiskyer>  ping me when you
have a binary for testing

**Comment by feiskyer** [comment]
@khenidak I'm working on the disk support. 

@djsly Thanks, will ping you when PR is ready

**Comment by feiskyer** [comment]
@djsly PR has sent out in #59716 and hyperkube image has been pushed to `feisky/hyperkube-amd64:v1.10.0-alpha.3-527-g52a7aef`. Please have a try and let me know if you have any problems.
