### ISSUE TITLE
v1.6 Release Blocking Issue/PR Umbrella Issue

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/kubernetes#43542]
### In flight

- [ ] [kube-up.sh should keep ABAC enabled by default](https://github.com/kubernetes/kubernetes/issues/43541)
- [x] [CNI consumers updated](https://github.com/kubernetes/kubernetes/issues/43488)

### Merged

- [x] [etcd downgrades](https://github.com/kubernetes/kubernetes/pull/43533)
- [x] [Taints](https://github.com/kubernetes/kubernetes/pull/43537)
- [x] [1.5 kubectl edit broken for Deployment](https://github.com/kubernetes/kubernetes/issues/42392)

### Determined to be non-blocking

- [x] [Pod security policy](https://github.com/kubernetes/kubernetes/issues/43538)

**Comment by Random-Liu** [comment]
Check the taints one, the PR is merged.

**Comment by liggitt** [comment]
is "Pod security policy" supposed to link to https://github.com/kubernetes/kubernetes/issues/43538?

**Comment by ethernetdan** [comment]
@liggitt fixed

**Comment by ethernetdan** [comment]
All complete.
