### ISSUE TITLE
Support for GPUs in Kubernetes

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#44107]
This issue is meant to track all issues and features around managing GPUs in kubernetes. This issue is meant to reflect priorities, timeline and owners too.
## v1.7
- [x] All GPUs get exposed to privileged containers #46007 [Owner: @cmluciano, Reviewer: @vishh ]
  - kubernetes/kubernetes.github.io#3870
- [x] Enable GPU node e2e tests - Requires starting VMs in GCE with GPUs [ Owner: @vishh  ] #45430
- [x] Enable Cluster e2e tests - Requires automated installation of Nvidia drivers on COS image [ @vishh] #45136

## Post v1.7 (1.8)
- [ ] Avoid depending of docker APIs for identifying GPUs in Use. Fixing this issue will make GPU integration work with all runtimes #43240 [Owner: @jiayingz, Reviewer: @vishh ]
- [ ] Add GPU metrics to cadvisor
- [ ] Run GPU e2e on PRs #47192

## Known Bugs
- [ ] Support for hot-plug of GPUs #44080 (Dropped because Nvidia drivers recommend rebooting nodes post installation)
- [x] gpusInUse info error when kubelet restarts #46087

**Comment by cmluciano** [comment]
I'd like to add [NVML support](https://github.com/kubernetes/community/pull/414) to this list 

I'm also working on some of the [TODOs in the NVIDIA pkg](https://github.com/kubernetes/kubernetes/issues/43240)

**Comment by vishh** [comment]
@cmluciano I'd prefer not tackling NVML until the overall integration for GPUs is finalized. Meanwhile, we can address all other open issues and improve testing, etc.

**Comment by cmluciano** [comment]
xref: 44552

**Comment by urzds** [comment]
I prepared a proposal for what we call the [Container Device Interface (CDI)](https://github.com/urzds/kubernetes/blob/proposal/container-device-interface/docs/proposals/container-device-interface.md): A generic way to allocate devices, including GPUs, to containers.

----

We use Kubernetes to schedule scientific 3D visualisation applications onto a cluster. Hence our containers use GPUs / DRM and other device nodes (e.g. TTYs).  Scheduling of Pods to Nodes with a capacity for such devices can be dealt with using [Opaque Integer Resources (OIR)](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#opaque-integer-resources-alpha-feature), where scripts external to Kubernetes handle device discovery and capacity reporting (see e.g. [kube-gpu-resources](https://github.com/urzds/kube-gpu-resources)).  The [Container Runtime Interface (CRI)](https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md) already supports [binding host device nodes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L586) to a container.  What is currently missing is a way for the Kubelet to generically allocate the available devices of a certain type to a container while it is being started.  The Container Device Interface (CDI) shall bridge this gap.

----

Please find the [full text of the proposal](https://github.com/urzds/kubernetes/blob/proposal/container-device-interface/docs/proposals/container-device-interface.md) in our copy of the Kubernetes proposal documents.  We would love to hear feedback from the community on this proposal.

**Comment by cmluciano** [comment]
All 1.7 tasks are complete @vishh . Since SIG-PM will be tracking the milestones closely for open issue in 1.7, do we want to move the remaining tasks to a new issue for 1.8?

**Comment by vishh** [comment]
Or change the milestone on this issue?

**Comment by cmluciano** [comment]
Moved to next candidate for now

**Comment by therc** [comment]
I have a change for kubectl to show GPU resources in the `describe nodes` output. Any chance it will get accepted? I'd rather not carry it in our fork, plus other users must be frustrated without it, but I also understand that this is an alpha resource.

**Comment by vishh** [comment]
@therc I'm planning on swapping the `alpha` resource with a non alpha one that will be forwards compatible. `kubectl` has a stricter deprecation policy. So can we hold off from merging your kubectl changes until I get around to defining a new alpha+ resource name?

**Comment by therc** [comment]
@vishh what's the timeframe for that change? 1.7? I can wait and even start to rework it when your first PR is out.

**Comment by vishh** [comment]
@therc BTW `kubectl describe` should already be displaying the `alpha` gpu resource.

**Comment by therc** [comment]
@vishh I should have been clearer: it adds the resource to the sections `Non-terminated Pods` and `Allocated resources` in the `describe node` output. Right now, it's only shown in the Capacity and Allocatable sections (as well as in the Requests/Limits sections in the `describe pods` output).

**Comment by vishh** [comment]
@therc Ahh. In that case I'd recommend waiting. I hope to define a beta API for Nvidia GPUs in v1.8.

**Comment by spiffxp** [comment]
/remove-priority P1
/priority important-soon
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)

**Comment by FrzMe** [comment]
The Documentation mentions that currently no GPU sharing is supported. We are strongly interested in having this as a feature. Is there an Issue tracking progress in implementing GPU sharing support?

**Comment by cmluciano** [comment]
I don't believe that this is a feature that we are targeting since I am not aware of wide-spread support of shared cards. cc @flx42 @renaudwastaken

**Comment by therc** [comment]
All Nvidia cards support sharing. Some (=recent ones) better than others. We have been sharing them for the past three years in our environment and for more than an year under Kubernetes, starting from G2 (Kepler-class) instances. There's an undocumented hack in pre-1.6 versions, but with recent ones you need ugly patching.
I brought it up in the past, but it's already difficult enough to find an agreement on more basic stuff like discovery. It is doable, but you'd need to bring a lot more state and GPU awareness into the Kubernetes scheduler (or use a separate one).

**Comment by therc** [comment]
I also mentioned this before, but I'll re-iterate: there is no enforced isolation between computation kernels on the GPU. You should share the hardware only if you know what you are doing and/or trust what you are running.

**Comment by flx42** [comment]
By default, kernels from different processes can't run on one GPU **simultaneously**, they are time sliced. The Pascal architecture brings instruction-level preemption instead of block-level preemption, but context switches are not free.
Also, there is no way of partitioning GPU resources (SMs, memory), or even assignin priorities when sharing a card.

I agree with @therc that there is higher priority work before considering GPU sharing.

**Comment by FrzMe** [comment]
For our usecase (multiple different Neural networks being evaluated in different containers) all the restrictions you stated would be fine. For us a very basic support in the form of stating how much GPU memory a Container needs (statically if needed) and scheduling to GPUs which still have enough "unclaimed" memory.
We don't need any form of enforcement of constraints or security on the GPUs themself.

Currently GPU sharing is possible with nvidia-docker and I would love to see basic support in Kubernetes (even manual management would be fine as a first step)

**Comment by tianshapjq** [comment]
@vishh I would like to give a try about adding gpu metrics to cAdvisor. I commited a pr [43934](https://github.com/kubernetes/kubernetes/pull/43934) in leveraging the nvidia-smi binary but it seems not a perfect choice depending of nvidia-smi. Do you think it's ok to leverage NVML instead of depending of nvidia-smi binary?

**Comment by flx42** [comment]
@tianshapjq the discussion is now here:
https://github.com/google/cadvisor/issues/1436

I listed multiple options, but we haven't decided on which approach to follow.

**Comment by tianshapjq** [comment]
@flx42 thx for your reference, I followed that issue as well. But I just wanna know if any news about this discussion?

**Comment by flx42** [comment]
Not that I'm aware of.

**Comment by shaklee3** [comment]
A couple comments related to future work:

1) Volta added more fine-grained sharing targeted at cloud companies. Perhaps the sharing should wait until that's adopted more.

2) Nvidia stated at their last conference nvidia-docker is being deprecated and they're making a newer version that doesn't rely on docker. Not sure if this changes anything.

**Comment by yongtang** [comment]
@flx42 @shaklee3 I am wondering if you have more information about Nvidia's plan about nvidia-docker not replying on docker for the new version?

> 2. Nvidia stated at their last conference nvidia-docker is being deprecated and they're making a newer version that doesn't rely on docker. Not sure if this changes anything.

That could be interesting. I am wondering if more I could know more details about it?

**Comment by vishh** [comment]
> Volta added more fine-grained sharing targeted at cloud companies. Perhaps the sharing should wait until that's adopted more.

We will need more details on the sharing semantics.

> Nvidia stated at their last conference nvidia-docker is being deprecated and they're making a newer version that doesn't rely on docker. Not sure if this changes anything.

Kubernetes doesn't really need nvidia docker since it has enough extensions to help surface nvidia GPUs to containers. We may have more than one way of handling Nvidia GPUs with Kubernetes though for a while, where libnvidia-container will be one of the solutions for a subset of users. The user facing APIs will remain the same though.

**Comment by shaklee3** [comment]
@yongtang The presentation can be viewed here:

http://on-demand.gputechconf.com/gtc/2017/video/s7177-jonathan-calmels-felix-abecassis-using-containers-for-gpu-accelerated-applications.mp4

Here is the link to the page of the new project:

https://github.com/NVIDIA/libnvidia-container

**Comment by yongtang** [comment]
@shaklee3  Thanks!

**Comment by vishh** [comment]
This issue is no longer tracking the current state. Closing this as obsolete

**Comment by bhack** [comment]
@vish Have we an update issue to follow?
