### ISSUE TITLE
Requirements for opaque integer resources to graduate from Alpha to Beta

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#44181]
Feature issue: [Opaque integer resources](https://github.com/kubernetes/features/issues/76)
[Sig-scheduling 2017 planning doc](https://docs.google.com/document/d/1f94-_aoyKSvS3XhkkLTDxleyfOrIz7RaTA243y_-gj8)

@kubernetes/sig-scheduling-misc 

--------

_Requirements:_

- [ ] Re-enable e2e tests for default CI runs (#42689)
- [ ] Subject OIRs to quota (TODO: issue)
- [ ] Ensure OIRs can be defaulted e.g. in admission control (TODO: issue)

--------

_Nice to have:_

- [ ] Kubectl describe node shows opaque integer resource request/limit for nonterminal pods (#44271)
- [ ] Kubectl patch node doesn't take effect (#44269)
- [x] Kubectl describe node should reflect OIR consumption in Allocatable field (#44270)

**Comment by ConnorDoyle** [comment]
@xiangpengzhao thanks for creating some usability issues for OIR -- tracking them here as proposed improvements to make before considering OIR for promotion from alpha to beta.

**Comment by ConnorDoyle** [comment]
xref #34508

**Comment by ConnorDoyle** [comment]
@davidopp / @timothysc - please add to 1.7 milestone

**Comment by spiffxp** [comment]
@kubernetes/sig-scheduling-misc do you want this in v1.7? is this the right sig to own this issue?

**Comment by ConnorDoyle** [comment]
Closing -- deprecated as of v1.8 in favor of Extended Resources. See https://github.com/kubernetes/features/blob/9c50a745086d92321685cdfcf3d0bbaf17e0ab2b/release-1.8/release_notes_draft.md#scheduling

**Comment by urzds** [comment]
Hi @ConnorDoyle! Are Extended Resources already documented? There is no link in the release notes draft, and a quick Google search did not turn up obvious matches.

**Comment by ConnorDoyle** [comment]
No, it still needs to be done. CC @vishh
