### ISSUE TITLE
[Federation] Support leader election for controller manager

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#44283]
This issue is to track all the tasks for adding leader election feature for federation controller manager.

Following are missing pieces in order to support the feature:
- [x] Refactor leader election package test code to remove redundancy - #44286
- [x] Refactor leader election package to use ObjectGetter Interface instead of clientset.interface - #44338 
- [x] Add support for federation-only namespaces - #46090
- [x] Add leader election to federation controller manager - #46090

cc @kubernetes/sig-federation-pr-reviews

**Comment by marun** [comment]
Is there a higher-level plan for federation HA that I've missed?  While supporting leader election for the control plane hosted in a single kube cluster is definitely important, has there been any discussion of how to approach loss - temporary or otherwise - of the hosting cluster?

**Comment by shashidharatd** [comment]
AFAIK there is no such high level plan for federation HA in the community. Although there was a task and few members from Huawei explored this feature. federation HA across regions is inherently difficult owing to associated latencies and etcd cluster does not have good support to deploy across regions. @kshafiee request to comment on this.
Also request @quinton-hoole to shed some light on this.

**Comment by kshafiee** [comment]
@shashidharatd @marun This is the design we previously shared with the community and used in production:
https://docs.google.com/document/d/18kB5W401WBhEjUOOXQnBb-nx3bFXK8pOCHbMbdXuBMg/edit?usp=sharing

**Comment by perotinus** [comment]
@kshafiee Thanks for the link! How much exposure did this proposal get? I see that it was mentioned in a SIG meeting a while back, but I didn't notice it coming up again or having been marked as reviewed and ready for implementation.

**Comment by shashidharatd** [comment]
@perotinus, The design shared by @kshafiee is for federation control plane HA and leader election feature is a basic building block to build POC for the design outlined in that document. There are still open issues in that design. leader election feature will just enable to try out different options and conclude the design.

I will open a separate issue for federation control plane HA, if one does not exist and we can discuss the design issues over there.

cc @kubernetes/sig-federation-misc

**Comment by nikhiljindal** [comment]
Ref https://github.com/kubernetes/features/issues/104

**Comment by shashidharatd** [comment]
Closing this as leader election for leader election for federation controller manager is implemented and merged.
