### ISSUE TITLE
kube-apiextensions-server needs more integration tests

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#45511]
There is an integration test framework for the `kube-apiextensions-server` which provides an easy-ish way to run the server standalone for testing scenarios.  See the example here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-apiextensions-server/test/integration/basic_test.go

This is a running list of tests that we need to have for good coverage.
 - [x] does the server come up
 - [x] does basic CRUD work (e.g. kubectl create, get, delete, label, annotate)
 - [x] does cross namespace list and watch work. @xiao-zhou
 - [x] Proper rejects for no-namespace creates. @nikhita  
 - [x] does de-registration and re-registration work @sdminonne 
 - [x] do multiple registrations work @sdminonne 
 - [x] does etcd storage function properly?  Correct serialization and key location @sdminonne 
 - [x] does discovery for kind, shortnames, etc come through correctly
 - [x] do colliding named resources work.  And when one is deleted does the gap close @nikhita
 - [x] do non-namespaced resources work correct @nikhita 
 - [x] [are self-links correct](https://github.com/kubernetes/kubernetes/issues/37622) @sdminonne 
 - [x] does finalization work.
-  [ ] do initializers work https://github.com/kubernetes/kubernetes/pull/47252 @sttts
 - [ ] e2e test that ensures that CRDs work in `kube-apiserver` https://github.com/kubernetes/kubernetes/pull/46865 @sttts 
 - [x] finalizers on CR instances should work @ash2k 

Tests to prevent regression of issues encountered previously with TPR
 - [x] does advanced CRUD work (e.g. kubectl edit, patch, apply, describe, explain, replace, watch) @nikhita 
 - [ ] does GC behave acceptably with CustomResources as owner or owned. @nikhita https://github.com/kubernetes/kubernetes/pull/46585, blocked on https://github.com/kubernetes/kubernetes/pull/46000
 - [x] [is integer data preserved](https://github.com/kubernetes/kubernetes/issues/30213) @nikhita
 - [ ] [does Helm work with CustomResources](https://github.com/kubernetes/helm/issues/1468)

@enisoc Add anything missing to the list and just ping me.
@sdminonne If you have cycles to jump in, let me know.

**Comment by deads2k** [comment]
@adohe you had asked about specific work items.  The first group of tests should be implementable now if you wanted to pick one out.  If you know how to wire up a `/finalize` endpoint (like namespaces), that's a place to look at too.

**Comment by sdminonne** [comment]
@deads2k Ok to help get in touch via slack or irc.

**Comment by xiao-zhou** [comment]
@deads2k you can put my name on "does cross namespace list and watch work. Proper rejects for no-namespace creates." For a start, I'll do a small PR.

**Comment by sttts** [comment]
@xiao-zhou done. I have split apart "rejects for no-namespace creates". @nikhita has a test ready if I have understood her correctly.

**Comment by nikhita** [comment]
@sttts thanks! yes, it is ready. will update the PR tomorrow and address comments.

**Comment by sdminonne** [comment]
submitted #45768 for de-registration but it fails (see #45878)

**Comment by enisoc** [comment]
@deads2k I added some new items, in a third section geared towards preventing regressions versus TPR.

**Comment by sdminonne** [comment]
xref: #46030

**Comment by nikhita** [comment]
All the tests are not done yet so I think this should be re-opened.

**Comment by deads2k** [comment]
@xiao-zhou could you take "do colliding named resources work. And when one is deleted does the gap close"?

You'll see this in conflicting short names.  You make two CRDs, both with the same shortname.  One of the two will get the name in status.  The other of the two will get a NameConflict condition.  When the one who has the name is updated to change its shortname, the nameconflict should be resolved for both.

**Comment by nikhita** [comment]
@deads2k I am currently working on it on this PR: https://github.com/kubernetes/kubernetes/pull/46200

**Comment by nikhita** [comment]
Also as an update, the test for checking if integer data is preserved is done in this PR: https://github.com/kubernetes/kubernetes/pull/46059

**Comment by deads2k** [comment]
there are three tests left and I think they can wait until 1.8.  GC doesn't work (missing GC bits), helm is an external project that proved difficult to vendor and test, and the kube-apiserver integration is at least somewhat covered in test-cmd.sh

**Comment by sttts** [comment]
For the kube-apiserver integration https://github.com/kubernetes/kubernetes/pull/46865 can be easily extended. It bootstraps a complete kube-apiserver with the normal bootstrapping code, without any mocking.

**Comment by nikhita** [comment]
All tests except the one for Helm are done. Does anything need to be done for Helm? If not, I believe we can close this now.

**Comment by sttts** [comment]
I think we can close this. Please reopen if you are missing any test coverage.
