### ISSUE TITLE
federation services: known issues

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#46240]
Documenting the list of known issues with federated services:

- [ ] Should configure CNAME records instead of A records on AWS: https://github.com/kubernetes/kubernetes/issues/35637
- [ ] Duplicate resource record errors with Route53: https://github.com/kubernetes/kubernetes/issues/42131
- [ ] Remove DNS entries when a cluster is removed from federation: https://github.com/kubernetes/kubernetes/issues/36657
- [ ] Fail to create DNS records for multizone clusters: https://github.com/kubernetes/kubernetes/issues/35997

cc @kubernetes/sig-federation-bugs @shashidharatd @madhusudancs

**Comment by madhusudancs** [comment]
> Should configure CNAME records instead of A records on AWS: #35637

Can we please characterize the first issue correctly? We already know that's not even the right solution. I would characterize it along the lines of "Ensure that resolved IP addresses don't go out of sync with the ELBs on AWS" or something like that? I think the linked issue also does a good job of explaining the issue.

**Comment by quinton-hoole** [comment]
Added priority.  Need to fix this before Federation GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#141.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
