### ISSUE TITLE
Additional tests and bug fixes for DaemonSet history

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#46981]
Follow up #45924: 

- [x] e2e test: **(PR #47387)**
  1. create DS
  1. update template - rollout proceeds only a little ways
  1. roll back by updating template to be the same as the original template. existing pods not yet updated in step 2 should not be restarted 
- [x] https://github.com/kubernetes/kubernetes/pull/45924#discussion_r119913915: wait for the history cache to be synced **(PR #47084)**
- [x] test DS history orphan and adoption **(PR #47084)**

Fine after 1.7:
- [x] https://github.com/kubernetes/kubernetes/pull/45924#discussion_r119845003: don't update label with UpdateStatus **(PR #47258)**
- [x] https://github.com/kubernetes/kubernetes/pull/45924#discussion_r119850091: construct the history once and then pass the references in manage and cleanupHistory **(PR #47258)**
- [ ] https://github.com/kubernetes/kubernetes/pull/45924#discussion_r119850689: clean up history after rollout is stable (it's fine for now)

@kubernetes/sig-apps-misc @erictune @kargakis @lukaszo

**Comment by janetkuo** [comment]
Done for 1.7.
