### ISSUE TITLE
Reposplit Umbrella Issue

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#47528]
Issues when split repos:

- [ ] kubernetes/newrepo split repo into kubernetes/kubernetes
  - [ ] Testing the code against kubernetes/kubernetes
  - [ ] Automatically updating the vendored version of kubernetes/newrepo in kubernetes/kubernetes when updated in newrepo
- [ ] Vendoring deps into kubernetes/newrepo shared with kubernetes/kubernetes
  - [ ] kubernetes/kubernets and kubernetes/newrepo must use the same version of deps they share
- [ ] Tracking issues for the release
  - [ ]  issues in kubernetes/newrepo need to be communicated to the release team and tracked
