### ISSUE TITLE
Task tracker for addition of pod priority and preemption to Kubernetes

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#47604]
Here is a list of items we need to add pod priority and preemption. These items are not the same size and some may need more work. We can break those down later into smaller tasks if needed.

- [x] Add a design doc to add priority to Kubernetes API.
- [x] Add pod priority
  - [x] Add priority fields to PodSpec.
  - [x] Add PriorityClass API object.
  - [x] Add an Admission Controller for priority.
- [x] Add a design doc for priority-based preemption.
- [x] Incorporate priority in pod scheduling logic (to fix the starvation problem)
- [x] Support PodDisruptionBudget in preemption.
- [x] Add priority-base preemption to scheduler.
- [x] Quota per priority
  - [x] Add priority fields to ResourceQuota.
  - [x] Incorporate priority in quota checks.
- [x] Add documentation on how to use pod priority and its effects on behavior of the system.

**Comment by bsalamat** [comment]
@kubernetes/sig-scheduling-feature-requests 
@kubernetes/sig-scheduling-misc

**Comment by ravisantoshgudimetla** [comment]
@bsalamat I see that you raised PR's for Add pod priority, https://github.com/kubernetes/kubernetes/pull/48377 - Can you please create individual issues against each task, so that it becomes clear. I want to work on some items and it will be helpful to have individual issues with clear description. Also, with these issues, they can be assigned to individuals. WDYT?

**Comment by davidopp** [comment]
I think this could be broken down into a few separate issues. Here's one possibility. Note that I'm just listing the things that haven't been started yet (IIUC the goal is for people to see what work they could take, so things that are already started probably aren't relevant?)
* implement priority/preemption in pod scheduling logic
* documentation for priority/preemption
* design for adding priority to ResourceQuota
* implement adding priority to ResourceQuota
* update ResourceQuota documentation to reflection priority

Does that look reasonable?

**Comment by bsalamat** [comment]
Thanks, @davidopp!
I created the issues to track remaining work items.

**Comment by ravisantoshgudimetla** [comment]
Thanks @davidopp and @bsalamat !!

**Comment by resouer** [comment]
@ravisantoshgudimetla have you begin design for adding priority to ResourceQuota? I think this is high priority in all remaining tasks.

**Comment by ravisantoshgudimetla** [comment]
@resouer I had change of priorities at my workplace because of which I will not be able to work on this issue this quarter. I had an offline discussion with @bsalamat on this. Please feel free to pick this up in case you are interested.

**Comment by resouer** [comment]
@ravisantoshgudimetla Thanks, I will pick up that part.

**Comment by resouer** [comment]
[Update] Just picked up `adding priority to ResourceQuota`

**Comment by dims** [comment]
@bsalamat @grodrigues3 @resouer - Do we still need this for 1.8? Can we please move it out if not? (we are already late for 1.8)

**Comment by bsalamat** [comment]
@dims All the items we had planned for 1.8 are already in. The rest should go to 1.9. So, yes, we can move it out now.

**Comment by bsalamat** [comment]
status/approved-for-milestone

**Comment by bsalamat** [comment]
kind/feature

**Comment by luxas** [comment]
@bsalamat @davidopp Can you confirm that this is on track for v1.9?

**Comment by bsalamat** [comment]
@luxas Given that code freeze is only one month away, we are not very confident at this point, but I still call it on track for 1.9.

**Comment by dims** [comment]
@bsalamat @luxas time to move this out to 1.10?

**Comment by bsalamat** [comment]
I think some of the items will be ready for 1.9. Particularly, a solution for starvation will probably be added in 1.9.

**Comment by bsalamat** [comment]
status/in-progress

**Comment by bsalamat** [comment]
This feature is built and moved to beta in Kubernetes 1.11.
