### ISSUE TITLE
CRI: support non-builtin container runtimes

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#47872]
The built-in cri-docker integration relies on some legacy support (e.g., the docker-cadvisor integration) that a new CRI integration does not have. Below is a list of issues we need to address to fully support a non-builtin, non-docker container runtime via CRI.

A (potentially incomplete) list of issues to unblock adopting a (non-docker) CRI integration.
- [ ] Refactor kubelet to consume container metrics from CRI: #46984
- [ ] Refactor kubelet to consume image filesystem stats from CRI: #33048
- [ ] Providing cgroups for kubelet/cadvisor to track resource usage of CRI shim and container runtime stats: #30702
- [ ] Authentication for the streaming server: #36666
- [ ] Improve log format to handle logs: #44976

/cc @Random-Liu @feiskyer @mrunalp

**Comment by jberkus** [comment]
@yujuhong this looks like a feature.  If it's targeted at 1.10, it needs kind/ and priority/ labels, and needs to be tracked in the Features repo.  Thanks.

**Comment by yujuhong** [comment]
https://github.com/kubernetes/features/issues/552

**Comment by jberkus** [comment]
Please update this tracking issue with which items you actually expect to get merged for 1.10.  Thanks!
@yujuhong

**Comment by jberkus** [comment]
reminder: this feature tracker will be removed from 1.10 at code freeze in 6 hours if it doesn't have status/approved-for-milestone and is driving towards completion in the next few days.  Thanks!
