### ISSUE TITLE
jsonpath umbrella issue

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#48025]
Currently our jsonpath initial realization is in this pr: https://github.com/kubernetes/kubernetes/pull/11738 we found lot of problem or bugs with this version of implementation below:

- [ ] https://github.com/kubernetes/client-go/issues/158 (JSONPath parser will not filter strings containing parentheses)
- [ ] https://github.com/kubernetes/kubernetes/issues/45546 (jsonpath: missing `left' in filter has confusing error message and fails unexpectedly) 
- [ ] https://github.com/kubernetes/kubernetes/pull/47421  (jsonpath: don't recurse into structs that are not actually nested)
- [ ]  https://github.com/kubernetes/kubernetes/issues/36391 (JSONpath not drilling down into an RS .spec.template.metadata.name)
- [ ] https://github.com/kubernetes/kubernetes/issues/20352 (JsonPath nested condition and multiple conditions are not working)
- [ ] https://github.com/kubernetes/kubernetes/issues/27090 (kubectl get -o jsonpath does not handle objects with RawExtension) this one maybe a more cli related issue.

I think our current implementation is somehow a little hard-coded, and we lack of a common syntax for our jsonpath rules, although there's some ref: https://kubernetes.io/docs/user-guide/jsonpath/ , http://goessner.net/articles/JsonPath/ here. I disscussed with @mtaufen before and if we can find a good third-party lib with more rigorous implementation that would be good, but for now I can't find one.

cc @smarterclayton @bgrant0607 @lavalamp @pwittrock @mtaufen  just wrote this umbrella issue maybe for future track
