### ISSUE TITLE
Umbrella: dynamic admission control to beta

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#49038]
A list of issues we need to address before declaring initializer and webhook admission controller as beta.

webhook admission controller:
- [x] move the admission API to k8s.io/api so that people can import the API to write webhook. (https://github.com/kubernetes/kubernetes/pull/48232)
- [x] GenericWebhook admission plugin is sending internal objects to webhooks (https://github.com/kubernetes/kubernetes/issues/49733)
- [x] Allow mutating webhook
  - [x] Add admission controller for Mutating, so recommended order of `--admission-control` is `MutatingWebhook, CompiledIn1, ... , CompiledInN, NonMutatingWebhook`
  - [x] apiregistration API: separate for MutatingWebhook and NonMutatingWebhook to distinguish mutating and not.
  - [x] Serialize mutating Webhooks into order in the apiregistration.  Leave non-mutating in parallel.
  - [x] update: we supported * ~~Beta will not support * match because we don't have any use case (gc and quota assume stay compliled in).  apiregistration: must specify exact GVK(s) webhook wants, so apiserver can convert.~~
  - [x] Conversion logic in apiserver, and figure out if anything needed for the 
  - [x] update: we only support json patch.~~ Require response has content-type, and content-type must be one of the 3 types of patches supported by Kubernetes.  This is to prevent losing new fields.~~
- [x] [WIP] plumb the proxy dialer: https://github.com/kubernetes/kubernetes/issues/49987

dynamic configuration:
- [x] evaluate if the synchronization mechanism (currently it's polling every 1s) is efficient enough. 
- [x] missing doc on default value: https://github.com/kubernetes/kubernetes/issues/49030
- [x] missing doc on breaking bootstrap loop: https://github.com/kubernetes/kubernetes/issues/49048
@lavalamp @smarterclayton @whitlockjc 

The following is the initializers, so it's deprecated.

Initializers (deprecated):

- [ ] Doc how to deploy a pod initializer as a deployment, and how to do the emergency fix. In this case, the order of deployment and creating initializerconfiguration is tricky.
- [ ] Enable initiailizer in the generic apiserver
- [ ] Add a Result field to each `metadata.intializers.pending[x]`, the current single `metadata.initializers.result` doesn't keep all failure messages if initializers work in parallel.
  * I don't want to support it. See https://github.com/kubernetes/kubernetes/issues/49038#issuecomment-325053156
  * can be de-prioritized if we don't plan to support partial ordering in 1.8.
- [x] [WIP] remove `initializerconfiguration.failurepolicy` and let initializer always fail close? Fix is https://github.com/kubernetes/kubernetes/pull/51300.
- [ ] shall apiserver return 504 or 202 if request timed out before initialization has finished
- [ ] interaction with quota: https://github.com/kubernetes/kubernetes/issues/51842, https://github.com/kubernetes/kubernetes/issues/51820
- [ ] under consideration: exempt some namespaces from initialization https://github.com/kubernetes/kubernetes/issues/51290
- [ ] [WIP] Let controllers see uninitialized controllees: https://github.com/kubernetes/kubernetes/issues/48893. Fix is https://github.com/kubernetes/kubernetes/pull/51247.
- [ ] Garbage collection of slow-to-initialize objects
- [x] [WIP] interaction with kubectl https://github.com/kubernetes/kubernetes/issues/49035. Fix is #50497. https://github.com/kubernetes/kubernetes/issues/49032
- [ ] [WIP] Allow mutating specs for all resources when uninitialized #50344
  - [x] mutating pod spec is handled specially in #51733
  - [ ] make validation during initialization generic, remove pod-specific validation changes added in #51733
- [x] [WIP] parallel patching of `metadata.initializers.pending`: https://github.com/kubernetes/kubernetes/issues/51131. Will be fixed by #51082
- [ ] API support for partial order among initializers #50714
  * I intend to de-prioritize this, because we expect <5 natively supported initializers per resource, which even in a heavily loaded cluster will cost <2s to resolve, and only 100ms to resolve in a lightly loaded cluster.
- [x] code example for initializers (@kelseyhightower is working on it)

**Comment by whitlockjc** [comment]
For the webhook, there is also an issue where the object sent over the wire is the internal representation of the object instead of the public representation.  This has an impact on serialization.  I'm not sure if this was reported yet but it came up during external testing.

**Comment by farcaller** [comment]
Is there an issue tracking the chicken-and-egg problem of controllers? E.g. if I have an admission controller that re-writes pods and it's started via a Deployment, what would happen if it fails and needs to be restarted? or if it's rolled out to a new version?

**Comment by caesarxuchao** [comment]
As an admin, you can set `metadata.initializers.pending={}` to skip initialization.

**Comment by smarterclayton** [comment]
validation: https://github.com/kubernetes/kubernetes/issues/47837

**Comment by smarterclayton** [comment]
I think we need mutating web hooks as well.

**Comment by smarterclayton** [comment]
Is there a bug covering that web hooks are sending internal?

**Comment by caesarxuchao** [comment]
Created https://github.com/kubernetes/kubernetes/issues/49733.

**Comment by caesarxuchao** [comment]
@smarterclayton @deads2k @lavalamp  is there more context on the mutating webhook? I can work on the design and implementation.

**Comment by deads2k** [comment]
webhook admission should be able to verify hostnames based on DNS name, not just IP address. (reported via slack)

**Comment by deads2k** [comment]
> @smarterclayton @deads2k @lavalamp is there more context on the mutating webhook? I can work on the design and implementation.

Webhook admission needs to be able to allow mutation, at least on update calls.  Initializers should be able to mutate values as well.

Once example use-case is and admission plugin that resolves image tags down to SHAs and overwrites them.

**Comment by caesarxuchao** [comment]
> webhook admission should be able to verify hostnames based on DNS name, not just IP address. (reported via slack)

cc @cheftako, the cert code of the admission webhook is identical to that of the aggregator.

**Comment by smarterclayton** [comment]
It was mostly described in the proposal, but some general points open:

1. a field should be exposed in web hook response status that is the
mutated object.  It is nil unless the web hook wishes to mutate the
object.  If it is set, that becomes the next version to be passed on.  We
need to talk about what fields are allowed to be mutated (all, some, none)
2. a mutating web hook cannot be called in parallel.  It must be called in
serial with other web hooks.  Order needs to be discussed.
3. mutation is not allowed to change the kind of the object.  It probably
shouldn't be allowed to change the API version either. should fail closed.
4. we don't have a way to "set" an object onto the admission attributes, so
we'd need to find the minimally invasive way to alter the returned object
from the web hook admission controller back up into the chain

**Comment by caesarxuchao** [comment]
It's useful if API server supports LIST/WATCH only uninitialized objects. It reduces traffic, especially when initializer controller runs in its own binary and cannot utilize the shared informer.

**Comment by caesarxuchao** [comment]
API support for partial orders among initializers: https://github.com/kubernetes/kubernetes/issues/50714

**Comment by deads2k** [comment]
In order to make it to beta, I think this needs to needs to be supportable for any resource, which is going to require making it into the generic apiserver.

@p0lyn0mial you've been in the generic apiserver admission chain recently.  Want to try to pull these into the generic chain?

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial you've been in the generic apiserver admission chain recently. Want to try to pull these into the generic chain?

sure, my pleasure.

**Comment by lavalamp** [comment]
My list:

* __P0__(API change) remove the failure policy field if we aren't going to implement fail-open
* Fix parallelism for initializers
  * __P0__(API change) Fix API to support multiple failure messages
 * Add a partial order mechanism. Not P0 because it should be an additive change to the API
* __P0__(Prevent broken clusters) Fix the major controllers to understand uninitialized objects
* Garbage collect old uninitialized objects 
* Add mutability to webhooks
  * __P0__(API change) figure out if this requires a breaking API change?
* Actually move the config API from alpha to beta.

Items I marked as __P0__ I think are required before we declare it beta. I don't think beta requires every feature we know we will want, it requires a stable API and it should be safe to run everywhere.

**Comment by caesarxuchao** [comment]
> Fix API to support multiple failure messages

I don't want to support multiple failures for two reasons:

* From user's perspective, multiple failure messages are not very useful. Because
  * one failure means the object will never be initialized. 
  * Even if we allow multiple failure messages, when the user observes the object, she won't know if there will be more failure messages.

* From apiserver's perspective, allowing multiple failure messages makes apiserver's code more complex.
Currently if one initializer controller reports failure, the apiserver writes the update to the etcd and then deletes the object, as a cleanup. Also, if the client is still waiting for the response to the CREATE request, the apiserver will return when it observes the update to `metadata.initializers.result`.
If we want to support multiple failure messages from multiple updates, it will be difficult for the apiserver to decide when to cleanup the fail-to-initialize objects, and when to return the CREATE call. The apiserver cannot tell if the remaining initializers are still processing the object, or if they will never process the object.

@lavalamp @erictune does the above reasons make sense?

**Comment by caesarxuchao** [comment]
We talked about moving the service IP allocator to use initializers. This requires more discussion.

**Comment by deads2k** [comment]
In addition to what @lavalamp listed, we need

1. **P0** make both work on generic apiservers




> Add mutability to webhooks
> P1(API change) figure out if this requires a breaking API change?

I don't think we can reasonably go to beta without actually making mutation work.  I think that's a critical part of admission that needs to be covered.

**Comment by lavalamp** [comment]
The reason to have multiple failure messages is so that the entire process can be deterministic.

**Comment by lavalamp** [comment]
I agree that the admission chain needs to be dynamic in the generic layer. I am quite nervous about compiling this in to every user supplied apiserver, because that will make upgrading hellish if we ever change that. This might be a case where it is better for that generic behavior to be shipped as a side-car container rather than be part of the library.

**Comment by gyliu513** [comment]
The `initializers` was now being used by isito to enable transparent injection (https://github.com/istio/pilot/pull/1104), it would be great to bump the `Initializers` admission control plugin to Beta to enlarge its adoption.

**Comment by caesarxuchao** [comment]
@p0lyn0mial have you started the move of the initializer and webhook plugins? If not, I plan to move the initializer plugin myself :)

**Comment by p0lyn0mial** [comment]
@caesarxuchao go ahead. I'd like to keep the `webhook` plugin for myself - I almost have it.

**Comment by erictune** [comment]
@caesarxuchao, @cheftako , @jpbetz and I were talking about how to do mutating webhooks.  we added some notes to "Allow mutating webhook" in the first comment.

**Comment by deads2k** [comment]
> Beta will not support * match because we don't have any use case (gc and quota assume stay compliled in). apiregistration: must specify exact GVK(s) webhook wants, so apiserver can convert.

Which apiserver?  Given CRD and aggregated apiservers, we know that we unrecognized content even if we specifically define the GVK.  `kube-apiserver` cannot assume the power to encode/decode and other apiservers would be responsible for their own admission chains.

**Comment by deads2k** [comment]
There is an in-depth exploration of what is required to have both of these come to beta here: https://github.com/kubernetes/community/pull/1137 .

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/53823, https://github.com/kubernetes/kubernetes/issues/53825, https://github.com/kubernetes/kubernetes/issues/53826, https://github.com/kubernetes/kubernetes/issues/53827,  and https://github.com/kubernetes/kubernetes/issues/53828 are issues for beta

**Comment by liggitt** [comment]
> Is/was there an issue to track the fact that the AdmissionReview has the object serialized in the internal representation? This was brought up when the initial implementation was tested: #49038 (comment)

This was fixed in 1.9 - https://github.com/kubernetes/kubernetes/pull/55127
