### ISSUE TITLE
Move workload API objects to group version apps/v1beta2

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#49135]
**FEATURE REQUEST**: Create a new version in the apps group for the core workloads API.
When we advance the core workloads API (DaemonSet, Deployment, ReplicaSet, and StatefulSet) to v1, we want them to advance as a group and be (where possible) consistent. Prior to doing so, we would like to make any API incompatible changes. In particular we will 
- [x] bump Deployment and StatefulSet to `apps/v1beta2` (#48746) @janetkuo
- [x] bump ReplicaSet to `apps/v1beta2` (#49238) @janetkuo
- [x] bump DaemonSet to `apps/v1beta2` (#49071) @foxish 
- [x] deprecate `.spec.rollbackTo`, and remove the `/rollback` subresource of apps/v1beta2 deployment ~or modify it such that the controller is not required to modify its own spec~. (#49340) @janetkuo 
- [x] add a `/scale` subresource for StatefulSet (#49168) @crimsonfaith91 
- [x] remove the `templateGeneration` feild of DaemonSet (#49454) @dixudx 
- [x] change the StatefulSet `observedGeneration` from a pointer to an int for consistency. (#49607) @dixudx  
- [x] review the API objects for consistency, and (where appropriate) make changes to bring them into alignment (modifying field names a necessary).
- [x] ensure that the defaults and validation are consistent and appropriate across all controllers.
- [x] deprecate core workloads API versions under `/extensions`
- [x] enable `apps/v1beta2` by default and remove WIP marks after API changes is done

We may find other incompatible changes that are required prior to promotion, and we would like to make them in this version, prior to releasing it. When the community is satisfied with the API surface, as contained in this version, and it is stable, we would like to promote all of the core workloads API to GA by moving the contained API to v1.

https://github.com/kubernetes/features/issues/353
/kind feature

**Comment by kow3ns** [comment]
@kubernetes/sig-apps-api-reviews 
@kubernetes/sig-apps-feature-requests 
/sig apps

**Comment by bgrant0607** [comment]
@kow3ns What's the corresponding issue in the features repo?

**Comment by kow3ns** [comment]
@bgrant0607 [ref](https://github.com/kubernetes/features/issues/353)

**Comment by lukaszo** [comment]
Is this a good moment to make RollingUpdate DS strategy a default? Like in Deployments. Or this will never happen?

**Comment by kargakis** [comment]
> Is this a good moment to make RollingUpdate DS strategy a default? Like in Deployments. Or this will never happen?

Yes, new api version means we can change the defaults. +1 on making rolling updates the default.

**Comment by smarterclayton** [comment]
+1

**Comment by janetkuo** [comment]
Yes, we planned to make StS and DS default strategy to be RollingUpdate

**Comment by bgrant0607** [comment]
@kow3ns Has it been figured out how PodDisruptionBudget will be taken into account by controllers other than StatefulSet, and how its maxUnvailable specification would relate to that specified by the controller's update strategy?

**Comment by kow3ns** [comment]
@bgrant0607 Controllers don't create evictions or drain. For each controller, workload owners specify the desired number of disruptions during rollouts, rollbacks, turn ups, and turn downs using the parameters of the corresponding objects. 

A PDB represents a contract between workload owners and cluster admins so that the former has a means to specify the tolerated number of disruptions to the latter.

The two concepts inter-operate and are related, but controllers (other than EvictionController) are agnostic to the PDB, and EvictionController is agnostic to the parameters of the workload specification.

**Comment by dims** [comment]
@kow3ns looks like there was a lot of progress, can we close this out or move this out of 1.8 milestone please?

**Comment by kow3ns** [comment]
shipped 1.8.0
