### ISSUE TITLE
Umbrella Issue: Move all e2e tests to subdirs and all TestNames Should Have SigPrefix

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubernetes#49161]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Tech debt cleanup :)

As described [here](https://github.com/kubernetes/community/blob/master/contributors/devel/release/testing.md#test), We want each of the sigs to have dashboards reflected in testgrid and every test that the sig owns to have [sig-<NAME>] as a **prefix**.  

Lots of good progress was made last week, but there are still additional tests with either

1) no sig owner mentioned in the testname.
2) the sig name mentioned somewhere other than the prefix
3) the testfile not yet in a sig-owned subdirectory.

We should be able to visit [testgrid](https://k8s-testgrid.appspot.com/google-gce) and see that all TestNames follow the same pattern of: 

[sig-name] TestName

**Comment by xiangpengzhao** [comment]
We still have some work to do. I try to triage the left e2e tests as below task list. Some of the sigs may be incorrect. Feel free to correct me if I'm wrong.

I can add this to my TODO list to help finish the work once all these are confirmed.

- [ ] cluster tests
  - [X] [sig-auth] apparmor, security_context (these two were already in sig-node), certificates, security_context, service_accounts: #48966 waiting for merging. Note: `audit` not determined, see: https://github.com/kubernetes/kubernetes/pull/48966/files#r130997323.
  - [ ] [sig-ui] dashboard
  - [ ] [sig-node] events, pod_gc, pods, pre_stop
  - [ ] [sig-storage] gke_local_ssd
  - [ ] [sig-network] example_cluster_dns
  - [ ] [sig-instrumentation] metrics_grabber_test
  - [ ] [sig-apps] network_partition
  - [ ] [sig-apimachinery] podpreset
  - [ ] [sig-scheduling] taints_test
  - [ ] [sig-federation] ubernetes_lite
  - [ ] [sig-???] examples, generated_clientset, gke_node_pools, limit_range, resource_quota, ssh

- [ ] common tests
  - [X] [sig-network] networking: #50198 waiting for merging.
  - [ ]  [sig-storage] configmap, downward_api, secrets (these three ones may be associated with sig-apimachinery discussing in #49217), downwardapi_volume, empty_dir, host_path, projected. Note: `volumes` pkg was added prefix in #48781.
  - [ ]  [sig-node] container_probe, docker_containers, expansion, init_container, kubelet_etc_hosts, pods, privileged, sysctl.

**Comment by xiangpengzhao** [comment]
@thockin does sig-network own `example_cluster_dns`?

**Comment by xiangpengzhao** [comment]
sig-ui: @bryk 
sig-node: @derekwaynecarr 
sig-storage: @saad-ali 
sig-network: @bowei 
sig-apps: @michelleN 
sig-api-machinery: @deads2k 
sig-federation: @quinton-hoole 

Can folks confirm my comment https://github.com/kubernetes/kubernetes/issues/49161#issuecomment-320502371 above ? Thanks!

**Comment by deads2k** [comment]
> [sig-apimachinery] podpreset

I think is in in service of service catalog.

apimachinery owns the infrastructure for running the APIs, but doesn't own the behavior of the APIs themselves.  The one exception that comes to mind is the CustomResourceDefinition (CRD) API, which we do own entirely.

From your unknown set, we own the generated clientsets.

**Comment by xiangpengzhao** [comment]
@deads2k Thanks! Task list updated.

@guangxuli are you interested in sending a PR to adding prefix to the tests which are confirmed by David ?
