### ISSUE TITLE
Standalone Azure cloud provider

### ISSUE THREAD

**Issue by karataliu** [kubernetes/kubernetes#50752]
This issue is to track tasks for supporting out-of-tree cloud provider for Azure.

As mentioned in design proposal [Refactor Cloud Provider out of Kubernetes Core](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider/cloud-provider-refactoring.md), all cloud provider specific code is planned to be removed from kubernetes repository.

# Work Items
## 1.8
- [x] Run standalone cloud provider
- [x] Setup standalone cloud provider repository for Azure
    - [x] Plan for issues and pull requests migration
    - [x] Create a util for code migration
    - [x] Build up cloud-control-manager application for Azure
## 1.9
- [x] Get ProviderID approach work
- [x] Fix related bugs
    - [x] #52522 Should be able to set cluster-name for cloud controller manager
## 1.10
- [x] Fix related bugs
  - [x] #56276 CloudNodeController should use patch to update node

## 1.14

- [ ] Ensure E2E test run for Azure cloud controller manager `#`
    - [x] Run E2E test against cluster running Azure cloud controller manager
    - [ ] Publish test results to testgrid
- [ ] Cleanup code dependencies on Azure cloud provider `*`
    - [x] Cleanup for Azure credential provider #57380
    - [ ] Cleanup for Azure Disk volume plugin
-  Azure volume support `#`
    - [x] Support for Azure Disk and Azure File (on tracking in the separate repos https://github.com/kubernetes-sigs/azuredisk-csi-driver and https://github.com/kubernetes-sigs/azurefile-csi-driver)
    - [x] In-tree AzureDisk and AzureFile would still be used
- Azure credential provider
  - [x] In-tree Azure credential provider would still be used

## Future

- [ ] Azure cloud provider code handoff `*`
    - [x] Add instructions for migrating existing issues and pull requests
    - [ ] Send PR to remove Azure cloud provider related code in kubernetes repo
    - [ ] Mark all PR with cloud provider code change as `do-not-merge`
- [ ] Out of tree AzureDisk and AzureFile
- [ ] Out of tree Azure credential provider

`*` Involves work in kubernetes repository
`#` Pending on upstream issues

**Comment by karataliu** [comment]
# Work Items Explained

## Setup standalone cloud provider repository for Azure
- Plan for issues and pull requests migration
    There are some ongoing issues and pull requests addressing the Azure cloud provider.

    During development of the standalone cloud provider, we will still be accepting issues and pull requests in kubernetes repository.

    If a related pull request got merged, it goes to the kubernetes repository, and later the code will be synced to the new repository, as described below.

    After switching to the new repository, we can advise users using the new location to create issues and pull requests. For ongoing issues and pull requests, it is suggested to migrate them to the new repository.

    We can create a util (just like the [cherry pick tool](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh)) for easy migration experience.

- Create a util for code migration
    To bootstrap the new repository, we will first need to import the existing Azure cloud provider code to the new cloud provider repository.

    During development of the standalone cloud provider, since we are still accepting pull requests, the upstream code base may change.

    We can create a util for syncing upstream changes to the new repository. In this case, it will be able to keep up with upstream and run tests continously.

- Build up cloud-control-manager application for Azure

    There is already the [cloud controller manager](https://github.com/kubernetes/kubernetes/tree/master/cmd/cloud-controller-manager) library, which could be used to run cloud provider logic outside of controller manager.
    
    When moving to the new repository, we could build an application upon the [cloud controller manager](https://github.com/kubernetes/kubernetes/tree/master/cmd/cloud-controller-manager) library. Examples: [rancher-cloud-controller-manager](https://github.com/rancher/rancher-cloud-controller-manager) , [keepalived-cloud-provider](https://github.com/munnerz/keepalived-cloud-provider).

    Finally, we can build up a docker image to wrap the application.

## Cleanup code dependencies on Azure cloud provider

Currently components depending Azure cloud provider includes: [azuer_credentials](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/azure/azure_credentials.go), [AzureDataDisk](https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/azure_dd), [AzureFile](https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/azure_file), and [e2e framework](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/BUILD).

- Cleanup for Azure credential provider
    For current code in `azure_credentials.go`, it uses cloud provider to parse configuration and get auth token. One solution is to rewrite related logic with Azure SDK directly.

    Besides, Azure credential provider runs from agent nodes, thus it is not easy to integrate with cloud-controller-manager. As per disscussion in [Issue#48690](https://github.com/kubernetes/kubernetes/issues/48690), an out-of-tree credential provider is proposed. The credential provider will pend on that to function correctly when kubelet is configured with external cloud provider.

- Cleanup for Azure Disk volume plugin
    `azure_dd/azure_common.go` calls some util function (MakeCRC32) in cloud provider, which could be rewrited or copied to its own scope.

    Other parts of Azure Disk volume plugin involves deeper dependency on cloud provider, will be discussed in `Azure volume support` section.

## Azure volume support
For now there are 2 volume plugins depending on Azure cloud provider: 'Azure Disk' and 'Azure File':
- azure_dd
    1. attacher.go          : Calls cloudprovider to get instance id by nodename
    2. attacher.go          : Calls cloudprovider to do attach/deattach data disk
    3. azure_provision.go   : Calls cloudprovider to create and delete Azure Disk instance

- azure_file
    1. azure_file.go        : Calls cloudprovider to get cloud environment dependent endpoint
    2. azure_provision.go   : Calls cloudprovider to create and delete Azure File instance

Pending issue: 
- Currently `cloud-controller-manager` does not support attach/detach or dynamic provision
- `kubelet` running agent nodes calls mount/unmount in volume plugin, thus it indirectly depends on cloud providers

As mentioned in [Refactor Cloud Provider out of Kubernetes Core](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md), one proposal is using [FlexVolume](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md), which supports external volume drivers.

Another proposal could be `CSI` as discussed in [PR](https://github.com/kubernetes/kubernetes/pull/46843), but it is not ready yet.

This should be a blocking issue for removing cloud provider.

## Ensure E2E test run for Azure cloud provider
- E2E test migration
    The overall E2E test migration plan may be pending on e2e test plan for [cloud-controller-manager](https://github.com/kubernetes/kubernetes/issues/44975).

    E2E framework has dependencies on server cloud providers including Azure: [BUILD file](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/BUILD). Needs to figure out where those files should be placed.

- Ensure E2E test result
    We shall add more test coverage for Azure cloud provider before switching to the new runtime approach.

    Also we should ensure test results are identical between running 'built-in cloud provdier' and 'standone cloud provider'.

**Comment by karataliu** [comment]
cc  @jdumars @wlan0 @brendanburns @kyliel

Please help review and I'll keep this updated.

**Comment by karataliu** [comment]
cc @brendandburns

**Comment by jdumars** [comment]
Adding to SIG Azure "work in progress" - thank you for an excellent summation here!

**Comment by jdumars** [comment]
@brendandburns  @karataliu @kyliel https://www.youtube.com/watch?v=XwhxuGoK0Ok&feature=youtu.be

**Comment by karataliu** [comment]
(Work Items Explained continued)
## Get ProviderID approach work
ProviderID is source for cloud controller manger to identify nodes, we need to ensure it works when switching from controller manager.

Related work:
Done: #51528, #51596, #51588, #51590, #51761
Pending: #51406

**Comment by jdumars** [comment]
See the parent issue here: https://github.com/kubernetes/features/issues/88

**Comment by luxas** [comment]
Thank you for this @karataliu :+1:!
Can you give me a brief status update what the next steps are please?
Did you notice a workgroup for this effort was created (we're hanging out in #wg-cloud-provider on Slack) and meet on Wednesdays 10am PT

**Comment by karataliu** [comment]
@luxas   We are now focusing on the v1.9 items listed in this issue.
Basically I'm now working on e2e test validation, by ensuring same e2e result for original cluster and cluster running with cloud controller manager. Things go well except for volume related cases. Thus now I'm concerned about progress on volume related work.
I just joined that workgroup, and will keep track on it. Thanks for the information.

**Comment by luxas** [comment]
It would be very valuable to get automatically running e2e tests even though the volume support isn't there quite yet @karataliu. Thanks!

**Comment by dims** [comment]
@karataliu @enisoc looks like plenty of stuff which will spill over to 1.10. Can we move the milestone?

**Comment by jberkus** [comment]
Hey, are you moving milestones on this?  Today is Code Slush.

**Comment by jberkus** [comment]
Has any other work been done on the items listed for 1.10?  I only see those tree PRs

**Comment by jdumars** [comment]
@jberkus this is effectively blocked pending the creation of org-based repos, and some continued discussion in architecture.

**Comment by feiskyer** [comment]
@karataliu Could you update the current status?

**Comment by feiskyer** [comment]
Still much work to do, move out of v1.11.

**Comment by khenidak** [comment]
@feiskyer can we move this to v1.13? if not then let us lock for v1.14 putting us at March timeframe.

**Comment by khenidak** [comment]
@justaugustus -- FYI

**Comment by feiskyer** [comment]
@khenidak Let's move this to v1.14 as v1.13 is code freezing soon and there are still some items to do.

/milestone v1.14

**Comment by luxas** [comment]
@feiskyer @khenidak What's the current status of this? Are you expecting to go beta/GA/stable with the Azure out-of-tree provider soon?

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will this reach beta in the next week?

**Comment by feiskyer** [comment]
@soggiest Yep, we are working it, but probably not release next week. I'm planning the release together with v1.14.0.

**Comment by spiffxp** [comment]
The description is really misleading given that it says nothing about v1.14.0 in it?

**Comment by feiskyer** [comment]
@spiffxp Thanks for tip, let me add the items for v1.14.

**Comment by feiskyer** [comment]
We have moved the work item tracking to github project https://github.com/orgs/kubernetes/projects/12 and design docs to [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md). Let's close this issue since it is duplicated with them.

/close
