### ISSUE TITLE
Move core controllers to use apps/v1beta2 APIs

### ISSUE THREAD

**Issue by liyinan926** [kubernetes/kubernetes#51049]
This is an issue to keep track of work on moving the four core controllers (`DaemonSet`, `Deployment`, `ReplicaSet`, and `StatefulSet`) to use `apps/v1beta2` APIs.

- [ ] Move `DaemonSet` controller to use `apps/v1beta2` APIs. (@janetkuo, #51157)
- [ ] Move `Deployment` controller to use `apps/v1beta2` APIs. (@crimsonfaith91 #51236)
- [ ] Move `ReplicaSet` controller to use `apps/v1beta2` APIs. (@liyinan926, #51050)
- [ ] Move `StatefulSet` controller to use `apps/v1beta2` APIs. (@dixudx, #51118)

@kow3ns @janetkuo 
/sig apps
/assign @liyinan926

**Comment by dixudx** [comment]
@liyinan926 I've submitted PR #51118 on bumping `StatefulSet` controller to use `apps/v1beta2`. PTAL. Thanks.

**Comment by janetkuo** [comment]
Doing so will make all these controllers NOT WORK if apps/v1beta2 isn't enabled (it's enabled by default). @bgrant0607

**Comment by bgrant0607** [comment]
Another issue is that moving these controllers to apps/v1beta2 will cause problems in updates to HA clusters in the case that not all masters are updated simultaneously.

Definitely do NOT change the default storage version nor preferred apiversion in the same release that the apiversion is introduced, which would break master rollbacks and the previous release of kubectl, which needs to work according to our supported version-skew policy.

I would suggest introducing the new apiversion in this release, and change all of the above to it in the next release.

**Comment by janetkuo** [comment]
FYI we aren't changing default storage version or preferred apiversion.

So in order to support HA cluster, this issue needs to target 1.9 instead. 

@kubernetes/sig-apps-feature-requests

**Comment by mattfarina** [comment]
In 1.8 they were released as `apps/v1beta2` and in master they are now `apps/v1`. What still needs to be done for this issue?

**Comment by enisoc** [comment]
@mattfarina We made the controller objects available through `apps/v1beta2` and now `apps/v1`, but the controller code itself still uses the `apps/v1beta1` or `extensions/v1beta1` APIs to read/write the controller objects. This issue is about changing the controller code to access controller objects through the new APIs.

**Comment by dims** [comment]
@liyinan926 @mattfarina @janetkuo can we move this to 1.10?

**Comment by liyinan926** [comment]
@kow3ns

**Comment by kow3ns** [comment]
@mattfarina @liyinan926 we can do this, it would be good to move the e2e through the entire migration path, but ultimately we will be doing moving it to apps/v1 in few weeks anyway at this point.

**Comment by janetkuo** [comment]
At this moment we should be moving to apps/v1 instead.
