### ISSUE TITLE
Task tracker of IPVS beta

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#51602]
There are some work to be done in the follow-up of #46580, that is, help IPVS existing alpha.

- [x] GCE CI failures(#54916)

- [x] cross-node visit NodePort (#53393)

- [x] hairpin issue (#53775)

- [x] Using ipset doing snat and packet filtering and reduce iptables call(#54203).

- [x] automatically load `ip_vs_*` kernel modules. (#51874, #52003)

- [x] creating e2e test suite for IPVS in upstream CI (#52834).

- [x] ip cmd -> netlink bind/unbind IP address to/from dummy device(#51686)

- [x] rsync to HEAD of iptables(#51682, #52014)

- [x] enable flush batch API(#52015)

- [x] Fix TODOs in codes (#52403)

- [x] Bug report (#51694, #52330)

- [x] Default sync period(#51777)

 - [x] IPV6 support(#52935, #53120  and more...)

/cc @thockin @quinton-hoole @haibinxie

**Comment by choury** [comment]
ref ![cleanLegacyService](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1331)
It will generate annoy error info If unbind multi-ports on one service .

**Comment by m1093782566** [comment]
@choury You're right. I think it's a nice finding. Can you fire a PR to fix it?

**Comment by choury** [comment]
@m1093782566 Sure, I'll make it soon.

**Comment by choury** [comment]
I found it is treated as already bound if `ip` returned 2 in `EnsureVirtualServerAddressBind`, but ref to the   [manual](http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS) and [source code](https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/tree/ip/ipaddress.c#n2080) of ip , it just means an error was reported by the kernel, such as "Operation not permitted". 
I prefer to use [netlink](https://github.com/vishvananda/netlink) instead of `ip` command to manager ip address.

**Comment by m1093782566** [comment]
> I prefer to use netlink instead of ip command to manage ip address.

Actually, I have considered to use netlink before. I think what you said make sense, but can we discuss it in other thread? Thanks!

**Comment by choury** [comment]
@m1093782566  I opened a issue  #51694

**Comment by SEJeff** [comment]
`s/tracer/tracker/` on the subject @m1093782566 :)

**Comment by m1093782566** [comment]
OOPS... I will fix that typo. Thanks @SEJeff

**Comment by choury** [comment]
Wish to use ipset to replace KUBE-MARK-MASQ chain.

**Comment by m1093782566** [comment]
> Wish to use ipset to replace KUBE-MARK-MASQ chain.

I find it's a reason suggestion and am trying to make it workable...

**Comment by Lion-Wei** [comment]
There are to ways to do this work:

1. Use `kubeadm`, but `kubeadm` doesn't support any kube-proxy config right now, so I had this pr #53962 , and also,  `kubernetes-anywhere` need support it too, see this pr: kubernetes/kubernetes-anywhere#464
2. Use `gce/kube-up.sh` build cluster. See this pr: kubernetes/test-infra#5209

The second way is much easier and faster, but I was told they gonna deprecated the `kube-up.sh`, so in the long term, we still need `kubeadm` and `kubernetes-anywhere`'s support.

If anybody have better way or have some suggestion about this, please let me know, I'll be really appreciate, Thanks.

**Comment by Lion-Wei** [comment]
There are to ways to add IPVS CI job:

1. Use `kubeadm`, but `kubeadm` doesn't support any kube-proxy config right now, so I had this pr #53962 , and also,  `kubernetes-anywhere` need support it too, see this pr: kubernetes/kubernetes-anywhere#464
2. Use `gce/kube-up.sh` build cluster. See this pr: kubernetes/test-infra#5209

The second way is much easier and faster, but I was told they gonna deprecated the `kube-up.sh`, so in the long term, we still need `kubeadm` and `kubernetes-anywhere`'s support.

If anybody have better way or have some suggestion about this, please let me know, I'll be really appreciate, Thanks.

**Comment by SEJeff** [comment]
This one is done as both PRs are merged:
```
 automatically load ip_vs_* kernel modules. (#51874, #52003)
```

**Comment by m1093782566** [comment]
@SEJeff ACK!

**Comment by m1093782566** [comment]
We are almost reaching the beta, except GCE CI failures, see #54916 

The failure is the case that, visiting Cluster IP from Pod A, and the backend Pod B is in the same host with the Pod A. Pod A failed to get response from Pod B until timeout.

I can reproduce the failures in my GCE cluster, but it works fine in my local-up cluster and people has never reported the issue yet. 

@Lion-Wei and I are digging...

**Comment by m1093782566** [comment]
IPVS CI is green now.
