### ISSUE TITLE
Requirements to promote CPU Manager from α to β

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#52031]
/kind feature

Task tracking issue for Beta CPU Manager.

- [x] Static policy container cpuset assignments are durable across Kubelet restarts either inspecting cgroupfs state or checkpoint state to disk. #54409
- [ ] Gating e2e tests are enabled in CI. This requires multi-CPU test nodes. #55980
- [ ] Enable the feature gate by default and mark the pre-release support level as "beta". #55977
- [ ] Beta-level docs

cc @balajismaniam @sjenning @derekwaynecarr

**Comment by flyingcougar** [comment]
As for check pointing - use etcd ?

**Comment by derekwaynecarr** [comment]
@ConnorDoyle - do you have thoughts about how we can introduce a common planning phase for device assignment and cpu assignment so that we can get the code in a structure where we can decide these things together?

/cc @sjenning

**Comment by ConnorDoyle** [comment]
@derekwaynecarr there's a more specific issue for that here: #49964. Did we decide yet whether to make that kind of topology awareness a blocker for beta?

**Comment by jeremyeder** [comment]
@derekwaynecarr

**Comment by balajismaniam** [comment]
The results from the new periodic test job for the CPU manager node e2e test is available at https://k8s-testgrid.appspot.com/wg-resource-management#kubelet-serial-gce-e2e-cpu-manager.
