### ISSUE TITLE
Revamp deployment tests

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#52113]
Ref. [Workload Controllers Test Plan](https://docs.google.com/document/d/1e2M3KD2wTfhISyyuqyX0pcUGZyzcyKoWo4CIlUojAdM/edit) 

### integration
- [x] Add TestDeploymentBasic with subtests that replace basic behavior unit tests like creating ReplicaSets, reacting to RS/Pod events, orphan/adopt, etc. (#55439)
- [x] Add TestDeploymentRollingUpdate with subtests for roll out, roll back, roll over, etc. (#54819)
- [x] Shorten poll interval (can be 100ms) and use `PollImmediate()` instead of `Poll()` (#52896)
### e2e
Convert "edge case" e2e tests to integration tests.
- [x] testPausedDeployment (#52054)
- [x] testRollbackDeploymentRSNoRevision (#53918)
- [x] testDeploymentLabelAdopted (#54105)
- [x] testScalePausedDeployment (#52054)
- [x] testScaledRolloutDeployment (#54824)
- [x] testOverlappingDeployment (#54326)
- [x] testFailedDeployment (#54331)
- [x] testDeploymentHashCollisionAvoidance (#52896)

### cmd

- [x] Make sure all appropriate kubectl commands are tested (ref cmd tests in [Workload Controller Tests](https://docs.google.com/spreadsheets/d/1YsKwQvcPX_eaEdCxjAooIz1cgnr0uHxrki3xBJAK-eM/edit#gid=0))
### upgrade
- [x] Don't pry into the ReplicaSets. Just check Deployment Status. The RS upgrade test will check the next layer down. (#53841)

### unit test
- [ ] Refactor sync call tree so we can unit test decisions (on this sync pass, create this, delete that) without needing a test fixture with mocks.
- [ ] Remove unit tests made redundant by new integration tests below (especially ones that need reactor/mock setup).

@kubernetes/sig-apps-misc

**Comment by crimsonfaith91** [comment]
We should also add a general proportional scaling e2e/integration test. It is only covered by a unit test currently. The test can be based on deployment tutorial found here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
