### ISSUE TITLE
replicaset tests have to be revamped

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#52118]
**Background**
As part of GA goal of core controllers, unit, integration, e2e, cmd, and upgrade tests of replicaset have to be revamped based on test plan guidelines suggested by @enisoc. This issue lists all necessary tasks for unit, e2e, cmd, and upgrade tests. Tasks for the integration tests are covered by #51484.

**Unit Test**
- [x] Refactor sync call tree so we can unit test decisions (on this sync pass, create this, delete that) without needing a test fixture with mocks. (PR #54185) 
- [x] Remove unit tests made redundant by new integration tests introduced in PR #52067 (especially ones that need reactor/mock setup). (PR #52354)
- [ ] ~Introduce helper functions that output which RSs should be enqueued for all types of pod event.~

**End-to-end Test**
- [x] Combine adopt and release tests into one to share setup/teardown. (PR #52320)

**Kubectl Command Test**
- [x] Test all appropriate kubectl commands. (PR #51061)

**Upgrade Test**
- [x] Test that RS survives upgrade. (PR #52449)

**Comment by crimsonfaith91** [comment]
@kubernetes/sig-apps
