### ISSUE TITLE
Requirements for local ephemeral storage to graduate to Beta

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#52463]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
In 1.8, the feature is alpha

**What you expected to happen**:
Graduate to beta in 1.10

**Requirements** :

In 1.9
- [x]  e2e test for quota (owner @NickrenREN) #52523

- [x] e2e test for limitrange (owner @NickrenREN) #52523

 - [x] e2e test for downward api (owner @NickrenREN) #52523

 - [x] kubereserved related(flag name and test cases) (owner @NickrenREN) #52708

 - [ ] kubectl support for local ephemeral storage (owner @NickrenREN)

I am working on these tasks

/cc @jingxu97 
/sig storage
