### ISSUE TITLE
Tracking work to deprecate alpha taint key and camelCase taint key 

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#53236]
Original bug report: #51246

However, this is a issue which may break existing user's system, we should make sure everything is under control during fix. Use this umbrella issue to track all work across the kubernetes org.

PR: use `not-ready` taint and auto replace `notReady` taint on node with it. #51266
- [x] with release-note
- [x] with proper milestone (1.9)
- [x] with tests
- [x] pass final review and merged

PR: Move of unreachable taint key out of alpha: #54208
- [x] with release-note
- [x] with proper milestone (1.9)
- [x] with tests
- [x] pass final review and merged

Docs update
- [x] kubernetes.github.io https://github.com/kubernetes/kubernetes.github.io/pull/5188
- [x] community: note the key's convention https://github.com/kubernetes/community/pull/1043
- [x] community: fix taint proposal https://github.com/kubernetes/community/pull/985

Announcement
- [x] sent to mailing list: kubernetes-dev kubernetes-user

**Comment by dims** [comment]
@resouer move to 1.10?

**Comment by resouer** [comment]
@dims I think this is expected to be fixed in 1.9 

The only PR under review is #54208, which is hopefully to get in. cc @bsalamat 

The community doc fix has already got lgtm for quite a long time but pending for merge. See: https://github.com/kubernetes/community/pull/985 Cloud you help with that?

**Comment by resouer** [comment]
All PR are in, the only thing is sending announcement in kubernetes-dev cc @dims

**Comment by resouer** [comment]
All fixes are in before 1.9 release, with proper release note, and announcement has been sent to mailing list. 

Close.
