### ISSUE TITLE
HugePages work tracker

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#53672]
This issue is meant to track planned work items for pre-allocated hugepages across releases.

This issue captures the plan of record discussed in the wg-resource-mgmt meetings.

## v1.9
- [x] HugePages should be restricted via ResourceQuota [**Owner**: @lichuqiang , fixed #54292]

Assess ability to graduate feature to beta.

## 1.10
- [x] HugePages should require the user to request cpu or memory [**Owner**: @tanshanshan fixed #54379]
- [x] HugePages should not be tied to QoS [**Owner**: @tanshanshan fixed #54379]
- [ ] HugePages promoted to beta [**Owner:** @derekwaynecarr, #56939]

## Future
- [ ] HugePages isolated at container and not just pod boundary [**Owner**: TBD]
- [ ] HugePages should be restricted via LimitRange [**Owner**: TBD]

cc @sjenning @jeremyeder @vishh @ConnorDoyle @kubernetes/sig-node-feature-requests

**Comment by lichuqiang** [comment]
> HugePages should be restricted via ResourceQuota

If no one is doing it, I'd like to work on the ResourceQuota part.

**Comment by tianshapjq** [comment]
would this be discussed in the meeting recently? i would like to try on the "via LimitRange" but seems more details need to be settled.

**Comment by lichuqiang** [comment]
@derekwaynecarr Regarding to the ResourceQuota issue, all I could think is to add support for resource HugePages in podEvaluator of quota, so that it could be aware of the hugepage declared in resourceQuota, and that requested in podSpec. 
It is thought to be a small change, The only thing that needs attention is the way to address resource HugePages, as it's name is not fixed, like CPU or memory, but in a specific format.
Correct me if I miss something :)

**Comment by derekwaynecarr** [comment]
@lichuqiang -- the quota change is relatively small, if you want to pick up the work, i would be happy to shephard it.

**Comment by derekwaynecarr** [comment]
@lichuqiang -- added you as owner, thanks for volunteering!  let me know when you have the pr up

**Comment by xiangpengzhao** [comment]
@tianshapjq are you ready for the LimitRange part? :)

**Comment by tianshapjq** [comment]
yes, I've worked on this for some time and will commit the pr ASAP. @xiangpengzhao @derekwaynecarr

**Comment by tianshapjq** [comment]
@derekwaynecarr hi, I am confused by the tests I've made, which seems the "HugePages should be restricted via LimitRange" has already been done. 
I created the LimitRange as below:
_apiVersion: v1
kind: LimitRange
metadata:
  name: mytest
spec:
  limits:
  - default:
      hugepages-2Mi: 40Mi
    defaultRequest:
      hugepages-2Mi: 40Mi
    type: Container_
and the pods created by the following yaml:
_apiVersion: v1
kind: Pod
metadata:
  generateName: hugepages-volume-
spec:
  containers:
  - image: tomcat_java:v6.0
    command:
    - /home/test.sh
    name: example_
and the output of the pod in yaml is like:
_spec:
  containers:
  - command:
    - /home/test.sh
    image: tomcat_java:v6.0
    imagePullPolicy: IfNotPresent
    name: example
    resources:
      limits:
        hugepages-2Mi: 40Mi
        memory: 250Mi
      requests:
        hugepages-2Mi: 40Mi
        memory: 125Mi_
Is this the LimitRange part already been done? Otherwise anything wrong with my understanding?
Also, I found an subtle error in the error info when creating pods restricted by the hugepage [#54387](https://github.com/kubernetes/kubernetes/pull/54387), would you please take a look?

**Comment by derekwaynecarr** [comment]
@tianshapjq -- thanks for the feedback, i have been distracted looking at other topics, but hope to return to this later this week.

**Comment by tianshapjq** [comment]
@derekwaynecarr I have filed an issue related to hugepages, would you please check when you are free? link: #54917

**Comment by tianshapjq** [comment]
@derekwaynecarr hi, I've worked on the _HugePages isolated at container and not just pod boundary_ issue and would like to confirm some details.
My first though was to implement this issue via docker, just like what cpu and memory did. But docker seems not support hugepage limit in present. Which means we have to get it done by coding in kubernetes or libcontainer, is that right? 
Please let me know if there are any other instructions that may help :)

**Comment by derekwaynecarr** [comment]
@tianshapjq -- to support isolation at container boundary, we would need support from the container runtime.  that would require support in the CRI to expose the resource, and support in individual container runtimes (contianerd, cri-o, docker, rkt, etc.) to actually make use of it.  in practice though, i have not seen a major requirement to support container boundary isolation.  do you have use cases in mind that would require it?

**Comment by tianshapjq** [comment]
@derekwaynecarr I have no any other use cases as well, for now all the achievements fit well for our requirements. BTW, does the 

> HugePages should be restricted via LimitRange
still need to move on? I found it seems already being supported by default.

**Comment by sjenning** [comment]
I don't think the intent was for #56939 to close this
/reopen
