### ISSUE TITLE
umbrella issue for HA (replicated) API Server

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#57213]
API Server relies on etcd for HA. But it also has internal objects/states that need to be initialized based on API objects in etcd. Example of that is CRDs that need a http handler. This issue is to keep track of all states we have in API server and make sure all of them are HA ready. Note that most of them are already HA.

- [ ] CRD http handler: Coordination required between API servers to mark a CRD as ready (#57042)
- [ ] Admission Webhooks: All API servers should became aware of webhooks before they mark as ready. Webhooks should be activated when all API servers are aware of them. (need an issue)
- [ ] Audit api server code for more issues

@kubernetes/sig-api-machinery-misc

**Comment by cheftako** [comment]
cc @cheftako

**Comment by jennybuckley** [comment]
cc @jennybuckley

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
What's the status of this issue from a SIG API Machinery standpoint?

**Comment by sttts** [comment]
> What's the status of this issue from a SIG API Machinery standpoint?

This topic was discussed in last sig-api-machinery meeting. But there is not more than general acknowledgement of the issue. Nobody came up with a design to solve it.

**Comment by neolit123** [comment]
this is an old one, but leaving it open.

/remove-sig cluster-lifecycle
^ please request discussion if needed.
