### ISSUE TITLE
Advanced Auditing 1.10 umbrella bug

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#58083]
This is a continuation of the work on the [Advanced Auditing feature](https://github.com/kubernetes/features/issues/22)

Umbrella issue for 1.11 release: https://github.com/kubernetes/kubernetes/issues/60392

## API-related changes

- ~Graduate API to stable~
  - Moved to 1.11
- [x] Integration with admission
  - [x] [Add Annotations to Advanced Audit API](https://github.com/kubernetes/kubernetes/pull/58806) by @CaoShuFeng 
  - ~[Add RBAC information to audit logs](https://github.com/kubernetes/kubernetes/pull/58807) by @CaoShuFeng~
    - Moved to 1.11
  - ~[Add PodSecurityPolicy admission information to audit logs](https://github.com/kubernetes/kubernetes/issues/56209)~
    - Moved to 1.11
  - ~What about webhooks? We want to answer: Who injected this side-car container?~
    - Moved to 1.11
- [x] [Audit policy supports pattern matching](https://github.com/kubernetes/kubernetes/issues/55305)
  - @hzxuzhonghu is working on this in https://github.com/kubernetes/kubernetes/pull/55306

## Bugfixes and improvements

- [x] [Introduce buffering for the log backend to fix file writing bottleneck](https://github.com/kubernetes/kubernetes/issues/53006)
  - @crassirostris is taking over this work from @hzxuzhonghu in https://github.com/kubernetes/kubernetes/pull/60076 and https://github.com/kubernetes/kubernetes/pull/60237
- [x] [Restore audit logging in the scalability tests](https://github.com/kubernetes/kubernetes/issues/53020)
  - @crassirostris is working on this in https://github.com/kubernetes/test-infra/pull/7000
- [x] [Audit rule matching logic incorrect when user attribute is nil](https://github.com/kubernetes/kubernetes/issues/59331)
  - @CaoShuFeng is working on this. PR: https://github.com/kubernetes/kubernetes/pull/59398
- ~Let a user choose an output API version~
  - Moved to 1.11
- ~Don't duplicate ResponseStatus: https://github.com/kubernetes/kubernetes/issues/60108~
  - Moved to 1.11
- ~[Optional] [Invalid api group for delete operations](https://github.com/kubernetes/kubernetes/issues/57829)~
  - Moved to 1.11
- ~[Optional] [Always retry audit webhook](https://github.com/kubernetes/kubernetes/issues/55621)~
  - Moved to 1.11

## Policy changes

- ~[Optional] [GCE audit policy should be made re-usable by other setups](https://github.com/kubernetes/kubernetes/issues/53321)~
  - Moved to 1.11
- ~[Optional] Audit policy should be tested (e.g. that it includes all core resources, [more context](https://github.com/kubernetes/kubernetes/issues/52265#issuecomment-329243972))~
  - Moved to 1.11

## Documentation

@crassirostris is working on this in https://github.com/kubernetes/website/pull/7679

- [x] Add a deprecation warning to the legacy audit system
- [ ] Describe setting up auditing in multi-apiserver setup
- [ ] Describe setting up throttling parameters depending on the Kubernetes deployment
- [ ] Specify behavior of patch requests: https://github.com/kubernetes/kubernetes/issues/60110

## To discuss

- ~[Optional] [Auditing federation setups](https://github.com/kubernetes/federation/issues/213)~
  - Moved to 1.11
- [x] ~Auditing multi-apiserver setups~
  - Already supported at some degree. Additional features to follow after v1

/cc @sttts @soltysh @tallclair @ericchiang @CaoShuFeng @hzxuzhonghu @piosz 

Feel free to add what's missing

**Comment by tallclair** [comment]
RE: integration with admission. I think it would be useful to see something similar for authn/z as well (i.e. which plugin authorized / authenticated the request, with the ability for the plugin to add arbitrary annotations (e.g. RBAC adds the role & binding used)). Not a requirement for 1.10 or GA, but nice to have.

**Comment by crassirostris** [comment]
Audit logging is a shared effort between sig-auth and sig-api-machinery

**Comment by tallclair** [comment]
In another thread, we were discussing audit logging in very high QPS clusters (e.g. very large clusters). That feels like something that should be addressed, or at least well defined (e.g. audit logging is only supported up to XX QPS).

A suggestion I threw out is to implement graceful degradation of the audit infrastructure (probably in the open source). One way of doing this would be to introduce priority to the audit policy, and then when the buffers are full (or too many requests start erroring) drop the lower priority events before the higher priority ones. We already have a course priority defined through the metadata read/write and data read/write CAL classification. We could also define some hard audit QPS limits (although it might be possible by adjusting the current parameters), and start dropping lower priority events to stay under those QPS limits.

I'm not sure the full priority mechanism should block GA, but I think we should have some more reliable or well-defined behavior in this area.

**Comment by crassirostris** [comment]
> (e.g. audit logging is only supported up to XX QPS).

It actually depends on the audit logging configuration. You can always support more QPS by bumping the audit logging throughput (e.g. the number of allowed QPS issued by webhook). It's a matter of policy in each cluster, not implementation per se

**Comment by tallclair** [comment]
Fair point... do we have any idea how cluster size maps to the defaults though? I.e. at what point should the cluster admin expect to need to raise those defaults or tighten the policy?

**Comment by sttts** [comment]
What is missing for `Auditing multi-apiserver setups`? 

As far as I see, we have the audit options in the generic apiserver library and have enabled it through https://github.com/kubernetes/kubernetes/blob/509df603b18d356777176953e5d160b6f3d0bba9/staging/src/k8s.io/apiserver/pkg/server/options/recommended.go#L35 in the `RecommendedOptions`. So the basic support exists.

We **do not** have
- custom user-agent strings or a `Component` field that can either be `kube-apiserver` or e.g. `service-catalog-apiserver`. Or does this work through the kubeconfig passed to the webhook?
- central configuration. For that we would need some kind of ComponentConfig for user provided API servers, or use a well-known ConfigMap in the kube-public namespace. 

/cc @deads2k

**Comment by tallclair** [comment]
From sig-auth discussion:

Graduating to V1 should require:
1) Restore audit in the scalability tests (already planned for 1.10)
2) A story for how other components are expected to integrate into the audit system.

For (2), the idea is that going to V1 puts the burden of integration on new features (as opposed to audit developers), but first they need the necessary hooks to integrate. I think the annotations (https://github.com/kubernetes/kubernetes/pull/58143) is the last piece of this story.

W.r.t. multi-apiserver setups, I think that the 2 issues @sttts mentioned should not be blockers for audit going to v1. Unless we want to move the policy & configuration to a component config, and deprecate the flags approach. However, there is a bootstrapping problem that needs to be solved to configure audit logging through component config (so we might still want flags?).

**Comment by smurfralf** [comment]
Please also include fix for Issue #59331

**Comment by crassirostris** [comment]
I added points about documentation & deprecation to the list of items to do

> Fair point... do we have any idea how cluster size maps to the defaults though? I.e. at what point should the cluster admin expect to need to raise those defaults or tighten the policy?

It depends on the expected QPS to the apiserver, which may be pretty irregular depending on the cluster setup and workloads. It seems it would be useful to add a paragraph to the documentation that would explain how these values should be set

> custom user-agent strings or a Component field that can either be kube-apiserver or e.g. service-catalog-apiserver. Or does this work through the kubeconfig passed to the webhook?

AFAIU, it's possible to pass user agent through kubeconfig: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/config.go#L83. However, it seems this behavior should be better documented

> W.r.t. multi-apiserver setups, I think that the 2 issues @sttts mentioned should not be blockers for audit going to v1

Agree. I mentioned this in the issue text. 2everyone: feel free to counter if you don't think this is the right approach

**Comment by tallclair** [comment]
Is the intent still for this to reach stable in 1.10? Code freeze is coming up ([02-26](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.10/release-1.10.md)). There are a lot of issues still open (including 2 I just filed: #60108 and #60110).

At this point I'm inclined to suggest we bump GA out to 1.11 unless there are strong objections.

**Comment by tpepper** [comment]
@crassirostris and @tallclair pending your decision on 1.10 or not please make sure to scrub the set of issues referenced off this one and either add the approved and approved-for-milestone labels or remove the v1.10 milestone target.

**Comment by crassirostris** [comment]
I agree, it doesn't make sense to try ask reach stable in 1.10, too much work, too little done already

I created [a new umbrella issue](https://github.com/kubernetes/kubernetes/issues/60392) for audit logging in 1.11 and moved items we're not pursuing this release there

The rest I believe is doable, most of the things left are either in review or docs-related

**Comment by crassirostris** [comment]
@CaoShuFeng @tallclair @sttts @ericchiang What's your take on the annotations effort? Do you think it makes sense to push for 1.10, or it's better to postpone it until 1.11?

**Comment by CaoShuFeng** [comment]
> @CaoShuFeng @tallclair @sttts @ericchiang What's your take on the annotations effort? Do you think it makes sense to push for 1.10, or it's better to postpone it until 1.11?

I am OK in either way.

**Comment by crassirostris** [comment]
Thanks!

@CaoShuFeng I think https://github.com/kubernetes/kubernetes/pull/58143 defintely should go to 1.11, there's too much work left. I'm moving it to the 1.11 umbrella issue

@tallclair @sttts WDYT about https://github.com/kubernetes/kubernetes/pull/58807? Is it close enough to completeness that we can ask for a couple of days for an exception?

**Comment by crassirostris** [comment]
It seems we don't have enough capacity to review https://github.com/kubernetes/kubernetes/pull/58807 and it has to be pushed to 1.11

**Comment by jberkus** [comment]
Should this issue be closed/moved to 1.11 then?

**Comment by jberkus** [comment]
oops, missing priority was my fault, moving back into milestone:

/priority critical-urgent
/remove-priority important-soon

**Comment by liggitt** [comment]
@tallclair has the work planned for 1.10 been completed at this point?

**Comment by tallclair** [comment]
Remaining work is resolving the test failures, https://github.com/kubernetes/kubernetes/issues/60719

**Comment by crassirostris** [comment]
@liggitt Besides test failures, docs only. I will create a PR shortly, my fault I didn't do this earlier

**Comment by jberkus** [comment]
Since the tests are now fixed, what remains with this tracker?

**Comment by crassirostris** [comment]
@jberkus Only docs: https://github.com/kubernetes/website/pull/7679

**Comment by liggitt** [comment]
doc PR is open and tagged for the 1.10 milestone. moving this issue to 1.11

**Comment by crassirostris** [comment]
Well, there's a separate issue for 1.11, so to avoid constant pinging from the bot and considering that docs PR is almost ready, I'll move this issue back to 1.10 and close
