### ISSUE TITLE
Umbrella issue for CRDs moving to GA

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#58682]
This is a continuation of the [CustomResourceDefinition feature](https://github.com/kubernetes/features/issues/95). 

As discussed earlier, the plan is to go GA. This is the list of tasks that need to be addressed for CRDs.

Please categorize (do not remove, please) whichever does not seem appropriate for moving to GA and put your name behind it. If you want to add any notes specific to a task, please list it as a bullet point and again, put your name behind it.

### GA-blocking

- [x] Generate OpenAPI spec for registered CRDs (https://github.com/kubernetes/kubernetes/pull/71192, #49465)
    -  @sttts: features in kubectl rely on this
- [ ] CustomResourceValidation feature to stable #62323  (will be promoted along with v1 API)
- [ ] CustomResourceSubresources feature to stable (will be promoted along with v1 API)
- [ ] CustomResourceWebhookConversion feature to stable (will be promoted along with v1 API)
  - [x] https://github.com/kubernetes/kubernetes/issues/64136
  - [ ] ConversionReview API to v1  (will be promoted along with v1 API)
  - [ ] scale test, ensure adequate metrics - tracked in https://github.com/kubernetes/enhancements/pull/1015
  - [x] resolve how webhooks indicate they want `v1` or `v1beta1` ConversionReview objects sent to them
- [x] rename `validation` -> `schema` in v1 (#64483)
- [x] Support quota for custom resources (#53777, kubernetes/community#798, #64201)
    - @sttts: critical for enterprise workloads
- [ ] ~~Prevent metadata update on subresource update (validate no changes were made)~~
    - @nikhita: done for CRs, but not CRDs
    - @liggitt: the current behavior for CRs was the important one for GA
- [x] Defaulting and pruning for custom resources (#59151, #63604)
    - @nikhita: design proposals and WIP PRs open (kubernetes/community#2443, #63604)

### Post-GA
- [ ] Human readable status from conditions for a CRD using additionalPrinterColumns (#67268)
  - @liggitt: this sounds like a good candidate for future enhancement, but not GA-blocking
- [ ] ~~Consider changing the schema language in CRDs (#67840)~~
  - @liggitt: resolved by https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md
- [x] Should support graceful deletion for storage (#68508)
- [ ] Enable arbitrary CRD field selectors by supporting a whitelist of fields in CRD spec (#53459)
    - @sttts: optional, can be added later
- [ ] Support graceful deletion for custom resources (#56567)
    - @sttts: optional, can be added later
- [ ] ~~CRD validation webhooks (kubernetes/community#1418)~~
    - @sttts: admission webhooks work today. More can be added later
    - @liggitt: validating webhooks cover this sufficiently
- [ ] Allow OpenAPI references in the CRD validation schema (#54579, #62872)
    - @sttts: optional, convenience, can be added later
- [ ] Generate json-schema for use in the CRDs from the go types (#59154, kubernetes/sample-controller#2, kubernetes/code-generator#28)
    - @sttts: only developer convenience
- [ ] Support for namespace-local CRD (#65551)
    - @sttts: optional feature, can be added later
    - @nikhita: we will probably not do this any time soon
- [ ] Support proto encoding for custom resources (#63677)
    - @nikhita: can be added later
- [x] `labelSelectorPath` should be allowed not be under `.status` (#66688)
    - @liggitt: this can be expanded if there is a need for it, and it is [not clear](https://github.com/kubernetes/kubernetes/issues/66688#issuecomment-425996199) this is desired
- [ ] Support arbitrary non-standard subresources for CRDs (https://github.com/kubernetes/kubernetes/issues/72637)
  - @liggitt: it is not clear that this is a pattern we want to encourage, and should not block graduating the standard REST spec/status feature set

### Completed features
- [x] Support multiple CRD APIVersions and migration (#57316, kubernetes/features#544, #60113, #63518)
    - [x] Support for no-op conversion versioning (#63830)
    - [x] Webhook conversion for custom resources (kubernetes/features#598, kubernetes/community#2420)
- [x] Allow retries on patch conflicts (#58017, #58414)
- [x] Subresources for Custom Resources (#38113)
- [x] Better kubectl printing for custom resources (#31343, #58603 60991)
- [x] Allow to specify categories for custom resources (#59561)
- [x] CustomResourceDefinitions should support maps in OpenAPI schema (#59485)
- [x] Allow more fields at root of CRD schema when status is enabled (#65293)
- [x] Support API Paging for CRDs and custom resources (#67861)

### Rejected or out-of-scope feature requests
- Allow modifying CR metadata on status update via modifying webhook (#70084)
    - @liggitt: allowing admission to make changes that would not be allowed via the API is not desired
- Support CRDs in dashboard (kubernetes/dashboard#2493)
    - @sttts: the dashboard is only one of many consumers. Not critical
- Fix `kubectl get --export` for custom resources (#48211)
    - @sttts: optional feature
    - @liggitt: export support for all objects is still under consideration - https://github.com/kubernetes/kubernetes/issues/24855

### GA-blocking

- [ ] kubectl get with a short name/category will error on the first try (#65517)
- [x] Invalid regex in OpenAPI validation crashes API server (#65470)
- [ ] Rename CustomResourceColumnDefinition `JSONPath` as `jsonPath` for v1 (#66531, tracked in https://github.com/orgs/kubernetes/projects/28)
- [ ] CRD Established condition has null for lastTransitionTime (#69654, tracked in https://github.com/orgs/kubernetes/projects/28)
- [ ] CRDs created in old versions don't have .metadata.generation (#68998, tracked in https://github.com/orgs/kubernetes/projects/28)
- [ ] CRD validation error from 1.11 server was not correct, lacks details of errors (#68787, tracked in https://github.com/orgs/kubernetes/projects/28)
- [ ] CRD cannot have a field named 'items' (#68466, tracked in https://github.com/orgs/kubernetes/projects/28)

### Non-GA blocking
- [ ] ~~Watcher falls into infinite loop on bad Custom Resource manifests (#57705)~~
    - @sttts: should be fixed, but is no deep problem
- [ ] ~~CRD age does not change from `<invalid>` as soon as it becomes Established (#57042)~~
    - @sttts: should be fixed, but is no deep problem
    - @liggitt: this is actually a client clock skew issue
- [ ] ~~Apiextensions discovery is broken without kube-aggragator (#68971)~~
    - @liggitt: still under investigation, working as intended in kube-apiserver

### completed bugs
- [x] kubectl is inconsistent when the CRD has the same names as that of a native resource (#42521)
    - @sttts: consistency issue, must be fixed
- [x] Collect prometheus metrics for custom resources (#55146)
- [x] Validate metadata and persist label/annotation values properly (#59451)
- [x] Allow `required` and `description`, along with `properties` in the root schema when the status subresource is enabled (#63533, #64766)
- [x] Creating a custom resource with non-traditional plurals _and_ subresources doesn't work with kubectl for 1.11 (#67235)
- [x] resourceVersion is incremented for custom resources on no-op writes (#67541)

## Tech debt
- [ ] Add CRD garbage collector tests to cover aggregated API server (#49801)
- [ ] Revisit Creating CustomResourceDefinitions from apiextensions-apiserver integration tests (#63656)
- [x] Add e2e test for CRD watch (#55538)
- [x] apimachinery passes through Unstructured in inconsistent ways (#60312)

/cc @sttts @deads2k @enisoc @liggitt @ironcladlou @mbohlool @lavalamp @caesarxuchao @jennybuckley @ash2k @munnerz

**Comment by nikhita** [comment]
Added https://github.com/kubernetes/kubernetes/issues/59151.

**Comment by nikhita** [comment]
Added https://github.com/kubernetes/kubernetes/issues/59154.

/cc @frankgreco

**Comment by nikhita** [comment]
Quick update for folks on this thread: have updated the main issue body with more features and bugs we need to get in.

**Comment by lavalamp** [comment]
Should we support export for CRDs somehow? It's mentioned above but the link doesn't seem to relate in an obvious way?

**Comment by rmohr** [comment]
>  Enable arbitrary CRD field selectors by supporting a whitelist of fields in CRD spec (#53459)
> @sttts: optional, can be added later

How important is it for others that CRs support custom field selectors? In combination with the status subresource it becomes pretty ugly to set labels. We have for instance a `status.nodeName` on our object and also set a corresponding label, so that the node daemons can see the objects. With the status subresource this is not an atomic operation anymore (#70084).

Right now we first set a label and then do the status update and have some extra logic in the daemons to detect the "glitch" and wait until the hand-over is completely done.

**Comment by liggitt** [comment]
> How important is it for others that CRs support custom field selectors? In combination with the status subresource it becomes pretty ugly to set labels

that is on the list of features to consider post-GA

**Comment by marun** [comment]
@liggitt An update via the status endpoint for a core type (e.g. `Namespace`) supports changes to metadata.  It appears that an update via the status endpoint for a CR does not allow changes to metadata.  Is my testing in error, or is this an intentional deviation in API behavior for CRDs?

**Comment by liggitt** [comment]
Some built-in namespaces support updating metadata via status subresources, and some do not. Allowing it was an oversight in early built-in resources. See https://github.com/kubernetes/kubernetes/issues/20978 and https://github.com/kubernetes/kubernetes/issues/45539

**Comment by liggitt** [comment]
closing this issue. GA features are covered by https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md and work in progress is tracked/categorized in https://github.com/orgs/kubernetes/projects/28
