### ISSUE TITLE
Schedule DaemonSet Pods by default scheduler

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#59194]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**:

After [discussion](https://docs.google.com/document/d/1v7hsusMaeImQrOagktQb40ePbK6Jxp1hzgFB9OZa_ew/edit#), we agree to let kube-scheduler to schedule DaemonSet Pods instead of DaemonSet controller. This issue is used to trace all related sub-tasks.

Design Doc: https://github.com/kubernetes/community/pull/1714
Features: https://github.com/kubernetes/features/issues/548

Tasks: 

- [x] Added Alpha flag for NoDaemonSetScheduler feature. (#59630)
- [x] Schedule DaemonSet Pods by default scheduler. (#59862)
- [x] Added MatchFields to NodeSelectorTerm. (#62002)
- [x] Supported nodeSelector.matchFields in scheduler. (#62453)
- [x] ~~Got target node name of pending DaemonSet pod. (#61387)~~
- [x] Schedule DaemonSet Pods in scheduler. (#63223)
- [x] Release notes and doc (https://github.com/kubernetes/website/pull/8842)

/cc @bsalamat

**Comment by ravisantoshgudimetla** [comment]
@k82cn Not sure how far you have gone with implementation. Feel free to assign some tasks to me after breaking this issue into sub-tasks.

**Comment by k82cn** [comment]
working branch is https://github.com/k82cn/kubernetes/tree/k8s_59194 :).

**Comment by k82cn** [comment]
@kow3ns , @bsalamat , would you help to review the related issues in order? I'll create a e2e test for it.

**Comment by bsalamat** [comment]
Thanks, @k82cn! Reviewed Task 0, 1, and 2. Will review 3 when/if it is ready.

**Comment by tpepper** [comment]
@kubernetes/kubernetes-milestone-maintainers this issue needs a priv'd user to assess and add approval for 1.10

**Comment by k82cn** [comment]
ACK.  In progress; comments addressed, waiting for review
ETA: 16/03/2018
Risks: low, only alpha feature is touched.

**Comment by jberkus** [comment]
ACK.  In progress
ETA: 19/03/2018
Risks: additional test fails caused by merge of #61161 

All code PRs for this feature issue have been merged, except  #59636, which will be deferred to 1.11 as it is not required for the feature.  At this point, the only thing open for this issue is the Docs patch, which is under review.

**Comment by jdumars** [comment]
ACK. In progress
ETA: 19/03/2018
Risks: additional test fails caused by merge of #61161

Still in progress AFAICT ~ keeping this issue alive

**Comment by tnozicka** [comment]
> After discussion, we agree to let kube-scheduler to schedule DaemonSet Pods instead of DaemonSet controller. 

Feels like I am too late for the party but I don't see any explicit approvals in that linked doc or anywhere else.

Who is **we**?

@k82cn would you mind pointing me to a written approval from sig-architecture for this feature? All I found was the exact opposite here: https://groups.google.com/forum/#!searchin/kubernetes-sig-architecture/daemonset%7Csort:date/kubernetes-sig-architecture/ICJLqRWL420/H0Lgf15dAgAJ

**Comment by bsalamat** [comment]
@tnozicka [Here is the doc](https://docs.google.com/document/d/1v7hsusMaeImQrOagktQb40ePbK6Jxp1hzgFB9OZa_ew/edit) that explains the problem and lists possible solutions. There is much discussions in the comments of the doc that you can read if you are interested. In a SIG scheduling meeting where Brian Grant from the SIG Architecture was present, we discussed the solutions and decided to choose solution #1 in the doc.

**Comment by bsalamat** [comment]
status/approved-for-milestone

**Comment by tnozicka** [comment]
> @tnozicka Here is the doc that explains the problem and lists possible solutions. There is much discussions in the comments of the doc that you can read if you are interested.

@bsalamat I don't want to take sides on the chosen path here but given that this was already discussed on the sig-architecture ML and several members were against it, there should have been the same discussion on that ML about that topic again.

I went though that doc and didn't see any explicit approval from those members of sig-architecture there. (Even if it would be in those comments, it's the wrong place.)

> In a SIG scheduling meeting where Brian Grant from the SIG Architecture was present, we discussed the solutions and decided to choose solution #1 in the doc.

Deciding it on the ML list is **open**, **auditable** and engages people from different time zones or otherwise engaged at that time.

@kubernetes/sig-architecture-feature-requests

**Comment by k82cn** [comment]
@tnozicka , as you known, there's a design doc PR [here](https://github.com/kubernetes/community/pull/1714) for this feature; people from different zone can give +1 or -1 comment during reviewing :)

BTW, is there any case that this feature can not 'handle' ?

**Comment by bsalamat** [comment]
> I don't want to take sides on the chosen path here but given that this was already discussed on the sig-architecture ML and several members were against it, there should have been the same discussion on that ML about that topic again.

The design doc was sent to the mailing list and there was discussion on the SIG meetings and doc. We cannot ensure that all the community members have seen all the topics and approve a design decision. That said, if you see any major issue with the decision, please comment on the doc or send an email to sig scheduling mailing list. We will consider all possible solutions and would like to choose the best.

**Comment by k82cn** [comment]
Update the status: the functional codes are merged; the doc PR is opened (https://github.com/kubernetes/website/pull/8842), waiting for review :)

**Comment by k82cn** [comment]
All related tasks were done, refer to the issue description for the detail :)
