### ISSUE TITLE
kubectl: some flag values are not bound

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#60366]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cli

**What happened**:

Currently xxxOptions does not get bound as default value for some flags, which may bring in potential risks/bugs for some commands.

Such as `kubectl attach pod1`,
https://github.com/kubernetes/kubernetes/blob/af58729c866abc6ebd08edf9e4c1e9bb5bbdc418/pkg/kubectl/cmd/attach.go#L86

Here the default value for flag `container` will always be an empty string, regardless of the actual value of `options.ContainerName`.

Already discussed this potential bug with @deads2k in Slack.

This issue is used to track those cleanup items.

- [x] flag value bindings for kubectl attach/convert/delete/drain/edit/exec commands (#60357 )
- [x] flag value bindings for kubectl apply commands (#60360 )
- [x] flag value bindings for kubectl label/patch/taint/top commands (#60361 )
- [x] flag value bindings for kubectl create/get/set commands (#60363)
- [x] kubectl: flag value bindings for common utils (#60364 )

**Comment by deads2k** [comment]
This is a really good bit of cleanup and I'm glad to see the pulls.

**Comment by dixudx** [comment]
/close

All the fixes have been merged.

**Comment by soltysh** [comment]
Thanks @dixudx!
