### ISSUE TITLE
Advanced Auditing 1.11 umbrella bug

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#60392]
This is a continuation of the work on the [Advanced Auditing feature](https://github.com/kubernetes/features/issues/22)

It's planned to release Audit Logging API to stable in 1.11. Here's the list of tasks:

## API-related changes

- [ ] Graduate API to stable
- [ ] Integration with admission 
  - [x] [Add RBAC information to audit logs](https://github.com/kubernetes/kubernetes/pull/58807) by @CaoShuFeng 
  - [x] [Add PodSecurityPolicy admission information to audit logs](https://github.com/kubernetes/kubernetes/issues/56209)
    - @CaoShuFeng is working on this in https://github.com/kubernetes/kubernetes/pull/58143
  - [ ] Annotate audit logs in remote admission webhooks
    - @CaoShuFeng is working on this in https://github.com/kubernetes/kubernetes/pull/58679

## Bugfixes and improvements

- [x] [Limit the batch physical size in batching audit backend](https://github.com/kubernetes/kubernetes/issues/60432)
- [x] [Don't duplicate ResponseStatus](https://github.com/kubernetes/kubernetes/issues/60108)
- [x] Let a user choose an output API version
  - @crassirostris is taking over this work from @soltysh in https://github.com/kubernetes/kubernetes/pull/60056
- [ ] Completely remove legacy audit logging
- [x] [Optional] [Invalid api group for delete operations](https://github.com/kubernetes/kubernetes/issues/57829)
- [ ] [Optional] [Always retry audit webhook](https://github.com/kubernetes/kubernetes/issues/55621)

## Policy changes

- [ ] [Optional] [GCE audit policy should be made re-usable by other setups](https://github.com/kubernetes/kubernetes/issues/53321)
- [ ] [Optional] Audit policy should be tested (e.g. that it includes all core resources, [more context](https://github.com/kubernetes/kubernetes/issues/52265#issuecomment-329243972))

## To discuss

- [ ] [Optional] [Auditing federation setups](https://github.com/kubernetes/federation/issues/213)

**Comment by loburm** [comment]
@timstclair @sttts 
Considering that Mik doesn't work on it anymore, should we open a new issue for tracking work that is left?

**Comment by loburm** [comment]
@timstclair @sttts @soltysh 
I would like to discuss possible blockers of graduating API to stable. Below inserting the list of tasks from Mik, but with recent updates:

## API-related changes

- [ ] Graduate API to stable
- [ ] Integration with admission 
  - [x] [Add RBAC information to audit logs](https://github.com/kubernetes/kubernetes/pull/58807) by @CaoShuFeng 
  - [ ] [Add PodSecurityPolicy admission information to audit logs](https://github.com/kubernetes/kubernetes/issues/56209)
    - @CaoShuFeng is working on this in https://github.com/kubernetes/kubernetes/pull/58143
  - [ ] Annotate audit logs in remote admission webhooks
    - @CaoShuFeng is working on this in https://github.com/kubernetes/kubernetes/pull/58679
## Bugfixes and improvements

- [x] [Limit the batch physical size in batching audit backend](https://github.com/kubernetes/kubernetes/issues/60432)
- [x] [Don't duplicate ResponseStatus](https://github.com/kubernetes/kubernetes/issues/60108)
- [x] Let a user choose an output API version
- [ ] Completely remove legacy audit logging
- [x] [Optional] [Invalid api group for delete operations](https://github.com/kubernetes/kubernetes/issues/57829)
- [ ] [Optional] [Always retry audit webhook](https://github.com/kubernetes/kubernetes/issues/55621)

## Policy changes

- [ ] [Optional] [GCE audit policy should be made re-usable by other setups](https://github.com/kubernetes/kubernetes/issues/53321)
- [ ] [Optional] Audit policy should be tested (e.g. that it includes all core resources, [more context](https://github.com/kubernetes/kubernetes/issues/52265#issuecomment-329243972))

## To discuss

- [ ] [Optional] [Auditing federation setups](https://github.com/kubernetes/federation/issues/213)

It looks that Audit Logging in a pretty good shape. From required work that has to be done I see only two PR that are not merged and still we need to perform final cleanups (removing legacy audit logging and graduating api).

Code freeze starts in 5th June, I think we should manage to finish this work. WDYT?

**Comment by tallclair** [comment]
@loburm I merged your updates into the original issue (I couldn't find a way to grant you edit access). I think we should remove the checklists from your comment to reduce confusion. I'm not sure about the GA graduation, but we should be able to get a lot of the other pieces in on time.

**Comment by soltysh** [comment]
Get as much as possible and we can consider graduating in the next release.

**Comment by tallclair** [comment]
Closing as we're passed the 1.11 milestone. 1.12 tracking issue coming soon...
