### ISSUE TITLE
Umbrella issue for OpenAPI v3 related improvements

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#60937]
The client libraries in https://github.com/kubernetes-client are generated from the [OpenAPI spec](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json) that we serve in k/k. Tracking [OpenAPI v3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) related issues and tooling support around OpenAPI v3 here:

- Lack of `OneOf` support for types that set `ReturnDeletedObject: true` in their storage configuration: https://github.com/kubernetes/kubernetes/issues/59501

As of today (3/8/2018): 
- [ ] swagger-codegen: [v3.0.0-rc0](https://github.com/swagger-api/swagger-codegen/releases/) only supports `java` and `inflector` languages
- [x] swagger-validator: OAS 3.0 support developed in [2.0 branch](https://github.com/swagger-api/validator-badge/tree/2.0), release date on http://online.swagger.io/validate TBD
- [x] swagger-parser: ~~[v2.0.0-rc3](https://github.com/swagger-api/swagger-parser/releases) still at rc phase~~ is released 4/17/2018

Ref: https://github.com/kubernetes/kubernetes/issues/51163

**Comment by roycaihw** [comment]
/sig api-machinery
/assign

cc @yliaog @mbohlool Please add anything that I missed

**Comment by sttts** [comment]
Can you describe how the given links are connected to v3 support for go-openapi? How do the Java projects relate to a Go library?

**Comment by roycaihw** [comment]
@sttts [kubernetes clients](https://github.com/kubernetes-client) are generated based on openapi spec that we serve in k/k. This issue is tracking:

1. known issues in kubernetes clients that could be solved if we serve openapi v3 in k/k
2. required tooling support around client generation if we start to serve openapi v3 in k/k

**Comment by sttts** [comment]
@roycaihw no, openapi is not used for that.

**Comment by roycaihw** [comment]
@sttts Are you saying serving openapi v3 in k/k may be not related to issues like #59501? AFAIK `kubernetes-client/gen` [uses the openapi spec](https://github.com/kubernetes-client/gen/blob/df8b843fb9621a396677f5c6dbe31103151907c1/openapi/preprocess_spec.py#L302-L303) to generate non-go clients such as java and python

**Comment by sttts** [comment]
> Are you saying serving openapi v3 in k/k may be not related to issues like #59501?

I think this was a misunderstanding. The clients in the kubernetes-client use OpenAPI, the Go clients in k/k itself don't.

**Comment by roycaihw** [comment]
@sttts Updated the first comment

**Comment by vosmith** [comment]
Hi @roycaihw , does this include upgrading to using the `enum` property in the specs?

For objects like the `io.k8s.api.core.v1.Container.ImagePullPolicy` the type is `string`, which could benefit from stricter definitions.  I just had a case where the `ImagePullPolicy` was set to `always` instead of `Always` which passed the yaml lint check, but failed to deploy.

**Comment by roycaihw** [comment]
@vosmith I think `enum` is supported in openapi v2. Please refer to discussion in https://github.com/kubernetes/kubernetes/issues/24562. The improvement is tracked in https://github.com/kubernetes/kubernetes/issues/25716. 

Currently in kubernetes we use openapi v3 spec in CRD validation schema where `enum` is also used.

**Comment by vosmith** [comment]
@roycaihw thank you!

**Comment by yue9944882** [comment]
do you have a timeline for supporting openapi v3 yet?

**Comment by lsowen** [comment]
Looks like swagger-codegen has released [v3.0.14](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.14), which supports a bunch of languages.  @roycaihw do you think this release is sufficient to push this forward?

**Comment by roycaihw** [comment]
@lsowen Thanks. That's great news. @p0lyn0mial is working on a [KEP](https://github.com/kubernetes/enhancements/pull/1263) for kubernetes openapi v3 support. Most of our [clients](https://github.com/kubernetes-client) have migrated to use [openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

IMO the generator/tooling is not blocking our clients any more. @yue9944882 has an issue that summarizes v3 spec requirements https://github.com/kubernetes/kubernetes/issues/79472. Let's close this one and track the issue there.

/close
