### ISSUE TITLE
pvc volumes used with subPath volume mounts don't support reconstruction

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#61372]
**Fix status:**
- [x] fixed in master in https://github.com/kubernetes/kubernetes/pull/61373
- [x] fixed in release-1.10 branch in #61518, will be in 1.10.0
- [x] fixed in release-1.9 branch in #61519, will be in 1.9.7
- [x] fixed in release-1.8 branch in #61520, will be in 1.8.11
- [x] fixed in release-1.7 branch in #61521, will be in 1.7.16

In SubPath fixes, PR https://github.com/kubernetes/kubernetes/pull/61044 adds bind mount for subpaths. It uses `/var/lib/kubelet/pods/<uid>/volume-subpaths/<volumename>` as the path name. The volumename in this path is the container's mount volume name which is also called OuterVolumeSpecName in [operation_executor.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go#L476).

This becomes an issue for volume reconstruction when kubelet restarts. Volume [reconstruction](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L556) scans the volume directories and recover the InnerVolumeSpecName (which is used to construct pod volume paths). Volume reconstruction has not enough information to recover the OuterVolumeSpecName and figure out which volume it maps to. In case kubelet needs to clean up mounts (it happens when volume spec cannot be reconstructed), it will fail to clean up the subpaths because of lacking the OuterVolumeSpecName.

We think it is better to use InnerVolumeSpecName for volume subPath instead of OuterVolumeSpecName so that volume clean up can work. The issue we might have is that some users might already deploy a cluster with subpath might already [SubPath fix](https://github.com/kubernetes/kubernetes/pull/61044). If the users perform an in-place upgrade, since new version will use InnerVolumeSpecName which might have conflicts with some other older version's OuterVolumeSpecName among different volumes. This change requires clear documentation and communication with the users.

**Comment by jingxu97** [comment]
cc @msau42 @jsafrane @gnufied

**Comment by msau42** [comment]
This impacts reconstruction of PVCs, where the inner and outer names are different.

**Comment by msau42** [comment]
While testing the e2es against a cluster without the fix, I noticed that subsequent pods using volumes failed to start.  My theory is that the unmount volume failed because the subpath was still mounted, and that blocked the volume manager from processing other pods.  But I thought that volume manager is supposed to run the unmount volume operation in a separate thread per volume, so this shouldn't happen.  Need to inspect the code more carefully to confirm the theory.  @jingxu97 could the volume reconstruction refactor have added a unmount volume call in the main volume manager thread?

**Comment by gnufied** [comment]
`cleanupMounts` runs in reconciler's goroutine - so if that function is blocked, it will not be able to process any more volumes. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L412 

Was the problem that `cleanupMounts` failed to unmount volume but got hung/stuck ?

**Comment by msau42** [comment]
I haven't confirmed for sure, but my guess is that unmount volume failed because the subpath was still mounted

**Comment by liggitt** [comment]
moving into the milestone for discussion
/milestone v1.10

**Comment by liggitt** [comment]
/status approved-for-milestone
per discussion in sig-release meeting today

**Comment by liggitt** [comment]
Re-opening to track fixes in release branches

**Comment by liggitt** [comment]
keeping in the v1.10 milestone until #61518 merges

**Comment by jberkus** [comment]
since this is now fixed in 1.10, I'm taking it out of the milestone so that the release team doesn't keep checking it.

**Comment by jsafrane** [comment]
Can this issue be closed now?
