### ISSUE TITLE
Kubectl refactorings umbrella issue

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#61471]
There are several items in kubectl that needs cleaning. This umbrella issue will hopefully allow to have a single place to point to all of them.

Tasks:
- [ ] server side print default in `kubectl`
- [ ] unify printers ([proposal](https://docs.google.com/document/u/1/d/19ZZFVe9oD1KQmk5uExggRWtRl_hKGfYnBXvHZJlgEro/edit?usp=sharing)) #61304
- [ ] all commands should use struct to hold their values (#60366)
- [ ] clean generators
- [ ] factory cleanup

**Comment by zjj2wry** [comment]
@soltysh i can help clean generators，we want to remove some old versions generators?

**Comment by soltysh** [comment]
@zjj2wry we need to discuss that during our next sig call to agree on the actual details.

**Comment by Lion-Wei** [comment]
@soltysh I will be glad to help on this work. : )

**Comment by soltysh** [comment]
@zjj2wry @Lion-Wei let's sync on slack as soon as @juanvallejo and I get the initial printers work done.

**Comment by soltysh** [comment]
@juanvallejo I think we've handled all of the stuff from the list. I've removed generators, since they will be handled in the next release. If you feel like there's something else missing lemme know, I'm closing as is.
