### ISSUE TITLE
subPath volume mount umbrella issue

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#61563]
This issue is tracking the status of the fixes for functional regressions related to the design change required to address [CVE-2017-1002101](https://github.com/kubernetes/kubernetes/issues/60813).

- [x] #61076: subPath volume mounts cannot be used with secret, configmap, projected, or downwardAPI volumes. *Fixed in 1.10.0, 1.9.5, 1.8.10, and 1.7.15*.
- [x] #61178: cleanup of subPath volume mounts, and setup of subPath volume mounts when restarting a container does not work properly. *Fixed in 1.10.0, 1.9.5, 1.8.10, and 1.7.15*.
- [x] #61283: subpath mounts in pods using fsGroup do not have set-GID bits set properly. *Fixed in 1.10.0, 1.9.7, 1.8.11, 1.7.16*.
- [x] #61372: volume reconstruction does not work with persistent volumes mounted via subPath. *Fixed in 1.10.0, 1.9.7, 1.8.11, 1.7.16*.
- [x] #61377: special types of files, such as unix sockets, cannot be mounted via subPath. *Fixed in 1.10.1, 1.9.7, 1.8.11.*
- [x] #62752: CreateContainerConfigError : failed to prepare subPath for volumeMount (possibly only for readOnly volumes). *Fixed in Kubernetes v1.8.14+, v1.9.9+, v1.10.4+*.
- [ ] #61446: volume reconstruction does not work with host path volumes mounted via subPath. *No immediate plans to address.*
- [ ] #61545: subpath mounts nested within atomic writer volumes (configmap, secret, downwardAPI, projected) do not work. *No immediate plans to address.*

/sig storage
/kind bug
/priority critical-urgent
/assign @msau42 @jsafrane @saad-ali @childsb

**Comment by vrubiella** [comment]
We are upgraded to the last stable version 1.9.7.

Now, is not possible mount/inject only one file without affected other files in a directory?

If I use subPath with fileName "caused \"not a directory\"" error is raised.

There are no solutions for this problem jet?. I'm reading a lot of related issues and try different examples with no success.

**Comment by pawelprazak** [comment]
is #63045 related?

**Comment by msau42** [comment]
@pawelprazak yes, but actually, that fix caused another regression, which has been fixed by https://github.com/kubernetes/kubernetes/pull/64351

**Comment by msau42** [comment]
We do not plan to address the two remaining issues in the near term:
#61446: volume reconstruction does not work with host path volumes mounted via subPath.  We eventually hope to address this by refactoring volume reconstruction to use kubelet checkpointing.  
#61545: subpath mounts nested within atomic writer volumes (configmap, secret, downwardAPI, projected) do not work.  Fixing this would require an api change to tell kubernetes whether to create a file or directory.  It's unclear whether this use case is common enough to warrant such a change, or if the workarounds are sufficient.
