### ISSUE TITLE
client-go credential providers 1.11 umbrella issue

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#61796]
/sig auth
/kind feature

Work to be done for the "External client-go credential providers" (https://github.com/kubernetes/features/issues/541) feature over the 1.11 release cycle.

(note: this feature will be modified throughout the release)

## Features
- [x] Support for TLS client certs https://github.com/kubernetes/kubernetes/issues/61421 (possibly @awly)
- [x] promote API to v1beta1 https://github.com/kubernetes/kubernetes/pull/64482

## Documentation
- [x] Clarify that expirationTimestamp causes the token to be cached in-process,  not written to disk. (@rajatjindal) (PR https://github.com/kubernetes/website/pull/7881)

**Comment by awly** [comment]
We had no issues developing for this API in https://github.com/kubernetes/cloud-provider-gcp/tree/master/cmd/gke-exec-auth-plugin and would like to see exec plugins promoted to Beta for 1.11 (w/ TLS support, if that makes it in)

**Comment by ericchiang** [comment]
Around discussion of this going beta.

Main concern with the existing implementation is the way the plugin is passed arguments.

```
KUBERNETES_EXEC_INFO='{
  "apiVersion": "client.authentication.k8s.io/v1alpha1",
  "kind": "ExecCredential",
  "spec": {
    "interactive": true
  }
}'
```

https://github.com/kubernetes/kubernetes/blob/82b355edf68db9e9955134dea0e54892ca5febca/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L235-L241

cc @awly 
cc @nckturner

Have implements found this to be an issue? Has this worked for windows users? If not, I'm for promoting this feature to beta.

**Comment by awly** [comment]
We used flags to pass arguments:
https://github.com/kubernetes/kubernetes/blob/82b355edf68db9e9955134dea0e54892ca5febca/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L244
https://github.com/kubernetes/cloud-provider-gcp/blob/master/cmd/gke-exec-auth-plugin/main.go#L19

Not an issue in our case.

**Comment by awly** [comment]
Oh, and the json request struct doesn't have any useful information for us
so we just ignore it.
I'm not sure there's any reason to have it.

**Comment by nckturner** [comment]
We don't have an issue with the environment variable either, we also currently don't use it either.  We do use kubectl's stdin for MFA auth, sending the prompt from the sdk to stderr.  

https://github.com/heptio/authenticator/blob/226f7ba533fe746d3a501fbeb1a0195d4696a5d5/pkg/token/token.go#L151

**Comment by liggitt** [comment]
> we also currently don't use it either. We do use kubectl's stdin for MFA auth, sending the prompt from the sdk to stderr.

are you able to reliably detect whether the invocation is interactive without using the info passed down via the envvar, so you don't block a non-interactive invocation with a prompt?

**Comment by ericchiang** [comment]
One more data point: a Red Hat initiative to integrate the exec plugin with kinit also doesn't use the input struct.

cc @patriot1burke if you want to expand at all

**Comment by patriot1burke** [comment]
"kcinit" not "kinit"...Maybe its a bad name :) ??!

https://github.com/keycloak/kcinit

**Comment by patriot1burke** [comment]
@ericchiang @awly @liggitt  We don't use input struct right now only because we don't support non-interactive mode.  Like Jordan, I also am wondering how interactive mode can be detected without the input struct.

I'm kind of unfamiliar with your doc structure.  Here's the

**Comment by patriot1burke** [comment]
Latest docs on this stuff?  Only link I have is:

https://github.com/kubernetes/website/pull/7648/files?short_path=8198851#diff-81988518a0a2049d5e8b98d3a542e98b

**Comment by Fedosin** [comment]
@ericchiang 

> Has this worked for windows users? If not, I'm for promoting this feature to beta.

I like your style :)

Actually everything works as expected for OpenStack! So I am inclined to promote the feature to beta.

**Comment by patriot1burke** [comment]
One concern/thought I had was how is this exec mode better than doing:
$ alias kubectl='kubectl --token=$(mytokengenscript)'

Isn't that simpler to set up than exec mode?

**Comment by Fedosin** [comment]
@patriot1burke As far as I understand, tokens will not be cached in this case, since we do not know their expiration date.

**Comment by Fedosin** [comment]
@patriot1burke I mean that if you explicitly specify a token as 'kubectl --token=some_token' then the plugin will immediately send a request without caching the token: https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go#L169

But if we use 'exec' mode then the token will be cached and the expiration date will also be stored.

**Comment by liggitt** [comment]
> $ alias kubectl='kubectl --token=$(mytokengenscript)'
> 
> Isn't that simpler to set up than exec mode?

that puts credentials in the process invocation, which isn't desired

**Comment by patriot1burke** [comment]
@Fedosin 

Our plugin is actually not specific to Kubernetes and is a generic utility for obtaining tokens using openid-connect (OAuth) and our IDP.  We cache tokens locally and manage expiration and refresh within the tool itself.   We actually store refresh tokens locally along with the access token as well as any other metadata that was returned by OAuth.  I would think that any OAuth authN integration would have to manage refresh tokens locally as well.  Additionally, we need to manage tokens ourselves because other CLI applications might be "reusing" the tokens (think cli sso).  Finally we also have the concept of "logout". 

I'm starting to believe that at least for us, this exec plugin is redundant?  If our tool is managing token lifecycle maybe we're better off just recommending the alias approach?

**Comment by nckturner** [comment]
@liggitt I'm not sure that we can reliably detect it, the AWS sdk will probably try to prompt regardless if the session is interactive or not if it detects that the role it is trying to assume requires MFA.  I haven't tested this though.  Sounds like there could be some improvement there.

**Comment by ericchiang** [comment]
@nckturner the exec'd command should be able to detect if it's part of an interactive session with a TTY check. Stdin is connected directly to the spawned process. See https://gist.github.com/ericchiang/4f8a99e7ad072f932a40d45ad499c347

If no one is using the input, maybe we should drop it for beta then re-introduce it as needs come up?

**Comment by nckturner** [comment]
Thanks @ericchiang, I'll try that.

**Comment by awly** [comment]
FYI, there's also a more official https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal

**Comment by awly** [comment]
ping @ericchiang 
Can we drop the input and promote exec plugins to Beta before 1.11 freeze?

**Comment by awly** [comment]
Looks like this can be closed now @ericchiang ?

**Comment by ericchiang** [comment]
@awly yep. Thanks for everyone's help through this release!

/close

**Comment by ericchiang** [comment]
(I'll be opening a docs RP in a bit for all the features that made it into 1.11)
