### ISSUE TITLE
CRD validation umbrella issue

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#62323]
We are trying to use CRD validation feature . But many things don't work or partially work. I would like to see these issues fixed before CRD is considered GA.

- [x] CustomResourceDefinitions should support maps in OpenAPI schema (#59485)
- [x] Generator for CRD Validation Schema (#59154) - see https://github.com/kubernetes/kubernetes/issues/59154#issuecomment-460990831
- [x] openapi-gen lacks support for enum (#62325) - the CRD schema allows defining enums. feature requests against openapi-gen should be made in https://github.com/kubernetes/kube-openapi/issues
- [x] ~~go-openapi/spec3 is not maintained (#62326)~~ k8s does not use this library
- [x] Generate valid openapi spec for intstr.IntOrString (#62329) - int-or-string is special-cased in CRD schemas and can produce valid openapi v3. see IntOrString discussion in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md#formal-definition
- [x] ObjectMeta openapi3 spec is invalid for CRDs (#66899) - addressed by `x-kubernetes-embedded-resource: true` extension in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md#formal-definition
- [ ] CRD validation resource immutable (#65973)

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/kubernetes/issues/58682

**Comment by nikhita** [comment]
@tamalsaha Can you update the list? The first point is done! :tada:

**Comment by wenjiaswe** [comment]
cc @mbohlool

**Comment by nikhita** [comment]
@tamalsaha can you add https://github.com/kubernetes/kubernetes/issues/65973 to the list?

**Comment by tamalsaha** [comment]
Done.

**Comment by nikhita** [comment]
@tamalsaha thank you!

**Comment by nikhita** [comment]
Just had a conversation with someone on the #kubernetes-novice channel on Slack about how it is not possible to make sure that each custom resource using a CRD has a unique value for that field.

Adding this comment here so we have a way to put it down someplace instead of creating a new issue...because this is "expected behaviour" since OpenAPI schema does not support it.

**Comment by roycaihw** [comment]
discussion around CR metadata validation behavior: https://github.com/kubernetes/kubernetes/issues/74620

**Comment by liggitt** [comment]
only `CRD validation resource immutable` (#65973) remains, closing this umbrella issue in favor of that single issue, which is also tracked in https://github.com/orgs/kubernetes/projects/28
