### ISSUE TITLE
Moving ImageLocalityPriority as a default priority

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#63842]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

`ImageLocalityPriority` has been implemented for quite a while (PRs: #18248 #20140). But due to scheduler cache is not ready at that time, this priority is not enabled by default considering the potential performance impact. See: https://github.com/kubernetes/kubernetes/pull/20140#discussion_r51342913

I think we can move this priority to default now. If anyone has concerns, please let me know. 

I will use this issue as a tracker.
 
The tasks in my mind includes:
- [x] Refactor the implementation with scheduler cache #63345 #63528 
   - We have a [benchmark report](https://docs.google.com/document/d/1dxmQ9yDwW2NXlFu82_w4KrOsPeekj_07Zoui12Cpv20/edit#) by @silveryfu , I believe the performance concern has been addressed
- [ ] Fix inconsistency with CRI runtime #63354 (Not the target for 1.12)
- [x] Enabled this feature by default and include Integration tests ~~and e2e tests~~ #68081 

**Anything else we need to know?**:

I would suggest 1.11 or 1.12 as the target release.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
how much improvement do we expect to get?

**Comment by silveryfu** [comment]
In terms of (performance) improvement, there are two pertinent questions here:

1. Scheduling overhead, _i.e._, how long it takes to schedule a pod, with vs. without image_locality;

2. How much performance improvement does image_locality enable (e.g., pod startup latency).

For 1., the patched implementation of image_locality, when enabled, is shown to have similar if not the same scheduling latency as when enabling only current default policies.

For 2., the significance of an improvement depends on the use case and workloads (e.g., how many images are used, arrival pattern etc.) - but if we just look at a single image reuse, the performance saving is substantial (tens of seconds in pod startup latency, plus saving on the rootfs for storing the images). 

Continuing the discussion, if there were no improvement or added values to image_locality, there would be no strong need to add complexity and features to the scheduling logic; plus, users can use affinity policy to set up pod-node affinity to address the image locality as well - so _it's a matter of "whether k8s should embed the affinity by default" vs. "whether k8s should let users themselves decide how to leverage the image locality."_ - current non-default setup leaves the flexibility to users, which makes sense.

On the other hand, _kube-scheduler is really sitting at the vantage point to address the pod-to-node image locality, automatically and correctly, and it seemingly does no harm to the scheduling performance._ 

Hence, it could be a nice **default** feature to have :)

**Comment by bsalamat** [comment]
> I think we can move this priority to default now. If anyone has concerns, please let me know.

It looks to me that the priority function is enabled by default. Am I missing something:
https://github.com/kubernetes/kubernetes/blob/2a989c60ff97445d3ca10234a368730f089adac7/pkg/scheduler/algorithmprovider/defaults/defaults.go#L100

**Comment by silveryfu** [comment]
@bsalamat I think the proposed is to move image locality to defaultPriorities(); whereas currently the policy can be enabled through --policy-configmap or file [#41600](https://github.com/kubernetes/kubernetes/issues/41600), which is arguably more "by default."

**Comment by k82cn** [comment]
sorry for the delay :(, just share my two concerns:

1. `image_locality` dependents on several factors that out of k8s control, e.g. network speed, disk I/O, docker image FS, total images in nodes and so on; that makes it hard to evaluate its performance improvement
2. if enabled `image_locality`, we'll also add it to eCache which adding a new checking on images changes

If we enabled this by default, I'd suggest to make it configurable in eCache as it dependents on user's environment/deployment.

**Comment by k82cn** [comment]
>> if enabled image_locality, we'll also add it to eCache which adding a new checking on images changes

> @k82cn Image locality is a priority function. eCache is used for predicates.

Ops, I'm thinking `But due to scheduler cache is not ready at that time` is referring to eCache :), so just ignore it that.

**Comment by resouer** [comment]
@bsalamat @k82cn Thanks for input! 

I will try to mentor and lead this feature ahead. cc @silveryfu Let's move on.

**Comment by silveryfu** [comment]
Subtasks of integration test:
- [ ] integration/scheduler createImageLocalityPod and nodes with image locality
- [ ] priorities_test
- [ ] scheduler_perf

Subtasks of e2e test:
- [ ] e2e framework createImageLocalityPod for reserving image locality on nodes
- [ ] e2e priorities

**Comment by resouer** [comment]
@bsalamat This issue also needed to be approved for 1.11 milestone.

**Comment by k82cn** [comment]
/status approved-for-milestone

As we sync up in last meeting, we'd like to get this done in 1.11 :)

**Comment by resouer** [comment]
As #68081 is in, this feature is no on track for 1.12 release.

**Comment by k82cn** [comment]
@resouer , @silveryfu , would you help to list related PRs to this issues, e.g. doc, enabled pr? The referred PRs are test related :)

**Comment by k82cn** [comment]
And should we close this issue?

**Comment by guineveresaenger** [comment]
note: i see this may be resolved, but moving it to 1.13 due to timing.

/milestone v1.13

**Comment by bsalamat** [comment]
> note: i see this may be resolved, but moving it to 1.13 due to timing.

@guineveresaenger The main part of this feature, which is to enable ImageLocalityPriority by default is already merged and shipped with 1.12.

**Comment by resouer** [comment]
> would you help to list related PRs to this issues, e.g. doc, enabled pr? The referred PRs are test related :)

@k82cn Please check the description of this issue they are already listed there :-)

And as Klaus suggested, I will close this issue to avoid future confusing, bug fixes and compatibility fixes can be tracked with seperated issues, e.g. #64413.

Also, @silveryfu & me are also designing image layer locality based scheduling (as @k82cn suggested before), should be a good candidate for upcoming releases.
