### ISSUE TITLE
[Umbrella issue] Plugin Watcher Work Tracker

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#65773]
This issue is meant to track and discuss planned work items for the plugin watcher API across releases.
 
This is not finalized yet. This issue will be updated once the community agrees to the different features and schedule.

The original design document [is here](https://docs.google.com/document/d/1dtHpGY-gPe9sY7zzMGnm8Ywo09zJfNH-E1KEALFV39s)

## v1.11: Done
- [X] Implement the pluginwatcher base code (PR #63328) [owner: @vikaschoudhary16]
- [X] CSI driver registration uses pluginwatcher (PR #64560) [owner: @sbezverk]

## v1.12 Must have
- [X] Add support for plugin directory hierarchy (PR #64660) [owner: @figo]
- [X] Use pluginwatcher in Device Manager (PR #58755) [owner: @vikaschoudhary16]
- [X] Change pluginwatcher interface (PR #64621) [owner: @RenaudWasTaken]
- [X] Add de-register method (issue: #64637) [owner: @RenaudWasTaken]
- [X] Allow the pluginwatcher lifecycle to do zero downtime upgrade (issue: #65772) [owner: @RenaudWasTaken]
- [X] Handling re-registration (issue: #65770) [owner: @RenaudWasTaken]
- [x] Update the pluginwatcher API to beta [owner: @RenaudWasTaken]
- [x] Remove feature gate [owner: @RenaudWasTaken]
- [x] Add a design doc (PR: kubernetes/community#2369) [owner: @vikaschoudhary16]

## v1.13 Must have

- [x] Gather a list of e2e tests and make sure the code coverage is high
- [x] Gather a list of production workloads and experience using the feature
- [ ] Scale tests experiences
- [x] Plugin watcher getting notified of every Kubelet directory event (Issue: kubernetes/issues/69015) [owner: @RenaudWasTaken]
- [x] Graduate to G.A

## v1.14 and onward Must have

- [ ] Design a mechanism that protect against a device plugin flooding the API [owner: *TBD*]
- [ ] Implement the flooding protection mechanism [owner: *TBD*]
- [ ] Design and gather Security/authentication requirements [owner: *TBD*]
- [ ] Implement Security/authentication [owner: *TBD*]

/sig node
/cc @vikaschoudhary16 @figo @sbezverk @saad-ali @vladimirvivien @jiayingz 

Feel free to add anyone I might have forgotten and to add some feature. I'll update this PR regularly

**Comment by vikaschoudhary16** [comment]
created PR for moving design from gdoc to community repo: https://github.com/kubernetes/community/pull/2369

**Comment by jiayingz** [comment]
@RenaudWasTaken  thanks a lot for filing this work tracker!

Some items we may also add to 1.2 or 1.3 releases may include:
- Adding design doc. I think Vikas already has a PR for this.
- Some e2e test plan. For device plugin, I think we also would like to get upgrade/downgrade parts well tested before enabling the feature by default.
- Handling fsnotify watcher errors.

Personally, I also would like to see flood protection be handled earlier, although not sure whether we should consider it a beta blocker.

**Comment by RenaudWasTaken** [comment]
@jiayingz do you mind creating an issue for handling fsnotify watcher errors and the e2e tests?
I've added the tasks to the tracker.

**Comment by jiayingz** [comment]
For fsnotify error, filed https://github.com/kubernetes/kubernetes/issues/66802

@vikaschoudhary16 had already added the test coverage for probe based mode in e2e_node device_plugin test. I filed https://github.com/kubernetes/kubernetes/issues/66803 for gpu based device plugin e2e test. Ideally, we want to add the e2e test coverage with a stub device plugin, but that would depend on the long pending work on implementing a stub device plugin based e2e test.

**Comment by vladimirvivien** [comment]
Is this feature targeting Beta anytime soon ? If not, what is missing ?

**Comment by vladimirvivien** [comment]
@RenaudWasTaken can you clarify here which of the followings will make it to 1.13 and thus graduate to GA ?

 > [ ] Add e2e tests plan [owner: @vikaschoudhary16 and / or @jiayingz]
  [ ] Design a mechanism that protect against a device plugin flooding the API [owner: TBD]
  [ ] Design and gather Security/authentication requirements [owner: TBD]

As we discussed #2 an #3 will come later right ?
