### ISSUE TITLE
Promote ScheduleDaemonSetPods to Beta in 1.12

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#66526]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description:**

The feature `ScheduleDaemonSetPods` was in alpha phase in 1.11.
In discussion of https://github.com/kubernetes/features/issues/548, it's agreed to promote this feature to beta in 1.12.

**Tasks:**

- [x] Update `ScheduleDaemonSetPods` to be beta in kube_features.go (#67899)
- [x] Added unschedulable and network-unavailable toleration. (#64954)
- [x] Remove rescheduler once scheduling DS pods by default scheduler moves to beta (#64725)
- [x] DaemonSet with node affinity for "dynamic" labels only works with one candidate value (#66298)
- [x] Pending pod scheduled onto master node when `ScheduleDaemonSetPods` is enabled (#66348)
- [x] [1.12] potential impact on kubeadm after enabled `ScheduleDaemonSetPods` (#66831)
- [x] daemonset pods not scheduled to cordoned node (#67845)
- [x] Release notes and doc (https://github.com/kubernetes/website/pull/9923)

**Links:**

- Design Doc: kubernetes/community#1714
- Feature: kubernetes/features#548
- Alpha Items: #59194

**Comment by Huang-Wei** [comment]
@k82cn @bsalamat ^^

**Comment by zparnold** [comment]
@Huang-Wei Hey there! I'm the wrangler for the Docs this release. Is there any chance I could have you open up a docs PR against the `release-1.12` branch as a placeholder? That gives us more confidence in the feature shipping in this release and gives me something to work with when we start doing reviews/edits. Thanks!

**Comment by Huang-Wei** [comment]
@zparnold thanks for the reminder. I've just created a placeholder here: https://github.com/kubernetes/website/pull/9923.

**Comment by zparnold** [comment]
Thanks!

**Comment by Huang-Wei** [comment]
Close this as all items have been completed.
