### ISSUE TITLE
[Umbrella issue] Quota Support For Priority-Class Work Tracker

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes/kubernetes#66673]
This issue is meant to track and discuss planned work items for the quota support for priority classes across  releases.
This list is not final. This issue will be updated and iterated over to add any missing items.

## v1.11 Done:
- [X]  Implement quota support for priority classes as alpha feature(https://github.com/kubernetes/kubernetes/pull/57963)
- [X] Fix an issue related to quota sync (#64750)
- [X] Add documentation (https://github.com/kubernetes/website/pull/9086)

## v1.12 Must Have:
- [ ] Graduate quota configuration API (PR #66156)
- [ ] Add unit tests to cover scope selectors (PR #66351)
- [ ] Add integration tests to cover scope selectors
- [ ] Graduate scope selectors to beta

/cc @bsalamat @derekwaynecarr @ravisantoshgudimetla @aveshagarwal @sjenning

**Comment by ravisantoshgudimetla** [comment]
Great job. Thanks Vikas :).
