### ISSUE TITLE
[Umbrella Issue] Authz & Core admission controller clientset/informer refactor internal->external

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#66680]
Leave the discussion open here :) 

We want to use external clientset / informers inside admission controllers instead of the internals. With the help of this, the admission check would be done by using external types as auxiliary types for 
 admitting internal types in the admission check. Basically the refactor of this part would be following the "defacto" that:

- if we are consuming some object => use external types
- if we are serving/handling some object => use internal types

So far we are already on the way of do the same refactoring for `kubectl`. Though we are not gonna apply the refactor to the admission controllers except for `Initialization`,`NamespaceLifeCycle`,`*Webhook`, etc. which are already refactored. The change for core admission controllers might still be necessary in the future. 

Literally, I'm a fan of the idea that refactoring throughout "internal->external" so that the lumping codes in this repo could be decoupled into more extensible parts. 😃

/cc @deads2k @sttts @soltysh 
/cc @adohe @dixudx

---

Admission Controller View:

- [x] ~`NodeRestriction` (node) externalization #67116~
- [x] ~`DenyEscalatingExec` (exec) externalization #67831~
- [x] ~`LimitRanger` externalization #67696~
- [x] ~`NamespaceAutoProvision/NamespaceExists` externalization #69133~
- [x] ~`PodNodeSelector` externalization #70167~
- [x] ~`PodPreset` externalization #67810~
- [x] ~`PodTolerationRestriction` externalization #70167~
- [x] ~`Priority` externalization #67842~
- [x] ~`ResourceQuota` externalization #67870~
- [x] ~`PodSecurityPolicy` externalization #67846 #69685~
- [x] ~`ServiceAccount` externalization #67576~
- [x] ~`DefaultStorageClass/StorageObjectInUseProtection` externalization #67194 #67704~

---

Resource Dependency View:

- [x] ~Pod: `NodeRestrction`, `NodeAuthorizer` #67116~ 
- [x] ~Node: `NodeAuthorizer` #67497~
- [x] ~PV: `NodeAuthorizer`, `StorageObjectInUseProtection` #67194~
- [x] ~VolumeAttachment: `NodeAuthorizer` #58462~
- [x] ~LimitRanger: `LimitRanger` #67696~
- [x] ~Namespace: `PodNodeSelector`, `PodTolerationRestriction` #70167~
- [x] ~PodPreset: `PodPreset` #67810~
- [x] ~PriorityClass: `Priority` #67842~
- [x] ~ResourceQuota: `ResourceQuota` #67870~
- [x] ~PodSecurityPolicy: `PodSecurityPolicy` #67846 #69685~
- [x] ~Secret: `ServiceAccount` #67576~
- [x] ~ServiceAccount: `ServiceAccount` #67576~
- [x] ~StorageClass: `DefaultStorageClass` #67704~
- [x] ~PVC: `StorageObjectInUseProtection` #67194~
- [x] ~RBAC*: `RBACAuthorizer` #63967~

**Comment by deads2k** [comment]
I think that using external clientsets, informers, and listers makes sense inside of admission.  The admission attributes would remain the same, but the external looks up made would be external.  For example, things like the the limitranger would use an external client to look up the list of limit ranges.

**Comment by dixudx** [comment]
Agree with @deads2k.

Thanks @yue9944882 for such a refactoring. Current k/k admissions use internal clientset/informers. While k/apiserver admissions use external. It's better to have them on a same basis. After such refactoring, we may not need to auto generated internal version clientsets and informers any more.

**Comment by yue9944882** [comment]
Updates, will apply this changes across admission controller and authorizers and propagate this changes by resource types.

**Comment by yue9944882** [comment]
@xmudrii thanks for helping! 😉

i'd strongly recommend u to get start with `podSecurityContext`. i got some unready changes on my local branch:

- `exec`: https://github.com/yue9944882/kubernetes/tree/refactor/exec-externalize
- `priority`: https://github.com/yue9944882/kubernetes/tree/refactor/externalize-priority-class-admission-controller

they're yet untested and might be buggy. would u mind continuing with them too based on my previous work?

**Comment by yue9944882** [comment]
> i'd strongly recommend u to get start with podSecurityContext.

revert that. it'll be a XXL one again 🙃
