### ISSUE TITLE
Dry-run: Path to GA

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#68514]
This is describing the steps necessary to move [Dry-run](https://github.com/kubernetes/features/issues/576) to Beta.

These are the list of features and bugs that need to be addressed before Dry-run can move to GA.

Please cross-out (do not remove, please) whichever does not seem appropriate for moving to GA and put your name behind it. If you want to add any notes specific to a task, please list it as a bullet point and again, put your name behind it.

## Features

- [x] Beta: Change flag from Alpha to Beta and default to enable #69644 @apelisse 
- [x] Beta: Update [documentation](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/using-api/api-concepts.md) @apelisse 
- [x] GA: Add prometheus metrics for dry-run (#74997, needs to be cherry-picked to 1.13)
- [x] GA: #68839 Change default for SideEffect in admissionregistration Webhook @apelisse
- [x] GA: Implement consistent server-side "dry-run" flag on Kubectl @julianvmodesto #85652 https://github.com/kubernetes/enhancements/pull/1399
- [x] ~GA: Add dry-run support in client-go @apelisse~ @lavalamp 
- [x] GA: Document dry-run requires write access (and so does kubectl diff as a consequence)

## Bugs

- [x] pods/eviction does not honor `dryRun: true`option #76943: #76969
- [x] cherry-pick #76969 to 1.13 and 1.14

## Tech Debt

- [ ] Create an integration test suite for dry-run sub-resources #76971

**Comment by apelisse** [comment]
Let's finish these two tasks and close that issue. Planned for 1.18.

**Comment by lavalamp** [comment]
I think that hasn't been true since 1.11?

**Comment by apelisse** [comment]
Correct, https://github.com/kubernetes/kubernetes/commit/98613924ea282ef70a6f9a14dda11e854fe02c28. 

It's two year old, and I don't think we do support these versions anymore (security patch etc, AFAIK).

**Comment by julianvmodesto** [comment]
Doc tasks:
- https://github.com/kubernetes/kubernetes/issues/83562
-https://github.com/kubernetes/kubernetes/issues/68514

**Comment by julianvmodesto** [comment]
I don't think `kubectl scale --dry-run` is blocking GA, so we seem covered here for addressing features, bugs, and testing before code freeze and only have the docs left.

**Comment by julianvmodesto** [comment]
Actually one last change to merge: https://github.com/kubernetes/kubernetes/pull/88133

**Comment by apelisse** [comment]
Only thing left now is updating the documentation.

**Comment by julianvmodesto** [comment]
Looks like we're done here!

Follow ups are being tracked in these issues:

-  umbrella https://github.com/kubernetes/features/issues/576
- https://github.com/kubernetes/kubernetes/issues/76971
- https://github.com/kubernetes/kubernetes/issues/88740

**Comment by apelisse** [comment]
Sweet!
