### ISSUE TITLE
Kubectl Diff path to GA

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#68526]
This is describing the steps necessary to move [kubectl diff](https://github.com/kubernetes/features/issues/491) to Beta and GA.

These are the list of features and bugs that need to be addressed before `kubectl diff` can move to beta and GA.

Please cross-out (do not remove, please) whichever does not seem appropriate for moving to Beta/GA and put your name behind it. If you want to add any notes specific to a task, please list it as a bullet point and again, put your name behind it.

## Features

- [x] Simplify and improve existing interface to be more focused #68525 @apelisse
- [x] Use server-side dry-run to get the merged version, rather than using Phil's code #69162 @apelisse
- [x] Move command out of alpha sub-commands #69167 @apelisse
- [x] Add proper documentation for the command @apelisse
- [x] Find a few places in the documentation where apply is used, and suggest running diff before, to see what will happen @apelisse
- [ ] GA: Document the command other than in the command itself #86525

## Bugs

- [x] Check server version or availability of the dry-run parameter to prevent unwanted changes to the server (old servers might ignore the dryRun parameter). #69449 @apelisse
- [x] Checking dry-run availability isn't done on "create" path #69745 @apelisse 
- [x] Return errors from "diff" are ignored, including if diff(1) doesn't exist #69742 @apelisse 
- [x] `KUBERNETES_EXTERNAL_DIFF` should be renamed `KUBECTL_EXTERNAL_DIFF` #69742 @apelise
- [x] When using dry-run patch, we need to patch against the same specific resourceVersion of the object, or it might diff two different version #71156 @apelisse

## Tech Debt

- [x] Change the way options are created #72204 (suggested by @soltysh)
- [ ] Add more tests in `test-diff.sh` (suggested by @soltysh)
- [x] Test that it works fine against CRDs

**Comment by guineveresaenger** [comment]
Hi @apelisse - I'm Enhancements Shadow for 1.13. Could you please update the release team with the likelihood of this enhancement making the 1.13 release? It looks close but when we don't see any updates in a few days, we would appreciate an update.

Code slush begins on 11/9 and code freeze is 11/15.

Thank you!

**Comment by apelisse** [comment]
Hi @guineveresaenger, this feature is pretty much ready, which is why I don't look super active here :-)

**Comment by zx8** [comment]
@apelisse I've found what I think is a bug:



```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

$ helm template . | kubectl alpha diff -f - MERGED
error: missmatching non-nil types for the same field: float64 int64
```

Not sure how to diagnose this. Anything I can do to help figure out the issue?

**Comment by apelisse** [comment]
Hey @zx8, thanks for the feedback! `kubectl diff` beta that is being released right now is significantly different from that version, and so this bug is not very relevant anymore. Please try the new diff version when 1.13 is released and tell me if you like it!

**Comment by zx8** [comment]
Oops, my mistake! I just rebuilt from `master` @ https://github.com/kubernetes/kubernetes/commit/a19bf332de92b523c31980b9a8959e6eccfc6ce4 and am getting:

```
$ helm template . | kubectl diff -f-
error: /v1, Kind=ConfigMap doesn't support dry-run
```

When commenting out the ConfigMap YAML and trying again, I get:

```
$ helm template . | kubectl diff -f-
error: apps/v1, Kind=Deployment doesn't support dry-run
```

I assume this requires the server to be running v1.13+ as well? I don't want to spam this issue with feedback so let me know if this is a legitimate bug and I'll raise it through the appropriate channel.

**Comment by apelisse** [comment]
Right, you need server-side dry-run (https://github.com/kubernetes/enhancements/issues/576) on the server (it's currently alpha so you might be able to try by enabling the feature-gate)

**Comment by julianvmodesto** [comment]
For properly documenting this feature, I've opened https://github.com/kubernetes/kubernetes/issues/86525

**Comment by julianvmodesto** [comment]
We could probably update the dry-run kep w/ a subsection on `kubectl diff` since we need a KEP for the release for this feature

**Comment by apelisse** [comment]
Do we really need a KEP? There is a kep for the feature, is it missing something specific?

**Comment by julianvmodesto** [comment]
Oh nevermind if there's a KEP for the feature already for diff. I was looking at the Enhancements Tracking sheet:

https://docs.google.com/spreadsheets/d/1RtCvByYdcqWc6I_A1cKgeXT2tBS7SyHGvSt_DWXz270/edit#gid=0

**Comment by julianvmodesto** [comment]
Looks like we're good for everything except for https://github.com/kubernetes/kubernetes/issues/87600 before code freeze. I'm going to also check integration tests again, but I feel that there is sufficient overlap with integration tests for dry-run verbs at least for the dry-run specific behavior. Otherwise, we only have a little docs left!

**Comment by apelisse** [comment]
> Otherwise, we only have a little docs left!

Do you know specifically what needs to be updated for the tests?

**Comment by julianvmodesto** [comment]
Hm I want to say we're covered, particularly after you added tests for https://github.com/kubernetes/kubernetes/pull/87437.

**Comment by julianvmodesto** [comment]
This is done!

Follow ups:
- https://github.com/kubernetes/kubernetes/issues/88905

/close
