### ISSUE TITLE
go modules adoption checklist

### ISSUE THREAD

**Issue by sigma** [kubernetes/kubernetes#68577]
/kind feature

**Description**:

This issue is to track the list of issues for a go modules (aka vgo) adoption. The list itself is a work in progress, and will be updated as issues popup or get resolved.

First class of issues: the current godep snapshot of packages is not a valid solution as far as go modules are concerned
- [x] gonum and cadvisor conflict. details in #68478
- [ ] heketi and k/k conflict. details in heketi/heketi#1272

This list needs to be empty to actually perform the migration. Post-migration, the burden will move to the dependency update workflow (similar issues will block the update).

Some more issues are to be expected, due to mainly 2 factors:
- go modules reason about test dependencies in addition to "regular" dependencies, which we currently completely ignore
- a large chunk of our dependencies are not versioned at all, meaning that no semver guarantees apply. It'll be easy to get incompatibilities once our dependencies start using go modules themselves.

Second class of issues: tooling needed
- [ ] it takes a non-negligible amount of effort to convince go to vendor everything we need at the top-level in k/k, given that some of our dependencies are actually only used by our staging sub-projects.
- [ ] since go modules don't track modifications at the sub-package level, we need to maintain Godeps.json files for a while, and there's no official tooling for that.
- [ ] our go modules dependencies need to be kept in sync across k/k and all staging repos.

https://github.com/sigma/vgo-k8s-tools has some (ugly) code to address all these, but is very much a work in progress

Third class of issues: go modules usability
- [ ] *extremely* opaque about what it does, and why. Took me some grepping the cache to understand why golang.org/x/exp was bumped in the first place in #68478. With our kind of dependency graph complexity, lack of clarity is hard to handle.
- [ ] we'll still need some scripting around go modules to maintain our dependency graph. Hopefully that should be after running regular module operations in the main or staging repos.

**Comment by sigma** [comment]
@kubernetes/sig-testing-proposals

**Comment by spiffxp** [comment]
FYI @kubernetes/sig-architecture-proposals

**Comment by bgrant0607** [comment]
cc @thockin @lavalamp @mattfarina

**Comment by lavalamp** [comment]
Excited to have someone looking at this!

**Comment by sdboyer** [comment]
It's worth noting that the path of least resistance (to the module system) will ultimately be to treat each currently-discrete staging repo as its own go module, and abandon the separate staging repos entirely.

ive also been thinking about how useful some kind of declaration would be to automatically treat all imports under a particular root as though there were a local `replace` declaration. As the number of Go modules within k8s increases, this will be increasingly useful, as it will obviate the need to litter replace statements everywhere.

**Comment by sigma** [comment]
a few thoughts:
- I don't know that the organization of the repo is the main issue. I think the higher-level problem is that we need those modules to be kept in sync (in terms of dependency graph) regardless of whether they live in the same repo or not, short of changing our support model. And there's just very little tooling support for doing that right now
- somehow the maintenance of the `replace` directives doesn't worry me so much, as it's one thing that we can pretty easily automate. But sure, a shortcut would be nicer.

**Comment by ixdy** [comment]
Has there been any progress on this? Go modules are likely to become the default in Go 1.13 (August 2019), and given the lifetime of Kubernetes releases, we should probably get ahead of that.

**Comment by ixdy** [comment]
cc @bcmills

**Comment by sigma** [comment]
As far as I'm concerned, I'm still waiting on heketi/heketi#1272 to be merged.

I would add that the difficulty of getting those ducks in a row seems like a systemic problem in the go modules approach. I'm not quite sure the incentives are stacked the right way.

**Comment by andreykaipov** [comment]
Sorry for my ignorance, but as someone fairly new to Go and Kubernetes, what's the problem with just running `go mod init`? I cloned this repo outside my GOPATH, ran `go mod init`, Go found what it needed from the `Godeps`, and boom - `make` worked with no issue and I didn't even cry once. I was shocked it worked so smoothly.

Go modules are experimental in Go 1.11, but would having a `go.mod` and `go.sum` in the root directory of the project really affect anything dependent on just Godep? Why not just add support for it now?

**Comment by BenTheElder** [comment]
> Go modules are experimental in Go 1.11, but would having a `go.mod` and `go.sum` in the root directory of the project really affect anything dependent on just Godep? Why not just add support for it now?

Yes it can affect them, adding a `go.mod`  (previously on accident) broke some tooling that depends on Kubernetes being findable in `GOPATH`, it couldn't query the package location anymore. Many tools in & out of the repo depend on GOPATH pretty heavily unfortunately, we need to disentangle that.

We also shouldn't check it in unless we're going to keep it up to date, so we need to update all the godeps scripts / presubmit(s) and the docs.

We also need to consider the publishing robot for `staging/`, the cross build container, if we will retain vendor/ (and if not if we will run a module proxy to avoid CI flakiness).

We've started using go modules for some other smaller sub-projects, and ran into bugs with the checksums (they _should_ and to seem to be fixed in >= go 1.11.4 now) ... it's probably worth shaking out the issues in these smaller projects first and letting it become stable before we switch the main repo.

**Comment by BenTheElder** [comment]
With go1.12 coming soon it has to be about time, but I don't think we have all of those things figured out just yet.

cc @cblecker @dims

**Comment by sigma** [comment]
> Sorry for my ignorance, but as someone fairly new to Go and Kubernetes, what's the problem with just running `go mod init`? I cloned this repo outside my GOPATH, ran `go mod init`, Go found what it needed from the `Godeps`, and boom - `make` worked with no issue and I didn't even cry once. I was shocked it worked so smoothly.

This is a bit misleading. It seems to work, but builds the wrong thing because staging/ is then ignored as the source of many of the k8s.io packages. Basically this allows `go mod` to reason about a much looser dependency graph, and ultimately claim "victory". When you enforce actual alignment of the dependency graph is when problems above start showing up.

**Comment by munnerz** [comment]
I've opened https://github.com/heketi/heketi/pull/1542 against heketi/heketi that bumps Kubernetes dependencies to client-go 1.10 😄 hopefully that's sufficiently new to have compatibility with the HEAD of kubernetes/kubernetes at the moment, but at the very least it'll make it far easier to bump again in future.

**Comment by liggitt** [comment]
I'm writing up a KEP for the 1.15 release for this here: https://github.com/kubernetes/enhancements/pull/908

I also have a WIP PR that uses `go mod vendor` to rebuild the vendor dir, populates go.mod files for each staging repo as a module.

The biggest unresolved question is what versioning strategy to use for the modules. Options are described in the KEP

**Comment by liggitt** [comment]
Accepted proposal for initial go module support is at https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md

https://github.com/kubernetes/kubernetes/pull/74877 contains the changes needed to reproducibly generate the vendor dir using go modules

https://github.com/kubernetes/publishing-bot/pull/169 is a WIP PR to publish go.mod files for staging component

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/74877 is merged and kubernetes/kubernetes vendoring is now managed using go modules

/close
