### ISSUE TITLE
Revisit and narrow down functionality of equivelance class cache

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#68720]
**Background**

*Pay Your Technical Debt!*

Per discussion [in recent sig meeting](https://docs.google.com/document/d/13mwye7nvrmV11q9_Eg77z-1w3X7Q1GTbslpml4J7F3A/edit#), we noticed the complexity of equiv class cache is growing fast in last 6 mo in order to balance between performance and functionality, and begin to divert from its original design.

The concern is, we are not so sure if this is quite align with the on-going scheduler framework and cleanup design which aim at "slimming" current scheduler to a simple and extensible component.

Thus from 1.12, we would like to do a revisit on this code base and probably narrow down its functionality to a "singleton" feature below (and replace #58222):

> We may consider narrow down eCache to handling pending pods under same controllerRef (or similar equiv class concept). E.g. avoid “failure flood” where pods with equivalent spec are grouped together and the scheduler avoids checking the schedulability of all of them when one is determined unschedulable. This is particularly useful in batch processing.

**Design Doc**

See: https://docs.google.com/document/d/1x907Ow183mHVdmIgBO_BjZA0DPjPnB1lzCRnbBtm1Ks/edit

Per discussion with sig-pm, this is a internal implementation improvement, not a user faced "feature", so no KEP required.

**Implementation plan**

- [x] Task 1: Clean up the old code #71013
- [ ] Task 2: Add concept of "equiv class" in scheduling queue, with unit test covered every queue OP #72677
- [ ] Task 3: Add integration test set to verify this feature until it is beta

**Evaluation**

- [x] Task 4: Evaluate performance impact of new queue implementation above

****

**Anything else we need to know?**:

/kind feature
/kind cleanup

cc @bsalamat @k82cn @misterikkit @msau42 and anyone may be interested in.

**Comment by resouer** [comment]
/assign

Also cc @mayank who trying to help.

**Comment by denkensk** [comment]
I am interested, can I do something with you?

**Comment by k82cn** [comment]
Prefer to get result/output of Task 4 before Task 2 & 3 :)

**Comment by bbarnes52** [comment]
@denkensk could I trouble you to update this issue for posterity?

As far as I can tell, the initial implementation of equivalence classes was removed in https://github.com/kubernetes/kubernetes/pull/71399 and the design described in https://docs.google.com/document/d/1x907Ow183mHVdmIgBO_BjZA0DPjPnB1lzCRnbBtm1Ks/edit#heading=h.41ul1d88aj6c was started in https://github.com/kubernetes/kubernetes/pull/72677 which was never merged. 

Was there any particular reason the redesign was not implemented, or would contributions be welcome here?

**Comment by denkensk** [comment]
@bbarnes52 
The new design was not merged because (maybe....) there were not enough people to help review the code. Do you have similar requirements as described in the design document? Can you describe it in detail? Maybe we can think about restarting it.

**Comment by bbarnes52** [comment]
Thanks for the details @denkensk. We're migrating to Kubernetes and are interested in running clusters larger than 5000 nodes. We're not yet sure where the scaling limit will ultimately come from, I was looking into equivalence classes since it was marketed as a critical feature for scaling Borg.
