### ISSUE TITLE
Scheduler Cleanup

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68951]
This is a tracking issue for the effort to reorganize kube-scheduler's code.

**Goals**
- Improve developer velocity and onboarding.
- Clarify which parts of the scheduler are API and which parts are implementation.
- Improve testability and test coverage.

We want to avoid the situation where two contributors send PRs for the same fix, so please coordinate here or on the linked issues before working on part of this. Discussion about the best way to clean up the scheduler is welcomed.

**Phase 1**

- [x] https://github.com/kubernetes/kubernetes/issues/68954 Create a new Scheduler constructor
- [x] https://github.com/kubernetes/kubernetes/issues/68955 Move informer event handlers to pkg/scheduler
- [x] https://github.com/kubernetes/kubernetes/issues/68956 Move SchedulingQueue to pkg/scheduler/internal/queue
-  <s>https://github.com/kubernetes/kubernetes/issues/68957  Inject `FeatureGate` instead of checking global variable</s> 
   *This task has been deferred until after the scheduling framework is implemented.*
- [x] https://github.com/kubernetes/kubernetes/issues/68958 Move `NodeInfo` utils into pkg/scheduler/cache 
- [x] https://github.com/kubernetes/kubernetes/issues/68959 Move FakeCache to pkg/scheduler/internal/cache/fake
- [x] https://github.com/kubernetes/kubernetes/issues/68960 Move CacheComparer to pkg/scheduler/internal/cache
- [x] https://github.com/kubernetes/kubernetes/issues/68961 Move scheduler cache interface and implementation to pkg/scheduler/internal/cache
- [x] https://github.com/kubernetes/kubernetes/issues/68962 Refactor scheduler_test.go to use a fake k8s client
- [x] https://github.com/kubernetes/kubernetes/issues/68963 Refactor factory_test.go to use a fake k8s client 
- [x] https://github.com/kubernetes/kubernetes/issues/68964 Simplify kube-scheduler’s server.go `run` 
- [x] https://github.com/kubernetes/kubernetes/issues/69138 Move pkg/scheduler/algorithm/well_known_labels.go out

**Phase 2**

- [ ] https://github.com/kubernetes/kubernetes/issues/71859 Move users of `factory.NewConfigFactory` to `scheduler.New` 
- [ ] https://github.com/kubernetes/kubernetes/issues/71860 Flatten Top Level Scheduler Struct
  - **Phase :panda_face:**
  - [x] https://github.com/kubernetes/kubernetes/issues/72543 Move cache debugger setup into a helper function
  - [x] https://github.com/kubernetes/kubernetes/issues/72544 Change `getBinderFunc` from method to function
  - [x] https://github.com/kubernetes/kubernetes/issues/72545 Change `MakeDefaultErrorFunc` from method to function
  - [x] https://github.com/kubernetes/kubernetes/issues/72546 Change `getNextPod` from method to function
  - [ ] https://github.com/kubernetes/kubernetes/issues/72547 Make a Scheduler without configFactory 😱 
- [ ] https://github.com/kubernetes/kubernetes/issues/71861 Simplify Config Processing
- [x] https://github.com/kubernetes/kubernetes/issues/71862 Rename `pkg/scheduler/cache` to `pkg/scheduler/nodeinfo`
- [ ] https://github.com/kubernetes/kubernetes/issues/71863 Rename `pkg/scheduler/util` to `pkg/scheduler/internal/podinfo` 
- [x] https://github.com/kubernetes/kubernetes/issues/71864 Move predicate types from `pkg/scheduler/algorithm` to `pkg/scheduler/algorithm/predicates` 
- [x] https://github.com/kubernetes/kubernetes/issues/71865 Move priority types from `pkg/scheduler/algorithm` to `pkg/scheduler/algorithm/priorities`
- [x] https://github.com/kubernetes/kubernetes/issues/71866 Move predicate and priority registration into their own packages
- [x] https://github.com/kubernetes/kubernetes/issues/71867 Move compatibility_test.go to `pkg/scheduler/api` 

**Phase 3**
¯\\\_(ツ)_/¯ 

/sig scheduling
/kind cleanup

**Comment by denkensk** [comment]
I want to take #68959 #68960 #68961 @misterikkit

**Comment by k82cn** [comment]
/assign misterikkit

@misterikkit , suppose you will help to trace the overall status of this issue; the developers in community can help on sub-tasks, e.g. pr, review :)

**Comment by timothysc** [comment]
This makes me very happy to see, thank you @misterikkit !

**Comment by misterikkit** [comment]
I am back from my time off, so I can give these issues attention. I think that the last two issues might get moved to phase 2, as they require more refactoring than anticipated.

**Comment by Adirio** [comment]
Is any of the tasks targeting `scheduling_queue.go`. There is an outdated comment in that file (currently at [lines 129-131](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L129-L131)) about that function being a copy of another that is said to be unsafe. The function was changed but the comment has not been removed/updated.

**Comment by misterikkit** [comment]
@Adirio I think that file is safe to change. Feel free to send a cleanup PR.

**Comment by misterikkit** [comment]
Phase 1 is officially complete!

**Comment by krmayankk** [comment]
should we close this @misterikkit  now ?

**Comment by Adirio** [comment]
@krmayankk I can answer to that: No.

This issue is tracking also **Phase 2** and a future **Phase 3**.

**Comment by alculquicondor** [comment]
/remove-lifecycle frozen
/assign

I had a chat with @misterikkit to take the lead of this cleanup

**Comment by alculquicondor** [comment]
We can consider this fixed.

More work will be needed during phase 2 of framework migration. But we will re-scope this.

/close
