### ISSUE TITLE
[umbrella issue] promote `TaintBasedEvictions` to beta in 1.13

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#69533]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Promote `TaintBasedEvictions` to beta in 1.13.

**Tasks**:

- [x] Simplify taint manager workqueue keys (#65350)
- [x] Increase the code coverage of NodeLifecycleController (#54297)
- [x] enable and improve e2e of NoExecuteTaintManager (#69657)
- [x] add e2e tests for TaintBasedEvictions (#69796)
- [x] Add test cases for taintbasedevictions (#69788)
- [x] enable `TaintBasedEvictions` in pkg/features/kube_features.go (#69824)
- [x] documents update in k/website (https://github.com/kubernetes/website/pull/10765)

**Links**:

- Feature: kubernetes/features#166

**Comment by Huang-Wei** [comment]
All issues have been resolved. Closing this.
