### ISSUE TITLE
Scheduler User Guide Documentation

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#69767]
This is a tracking issue for the effort to add kube-scheduler's user guide documentation.

**Goals**:
If you saw the lengthy thread on slack#sig-scheduling recently, you might have noticed that users find configuring the scheduler (or scheduler extenders) to be difficult and undocumented. In fact, some of the best kube-scheduler documentation was not written by us!

e.g.
https://jvns.ca/blog/2017/07/27/how-does-the-kubernetes-scheduler-work/
http://alexandrutopliceanu.ro/post/scheduling-in-kubernetes/
https://thenewstack.io/implementing-advanced-scheduling-techniques-with-kubernetes/

Recent discussion also included talk of how the scheduler should behave when cluster autoscaler is in use. We feel like these common use cases come up in slack over and over again.

We should take this opportunity to write some awesome documentation on how to use and extend kube-scheduler. This is a task that can easily be divided across several contributors, and can include both new and experienced sig-scheduling contributors.

Regardless of whether you use or understand kubernetes, this is a great opportunity to learn more about kube-scheduler. At the same time, perhaps the first step in your journey to the kubernetes. And **_don not worry if you run into a problem, we will help you with it_**.

**Document Plans**:
- [ ] #69768 How does the Kubernetes scheduler works?
- [ ] #69769 How to customize and extend the kubernetes scheduler?
- [ ] #69770 How to configure your kubernetes scheduler?
- [ ] #69840 Choose scheduling algorithms and strategies for your cluster.
- [ ] #69771 Learning kube-scheduler's design and implementation from source code.

You can put the document in the https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/scheduling directory. We want to avoid the situation where two contributors send PRs for the same fix, so please coordinate here or on the linked issues before working on part of this. Discussion about the user guide documentation of scheduler is welcomed.

@bsalamat @k82cn @misterikkit @ravisantoshgudimetla @Huang-Wei @resouer 
Any documentation that you think are necessary to add, please comment here, I will add it.

/sig scheduling
/kind documentation

**Comment by k82cn** [comment]
IMO, we also need to provide some doc on our policy/algorithms: what's the target user case of algorithm? how to configure it? Source code of scheduler is low priority to me for now.

**Comment by misterikkit** [comment]
Since this is the tracker issue,
/assign @wgliang 
/remove-help

**Comment by misterikkit** [comment]
> provide some doc on our policy/algorithms

Strongly agree: The type of users who need help using the scheduler are often trying to configure predicates/priorities. I think scheduler configuration should be a separate topic.

Another topic that needs addressing is how our documentation will be organized and discovered. That is a good area for the lead (@wgliang in this case) to set a direction.

**Comment by misterikkit** [comment]
> I think scheduler configuration should be a separate topic.

Oops, it's already a separate topic. :+1:

**Comment by saurav-malani** [comment]
Hello @wgliang @misterikkit @k8s-ci-robot @k82cn I am an Outreachy applicant. I am looking for a "good first issue". So, if this issue is not taken up by anyone. I would like to work on it. If not taken, can you provide all the relevant details, that will be helpful to me? TIA.

**Comment by wgliang** [comment]
@saurav-malani Cool, currently only #69840 is not claimed, I would appreciate if you are willing to work on it.

**Comment by saurav-malani** [comment]
@wgliang I would love to work on it! Can you please assign it to me. Also, can you share other relevant details, that I should refer to get my task done.

**Comment by Adirio** [comment]
Read the contributing guides @saurav-malani, they can not assign them to you as github only allows to assign organization members or contributors IIRC. Comment on it saying you want to take it to let others know you are going to be working on it.

**Comment by misterikkit** [comment]
@saurav-malani Yeah, we can do a "soft assign" which is just a comment on that issue stating you will work on it. Unfortunately, github doesn't let us put you in the assignee field.

In my view, the five issues linked from here are medium-sized documentation efforts. And since we're writing English instead of Golang, it's easier for multiple contributors to collaborate on a single document.

**Comment by Adirio** [comment]
I do agree with misterikkit, but that requires a deep understanding on the scheduler as a whole, while each part may be done just understanding some parts. For example you do not need to know how the `Lister`s and `Informer`s work if you are witting about the configuration of schedulers.

**Comment by huynq0911** [comment]
Besides, I saw that we have already had some Scheduler documents in **community** repo:
- https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler.md
- https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler_algorithm.md
- https://github.com/kubernetes/community/tree/master/contributors/design-proposals/scheduling
Although these documents do not focus on above questions, at least it contains something that we can use. (Forks can use it as references)
I think it will better to merge documents between the two repositories.

**Comment by misterikkit** [comment]
After seeing some of the PRs for this task, I am wondering whether https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/scheduling is the right location for all of these. Does creating a new directory in that repo add a "group" to the table of contents on the left?

**Comment by YunWang** [comment]
Hello @wgliang Is there any issue not taken?if any, I would like to work on it.

**Comment by wgliang** [comment]
@YunWang You can take it any one. Some work needs to be supplemented and continued, and it would be great if you could continue to advance. Thanks！

**Comment by YunWang** [comment]
> @YunWang You can take it any one. Some work needs to be supplemented and continued, and it would be great if you could continue to advance. Thanks！

@wgliang Thanks. I would like to woke on [#69771](https://github.com/kubernetes/kubernetes/issues/69771). And I will make a PR as soon as possible.

**Comment by YunWang** [comment]
@wgliang I have made a PR [#15777](https://github.com/kubernetes/website/pull/15777#issuecomment-520112007). Could you have it a look and give me some suggestions to do my job better?
