### ISSUE TITLE
IPv6-only cluster e2e Testing Issues

### ISSUE THREAD

**Issue by hhoover** [kubernetes/kubernetes#70248]
**Which test(s) are failing**:

### Test regex is looking for an IPv4 address

[Fail] [sig-api-machinery] Downward API [It] should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2325

[Fail] [sig-api-machinery] Downward API [It] should provide host IP as an env var [NodeConformance] [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2325

---

### Container(s) used in the test can't do liveness/readiness probes using an IPv6 address.

[Fail] [sig-cli] Kubectl client [k8s.io] Guestbook application [It] should create and stop a working application  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1914

[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should perform canary updates and phased rolling updates of template modifications [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323

[Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:158

[Fail] [k8s.io] Probing container [It] should *not* be restarted with a /healthz http liveness probe [NodeConformance] [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:445

[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should perform rolling updates and roll backs of template modifications [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323

[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323

[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] Burst scaling should run to completion even with unhealthy pods [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323

---

### Test is looking for an A record, vs an AAAA record:

[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:497

[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:497

**Since when has it been failing**: 

**Testgrid link**:

**Reason for failure**: (see above)

**Anything else we need to know**:
Can be reproduced with an IPv6 Kubernetes cluster (v1.11) and a Sonobuoy e2e run. The IPv6 cluster can be run locally with DinD:

```
wget https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.11.sh
$ chmod +x dind-cluster-v1.11.sh
$ export IP_MODE=ipv6
$ ./dind-cluster-v1.11.sh up
```

/assign @timothysc 

/kind failing-test

**Comment by BenTheElder** [comment]
So far kubeadm-dind-cluster is the only thing offered up for CI to test this, there's some ongoing work from @leblancd to do this.

**Comment by timothysc** [comment]
@BenTheElder When can we put kind on the hot-seat?  We could pilot with a sig-cluster-lifecycle periodic job?  

/cc @neolit123

**Comment by BenTheElder** [comment]
`kind` has some conformance test CI [here](http://testgrid.k8s.io/conformance-providerless) for now (I am to split that dashboard into one for kind and one for local-up-cluster). Normal / serial conformance testing is quite stable, pretty much the only failures in the past month have been a build/network flake or two and the e2e test provider breakage.

We could put it in the hot seat nowish, it's fairly stable and I'm aiming to cut a release very soon (I hope tomorrow, maybe next week), though multi-vs-single node might (?) be an issue. Currently it only supports a single node per cluster.

**Comment by BenTheElder** [comment]
> but for things like IPV6 we might want to test at least one worker node too.

Maybe? We also have ipv6 loopback etc though, and an """External IP address""" for the node container. It depends on what exactly we need to test. Here it looks like just tolerating ipv6 addresses in places, which shouldn't actually require multi-node afaict. Not sure about other tests though..

> also i'm not sure if some tests will always be red, because they assume multi node.

Nope, see the dashboard above. All of the tests listed here are conformance, and `kind` is passing those. One or two may be skipped, but there's a separate discussion about this for minikube and co..

**Comment by neolit123** [comment]
ok, sounds good.

> All of the tests listed here are conformance, and kind is passing those

is it passing them for 1.11 too btw?

for conformance in particular, since kind is already passing conformance tests, what extra coverage would we need under a sig-cluster-lifecycle job?

**Comment by jberkus** [comment]
this test failure looks to be non-blocking from the description.  setting priority appropriately.

/priority important-longterm

**Comment by BenTheElder** [comment]
> is it passing them for 1.11 too btw?

yes :-)

> for conformance in particular, since kind is already passing conformance tests, what extra coverage would we need under a sig-cluster-lifecycle job?

not sure. I plan to move those to their own conformance dashboard (as well as the -all) and then discuss further if we want to depend on these more soon. 
Getting a last end-user (not ci!!) breaking change out the door then getting a stable release w/ binaries etc. currently, then a kubetest deployer before I bring that up myself.

**Comment by leblancd** [comment]
Some triaging on these failures:

- **Test is looking for an A record, vs an AAAA record:**
These failures look like K/K issue [#62883](https://github.com/kubernetes/kubernetes/issues/62883).
This was deemed to be a kube-dns issue (inability to handle PTR probes), but works with coreDNS. Since coreDNS is expected to be the default DNS server soon, this was closed.

- **Test regex is looking for an IPv4 address (Downward API failures)**
The e2e test code is looking for an IPv4 Pod IP address, specifically a dotted decimal "d.d.d.d" pattern.
This can be found in the file test/e2e/common/downward_api.go here:
```
    framework.ConformanceIt("should provide pod name, namespace and IP address as env vars [NodeConformance]", func() {
. . . 
            "POD_IP=(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)",
```
and here:
```
    framework.ConformanceIt("should provide host IP as an env var [NodeConformance]", func() {
. . .
        expectations := []string{                                                                                                                                  
             "HOST_IP=(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)",                
         }
```
This code should be changed to accept V4 and V6 patterns.

- **Container(s) used in the test can't do liveness/readiness probes using an IPv6 address.**
This failure:
```
•	[Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod [Conformance]
```
appears to be caused by an IPv4-ism in file kubernetes/test/e2e/node/pre_stop.go:
```
func testPreStop(c clientset.Interface, ns string) {
. . .
                                   "wget", "-O-", "--post-data=" + val, fmt.Sprintf("http://%s:8080/write", podOut.Status.PodIP),
```
Here, the %s for the PodIP would need to have surrounding square brackets when the pod IP is an IPv6 address.

**Comment by rajansandeep** [comment]
There are 2 PRs https://github.com/kubernetes/kubernetes/pull/59894 and https://github.com/kubernetes/kubernetes/pull/70188 open to help adapt the DNS tests for IPv6. Both these PRs have been tested in a local IPv6 dind cluster and have been passing the tests for CoreDNS.

**Comment by fturib** [comment]
How do we expect to name the tests that are for IPv4 only (I means that will be successful only on a cluster that support IPv4), and the tests that are for IPv6 only ?

in the PR mentioned above by @rajansandeep , we labeled:

[Feature:Networking-IPv4] and [Feature:Networking-IPv6] . .. but, because of the "Feature:" none of these tests will run in most of e2e tests.

if I specify [IPv4], maybe the new Ipv6 e2e test environement will not run that test
But, if I specify [IPv6], the current e2e test environment (I mean any gce ...) will test it whatever ...

**Comment by leblancd** [comment]
@fturib - Yes, I agree. Looking at the documentation for [Kinds of tests](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#kinds-of-tests), the Feature tag should be used "If a test has non-default requirements to run or targets some non-core functionality, and thus should not be run as part of the standard suite". So we probably should be using [IPv4] and not [Feature:Networking-IPv4].

**Comment by pmichali** [comment]
For this failure:
```
[Fail] [sig-cli] Kubectl client [k8s.io] Guestbook application [It] should create and stop a working application [Conformance]
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1914
```

It looks like redis master/slave pods are created and they are not responding to requests.  The app listens on a bind address, which by default is 0.0.0.0 (IPv4 only). Told, on slack, that if don't specify "::", it will not listen for IPv6 addresses.  Unfortunately, this appears to only be configurable via a config file, and not by the redis YAML files used for testing.

**Comment by pmichali** [comment]
For this failure:
```
[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should perform canary updates and phased rolling updates of template modifications [Conformance]
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323
```

The test starts up NGINX, and, like the previous issue, it is listening on 0.0.0.0 port 80 by default. The configuration file needs to be changed to listen for IPv6 as well. A config sample shows using the "listen" config setting "[::]:80" to listen for both IPv6 and IPv4.  This could be placed in the Dockerfile for the image, as was done by Dane here: https://github.com/leblancd/kube-v6/blob/master/nginx_v6/Dockerfile

**Comment by rpothier** [comment]
The same failure as described above is also causing the below tests to fail
[StatefulSetBasic] [It] should perform rolling updates and roll backs of template modifications [Conformance]
[StatefulSetBasic] [It] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Conformance]
[StatefulSetBasic] [It] Burst scaling should run to completion even with unhealthy pods [Conformance]

**Comment by pmichali** [comment]
For this failure:
```
[Fail] [k8s.io] Probing container [It] should not be restarted with a /healthz http liveness probe [NodeConformance] [Conformance]
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:445
```
The test starts up a pod, using the nginxslim image. I suspect that this has the same problem with the pod ignoring IPv6 requests, and that the same solution (customizing the image to list to "[::]:80") would allow it to listen to both IPv4 and IPv6 requests.

**Comment by pmichali** [comment]
I think my last issue is the same problem…nginx used. For grins, I substituted the image with ngnx_v6 from Dane’s repo, and the test failed with image pull error. I changed the version to “latest” (was 0.20 and there are serval images with different versions used for different tests I guess). Unfortunately, it is trying to pull that image from the upstream repo:

Oct 29 18:57:25.511: INFO: At 2018-10-29 18:53:03 +0000 UTC - event for liveness-http: {kubelet kube-node-1} BackOff: Back-off pulling image "k8s.gcr.io/nginx_v6-amd64:latest<http://k8s.gcr.io/nginx_v6-amd64:latest>"
Oct 29 18:57:25.511: INFO: At 2018-10-29 18:53:03 +0000 UTC - event for liveness-http: {kubelet kube-node-1} Failed: Error: ImagePullBackOff


Oh well…

Paul Michali (pcm)

On Oct 29, 2018, at 2:43 PM, rpothier <notifications@github.com<mailto:notifications@github.com>> wrote:


The same failure as described above is also causing the below tests to fail
[StatefulSetBasic] [It] should perform rolling updates and roll backs of template modifications [Conformance]
[StatefulSetBasic] [It] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Conformance]
[StatefulSetBasic] [It] Burst scaling should run to completion even with unhealthy pods [Conformance]

**Comment by pmichali** [comment]
To summarize, each of the test failures are either due to a known issue for kube-dns that was judged not to be handled, test case changes to support checking IPv6 values, or test apps that need IPv6 support enabled (redis, nginx).  None of the issues point to IPv6 Kubernetes functionality.

**Comment by hhoover** [comment]
Two additional failures for 1.12 that I believe are caused by IPv4-isms in the containers used:

```
[Fail] [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook [It] should execute poststart exec hook properly [NodeConformance] [Conformance] 
/workspace/anago-v1.12.1-beta.0.52+4ed3216f3ec431/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/lifecycle_hook.go:75

[Fail] [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook [It] should execute prestop exec hook properly [NodeConformance] [Conformance] 
/workspace/anago-v1.12.1-beta.0.52+4ed3216f3ec431/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/lifecycle_hook.go:84
```

**Comment by jberkus** [comment]
All: is this failure related to CoreDNS?  If it is, then this test may become blocking until we know what's causing the failure.

**Comment by pmichali** [comment]
@jerkus. No. The failure is specific to kube-dns, and the decision was made not to update kube-dns, due to the plan to transition to CoreDNS.  I'm not sure how those test cases should be dispositioned (as they are run for kube-dns and CoreDNS).

**Comment by timothysc** [comment]
@kubernetes/sig-network-bugs - Are folks intending to address the testing issues in 1.14?  

We have a KIND test, but I'm not certain we've enabled IPv6 as part of those tests.
/cc @neolit123 @BenTheElder

**Comment by timothysc** [comment]
In reading back, I really think a feature such as this needs a complete test-jig.

**Comment by neolit123** [comment]
working on ipv6 test cases for kind/kubeadm might not be possible, due to the other priorities we have at e moment. i can see this happening in the 1.15 cycle.

**Comment by timothysc** [comment]
FWIW I really think @kubernetes/sig-network-misc should be owning the test-bed for this.

**Comment by BenTheElder** [comment]
+1, we're getting more KIND tests up but mostly using boring / default networking options, I don't believe anyone has tried to do IPV6 yet.

**Comment by aojea** [comment]
I've started to work on this, @timothysc @thockin feel free to assign this issue to me.
The plan I have in mind is:

### Fix current known issues with IPv6 and e2e tests:

- [x] Kubernetes e2e suite.[sig-node] Downward API should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance] #75237 
- [ ] Kubernetes e2e suite.[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Burst scaling should run to completion even with unhealthy pods [Conformance]
- [x] Kubernetes e2e suite.[k8s.io] Probing container should *not* be restarted with a /healthz http liveness probe [NodeConformance] [Conformance] #75244 
- [x] Kubernetes e2e suite.[sig-network] DNS should provide DNS for the cluster [Conformance] #75243 
- [ ] Kubernetes e2e suite.[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]
- [x] Kubernetes e2e suite.[sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance] #75237 
- [x] Kubernetes e2e suite.[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance] #75245 
- [ ] Kubernetes e2e suite.[k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance]
- [x] Kubernetes e2e suite.[sig-network] DNS should provide DNS for services [Conformance]  #75243 
- [ ] Kubernetes e2e suite.[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Conformance]
- [x] Kubernetes e2e suite.[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance] #75245 
- [ ] Kubernetes e2e suite.[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
- [ ] Kubernetes e2e suite.[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance]

### Add IPv6 support to `kind` 
- [ ] https://github.com/kubernetes-sigs/kind/pull/348

### Add automated testing using `kind`,
- [ ] I'm running automated tests with `sonobuoy`  here https://circleci.com/gh/aojea/kindnet/104 as a POC

**Comment by aojea** [comment]
Seems that we can start to have automated testing soon :) https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/348/pull-kind-conformance-parallel-ipv6/1136793268353241088/

**Comment by BenTheElder** [comment]
/assign
We're very close to having continuous testing for this.

**Comment by aojea** [comment]
Current tests failures for referenceÑ

- [ ] [sig-network] DNS should provide DNS for services [Conformance] expand_more	10m17s
- [ ] [sig-network] DNS should provide DNS for the cluster [Conformance] expand_more	10m11s
- [ ] [k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance] expand_more	1m42s
- [ ] [sig-network] DNS should provide DNS for ExternalName services [Conformance] expand_more	10m56s
- [ ] [sig-network] DNS should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance] expand_more	10m31s
- [ ] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Conformance] expand_more	10m19s
- [ ] [sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance] expand_more	1m18s
- [ ] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Burst scaling should run to completion even with unhealthy pods [Conformance] expand_more	10m17s
- [ ] [sig-cli] Kubectl client [k8s.io] Guestbook application should create and stop a working application [Conformance] expand_more	4m12s
- [ ] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance] expand_more	10m17s
- [ ] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance] expand_more

**Comment by aojea** [comment]
2 PRs to go and we are green
The DNS PR one is trickier, would love someone from sig-network reviewing it

**Comment by BenTheElder** [comment]
https://testgrid.k8s.io/conformance-kind FYI :upside_down_face: 

specifically:
https://testgrid.k8s.io/conformance-kind#kind%20(IPv6),%20master%20(dev)

and:
https://testgrid.k8s.io/conformance-kind#kind%20(IPv6),%20master%20(dev)%20%5Bnon-serial%5D

**Comment by aojea** [comment]
I'll be some time off, but will check once I back why the DNS tests are still failing, the patch worked in my environment :thinking:

**Comment by aojea** [comment]
dns-test-service.dns-346.svc.cluster.local.c.k8s-prow-builds.internal. A: plugin/kubernetes: no next plugin found
2019-06-27T04:54:28.80348837Z stdout F 2019-06-27T04:54:28.803Z [ERROR] plugin/errors: 2 dns-test

We.are using a custom coredns config for the ci, checking the logs of the coredns pods I think the problem should be there https://github.com/kubernetes-sigs/kind/blob/572fda58f2d3b6573d460b179338e8cf5e772aa2/hack/ci/e2e.sh#L136

**Comment by aojea** [comment]
I´ve found the problem with the DNS tests, it was environmental, related to the CI configuration.

CoreDNS needs a different configuration to run in the CI because of:

1. The CI doesn´t provide IPv6 external connectivity, thus we can´t use upstream DNS servers and CoreDNS fail to work. We need to configure CoreDNS to work offline
2. The CI adds to the resolv.conf the following domains to search: c.k8s-prow-builds.internal google.internal. CoreDNS should handle those domains and answer with NXDOMAIN instead of SERVFAIL in order that the pod continuous querying the DNS server.

Finally, we can close this issue once https://github.com/kubernetes-sigs/kind/pull/684 merges
