### ISSUE TITLE
Rebase most docker images on gcr.io/distroless/static

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#70249]
EDIT (from @justaugustus - 5/8/20):

### `go-runner` (distroless++) (@dims)

- [x] (https://github.com/kubernetes/kubernetes/pull/90804) New go-runner image for distroless scenarios
- [x] (https://github.com/kubernetes/k8s.io/pull/849) Promote the new `go-runner` image - `v0.1.0`
- [x] (https://github.com/kubernetes/kubernetes/pull/90852) Bump `go-runner` to `v0.1.1`
- [x] (https://github.com/kubernetes/k8s.io/pull/853) Promote `go-runner:v0.1.1` image
- [x] (https://github.com/kubernetes/kubernetes/pull/90674) Switch core master base images from debian to distroless
- [x] (https://github.com/kubernetes/kubernetes/pull/91329) Flexvolume master driver is blocking controller-manager from moving to distroless - https://github.com/kubernetes/kubernetes/issues/78737

### Debian base images (`debian-base`, `debian-iptables`) and `pause` (@justaugustus)

- [x] (https://github.com/kubernetes/kubernetes/issues/58012) Base image (debian-base, debian-iptables) updates & building on K8s Infra
- [x] (https://github.com/kubernetes/kubernetes/issues/90698) 'pause' base image updates & building on K8s Infra
- [x] (https://github.com/kubernetes/kubernetes/pull/88603) Remove `debian-base` image
- [ ] () Remove `debian-iptables` image

---

Forked from https://github.com/kubernetes/kubernetes/issues/40248 (think of this as V2).

`scratch` is not quite sufficient as a base image for static go binaries. Common dependencies include ca-certificates, resolv.conf, hosts, and nsswtich (see https://github.com/kubernetes/kubernetes/issues/69195).  See below for a more complete list.

We need to decide if we want a scratch+config base image (either found or created by us), or a more complete distro (e.g. debian-base, at the cost of more frequent patching). `gcr.io/distroless/static` has also been proposed, or could provide inspiration for a static base.

**Blocked by:** (for the scratch case) https://github.com/kubernetes/kubernetes/issues/61006, for logs redirection.

/kind bug
/cc @ixdy 

---

**Appendix**

Here is a list of `/etc/*` files referenced from the go source (obviously some of these are not applicable):
```
$ grep -rEoIh '/etc/[-a-zA-Z./_]+[a-zA-Z]' | sort -u
/etc/alpine-release
/etc/apache
/etc/apache/mime.types
/etc/certs/ca-certificates.crt
/etc/group
/etc/hosts
/etc/localtime
/etc/mdns.allow
/etc/mime.types
/etc/nsswitch.conf
/etc/openssl/certs
/etc/openssl/certs/ca-certificates.crt
/etc/passwd
/etc/passwd/foo
/etc/passwx
/etc/paths.d/go
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
/etc/pki/tls/cacert.pem
/etc/pki/tls/certs
/etc/pki/tls/certs/ca-bundle.crt
/etc/profile
/etc/protocols
/etc/release
/etc/resolv.conf
/etc/security/cacerts
/etc/services
/etc/ssl/ca-bundle.pem
/etc/ssl/cacert.pem
/etc/ssl/cert.pem
/etc/ssl/certs
/etc/ssl/certs/ca-certificates.crt
```

**Comment by neolit123** [comment]
not sure if sig cluster lifecycle is the best owner for this.
adding sig release and sig architecture.
/sig release
/sig architecture

**Comment by timothysc** [comment]
/assign @ixdy 

This is not sig-cluster-lifecycle typically.

**Comment by dims** [comment]
@kfox1111  is https://github.com/kubernetes/kubernetes/pull/70245 not enough?

**Comment by ixdy** [comment]
before #70245 there was #69238, though that didn't make it into 1.12. cc @BenTheElder

**Comment by BenTheElder** [comment]
Yeah, I added an nsswitch.conf as a small stopgap in https://github.com/kubernetes/kubernetes/pull/69238, but I'd like to see a standard base image as well which should simplify the build and patching a bit.

We could backport https://github.com/kubernetes/kubernetes/pull/70245 or https://github.com/kubernetes/kubernetes/pull/69238 to 1.12, I'm not sure what the best choice is. https://github.com/kubernetes/kubernetes/pull/69238 is smaller but https://github.com/kubernetes/kubernetes/pull/70245 is the preferable change going forward.

**Comment by BenTheElder** [comment]
Note that go's defaults actually match the documentation for not having an `/etc/nsswitch.conf`:
https://golang.org/src/net/conf.go#L197
http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html (`hosts: dns [!UNAVAIL=return] files`), it's just that they don't match the default most distros seem to ship of `hosts: files dns` which is probably what most of us want ...

**Comment by tallclair** [comment]
Another option is to just use [distroless/base](https://github.com/GoogleContainerTools/distroless/tree/master/base), although it does include a few c libraries that we don't need.

**Comment by BenTheElder** [comment]
would distroless/base have what we need for EG the iptables (kubeproxy) variant?

**Comment by tallclair** [comment]
I don't think so - it doesn't have a package manager so iptables would still need to be manually added (and managed).

**Comment by tallclair** [comment]
It looks like distroless is planning to put out an image without the c libraries, specifically for this use case. I think we should just use that as soon as it's ready: https://github.com/GoogleContainerTools/distroless/issues/256

**Comment by tallclair** [comment]
**Update:**

[gcr.io/distroless/static](https://gcr.io/distroless/static) is now available. I suggest we work towards this end-state:

All official Kubernetes images & addons are based on 1 of 2 images: `gcr.io/distroless/static:latest` wherever possible, or a full featured distro for the cases where it's absolutely required.

For the latter, our current recommendation is `k8s.gcr.io/debian-base`, but that is subject to change. For these cases, the dependencies _should_ be well-documented, and we should eventually work towards building from source, and basing on a distroless image.

**Action Items:**

1. (Prerequisite) verify that the single distroless/static image supports all architectures. If it does not, work with that team to release images for cross-platform support (cc @luxas, xref https://github.com/GoogleContainerTools/distroless/pull/259#issuecomment-447986989)
2. Rebase all `FROM scratch` images on `gcr.io/distroless/static:latest`. There are some known-issues with running go static binaries on scratch, and this move should fix those (e.g. https://github.com/kubernetes/kubernetes/issues/69195).
3. Rebase system images using shell-redirection for logs on distroless/static, by leveraging [klog's](https://github.com/kubernetes/klog) `--log-file` option to eliminate shell usage. (Requires v1.13+)
4. Chip away at the remaining images with miscellaneous shell dependencies. In some cases, the shell usage should be rewritten as a feature of the binary, in others it's a harder dependency that should be documented and migrated to debian-base (see above). We should have separate tracking issues for fixing these on a case-by-case basis.

I propose we try to tackle 1-3 in Kubernetes 1.14.

/milestone v1.14
/help-wanted

**Comment by srmocher** [comment]
@tallclair I would like to start digging into this.

**Comment by BenTheElder** [comment]
SGTM, one thing worth noting is that a few related projects have used k8s.gcr.io/debian-base (one of mine used to), wish we had a good way to signal intent regarding the future of that image.

**Comment by ixdy** [comment]
it seems like it might be a bit late to tackle this for 1.14 (cc @spiffxp), though it might be worth starting on a KEP to outline this in any case?

**Comment by mkumatag** [comment]
> 1. verify that the single distroless/static image supports all architectures. If it does not, work with that team to release images for cross-platform support (cc @luxas, xref [GoogleContainerTools/distroless#259 (comment)](https://github.com/GoogleContainerTools/distroless/pull/259#issuecomment-447986989))

@dims @tallclair as `distroless/static` does not contain any platform specific code and just contains:

```
ca-certificates
A /etc/passwd entry for a root user
A /tmp directory
tzdata
```

So we are safe using this instead of scratch wherver needed.

**Comment by soggiest** [comment]
We're well into code freeze for 1.14, is this necessary/release-blocking? Also, this seems to be a major enhancement without a KEP as mentioned above. Based on the work defined above that's appears to be remaining and there is no KEP associated with this do you mind if we push this to 1.15?

**Comment by tallclair** [comment]
Definitely not release-blocking.
/milestone v1.15

@yuwenma it sounds like there's demand for a KEP. Would you mind translating your design doc into a KEP? Follow https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md for guidelines.

**Comment by yuwenma** [comment]
@tallclair Sounds good to me. I'll do that.

**Comment by xmudrii** [comment]
Hello! We have started the code freeze for 1.15. Is this issue still planned for the 1.15 cycle?

**Comment by yuwenma** [comment]
> Hello! We are starting the code freeze for 1.15 tomorrow EOD. Is this issue still planned for the 1.15 cycle?

Hi Marko, thanks for the check.
Yes! This is planed. We have had the majority of the work done. Have three more PRs need to go in (under review). Please note, this is not a feature request but more of a bug-fix/internal-cleanup due to the security reasons. Does it have to strictly follow the code freeze policy?

**Comment by soggiest** [comment]
Hello,
I'm the Bug Triage Lead for 1.15. All issues and PRs are subject to the Code Freeze policy, this is to try and maintain as much stability as possible while preparing a new release. Last release there were comments about creating a KEP for this work, was that ever completed? If so, if your code is complete, and a documentation PR is open then this will likely land in this release. If a KEP has not been created this issue, and associated PRs, may still be incorporated in this release during the Code Thaw phase. For more information please refer to this doc: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.15

**Comment by yuwenma** [comment]
Thanks for the reminder. yeah, we are following the policy and here's the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md)

We have the PRs ready and they depend on the latest klog (v0.3.2, created yesterday). I'm currently working on importing the new klog version to k/k (#78465 the new klog release may require some test updates) and afterwords we can have the blocking PR merged. 

Due to our current situation, do you have any suggestions what can be the good release phase for us? should we go with the Code Thaw phase?

**Comment by soggiest** [comment]
If you can get the Klog version updated and the PRs merged by EOD tomorrow (May 30th)  you will be fine, otherwise shoot for Code Thaw. I recommend trying to pull in the appropriate Sig leadership to help review/expedite your PRs getting merged

**Comment by xmudrii** [comment]
Hello once again! I'd just like to check what's the current status of this issue and is it still planned for v1.15? Thanks!

**Comment by yuwenma** [comment]
[Here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md#implementation-history)'s the status updates:
We have [these images](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md#rebased-images) rebased.
And here's the [exception list](https://github.com/kubernetes/sig-release/blob/master/release-engineering/baseimage-exception-list.md).

**Comment by soggiest** [comment]
It looks like Klog is still an issue, can we move this to 1.16?

**Comment by soggiest** [comment]
Since I didn't receive a response I'm bumping this to 1.16
/milestone v1.16

**Comment by xmudrii** [comment]
@tallclair @yuwenma Hello! I'm bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by xmudrii** [comment]
@tallclair @yuwenma Any update on this? Should we move it to the next milestone?

**Comment by tallclair** [comment]
/milestone v1.17

This is an ongoing issue with incremental improvements in each release.

**Comment by smourapina** [comment]
@tallclair @yuwenma Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still on track for 1.17?

**Comment by alejandrox1** [comment]
Context: sig-architecture subgroup work to search for technical debt
Category: Security
Reason: Distroless containers decreased attack surface

**Comment by neolit123** [comment]
/milestone v1.19
/remove-lifecycle stale

switching milestone to next cycle. please change back if need.

**Comment by tallclair** [comment]
@dims @yuwenma - have the klog issues that were blocking some of the control plane images been resolved?

/cc @justaugustus

**Comment by dims** [comment]
@tallclair we haven't tracked it down yet. last debugging was here - https://github.com/kubernetes/kubernetes/pull/83390#issuecomment-537813852

**Comment by justaugustus** [comment]
I've updated the PR description with some of the current work Dims and I are doing.

/assign @dims @justaugustus 
/remove-help
/remove-priority important-longterm
/priority important-soon

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering

**Comment by jtslear** [comment]
Hello, @jtslear here from Bug Triage! This issue has not been updated for a long time, so I'd like to check on the status. The code freeze is starting June 25th and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the issue is tagged for 1.19, is it still planned for this release?

**Comment by justaugustus** [comment]
@jtslear -- Yep, it's active for this release.
The issue description and tracked items was updated 18 days ago and there are several merged PRs linking back to this.

**Comment by jtslear** [comment]
I still see  a couple open PR's.  Due to reaching the code freeze deadline, I'm going to bump this to the next release.

/milestone v1.20

**Comment by mkorbi** [comment]
Heyho @tallclair @jtslear  I wanted to check how it is going?

As the issue is tagged for 1.20, is it still planned for this release?

**Comment by justaugustus** [comment]
This is roughly done, but I need to backfill docs.
/milestone v1.21

**Comment by ams0** [comment]
Hi @justaugustus , is still planned for 1.21? We start code freeze today, so I wonder if we should leave it for this release or move to the next

**Comment by xmudrii** [comment]
@justaugustus Is there any update on this? Are the docs backfilled yet?

**Comment by voigt** [comment]
Hey there (@tallclair, @xmudrii, ), Bug-Triage here 👋 ,
looks like this issue hasn't received any update since it has been assigned to `milestone 1.22`. Given the fact that the code freeze for this release already started and the issue has been transitioned a couple of releases yet, **I´d like to suggest clearing the milestone label for now.**

We will remove the `milestone 1.22` label if this issue doesn't receive any significant update in 7d from now.

**Comment by BenTheElder** [comment]
I'm prototyping what distroless + additional necessary c binaries (like iptables) would look like in the KIND subproject here: https://github.com/kubernetes-sigs/kind/pull/2373

It's not bad actually, especially given that distroless has images intended for C, C++ applications (adds libc6, adds libgcc1). I've been writing a generalizable approach to automatically copy binary + runtime dynamic library deps + their copyrights based on inspecting binaries with `ldd` in a multi-stage build.

**Comment by tallclair** [comment]
@BenTheElder my concern with this approach is that it will essentially hide the packages & versions from vulnerability scanners, which I think mostly just look for package manager manifests. I wonder how hard it would be to keep a package manifest with the relevant packages in the image?

Also, how does your approach compare to using bazel to build docker imagse?

**Comment by justaugustus** [comment]
Still needs a review of docs; will work on this during some intercycle downtime
/remove-lifecycle rotten
/lifecycle frozen
/milestone v1.24

**Comment by doshyt** [comment]
@justaugustus hi, I'm with the Bug triage team for 1.24 - we noticed that this issue has not been updated for a while. I wonder if there is any work planned or expected that would go into 1.24?  Thanks!

**Comment by BenTheElder** [comment]
I don't believe there are any further changes in 1.24.

Sorry @tallclair I missed your reply https://github.com/kubernetes/kubernetes/issues/70249#issuecomment-887055048

> @BenTheElder my concern with this approach is that it will essentially hide the packages & versions from vulnerability scanners, which I think mostly just look for package manager manifests. I wonder how hard it would be to keep a package manifest with the relevant packages in the image?

I don't think that will be hard at all. Distroless has pretty much the same proposition when using anything beyond "base", e.g. the "static" image has glibc from debian packaging.

If we can settle on what information we wish to preserve (or generate!) we should be able to do this, e.g. currently we preserve package copyright info. And presumably distroless either doesn't handle this and leaves us in the same boat with other images, or we can copy what they're doing.

I'd have to dig more to see, I think this is `/lib/dpkg/status.d/` which is in the distroless base image, we should be able to preserve those in the same way we preserve copyright.

> Also, how does your approach compare to using bazel to build docker imagse?

Well, currently I'm using a multi-stage dockerfile but the overall approach can be implemented many ways.

Multi-stage dockerfiles can be pinned to pull source images by digest and are relatively hermetic since they're inherently a sandboxed filesystem. If we have any concerns with this, we could also pull the package contents directly and add them to an image. The bazel rules_docker package largely wraps https://github.com/google/containerregistry

Bazel is also slightly a moot point for kubernetes following https://github.com/kubernetes/enhancements/issues/2420

**Comment by BenTheElder** [comment]
@tallclair nudged me about this, digging around shows that distroless images persist package versions by putting the package control file in `/var/lib/dpkg/status.d/$package`, which is _close_ to normal dpkg `/var/lib/dpkg/status` (one big file with a blank line between packages, and some additional info beyond the control file)

Source: https://github.com/bazelbuild/rules_docker/commit/f5432b813e0a11491cf2bf83ff1a923706b36420

Scanners already need to implement support for this to handle our other distroless images.

We can very easily grab the package status and stage it along with the copyright and libraries we need for each binary, you can see this added to my prototype here:

https://github.com/kubernetes-sigs/kind/pull/2624/commits/6957f378cf6506885318507e4cbd9320f94eda96 (first commit in https://github.com/kubernetes-sigs/kind/pull/2624)

**Comment by BenTheElder** [comment]
I think if we wanted to continue with this approach for the iptables image it would look like:
1) rewrite the iptables / iptables-nft select hack script to be a static go binary instead of a shell script
2) convert the image build to look like kubernetes-sigs/kind images/haproxy, but instead of haproxy do the iptables binaries and stage them and their libraries, add the version select script + symlinks

Then we'd have an image with just iptables binaries, their library dependencies, tzdata etc. from distroless base, their copyright files, and their dpkg statuses, along with some symlinks and a go binary for switching between iptables-legacy and iptables-nft.

That image should be smaller and have less vulnerability scanner alerts.

Step 1) is probably reasonable to consider regardless of step 2) anyhow, if someone wanted to take this up. You'll need to talk to SIG Network about these changes first though. This new image would also be a breaking change for any other projects that base on debian-iptables.

**Comment by dims** [comment]
/milestone v1.25

kick this down the road, no activity.

**Comment by helayoty** [comment]
@dims @tallclair 👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this Issue and if we are still targeting the current release.

**Comment by dims** [comment]
@helayoty there was progress (please see #https://github.com/kubernetes/kubernetes/issues/109406), we will have to take an inventory when 1.26 opens up. 

/milestone v1.26

**Comment by salaxander** [comment]
Heya @dims and @tallclair - 1.26 bug triage team checking in to see how we're looking for this release?

Thanks!

**Comment by dims** [comment]
@salaxander the last thing we wanted to do here was distroless kubeproxy which got done already.

- https://groups.google.com/g/kubernetes-sig-network/c/CbqCwv4zLq4/m/3MZEPAWXAAAJ
- https://github.com/kubernetes/kubernetes/pull/111060

We should close this out! thanks everyone!

**Comment by dims** [comment]
@rikatz Do you mind doing a quick update to https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/1729-rebase-images-to-distroless/README.md and https://github.com/kubernetes/sig-release/blob/master/release-engineering/baseimage-exception-list.md to reflect the fact that we now have kubeproxy with distroless images? thanks!

**Comment by BenTheElder** [comment]
We should probably still make distroless kubeproxy lighter and make sure our projects pick it up so we can phase out the old full image, do we have follow-up issues for getting the shell etc out of there and making sure we've rolled out the image to subprojects?
