### ISSUE TITLE
[UMBRELLA ISSUE] Prune hub-typed clienset/informer/lister from k/k

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#70657]
/kind cleanup
/sig  api-machinery
/priority important-longterm

all hub type should be scoped in the handler. as the dependencies from admission/controllers are removed, we are now able to prune the legacy hub-typed clientset/informer/lister from kube-apiserver.

- [x] aggregator hub clientset/informer/lister #69683 #79418
- [x] master hub informer/lister
    - #70174 Switch to versioned types in bootstrap token authenticator
    - #70217 The actual switch
- [x] master hub clientset
    - #70409 Use loopback connection in master endpoint lease
    - #70520 Switch to versioned types in ca registration hook
    - #70950 Switch to versioned clientset for kubectl describer #71104 #71101
    - #75616 Removes internal client usages in e2e test.
    - #71136 Literally the switch
- [x] apiextensions hub clientset/informer/lister #84005
- [ ] trim code-generator and its scripts
