### ISSUE TITLE
Umbrella: dynamic audit configuration to beta

### ISSUE THREAD

**Issue by pbarker** [kubernetes/kubernetes#70816]
This holds a list of issues to be completed before dynamic audit configuration moves to beta.

- [ ] scalability tests https://github.com/kubernetes/kubernetes/issues/70814
- [ ] webhook authentication https://github.com/kubernetes/kubernetes/issues/70815
- [ ] complete policy https://github.com/kubernetes/kubernetes/issues/70818 (nice to have, not required)
- [ ] cheap buffers https://github.com/kubernetes/kubernetes/pull/70560
- [x] e2e test https://github.com/kubernetes/kubernetes/pull/70036
- [x] integration test https://github.com/kubernetes/kubernetes/pull/69902
- [ ] webhook versioning https://github.com/kubernetes/kubernetes/issues/71464
- [ ] remove feature gate and update api version https://github.com/kubernetes/kubernetes/pull/73981

**Comment by tallclair** [comment]
IMO, the complete policy doesn't need to block the beta.

**Comment by tallclair** [comment]
Putting this in the v1.14 milestone to be consistent with the [enhancement tracker](https://github.com/kubernetes/enhancements/issues/600). If we think it's going to slip, we should update both.
/milestone v1.14

**Comment by shturec** [comment]
Bringing it up here because slack invites are offline and can't get in touch.   
What's the reason for treating "complete policy" as a nice to have now? The out-of-tree PoC seems to have advanced. Why wouldn't it make into the beta?

**Comment by pbarker** [comment]
Hey @shturec, we would like to get policy in as soon as possible but there are many things to consider here and API reviewers don't have much bandwidth right now.

**Comment by krmayankk** [comment]
Hello from  Bug Triage Shadow .  I'd like to remind that code freeze is coming in 3 days (Friday, 8th March). ❄️ 🏔 Is this still planned  to be fixed for 1.14?

**Comment by soggiest** [comment]
@pbarker we're well into Bug Freeze and there seems to be quite a bit of work associated with this. Can we move it to 1.15?

**Comment by pbarker** [comment]
yes no problem @soggiest, thank you

**Comment by tallclair** [comment]
/milestone v1.16

Moving this to v1.16 to keep in sync with https://github.com/kubernetes/enhancements/issues/600.

**Comment by tamalsaha** [comment]
We would like to see this issue make progress on 1.16 cycle. Are there any blockers beyond review bandwidth?

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16? If not please re-tag the issue to the planned milestone.
