### ISSUE TITLE
Trace works about enable the ipvs mode for the kube-proxy by default

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#71202]
This issue is to trace the works about make IPVS mode as kube-proxy default mode.
/kind feature

- [ ] kube-proxy IPVS spurious logs removing IPv6 address. #70113
- [ ] kube-proxy ipvs auto detect network interface mtu. #68546 (WIP)
- [ ] In ipv6-only cluster with proxy-mode=ipvs ipv4 entries are used for NodePort. #68437 (WIP)
- [ ] Unable use localhost:<nodeport> with IPVS. #67730 (WIP)
- [ ] IPVS is not working with hostport. #66103
- [ ] Make IPVS as default kube-proxy mode.

@luxas @timothysc @m1093782566 @bowei @caseydavenport @cmluciano , Please check.

**Comment by m1093782566** [comment]
cc @thockin @rramkumar1

**Comment by Lion-Wei** [comment]
https://github.com/kubernetes/kubernetes/issues/68974 and #65820 are solved issue, so I didn't put them on the list, seems both those two issue can be closed. : )

**Comment by timothysc** [comment]
Are you intending to target 1.14?

**Comment by luxas** [comment]
> Are you intending to target 1.14?

ping @Lion-Wei

**Comment by m1093782566** [comment]
Yes，we are
发件人：Lucas Käldström
收件人：kubernetes/kubernetes,
抄 送：dujun (D),Mention,
时间：2018-12-04 21:03:57
主 题：Re: [kubernetes/kubernetes] Trace works about enable the ipvs mode for the kube-proxy by default (#71202)


Are you intending to target 1.14?

ping @Lion-Wei<https://github.com/Lion-Wei>

**Comment by luxas** [comment]
Ok. We need to extensively build out e2e testing for this then.

**Comment by luxas** [comment]
cc @kubernetes/sig-testing @kubernetes/sig-cluster-lifecycle @kubernetes/sig-network-feature-requests @kubernetes/sig-architecture-feature-requests for visibility, as this is significant

**Comment by BenTheElder** [comment]
not sure what coverage we have for this currently (had to track it all!), but we definitely need thorough e2e coverage if we're going to flip defaults. FYI @spiffxp

**Comment by m1093782566** [comment]
There are already some test grids for IPVS proxier.

**Comment by dghubble** [comment]
Some of the issues listed (in particular, not working with hostport #66103) have hindered adopting IPVS in clusters, let alone considering it the default. Since these were missed when IPVS mode was called GA, is there some other maturation window envisioned?

**Comment by justaugustus** [comment]
Given @dghubble's feedback, I'd like to see a KEP for this that includes well-defined graduation criteria.

**Comment by uablrek** [comment]
In the ipv4/ipv6 dual-stack kep https://github.com/kubernetes/enhancements/pull/648 ipvs support is still only "nice-to-have". If proxier ipvs is default one may have to "downgrade" to iptables to get dual stack.
IMO ipvs should be supported also for dual stack.

**Comment by Quentin-M** [comment]
https://github.com/kubernetes/kubernetes/issues/71071

**Comment by luxas** [comment]
@uablrek Yes, but in ipv6-only cluster ipvs should still work out-of-the-box without a "downgrade" to iptables, right?

Also I noticed this fun thing that ipvs is marked as experimental still in the CLI:
```
--proxy-mode ProxyMode
    Which proxy mode to use: 'userspace' (older) or 'iptables' (faster) or 'ipvs' (experimental). If blank, use the best-available proxy (currently iptables).  If the iptables proxy is selected, regardless of how, but the system's kernel or iptables versions are insufficient, this always falls back to the userspace proxy.
```

**Comment by nikopen** [comment]
Greetings!

:mountain_snow: code freeze :mountain_snow:  is coming in about 10 days, is this intented to be implemented in the following 2-3 weeks?

@m1093782566 @Lion-Wei

**Comment by soggiest** [comment]
Hello! Code freeze for 1.14 is coming up in 2 days. Will this be implemented in the next week? Or should we punt until 1.15?

@m1093782566 @Lion-Wei

**Comment by m1093782566** [comment]
Sound fair, we can put it to 1.15 cycle.

**Comment by uablrek** [comment]
It *must* be clearified that proxy-mode=ipvs does **not** work in an ipv6-only cluster.

The support for ipv6 in proxy-mode=ipvs is re-classified as a "feature" in #65006

**Comment by uablrek** [comment]
@luxas 

About https://github.com/kubernetes/kubernetes/issues/71202#issuecomment-445444687, apparently proxy-mode=ipvs was not intended to work with ipv6.

**Comment by dims** [comment]
/remove-sig architecture

please re-tag arch if needed, looks like all items fall under sig-network

**Comment by rikatz** [comment]
So we've been discussing about the evolution of kube-proxy and the maintainability of the modes (IPtables, ipvs, and so on) and we've reached a consensus that  we need to evolve the vendoring of kube-proxy logics, modules (also take a look at: https://github.com/kubernetes-sigs/kpng)

So right now, talking with other sig-network folks, (@thockin @aojea @jayunit100 @uablrek ) we think this is not a movement we want to do right now (defaulting to IPVS)  so I'm closing this issue :)

Thanks!

/close
