### ISSUE TITLE
Umbrella issue - Update DropDisabled[Alpha]Fields behavior

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#72169]
Over the past several months, there have been multiple discussions about how to safely evolve API types in a way that enables safe rolling upgrade, safe single-version downgrade, and safely disabling a problematic feature even with existing persisted data.

One of the outcomes was a tweak to the guidance around how fields for disabled features are dropped and validated. https://github.com/kubernetes/community/pull/3040 contains the updated guidance.

This issue tracks sweeping the handling of existing conditional fields to follow that approach.

https://github.com/kubernetes/kubernetes/pull/70490/commits/de96583d8cc3b8ab63b53d64f7af88430e862b0f demonstrates the desired approach, and https://github.com/kubernetes/kubernetes/pull/70490/commits/c4a02542015c9812ef0c6df9fd0c8d96dbfa902a demonstrates dropping the problematic validation.

* [ ] s/DropDisabledAlphaFields/DropDisabledFields/g
* [ ] pass new and existing object to the DropDisabledFields functions
* [ ] PersistentVolume
  * [ ] `VolumeMode`
  * [x] `PersistentVolumeSource.CSI`
* [ ] PersistentVolumeClaim
  * [ ] `VolumeMode`
* [ ] PodSpec
  * [ ] `Priority` / `PriorityClassName` - @sbezverk 
  * [ ] `Volumes[*].EmptyDir.SizeLimit`
  * [x] `Containers[*].VolumeMounts[*].SubPath` - @liggitt, #70490
  * [ ] `Containers[*].VolumeDevices`
  * [ ] `SecurityContext.RunAsGroup` / `Containers[*].SecurityContext.RunAsGroup`
  * [ ] `RuntimeClassName`
  * [ ] `Containers[*].SecurityContext.ProcMount`
* [ ] PodSecurityPolicy
  * [ ] `AllowedProcMountTypes`
  * [ ] `RunAsGroup`
* [ ] StorageClass
  * [ ] `VolumeBindingMode`
  * [ ] `AllowedTopologies`

/assign
/milestone v1.14
/sig api-machinery
/kind cleanup
/priority important-soon

**Comment by mourya007** [comment]
@liggitt I would like to work on the PodSecurityPolicy.

**Comment by liggitt** [comment]
> @liggitt I would like to work on the PodSecurityPolicy.

sounds good, can you take the AllowedProcMountTypes field?

**Comment by liggitt** [comment]
opened follow-up tracker to address removing feature-gate-conditional validation - https://github.com/kubernetes/kubernetes/issues/72651
