### ISSUE TITLE
Umbrella: Remove feature-gate-conditional validation for existing objects

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#72651]
This is a follow-up to https://github.com/kubernetes/kubernetes/issues/72169 to sweep API object validation to remove conditional logic that can cause problems for existing objects across skewed API servers, or if a feature gate is disabled after having been enabled.

This is the list of feature gates that are currently checked in validation, and the work required to make them safe for skewed apiserver scenarios:

- [x] AppArmor - @liggitt, https://github.com/kubernetes/kubernetes/pull/72655
  - plumb `podAnnotations`, `oldPodAnnotations` into `pod#DropDisabledFields`, update callers
  - add logic to `pod#DropDisabledFields` that removes apparmor-prefixed annotations from `podAnnotations` if the `AppArmor` feature-gate is disabled and `oldPodAnnotations` did not contain any apparmor-prefixed annotations
  - remove the `AppArmor` feature-gate check in validation.go
- [x] ResourceQuotaScopeSelectors - @sbezverk, https://github.com/kubernetes/kubernetes/issues/72664
  - create a `resourcequota#DropDisabledFields` utility (following `persistentvolume#DropDisabledFields` as an example) and call it from the resourcequota PrepareForCreate/PrepareForUpdate strategy methods
  - add logic to `resourcequota#DropDisabledFields` to set `resourceSpec.ScopeSelector` to nil if the `ResourceQuotaScopeSelectors` feature is disabled and `oldResourceQuotaSpec` does not have `ScopeSelector` set
  - remove the `ResourceQuotaScopeSelectors` feature gate check from validation.go#validateScopeSelector
- [x] PersistentLocalVolumes - @sbezverk, https://github.com/kubernetes/kubernetes/pull/72686
  - add logic to `persistentvolume#DropDisabledFields` to set `pvSpec.PersistentVolumeSource.Local` to nil if the `PersistentLocalVolumes` feature is disabled and `oldPVSpec` does not have `PersistentVolumeSource.Local` set
  - remove the `PersistentLocalVolumes` feature-gate check in validation.go
- [x] VolumeSnapshotDataSource - @rajathagasthya, https://github.com/kubernetes/kubernetes/pull/72666
  - add logic to `persistentvolumeclaim#DropDisabledFields` to set `pvcSpec.DataSource` to nil if the `VolumeSnapshotDataSource` feature is disabled and `oldPVCSpec` does not have a non-nil DataSource
  - remove the `VolumeSnapshotDataSource` feature gate check from validation.go#ValidatePersistentVolumeClaimSpec
- [x] PodShareProcessNamespace - @rajathagasthya, https://github.com/kubernetes/kubernetes/pull/72698
  - add logic to `pod#DropDisabledFields` to set `podSpec.SecurityContext.ShareProcessNamespace` to nil if the `PodShareProcessNamespace` feature is disabled and `oldPodSpec` does not have `SecurityContext.ShareProcessNamespace` set
  - remove the `PodShareProcessNamespace` feature gate check from validation.go#ValidatePodSecurityContext
- [x] PodReadinessGates - @rajathagasthya, https://github.com/kubernetes/kubernetes/pull/72695
  - add logic to `pod#DropDisabledFields` to set `podSpec.ReadinessGates` to nil if the `PodReadinessGates` feature is disabled and `oldPodSpec` does not have `ReadinessGates` set
  - remove the `PodReadinessGates` feature gate check from validation.go#validateReadinessGates
- [x] Sysctls, @rajathagasthya, https://github.com/kubernetes/kubernetes/pull/72752
  - add logic to `podsecuritypolicy#DropDisabledFields` to drop `spec.AllowedUnsafeSysctls` and `spec.ForbiddenSysctls` if the `Sysctls` feature is disabled and the old psp is nil or has both of those fields set to nil
  - add logic to `pod#dropDisabledFields` to drop `spec.SecurityContext.Sysctls` if the `Sysctls` feature is disabled and the old pod is nil or has that field set to nil
  - remove the `Sysctls` feature gate check from `ValidatePodSecurityContext` and `validatePodSecurityPolicySysctls`
- [x] ExpandPersistentVolumes, @rajathagasthya, https://github.com/kubernetes/kubernetes/pull/72739
  - add logic to `persistentvolumeclaimStatusStrategy#PrepareForUpdate` to drop `newPv.Status.Conditions` if `oldPv.Status.Conditions` is nil
  - remove the `ExpandPersistentVolumes` feature gate check from `ValidatePersistentVolumeClaimStatusUpdate`
- [x] TokenRequestProjection - @mourya007, https://github.com/kubernetes/kubernetes/pull/72714
  - add logic to `pod#DropDisabledFields` to set `podSpec.Volumes[*].Projected.Sources[*].ServiceAccountToken` to nil if the `TokenRequestProjection` feature is disabled and `oldPodSpec` does not have any `ServiceAccountToken` projected volumes
  - remove the `TokenRequestProjection` feature gate check from validation.go#validateProjectionSources
- [x] CustomPodDNS, @MrHohn, https://github.com/kubernetes/kubernetes/pull/72832
  - graduate to GA and stop honoring the feature gate in 1.14
- [x] HugePages, @derekwaynecarr, https://github.com/kubernetes/kubernetes/pull/72785
  - graduate to GA and stop honoring the feature gate in 1.14
- [x] SCTPSupport, @liggitt - https://github.com/kubernetes/kubernetes/pull/73774
  - Move conditional SCTPSupport validation to validation functions with knowledge of the old and new object
  - Change the validation to only forbid the ProtocolSCTP value if the feature is disabled AND the old object was not using the value
  - Call the conditional validation from the Validate/ValidateUpdate strategy methods for relevant objects

/assign

**Comment by mourya007** [comment]
@liggitt  I would like to work on these, if nobody has  taken yet.

**Comment by rajathagasthya** [comment]
@liggitt I can take a few once the work is identified. Thanks!

**Comment by sbezverk** [comment]
@liggitt I can look into ` PersistentLocalVolumes`

**Comment by liggitt** [comment]
@sbezverk, can you take ResourceQuotaScopeSelectors ?
@mourya007, can you take PersistentLocalVolumes?
@rajathagasthya, can you take VolumeSnapshotDataSource?

**Comment by mourya007** [comment]
> @sbezverk, can you take ResourceQuotaScopeSelectors?
> @mourya007, can you take PersistentLocalVolumes?
> @rajathagasthya, can you take VolumeSnapshotDataSource?

@liggitt Sure I will take this and  Can I work on the AppArmor also along with the PersistantLocalVolumes ?

**Comment by liggitt** [comment]
> Can I work on the AppArmor also

I was going to take that one since it requires plumbing addition info into the strategy field-clearing methods

**Comment by mourya007** [comment]
@liggitt ok no issue , thanks

**Comment by truongnh1992** [comment]
Could I work on some of items in TBD?

**Comment by liggitt** [comment]
> @liggitt Can I take PodShareProcessNamespace and PodReadinessGates as well while I'm at it?

sure... let's keep it in a separate PR so we can pipeline reviews/merges

**Comment by liggitt** [comment]
> Could I work on some of items in TBD?

Once the work is planned out, sure. The TBD ones are a bit more involved, was planning to get the simple ones reviewed and merged first.

**Comment by mourya007** [comment]
@liggitt  Can i take  TokenRequestProjection ?

**Comment by liggitt** [comment]
cc @derekwaynecarr @MrHohn 

can we graduate the HugePages and CustomPodDNS features to GA in 1.14 and remove feature gate checks, rather than trying to untangle their conditional validations? both have been enabled by default since 1.10

**Comment by rajathagasthya** [comment]
@liggitt I'm looking at `ExpandPersistentVolumes`. What changes are required for `TestValidatePersistentVolumeClaimStatusUpdate`? I made the other changes, but not sure about the test cases since both the scenarios there seem to depend on the feature gate.

**Comment by liggitt** [comment]
> @liggitt I'm looking at `ExpandPersistentVolumes`. What changes are required for `TestValidatePersistentVolumeClaimStatusUpdate`?

No change is required there... that check allows limited *changes* to that part of the object when the feature is enabled. The logic when the feature is disabled does not do anything that would invalidate existing data that was persisted while the feature was enabled, which is the present concern.

**Comment by MrHohn** [comment]
> can we graduate the HugePages and CustomPodDNS features to GA in 1.14 and remove feature gate checks, rather than trying to untangle their conditional validations? both have been enabled by default since 1.10

For CustomPodDNS (https://github.com/kubernetes/enhancements/issues/504) we are ready to promote it to GA and the change should be minimal. Will try to shot a PR soon.

cc @bowei

**Comment by derekwaynecarr** [comment]
@liggitt i think we probably could graduate hugepages, and handle the future concerns around topology alignment to a separate feature as it has no impact on the API, just kubelet behavior.

**Comment by liggitt** [comment]
> @liggitt i think we probably could graduate hugepages, and handle the future concerns around topology alignment to a separate feature as it has no impact on the API, just kubelet behavior.

great, thanks. I opened https://github.com/kubernetes/kubernetes/pull/72784 with a hold on it and assigned it to you and Dawn
