### ISSUE TITLE
Extensibility features - Path to GA

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#73185]
This is an umbrella issue to track all bugs/enhancements required to declare Kubernetes extensibility features GA. Specifically it tracks "Admission Webhooks" and "Custom Resource Definitions". The goal is to have a usable, supportable feature with stable GA API.

# Admission Webhooks
*API*: These are issues/design requests that could affect a stable API:

Discussed on [2019-01-23](https://github.com/kubernetes/kubernetes/issues/73185#issuecomment-457052979) and [2019-01-28](https://github.com/kubernetes/kubernetes/issues/73185#issuecomment-458287902):
- [ ] ~~`AdmissionReview` to v1, allow webhooks to indicate the version(s) of admission review they can receive~~ tracked in https://github.com/kubernetes/kubernetes/issues/79893
- [x] finer control over webhook target (#57964)
  - [x] objectSelector to select on object labels
  - [x] scope to select namespaced/cluster-scoped/all
- [x] expose timeout control via API (#60914)
- [x] allow ports other than 443 for the service reference
- [ ] ~~allow http localhost for webhook URL~~
- [x] pass existing object(s) to admission for DELETE operations
- [x] rerun mutating admission in the presence of mutating webhook changes (resolves plugin ordering problem  ([discussion issue](https://github.com/kubernetes/kubernetes/issues/73291))
- [x] pass {Create,Update,Patch,Delete}Options to admission ([discussion issue](https://github.com/kubernetes/kubernetes/pull/68873))

Discussed and declined/deferred:
- [ ] Decision on request to reference CA trust bundle via secret/configmap reference instead of inline ([discussion issue](https://github.com/kubernetes/kubernetes/issues/72944))
- [ ] Decision on whether new webhook auth mechanism is required for GA ([Discussion issue](https://github.com/kubernetes/enhancements/pull/658))

*documentation/test*:
- Cluster Admin Guide to Admission Webhooks
- Test client authentication in admission webhook e2e test (#54709)
- Performance test for mutating and non-mutating webhooks (TODO(@mbohlool): issue with more details)
- Measure the performance cost of creating a selector per webhook call and cache namespace selector if necessary (TODO(mbohlool): issue with more details)

# Custom Resource Definitions
Todo(@mbohlool): Add issues from Doc.

@kubernetes/sig-api-machinery-misc 
cc: @liggitt @sttts @deads2k @lavalamp @caesarxuchao @roycaihw @erictune @fedebongio

**Comment by caesarxuchao** [comment]
Another potential API change: https://github.com/kubernetes/kubernetes/issues/72944

**Comment by caesarxuchao** [comment]
We didn't get a chance to discuss https://github.com/kubernetes/kubernetes/issues/72944 in the meeting, @liggitt can you comment in that issue? Thanks.

**Comment by mengqiy** [comment]
Another thing that was discussed in https://github.com/kubernetes/kubernetes/pull/68873#issuecomment-451586879.
We need decision regarding how webhooks handles `{Create,Update,Delete}Options`.

**Comment by liggitt** [comment]
remaining issues are tracked in individual issues and in https://github.com/orgs/kubernetes/projects/32

/close
