### ISSUE TITLE
CSI Inline Volume Implementation Umbrella Issue

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#73929]
**What would you like to be added**:

This is an umbrella issue to track for the implementation of the CSI Inline Volume.

**Why is this needed**:
Please see KEP for detail - https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190122-csi-inline-volumes.md

## Persistent Inline Volume Tasks
* [x] Update KEP with suggestions (@vladimirvivien)
* [x] Rebase existing code in https://github.com/kubernetes/kubernetes/pull/68232 (@vladimirvivien) 
* [ ] Add field `Lifecycle` to `CSIDriver` API object
* [x] Update/implement persistent inline volume for intree CSI code (@vladimirvivien )
* [ ] Start code review (via SIG node, SIG arc) (@vladimrvivien)
* [x] Update/implement unit tests for persistent inline volume for intree code (@vladimirvivien )
* [ ] Create e2e tests for persistent inline deployments
* [ ] Update/implement persistent inline attachment in external provisioner

## Ephemeral Inline Volume Tasks
* [ ] Update intree code to support Ephemeral 
* [ ] Add unit tests for ephemeral use cases
* [ ] Update/implement host path CSI driver to support ephemeral
* [ ] e2e tests for ephemeral volume deployments
