### ISSUE TITLE
Umbrella issue for Publish CRD OpenAPI followups

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#74976]
This is to track follow-up tasks for Publish CRD OpenAPI https://github.com/kubernetes/kubernetes/pull/71192

**in 1.14:**
- [x] Add e2e test to sig-cli for current kubectl client-side validation behavior around CustomResources (not depending on the openapi publish feature) https://github.com/kubernetes/kubernetes/pull/74832
- [x] Website documentation https://github.com/kubernetes/website/pull/12910

**post-1.14:**
- [ ] Move definition code-generation to k8s.io/apiextensions-apiserver (related: https://github.com/kubernetes/kubernetes/pull/74133)
- [ ] Unify openapi path generation between CRD and native resources (i.e. builder.go) (https://github.com/kubernetes/kubernetes/pull/75736)
- [ ] Fix too-strict client-side validation (https://github.com/kubernetes/kube-openapi/pull/143, https://github.com/kubernetes/kube-openapi/pull/147)
- [x] Add alpha feature tests to CI https://github.com/kubernetes/test-infra/pull/11618#issuecomment-469863921 (https://github.com/kubernetes/test-infra/pull/12070)
- [x] Remove `[Feature:XXX]` tag from e2e tests so they get run by default when we go to beta
- [ ] Long-term solution for coordinating between KAS replicas in HA https://github.com/kubernetes/kubernetes/pull/76388
   - general issue: https://github.com/kubernetes/kubernetes/issues/57213
   - general design proposal: https://groups.google.com/d/msg/kubernetes-sig-api-machinery/gTS-rUuEVQY/9bUFVnYvAwAJ

**clean up:**
- [x] Move `schemaFoo` and `PatchSchema` method (and etc.) to test/e2e/framework/crd_util.go, to be shared by https://github.com/kubernetes/kubernetes/pull/74832 and https://github.com/kubernetes/kubernetes/pull/71192

/sig api-machinery
cc @liggitt @mbohlool @sttts

**Comment by liggitt** [comment]
tasks are tracked in individual items, closing this

/close
