### ISSUE TITLE
Tracking issue for WG Component Standard Work

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#75426]
This issue is to track the broad areas of work being performed by wg-component-standard.
We may want to move it to another location, e.g. component-base repo (but for now can't create issues there).

Overall enhancement issue: https://github.com/kubernetes/enhancements/issues/783

# Flags and ComponentConfig

## Serializers
- [x] Implement a dedicated serializer package for ComponentConfigs
  - https://github.com/kubernetes/kubernetes/pull/74111
  - strict codec, multiple objects, etc.

## Testing
- [ ] Greatly increase test coverage for ComponentConfigs
  - https://github.com/kubernetes/kubernetes/pull/72778
  - testing framework for the ComponentConfig pattern

## Helper Libraries
- [ ] legacyconfig (née kflag)
  - KEP: https://github.com/kubernetes/enhancements/pull/764
  - Example: https://github.com/kubernetes/kubernetes/pull/73494
  - Flag registration shim that makes value application more flexible
- [x] Move flag util pkgs to k8s.io/component-base/cli
  - https://github.com/kubernetes/kubernetes/pull/73408

### *-controller-manager
- [ ] kube-controller-manager ComponentConfig
  - https://github.com/kubernetes/enhancements/issues/786
- [x] Move config local to every controller in KCM
  - https://github.com/kubernetes/kubernetes/pull/72800
  - give each controller its own config type
- [ ] add typemeta to every sub-controller configuration, so we can serializable config for KCM
  - https://github.com/kubernetes/kubernetes/pull/74059
- [ ] Add support for configuring kube-controller manager via a config file instead of command line flags
  - https://github.com/kubernetes/kubernetes/pull/70359
- [x] Implement the --controllers flag fully for the cloud-controller manager
  - https://github.com/kubernetes/kubernetes/pull/68283
  - flag that allows controllers to be enabled/disabled in cloud-controller-manager

### kube-scheduler
- [ ] Graduate the kube-scheduler ComponentConfig to v1beta1
  - https://github.com/kubernetes/enhancements/issues/785

### kube-proxy
- [ ] Graduate the kube-proxy ComponentConfig to v1beta1
  - https://github.com/kubernetes/enhancements/issues/784

### kubelet
- [ ] kubelet.config.k8s.io to GA
  - [ ] Many flags still need to be migrated to config.
  - [ ] Consider refactoring to simplify dynamic config (see below).
  - [ ] Provide a solution for instance-specific Kubelet configuration: https://github.com/kubernetes/kubernetes/issues/61647
  - [ ] Provide a solution for os-specific component config: https://github.com/kubernetes/kubernetes/issues/61649
- Dynamic Kubelet config
  - Dynamic config is hard to bootstrap: https://github.com/kubernetes/kubernetes/issues/71374
  - The APIs exposed may be too low level in many cases.
    - Revisit the conversation on whether to expose a subset. Potentially via policy objects.
    - When we solve instance-specific config (above), consider making many of the low level options
      (e.g. cgroup names) part of the instance-specific config; even though they *can* be shared,
      live modification can be dangerous and most people probably won't want to.

# Log standardization

- [x] Move logs from apiserver to component-base
  - https://github.com/kubernetes/kubernetes/pull/72890

# Open Questions
- How do we allow configs to be composable in controller-managers?
- What is the vision for logging we want in Kubernetes?

**Comment by SergeyKanzhelev** [comment]
@mtaufen is this group still active? Should this issue be closed as it had no activity for a while?

**Comment by mtaufen** [comment]
Not active for some time. I've been a bad citizen and haven't gotten to officially dissolving it yet :(.

We can close it if it's just creating noise, I think the content is pretty outdated anyway.
