### ISSUE TITLE
Projected service account token: make sure all system components have updated client-go

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#75551]
**What happened**:
As an example, metrics server hasn't been updated: https://github.com/kubernetes-incubator/metrics-server/issues/232

For me, this caused namespace deletion to fail after the token got rotated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alpha cluster (mine was 1.14)
2. Let it sit for a while (mine was a few hours but it could take less)
3. Create an empty ns
4. Delete the ns will hang

apiserver logs show:
```
E0321 00:32:36.459769       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, Token has expired.]
I0321 00:32:36.460494       1 wrap.go:47] GET /api/v1/nodes?limit=500&resourceVersion=0: (4.386595ms) 401 [metrics-server/v0.0.0 (linux/amd64) kubernetes/$Format 35.193.27.95:47328]
```

Components:

```
kubeadm
```

- [x] coredns (CoreDNSVersion = "v1.8.0")

```
egrep -ohr 'image:.*' cluster/  | sort | uniq 
```

## sig-cluster-lifecycle?
- [x] image: k8s.gcr.io/addon-manager/kube-addon-manager:v9.1.4 - invokes kubectl repeatedly

## sig-networking
- [x] image:  k8s.gcr.io/networking/ingress-gce-404-server-with-metrics-amd64:v1.10.11 - kubernetes 1.18 - https://github.com/kubernetes/ingress-gce/blob/v1.10.11/go.mod
- [x] image: gcr.io/projectcalico-org/cni:v3.16.2 - https://github.com/kubernetes/kubernetes/issues/75551#issuecomment-822807601
- [x] image: gcr.io/projectcalico-org/node:v3.16.2 - https://github.com/kubernetes/kubernetes/issues/75551#issuecomment-822807601
- [x] image: gcr.io/projectcalico-org/typha:v3.16.2 - https://github.com/kubernetes/kubernetes/issues/75551#issuecomment-822807601
- [x] image: k8s.gcr.io/coredns:1.7.0
- [x] image: gcr.io/k8s-ingress-image-push/ingress-gce-glbc-amd64:v1.11.0 - kubernetes 1.18 - https://github.com/kubernetes/ingress-gce/blob/v1.11.0/go.mod
- [x] image: k8s.gcr.io/dns/k8s-dns-node-cache:1.17.0 - https://github.com/kubernetes/dns/blob/1.17.0/go.mod#L57 - https://github.com/kubernetes/client-go/commit/78d2af792bab - 1.15.0

**To fix:** (https://github.com/kubernetes/kubernetes/issues/101283)
- [ ] image: k8s.gcr.io/k8s-dns-dnsmasq-nanny:1.15.10 - https://github.com/kubernetes/dns/blob/1.15.10/Gopkg.toml#L70 - pre-1.14 libraries
- [ ] image: k8s.gcr.io/k8s-dns-kube-dns:1.15.10 - https://github.com/kubernetes/dns/blob/1.15.10/Gopkg.toml#L70 - pre-1.14 libraries
- [ ] image: k8s.gcr.io/k8s-dns-sidecar:1.15.10 - https://github.com/kubernetes/dns/blob/1.15.10/Gopkg.toml#L70 - pre-1.14 libraries
- [ ] image: k8s.gcr.io/networking/ip-masq-agent-amd64:v2.6.0 - tag unknown, master is at 1.13.x - https://github.com/kubernetes-sigs/ip-masq-agent/blob/master/Godeps/Godeps.json

## sig-node
- [x] image: "gcr.io/gke-release/nvidia-gpu-device-plugin@sha256:a75ec0caa9e3038bd9886b3f36641a624574ff34b064974de6ee45048de3372b" - @ruiwen-zhao, https://github.com/kubernetes/kubernetes/issues/75551#issuecomment-822798567
- [x] image: k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.5 - https://github.com/kubernetes/node-problem-detector/blob/v0.8.5/go.mod#L33 - https://github.com/kubernetes/client-go/commit/6502b5e7b1b5 - 1.14.5

**To fix:** (https://github.com/kubernetes/kubernetes/issues/101285)
- [ ] image: k8s.gcr.io/gke-node-termination-handler@sha256:aca12d17b222dfed755e28a44d92721e477915fb73211d0a0f8925a1fa847cca - https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/pull/14 - https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/blob/8aabd1dba354fc0f6d04b5cc145f7545608b0162/Gopkg.toml - 1.10-level libraries

## sig-instrumentation
- [x] image: k8s.gcr.io/fluentd-gcp-scaler:0.5.2 - Doesn't use client-go
- [x] image: gcr.io/stackdriver-agents/stackdriver-logging-agent:{{ fluentd_gcp_version }} (defaults to 1.6.17) - doesn't use client-go
- [x] image: gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.21-1 - c++, doesn't use client-go
- [x] image: docker.elastic.co/kibana/kibana-oss:7.4.2 - Doesn't use client-go
- [x] image: quay.io/fluentd_elasticsearch/fluentd:v3.1.0 - Doesn't use client-go
- [x] image: quay.io/fluentd_elasticsearch/elasticsearch:v7.4.3 - client-go v0.19.2

**To fix:** (#101341)
- [ ] image: k8s.gcr.io/event-exporter:v0.3.1 - Uses client-go 1.7: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/950d544a071c90a7fb1242a4d329fb1746e46870/event-exporter/Gopkg.lock#L561
- [ ] image: k8s.gcr.io/prometheus-to-sd:v0.5.0 - client-go 1.12: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/1e4b1f90ac378f25770c8a60e2c83ca1484752ca/prometheus-to-sd/Gopkg.lock#L450
- [ ] image: k8s.gcr.io/prometheus-to-sd:v0.7.2 - client-go 1.12: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/55b57bafadd5552625e58c52303446e8b82e47a9/prometheus-to-sd/Gopkg.lock#L450

## sig-autoscaling
- [x] image: k8s.gcr.io/metrics-server-amd64:v0.3.6 - https://github.com/kubernetes-sigs/metrics-server/blob/v0.3.6/Gopkg.toml#L86
- [x] image: k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.7.1 - https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/1.7.1/go.mod#L23 - https://github.com/kubernetes/client-go/commit/8e956561bbf5 - client-go 1.15.1
- [x] image: k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.8.1 - https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/1.8.1/go.mod#L23 - https://github.com/kubernetes/client-go/commit/8e956561bbf5 - client-go 1.15.1 
- [x] image: k8s.gcr.io/cpvpa-amd64:v0.8.3 - https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/blob/v0.8.3/go.mod - https://github.com/kubernetes/client-go/commit/8e956561bbf5 - client-go 1.15.1 

**To fix:** (https://github.com/kubernetes/kubernetes/issues/101286)
- [ ] image: k8s.gcr.io/addon-resizer:1.8.11 - Kubernetes 1.11 - https://github.com/kubernetes/autoscaler/blob/addon-resizer-1.8.11/addon-resizer/Godeps/Godeps.json#L1191

## sig-apimachinery?
- [x] image: k8s.gcr.io/kas-network-proxy/proxy-agent:v0.0.15 - https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/v0.0.15/go.mod
- [x] image: k8s.gcr.io/kas-network-proxy/proxy-server:v0.0.15 - https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/v0.0.15/go.mod
- [x] ~~image: k8s.gcr.io/etcd-version-monitor:0.1.3~~ no token use

## sig-testing
- [x] image: k8s.gcr.io/conformance-amd64:v1.14 - image doesn't even exist, k8s.gcr.io/conformance:v1.14.0 was built from 1.14.0
- [x] image: gcr.io/k8s-testimages/logexporter:v20200401-c3269f485 - doesn't use client-go - https://github.com/kubernetes/test-infra/blob/3928e8a2770bc1b58b80030ff5b7d2fee77ddde1/logexporter/cmd/main.go

## sig-auth?
- [x] ~~image: k8s.gcr.io/metadata-proxy:v0.1.12~~ no token or client-go use

## sig-storage
- [x] image: k8s.gcr.io/sig-storage/snapshot-controller:v3.0.2 - https://github.com/kubernetes-csi/external-snapshotter/blob/v3.0.2/go.mod#L21

## sig-ui
- [x] image: kubernetesui/dashboard:v2.0.1 - client-go v0.18 - https://github.com/kubernetes/dashboard/blob/v2.0.1/go.mod#L20
- [x] image: kubernetesui/metrics-scraper:v1.0.4 - https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/v1.0.4/go.mod#L31 - https://github.com/kubernetes/client-go/commit/6e378217e628 - https://github.com/kubernetes/kubernetes/commit/d9f3e96796e2d154b1d4caa156ba95ff9b01e5b2 - includes https://github.com/kubernetes/kubernetes/pull/72437

**Comment by msau42** [comment]
@kubernetes/sig-auth-bugs 

cc @mikedanese @liggitt

**Comment by mikedanese** [comment]
Thanks. I'll take a look.

**Comment by markyjackson-taulia** [comment]
@mikedanese Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still intended for 1.17?

**Comment by markyjackson-taulia** [comment]
Circling back on this. A kind reminder that code freeze for this release is on November 14. Is this issue still intended for 1.17? By end of week if there is not movement on this I will move to 1.18 milestone

**Comment by markyjackson-taulia** [comment]
@mikedanese Any update?

**Comment by markyjackson-taulia** [comment]
Sent a slack DM and will wait till 5 pm pst. If no response I will have to move this out of v1.18 milestone

**Comment by gianarb** [comment]
Hello @mikedanese  !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by mikedanese** [comment]
cc @happinesstaker @zshihang

**Comment by zshihang** [comment]
system components:
- [x] metrics-server
...

**Comment by desponda** [comment]
👋  1.21 Bug triage here! Is this still being targeted for 1.21 Milestone release?
@mikedanese @liggitt

**Comment by liggitt** [comment]
This is not required for 1.21, but is required for 1.22 (for bound service account token GA)

/milestone v1.22

**Comment by liggitt** [comment]
@ruiwen-zhao, please confirm the current version of gcr.io/gke-release/nvidia-gpu-device-plugin used in master either 1) does not contact the kubernetes API or 2) does so using a version of client-go at 1.14+

**Comment by ruiwen-zhao** [comment]
> @ruiwen-zhao, please confirm the current version of gcr.io/gke-release/nvidia-gpu-device-plugin used in master either 1) does not contact the kubernetes API or 2) does so using a version of client-go at 1.14+
The device plugin talks to kubelet on the node using kubelet's [DevicePlugin API](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1alpha/api.proto).


It uses [client-go 0.19.2](https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/vendor/modules.txt#L152) and [kubernetes 1.19.3 ].(https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/vendor/modules.txt#L144)

**Comment by zshihang** [comment]
- gcr.io/projectcalico-org/cni:v3.16.2: https://github.com/projectcalico/cni-plugin/blob/4c440351e94c89a39f64dfa701f45414a319b1e8/go.mod#L42
- gcr.io/projectcalico-org/node:v3.16.2: https://github.com/projectcalico/node/blob/540bae1729bff3fd201e78bac6a7e83a4ac0ae7e/go.mod#L21
- gcr.io/projectcalico-org/typha:v3.16.2: https://github.com/projectcalico/typha/blob/b31b460cbc273d82d3debdf222b7898a3683a8a0/go.mod#L20

**Comment by zshihang** [comment]
@coffeepac, @monotek could you check if quay.io/fluentd_elasticsearch/elasticsearch:v7.4.3 and quay.io/fluentd_elasticsearch/fluentd:v3.1.0 talk to API server? if they do, are they using client-go 1.14+

**Comment by liggitt** [comment]
took a stab at categorizing remaining images by sig

**Comment by liggitt** [comment]
> ## sig-instrumentation
> * [ ]  image: gcr.io/k8s-testimages/logexporter:v20200401-c3269f485
> * [ ]  image: k8s.gcr.io/event-exporter:v0.3.1
> * [ ]  image: k8s.gcr.io/fluentd-gcp-scaler:0.5.2
> * [ ]  image: k8s.gcr.io/prometheus-to-sd:v0.5.0
> * [ ]  image: k8s.gcr.io/prometheus-to-sd:v0.7.2
> * [ ]  image: kubernetesui/metrics-scraper:v1.0.4
> * [ ]  image: gcr.io/stackdriver-agents/stackdriver-logging-agent:{{ fluentd_gcp_version }} (defaults to 1.6.17)
> * [ ]  image: gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.21-1
> * [ ]  image: docker.elastic.co/kibana/kibana-oss:7.4.2
> * [ ]  image: quay.io/fluentd_elasticsearch/elasticsearch:v7.4.3
> * [ ]  image: quay.io/fluentd_elasticsearch/fluentd:v3.1.0

@kubernetes/sig-instrumentation-members, please sweep the listed images to determine:

1. whether they use the mounted service account token to contact the API server
2. if so, whether they are using a 1.14+ level of client-go

Images that use mounted service account tokens should use client-go 1.14+ in 1.22+ in order to pick up auto-rotated tokens correctly.

**Comment by dashpole** [comment]
`kubernetesui/metrics-scraper` is owned by sig-UI.

`gcr.io/k8s-testimages/logexporter` is part of test-infra: https://github.com/kubernetes/test-infra/tree/master/logexporter.

For the gcp-related images,

* k8s.gcr.io/prometheus-to-sd:v0.5.0 Uses client-go 1.12: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/1e4b1f90ac378f25770c8a60e2c83ca1484752ca/prometheus-to-sd/Gopkg.lock#L450
* k8s.gcr.io/prometheus-to-sd:v0.7.2 Uses client-go 1.12: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/55b57bafadd5552625e58c52303446e8b82e47a9/prometheus-to-sd/Gopkg.lock#L450
* k8s.gcr.io/event-exporter:v0.3.1 Uses client-go 1.7: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/950d544a071c90a7fb1242a4d329fb1746e46870/event-exporter/Gopkg.lock#L561
* k8s.gcr.io/fluentd-gcp-scaler Doesn't use client-go
* gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.17  Doesn't use client-go from what I can tell (its a fluentd fork) https://github.com/GoogleCloudPlatform/google-fluentd/tree/7bc59e309ceb51f20e9ed328919058c32c19ef04
* gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.21-1  Still looking for this one...

I'm not sure about the fluentd-elasticsearch images:

* docker.elastic.co/kibana/kibana-oss:7.4.2
* quay.io/fluentd_elasticsearch/elasticsearch:v7.4.3
* quay.io/fluentd_elasticsearch/fluentd:v3.1.0

@coffeepac do you know?

**Comment by coffeepac** [comment]
kibana:  no
fluentd: no
elasticsearch:  maybe, will edit comment after I check.

**Comment by liggitt** [comment]
> `kubernetesui/metrics-scraper` is owned by sig-UI.
> 
> `gcr.io/k8s-testimages/logexporter` is part of test-infra: https://github.com/kubernetes/test-infra/tree/master/logexporter.

thanks, moved those to the right sig groupings and tracked those down

**Comment by zshihang** [comment]
thanks everyone. all images are updated.

/close
