### ISSUE TITLE
Tracking Issue - PodSpec Coverage

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#76345]
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

Why is this needed:
Add or promote PodSpec coverage for conformance

/area conformance
/sig testing

**Comment by timothysc** [comment]
TODO:  Measure current field coverage and report back.  
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#pod-v1-core

**Comment by hh** [comment]
@timothysc results will look something like this unless you suggest otherwise:

```sql-mode
select distinct resource_field as field, param_kind as kind, 0 as hits, 0 as test_hits, 0 as conformance_hits
from api_resources_fields
where api_resource_name like '%PodSpec%'
order by field;
```

```sql-mode
             field             |                    kind                     | hits | test_hits | conformance_hits 
-------------------------------|---------------------------------------------|------|-----------|------------------
 activeDeadlineSeconds         | integer                                     |    0 |         0 |                0
 affinity                      | io.k8s.api.core.v1.Affinity                 |    0 |         0 |                0
 automountServiceAccountToken  | integer                                     |    0 |         0 |                0
 containers                    | io.k8s.api.core.v1.Container                |    0 |         0 |                0
 dnsConfig                     | io.k8s.api.core.v1.PodDNSConfig             |    0 |         0 |                0
 dnsPolicy                     | string                                      |    0 |         0 |                0
 enableServiceLinks            | integer                                     |    0 |         0 |                0
 ephemeralContainers           | io.k8s.api.core.v1.EphemeralContainer       |    0 |         0 |                0
 hostAliases                   | io.k8s.api.core.v1.HostAlias                |    0 |         0 |                0
 hostIPC                       | integer                                     |    0 |         0 |                0
 hostname                      | string                                      |    0 |         0 |                0
 hostNetwork                   | integer                                     |    0 |         0 |                0
 hostPID                       | integer                                     |    0 |         0 |                0
 imagePullSecrets              | io.k8s.api.core.v1.LocalObjectReference     |    0 |         0 |                0
 initContainers                | io.k8s.api.core.v1.Container                |    0 |         0 |                0
 nodeName                      | string                                      |    0 |         0 |                0
 nodeSelector                  | integer                                     |    0 |         0 |                0
 overhead                      | integer                                     |    0 |         0 |                0
 preemptionPolicy              | string                                      |    0 |         0 |                0
 priority                      | integer                                     |    0 |         0 |                0
 priorityClassName             | string                                      |    0 |         0 |                0
 readinessGates                | io.k8s.api.core.v1.PodReadinessGate         |    0 |         0 |                0
 restartPolicy                 | string                                      |    0 |         0 |                0
 runtimeClassName              | string                                      |    0 |         0 |                0
 schedulerName                 | string                                      |    0 |         0 |                0
 securityContext               | io.k8s.api.core.v1.PodSecurityContext       |    0 |         0 |                0
 serviceAccount                | string                                      |    0 |         0 |                0
 serviceAccountName            | string                                      |    0 |         0 |                0
 shareProcessNamespace         | integer                                     |    0 |         0 |                0
 subdomain                     | string                                      |    0 |         0 |                0
 terminationGracePeriodSeconds | integer                                     |    0 |         0 |                0
 tolerations                   | io.k8s.api.core.v1.Toleration               |    0 |         0 |                0
 topologySpreadConstraints     | io.k8s.api.core.v1.TopologySpreadConstraint |    0 |         0 |                0
 volumes                       | io.k8s.api.core.v1.Volume                   |    0 |         0 |                0
(34 rows)

```

**Comment by hh** [comment]
Fields that have tests we could promote, or slightly rewrite:

```
   podspec_field   |                                             test                                             
-------------------+----------------------------------------------------------------------------------------------
 dnsConfig         |  [sig-network] DNS should support configurable pod DNS nameservers
 dnsConfig         |  [sig-network] DNS should support configurable pod resolv.conf
 priorityClassName |  [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path
 readinessGates    |  [k8s.io] Pods should support pod readiness gates [NodeFeature:PodReadinessGate]
```

- [x] [[sig-network] DNS should support configurable pod DNS nameservers](https://github.com/kubernetes/kubernetes/pull/81964/files) Thanks @BobyMCbobs
- [ ]  [k8s.io] Pods should support pod readiness gates [NodeFeature:PodReadinessGate] [Promotion](https://github.com/kubernetes/kubernetes/pull/79875) failed, slight rewrite needed
- [ ] [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path - needs a [promotion](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/preemption.go#L307) and there is also a  [new test being written](https://github.com/kubernetes/kubernetes/pull/82546)
