### ISSUE TITLE
Reduce sizes of binaries

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#76506]
- [ ] [Evaluate use of google.golang.org/api/compute/v0.alpha](https://github.com/kubernetes/kubernetes/issues/76504)
- [ ] [Reduce size of VMWare library dependency](https://github.com/kubernetes/kubernetes/issues/66321)
- [ ] [Work with etcd folks to remove use of github.com/ugorji/go/codec](https://github.com/etcd-io/etcd/pull/10667)
- [ ] [Figure out how to rework credential providers](https://github.com/kubernetes/kubernetes/issues/74379) for the rancher/go-rancher dependency

Sizes of packages as of this morning:
```
2.0M    ./k8s.io/kubernetes/vendor/github.com/json-iterator/go.a
2.0M    ./k8s.io/kubernetes/vendor/github.com/vishvananda/netlink.a
2.2M    ./k8s.io/kubernetes/vendor/gonum.org/v1/gonum/lapack/gonum.a
2.5M    ./k8s.io/kubernetes/vendor/gonum.org/v1/gonum/blas/gonum.a
3.0M    ./k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/autoscaling.a
3.1M    ./k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/OpenAPIv2.a
3.4M    ./k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.a
4.0M    ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/object.a
4.3M    ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/methods.a
4.4M    ./k8s.io/kubernetes/vendor/github.com/rancher/go-rancher/client.a
6.3M    ./k8s.io/kubernetes/vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud.a
8.3M    ./k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute.a
9.7M    ./k8s.io/kubernetes/vendor/github.com/ugorji/go/codec.a
14M    ./k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2017-09-01/network.a
14M    ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v1.a
15M    ./k8s.io/kubernetes/vendor/github.com/xanzy/go-cloudstack/cloudstack.a
16M    ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.beta.a
20M    ./k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/ec2.a
20M    ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.alpha.a
28M    ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/types.a
```

Steps to gather latest sizes:
```
go build -a -v ./cmd/hyperkube 2>&1 | grep vendor | grep -v vendor/k8s.io > built.txt
cat built.txt | xargs -L 1 -I {} go build -o "{}.a" {}
find . -type f -name *.a -exec du -h {} \; | sort -h | grep -v vendor/k8s.io
```

**Comment by BenTheElder** [comment]
cc @mattjmcnaughton

**Comment by mattjmcnaughton** [comment]
Cool, thanks @BenTheElder !

For those following along, @dims and I have been chatting about how this KEP to [Build Kubelet without Docker](https://github.com/kubernetes/enhancements/pull/1546) could be a useful way to reduce Kubelet binary sizes (along with a couple of other benefits).

**Comment by luxas** [comment]
/remove-lifecycle rotten
/reopen

This doesn't seem "fixed" yet.

**Comment by frapposelli** [comment]
I believe we have a `providerless` target to build Kubernetes now. Is there any data available to compare that target and the numbers that @dims had in the issue above?

**Comment by jpeach** [comment]
Here's what I got building with `GOFLAGS="-tags=providerless,dockerless"`. The binaries build, but `providerless` doesn't seem to be plumbed through the tests, so `make all` fails to build.

| No tags | tags=providerless,dockerless | binary |
|--|--|--|
|  38M  |  38M | kubeadm
| 113M  |  62M | kube-apiserver
| 108M  |  56M | kube-controller-manager
|  39M  |  39M | kubectl
| 109M  |  59M | kubelet
|  38M  |  38M | kube-proxy
|  41M  |  41M | kube-scheduler

**Comment by BenTheElder** [comment]
:wave: Making the tests providerless is not something we have a solid plan for yet. The core components we do (SIG cloud provider owns this).

[kind](https://sigs.k8s.io/kind) builds binaries in this mode by default. These tags are meant for testing Kubernetes prior to future hard deletion of the code, they're not advertised for production and not used in releases intentionally. https://github.com/kubernetes/enhancements/pull/1180

Some of the packages in OP are not covered by this. Binaries are still pretty large IMHO

**Comment by BenTheElder** [comment]
Also we're not 100% able to delete everything cloud provider from the core components yet even in the "providerless" tag. Off the top of my head kubelet credential providers still had tight coupling (there's a plan in the works to use a plug-in / exec model going forward though).

**Comment by dims** [comment]
Adjusting the script as we no longer have hyperkube :)
```
to_build=$(rg "package main" ./cmd/ | cut -f 1-3 -d '/' | sort | uniq)
go build -a -v $to_build 2>&1 | grep -v k8s.io/ > built.txt
cat built.txt | xargs -L 1 -I {} go build -o "{}.a" {}
find . -type f -name "*.a" -exec du -h {} \; | grep -v k8s.io/ | sort -h
```

**Comment by dims** [comment]
everything above 1 MB are as follows:

```
1.1M	./debug/dwarf.a
1.1M	./github.com/Azure/go-autorest/autorest.a
1.1M	./github.com/gophercloud/gophercloud.a
1.1M	./github.com/spf13/afero.a
1.1M	./google.golang.org/api/tpu/v1.a
1.1M	./internal/profile.a
1.1M	./text/template.a
1.1M	./text/template/parse.a
1.2M	./crypto/x509.a
1.2M	./github.com/containerd/containerd/api/services/containers/v1.a
1.2M	./github.com/stretchr/testify/assert.a
1.2M	./go.etcd.io/etcd/raft.a
1.2M	./google.golang.org/protobuf/types/descriptorpb.a
1.3M	./encoding/gob.a
1.3M	./github.com/emicklei/go-restful.a
1.3M	./github.com/gophercloud/gophercloud/openstack/compute/v2/servers.a
1.3M	./github.com/vmware/govmomi/pbm/types.a
1.3M	./gopkg.in/square/go-jose.v2.a
1.4M	./github.com/cilium/ebpf.a
1.4M	./github.com/stretchr/objx.a
1.4M	./go.uber.org/zap/zapcore.a
1.4M	./syscall.a
1.5M	./go.opencensus.io/plugin/ochttp.a
1.6M	./github.com/gogo/protobuf/protoc-gen-gogo/descriptor.a
1.6M	./github.com/google/go-cmp/cmp.a
1.6M	./github.com/prometheus/procfs.a
1.6M	./gopkg.in/yaml.v2.a
1.6M	./math/big.a
1.7M	./github.com/vmware/govmomi/vim25/mo.a
1.7M	./google.golang.org/grpc/internal/transport.a
1.7M	./google.golang.org/protobuf/internal/filedesc.a
1.7M	./gopkg.in/yaml.v3.a
1.8M	./github.com/prometheus/client_golang/prometheus.a
1.8M	./github.com/prometheus/client_golang/prometheus/promhttp.a
2.0M	./github.com/containerd/containerd/api/services/tasks/v1.a
2.0M	./github.com/opencontainers/runc/libcontainer.a
2.2M	./github.com/spf13/pflag.a
2.3M	./reflect.a
2.4M	./github.com/docker/docker/client.a
2.4M	./github.com/modern-go/reflect2.a
2.4M	./go.starlark.net/starlark.a
2.5M	./github.com/aws/aws-sdk-go/service/elb.a
2.5M	./github.com/godbus/dbus/v5.a
2.5M	./go.etcd.io/etcd/clientv3.a
2.5M	./golang.org/x/sys/unix.a
2.6M	./google.golang.org/grpc.a
2.7M	./crypto/tls.a
2.7M	./github.com/Azure/azure-sdk-for-go/storage.a
2.8M	./net.a
2.9M	./github.com/container-storage-interface/spec/lib/go/csi.a
2.9M	./golang.org/x/crypto/ssh.a
2.9M	./gonum.org/v1/gonum/mat.a
3.0M	./golang.org/x/net/http2.a
3.2M	./gonum.org/v1/gonum/lapack/gonum.a
3.3M	./github.com/aws/aws-sdk-go/aws/endpoints.a
3.3M	./github.com/aws/aws-sdk-go/service/elbv2.a
3.3M	./github.com/gogo/protobuf/types.a
3.3M	./github.com/json-iterator/go.a
3.4M	./github.com/aws/aws-sdk-go/service/ecr.a
3.4M	./google.golang.org/api/container/v1.a
3.5M	./gonum.org/v1/gonum/blas/gonum.a
4.1M	./github.com/aws/aws-sdk-go/service/kms.a
4.1M	./github.com/gogo/protobuf/proto.a
4.3M	./github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources.a
4.3M	./github.com/vishvananda/netlink.a
4.5M	./github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice.a
4.5M	./google.golang.org/protobuf/internal/impl.a
5.0M	./github.com/aws/aws-sdk-go/service/autoscaling.a
5.4M	./github.com/googleapis/gnostic/openapiv2.a
5.6M	./go.etcd.io/etcd/etcdserver/etcdserverpb.a
5.8M	./github.com/vmware/govmomi/object.a
6.0M	./net/http.a
6.1M	./github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry.a
6.4M	./github.com/vmware/govmomi/vim25/methods.a
7.0M	./runtime.a
7.5M	./github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage.a
18M	./github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud.a
22M	./github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute.a
29M	./google.golang.org/api/compute/v1.a
34M	./google.golang.org/api/compute/v0.beta.a
37M	./google.golang.org/api/compute/v0.alpha.a
43M	./github.com/aws/aws-sdk-go/service/ec2.a
45M	./github.com/vmware/govmomi/vim25/types.a
55M	./github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network.a
```

**Comment by jpeach** [comment]
FWIW, a single-binary build (+providerless, +dockerless) that includes kubadm, kube-apiserver, kube-controller-manager, kubectl, kubelet, kube-proxy and kube-scheduler is only 98M on Linux. Supporting a bundled build seems like a good win independent of shrinking any other dependencies.

**Comment by BenTheElder** [comment]
Most of those binaries are usually run as pods where that doesn't necessarily make sense.
We stopped supporting hyperkube because nobody would step up to maintain it (there's a long history there). You can build hyperkube out of tree now.

**Comment by dims** [comment]
```
find vendor/ -name "*.go" | sed 's![^/]*$!!' | sort | uniq | cut -f 2- -d '/' | sed 's/.$//' > built.txt
cat built.txt | grep -v vendor/k8s.io | xargs -L 1 -I {} go build -mod vendor -v -o "vendor/{}.a" {}
find . -type f -name *.a -exec du -h {} \; | sort -h | grep -v vendor/k8s.io
```

**Comment by dims** [comment]
everything above 1 MB as of Sep 15, 2022

```
1.0M	./vendor/github.com/gogo/protobuf/plugin/populate.a
1.0M	./vendor/github.com/golang/protobuf/proto.a
1.0M	./vendor/github.com/russross/blackfriday.a
1.0M	./vendor/google.golang.org/protobuf/encoding/protojson.a
1.0M	./vendor/gopkg.in/square/go-jose.v2/json.a
1.0M	./vendor/sigs.k8s.io/kustomize/kyaml/kio.a
1.1M	./vendor/github.com/gogo/protobuf/plugin/marshalto.a
1.1M	./vendor/github.com/libopenstorage/openstorage/api.a
1.1M	./vendor/github.com/spf13/cobra.a
1.1M	./vendor/golang.org/x/net/html.a
1.1M	./vendor/google.golang.org/api/tpu/v1.a
1.1M	./vendor/sigs.k8s.io/json/internal/golang/encoding/json.a
1.2M	./vendor/github.com/Azure/go-autorest/autorest.a
1.2M	./vendor/github.com/cilium/ebpf/internal/btf.a
1.2M	./vendor/github.com/containerd/cgroups/stats/v1.a
1.2M	./vendor/github.com/felixge/httpsnoop.a
1.2M	./vendor/github.com/gogo/protobuf/plugin/description.a
1.2M	./vendor/github.com/gogo/protobuf/plugin/face.a
1.2M	./vendor/github.com/gogo/protobuf/plugin/union.a
1.2M	./vendor/github.com/google/cadvisor/third_party/containerd/api/services/containers/v1.a
1.2M	./vendor/github.com/grpc-ecosystem/grpc-gateway/runtime.a
1.2M	./vendor/go.uber.org/zap.a
1.2M	./vendor/google.golang.org/protobuf/reflect/protoreflect.a
1.2M	./vendor/google.golang.org/protobuf/types/descriptorpb.a
1.3M	./vendor/github.com/gogo/protobuf/plugin/gostring.a
1.3M	./vendor/github.com/gogo/protobuf/plugin/stringer.a
1.3M	./vendor/github.com/gogo/protobuf/plugin/unmarshal.a
1.3M	./vendor/github.com/google/pprof/profile.a
1.3M	./vendor/github.com/onsi/gomega/matchers.a
1.3M	./vendor/github.com/russross/blackfriday/v2.a
1.3M	./vendor/github.com/vmware/govmomi/pbm/types.a
1.3M	./vendor/go.etcd.io/bbolt.a
1.3M	./vendor/go.etcd.io/etcd/raft/v3.a
1.3M	./vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.a
1.3M	./vendor/go.opentelemetry.io/otel/metric.a
1.3M	./vendor/sigs.k8s.io/kustomize/kyaml/yaml.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/compare.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/equal.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/size.a
1.4M	./vendor/github.com/onsi/ginkgo/v2/internal.a
1.4M	./vendor/github.com/stretchr/testify/assert.a
1.4M	./vendor/go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.a
1.4M	./vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1.a
1.4M	./vendor/gopkg.in/square/go-jose.v2.a
1.5M	./vendor/github.com/cilium/ebpf.a
1.5M	./vendor/github.com/google/cel-go/cel.a
1.5M	./vendor/github.com/stretchr/objx.a
1.5M	./vendor/go.etcd.io/etcd/server/v3/embed.a
1.5M	./vendor/go.etcd.io/etcd/server/v3/mvcc.a
1.6M	./vendor/github.com/emicklei/go-restful/v3.a
1.6M	./vendor/github.com/google/cel-go/checker.a
1.6M	./vendor/go.opencensus.io/plugin/ochttp.a
1.6M	./vendor/gopkg.in/yaml.v2.a
1.7M	./vendor/github.com/onsi/ginkgo/v2/types.a
1.7M	./vendor/github.com/vmware/govmomi/vim25/mo.a
1.7M	./vendor/go.uber.org/zap/zapcore.a
1.7M	./vendor/gopkg.in/yaml.v3.a
1.7M	./vendor/sigs.k8s.io/structured-merge-diff/v4/value.a
1.8M	./vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor.a
1.8M	./vendor/github.com/google/cel-go/parser.a
1.8M	./vendor/github.com/google/go-cmp/cmp.a
1.8M	./vendor/sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.a
1.9M	./vendor/github.com/google/cel-go/interpreter.a
1.9M	./vendor/go.etcd.io/etcd/api/v3/etcdserverpb/gw.a
1.9M	./vendor/golang.org/x/tools/go/internal/gcimporter.a
2.0M	./vendor/github.com/prometheus/procfs.a
2.0M	./vendor/google.golang.org/grpc/internal/transport.a
2.0M	./vendor/google.golang.org/protobuf/internal/filedesc.a
2.1M	./vendor/github.com/opencontainers/runc/libcontainer.a
2.1M	./vendor/github.com/prometheus/client_golang/prometheus/promhttp.a
2.2M	./vendor/github.com/gogo/protobuf/plugin/testgen.a
2.2M	./vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator.a
2.2M	./vendor/github.com/google/cadvisor/third_party/containerd/api/services/tasks/v1.a
2.3M	./vendor/github.com/prometheus/client_golang/prometheus.a
2.4M	./vendor/google.golang.org/appengine/internal/datastore.a
2.5M	./vendor/github.com/google/cel-go/common/types.a
2.5M	./vendor/github.com/spf13/pflag.a
2.6M	./vendor/go.starlark.net/starlark.a
2.6M	./vendor/golang.org/x/tools/internal/imports.a
2.7M	./vendor/github.com/aws/aws-sdk-go/service/elb.a
2.7M	./vendor/github.com/modern-go/reflect2.a
2.7M	./vendor/google.golang.org/grpc.a
2.8M	./vendor/github.com/vmware/govmomi/simulator/esx.a
2.8M	./vendor/github.com/vmware/govmomi/simulator/vpx.a
2.9M	./vendor/go.etcd.io/etcd/client/v3.a
3.0M	./vendor/github.com/Azure/azure-sdk-for-go/storage.a
3.0M	./vendor/github.com/godbus/dbus/v5.a
3.0M	./vendor/gonum.org/v1/gonum/lapack/gonum.a
3.1M	./vendor/golang.org/x/sys/unix.a
3.2M	./vendor/gonum.org/v1/gonum/mat.a
3.3M	./vendor/golang.org/x/crypto/ssh.a
3.4M	./vendor/github.com/aws/aws-sdk-go/aws/endpoints.a
3.4M	./vendor/github.com/container-storage-interface/spec/lib/go/csi.a
3.4M	./vendor/github.com/json-iterator/go.a
3.5M	./vendor/github.com/gogo/protobuf/types.a
3.5M	./vendor/golang.org/x/net/http2.a
3.5M	./vendor/google.golang.org/api/monitoring/v3.a
3.7M	./vendor/github.com/aws/aws-sdk-go/service/elbv2.a
3.7M	./vendor/gonum.org/v1/gonum/blas/gonum.a
3.7M	./vendor/google.golang.org/api/container/v1.a
4.3M	./vendor/github.com/aws/aws-sdk-go/service/ecr.a
4.3M	./vendor/go.etcd.io/etcd/server/v3/etcdserver.a
4.5M	./vendor/github.com/gogo/protobuf/proto.a
4.6M	./vendor/github.com/aws/aws-sdk-go/service/kms.a
4.6M	./vendor/github.com/vishvananda/netlink.a
4.8M	./vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources.a
4.9M	./vendor/google.golang.org/protobuf/internal/impl.a
5.0M	./vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice.a
5.5M	./vendor/github.com/google/gnostic/openapiv2.a
5.5M	./vendor/github.com/google/gnostic/openapiv3.a
5.5M	./vendor/github.com/vmware/govmomi/simulator.a
6.3M	./vendor/github.com/aws/aws-sdk-go/service/autoscaling.a
6.4M	./vendor/github.com/vmware/govmomi/object.a
6.8M	./vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry.a
7.2M	./vendor/github.com/vmware/govmomi/vim25/methods.a
7.4M	./vendor/github.com/antlr/antlr4/runtime/Go/antlr.a
8.2M	./vendor/go.etcd.io/etcd/api/v3/etcdserverpb.a
8.4M	./vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage.a
9.4M	./vendor/github.com/google/cel-go/parser/gen.a
 12M	./vendor/github.com/onsi/ginkgo/v2/ginkgo.a
 21M	./vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud.a
 25M	./vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute.a
 36M	./vendor/google.golang.org/api/compute/v1.a
 41M	./vendor/google.golang.org/api/compute/v0.beta.a
 47M	./vendor/github.com/vmware/govmomi/vim25/types.a
 47M	./vendor/google.golang.org/api/compute/v0.alpha.a
 51M	./vendor/github.com/aws/aws-sdk-go/service/ec2.a
 62M	./vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network.a
```

**Comment by dims** [comment]
with https://github.com/kubernetes/kubernetes/pull/116329 we no longer have AWS sdk in `vendor/`

**Comment by BenTheElder** [comment]
Are those sizes actually 1:1 with binary size even after linking etc? I think go's dead code elimination is somewhat limited by reflection but ... https://stackoverflow.com/a/42827979

I think even if say, azure SDK is huge, the actual binary impact may be much smaller if not much of it the package is used in the resulting binary, after dead-code elimination.

(not to mention e.g. ginkgo which I hope isn't imported into our prod binaries anywhere)

**Comment by dims** [comment]
Results after the GCP cloud provider and credential provider was dropped.

```
1004K	./vendor/go.opentelemetry.io/otel/semconv/v1.21.0.a
1004K	./vendor/google.golang.org/genproto/googleapis/api/annotations.a
1016K	./vendor/github.com/asaskevich/govalidator.a
1.1M	./vendor/github.com/containerd/ttrpc.a
1.1M	./vendor/github.com/go-openapi/swag.a
1.1M	./vendor/github.com/gogo/protobuf/plugin/populate.a
1.1M	./vendor/github.com/golang/protobuf/proto.a
1.1M	./vendor/github.com/sirupsen/logrus.a
1.1M	./vendor/go.etcd.io/etcd/client/pkg/v3/transport.a
1.1M	./vendor/go.etcd.io/etcd/client/v2.a
1.1M	./vendor/go.etcd.io/etcd/server/v3/mvcc/backend.a
1.1M	./vendor/go.etcd.io/etcd/server/v3/proxy/grpcproxy/adapter.a
1.1M	./vendor/golang.org/x/net/html.a
1.1M	./vendor/google.golang.org/protobuf/encoding/protojson.a
1.1M	./vendor/sigs.k8s.io/structured-merge-diff/v4/typed.a
1.2M	./vendor/github.com/gogo/protobuf/plugin/marshalto.a
1.2M	./vendor/github.com/libopenstorage/openstorage/api.a
1.2M	./vendor/github.com/prometheus/common/model.a
1.2M	./vendor/go.etcd.io/etcd/server/v3/etcdserver/api/v3election/v3electionpb.a
1.2M	./vendor/gopkg.in/square/go-jose.v2/json.a
1.2M	./vendor/sigs.k8s.io/kustomize/kyaml/kio.a
1.3M	./vendor/github.com/containerd/cgroups.a
1.3M	./vendor/github.com/containerd/cgroups/stats/v1.a
1.3M	./vendor/github.com/grpc-ecosystem/grpc-gateway/runtime.a
1.3M	./vendor/github.com/spf13/cobra.a
1.3M	./vendor/github.com/stretchr/testify/require.a
1.3M	./vendor/sigs.k8s.io/json/internal/golang/encoding/json.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/description.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/face.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/union.a
1.4M	./vendor/github.com/gogo/protobuf/plugin/unmarshal.a
1.4M	./vendor/github.com/google/cadvisor/third_party/containerd/api/services/containers/v1.a
1.4M	./vendor/github.com/google/cel-go/checker.a
1.4M	./vendor/github.com/google/cel-go/common/stdlib.a
1.4M	./vendor/github.com/google/pprof/profile.a
1.4M	./vendor/github.com/onsi/gomega/matchers.a
1.4M	./vendor/github.com/russross/blackfriday/v2.a
1.4M	./vendor/go.opentelemetry.io/otel/sdk/trace.a
1.4M	./vendor/google.golang.org/protobuf/reflect/protoreflect.a
1.5M	./vendor/github.com/gogo/protobuf/plugin/gostring.a
1.5M	./vendor/github.com/gogo/protobuf/plugin/stringer.a
1.5M	./vendor/go.etcd.io/bbolt.a
1.5M	./vendor/go.etcd.io/etcd/raft/v3.a
1.5M	./vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.a
1.5M	./vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1.a
1.5M	./vendor/gopkg.in/square/go-jose.v2.a
1.6M	./vendor/github.com/cilium/ebpf/btf.a
1.6M	./vendor/github.com/felixge/httpsnoop.a
1.6M	./vendor/github.com/gogo/protobuf/plugin/compare.a
1.6M	./vendor/github.com/gogo/protobuf/plugin/equal.a
1.6M	./vendor/github.com/gogo/protobuf/plugin/size.a
1.6M	./vendor/golang.org/x/tools/internal/gcimporter.a
1.7M	./vendor/github.com/cilium/ebpf.a
1.7M	./vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime.a
1.7M	./vendor/go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.a
1.7M	./vendor/gopkg.in/yaml.v2.a
1.7M	./vendor/sigs.k8s.io/yaml/goyaml.v2.a
1.8M	./vendor/github.com/emicklei/go-restful/v3.a
1.8M	./vendor/github.com/google/go-cmp/cmp.a
1.8M	./vendor/github.com/onsi/ginkgo/v2/internal.a
1.8M	./vendor/github.com/stretchr/testify/assert.a
1.8M	./vendor/go.etcd.io/etcd/server/v3/mvcc.a
1.8M	./vendor/gopkg.in/yaml.v3.a
1.9M	./vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor.a
1.9M	./vendor/sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.a
1.9M	./vendor/sigs.k8s.io/kustomize/kyaml/yaml.a
1.9M	./vendor/sigs.k8s.io/structured-merge-diff/v4/value.a
2.0M	./vendor/github.com/fxamacker/cbor/v2.a
2.0M	./vendor/go.uber.org/zap/zapcore.a
2.0M	./vendor/google.golang.org/protobuf/types/descriptorpb.a
2.1M	./vendor/github.com/google/cel-go/common/ast.a
2.1M	./vendor/github.com/google/cel-go/ext.a
2.1M	./vendor/github.com/opencontainers/runc/libcontainer.a
2.2M	./vendor/github.com/onsi/ginkgo/v2/types.a
2.2M	./vendor/github.com/prometheus/procfs.a
2.2M	./vendor/go.etcd.io/etcd/api/v3/etcdserverpb/gw.a
2.2M	./vendor/go.etcd.io/etcd/server/v3/embed.a
2.2M	./vendor/google.golang.org/grpc/internal/transport.a
2.3M	./vendor/github.com/google/cel-go/interpreter.a
2.3M	./vendor/github.com/prometheus/client_golang/prometheus/promhttp.a
2.3M	./vendor/go.uber.org/zap.a
2.3M	./vendor/google.golang.org/protobuf/internal/filedesc.a
2.4M	./vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator.a
2.5M	./vendor/github.com/gogo/protobuf/plugin/testgen.a
2.5M	./vendor/github.com/google/cadvisor/third_party/containerd/api/services/tasks/v1.a
2.5M	./vendor/github.com/google/cel-go/parser.a
2.6M	./vendor/google.golang.org/appengine/internal/datastore.a
2.7M	./vendor/github.com/spf13/pflag.a
2.7M	./vendor/golang.org/x/tools/internal/imports.a
2.8M	./vendor/github.com/prometheus/client_golang/prometheus.a
2.9M	./vendor/github.com/modern-go/reflect2.a
3.1M	./vendor/go.starlark.net/starlark.a
3.2M	./vendor/github.com/godbus/dbus/v5.a
3.2M	./vendor/github.com/google/cel-go/common/types.a
3.3M	./vendor/go.etcd.io/etcd/client/v3.a
3.3M	./vendor/google.golang.org/grpc.a
3.5M	./vendor/github.com/google/cel-go/cel.a
3.6M	./vendor/github.com/gogo/protobuf/types.a
3.7M	./vendor/github.com/json-iterator/go.a
3.7M	./vendor/golang.org/x/crypto/ssh.a
3.8M	./vendor/golang.org/x/sys/unix.a
4.2M	./vendor/github.com/container-storage-interface/spec/lib/go/csi.a
4.2M	./vendor/golang.org/x/net/http2.a
4.6M	./vendor/github.com/vishvananda/netlink.a
5.2M	./vendor/google.golang.org/protobuf/internal/impl.a
5.4M	./vendor/github.com/gogo/protobuf/proto.a
5.4M	./vendor/github.com/google/gnostic-models/openapiv2.a
5.4M	./vendor/github.com/google/gnostic-models/openapiv3.a
5.8M	./vendor/go.etcd.io/etcd/server/v3/etcdserver.a
6.3M	./vendor/golang.org/x/tools/cmd/stringer.a
7.6M	./vendor/github.com/antlr4-go/antlr/v4.a
8.6M	./vendor/go.etcd.io/etcd/api/v3/etcdserverpb.a
8.9M	./vendor/github.com/google/cel-go/parser/gen.a
13M	./vendor/github.com/onsi/ginkgo/v2/ginkgo.a
```

**Comment by dims** [comment]
closing this 5 year old issue now that we have cleaned up all the in-tree cloud providers.

/close
