### ISSUE TITLE
Umbrella issue for Even Pods Spread  [Alpha]

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#77284]
This issue works as an umbrella holding up all related items of implementing KEP "Even Pods Spread" in 1.16 as an alpha feature.

### Work Items

- [x] 1. API changes - #77327
	- Manual API changes
	- Auto-generated files
	- Defaulting, validation and spec removal if feature gate is disabled
    - Unit tests
- [x] 2. Scheduler Predicate Metadata calculation - #77760
    - build a new topologyPairsPodSpreadMap into PredicateMetadata
    - PredicateMetadata initilization
    - update ShallowCopy()
    - Unit tests
- [x] 3. Scheduler Predicate Core - #77828
	- Define a new Predicate
	- Core predicate logic
    - UT on predicate and generic_scheduler
- [x] 4. Supports Preemption - #79062
    - implements addPod()/removePod() for podSpreadMap
    - UT on preemption logic and generic_scheduler
- [x] 5. Scheduler Priority - #79063
	- Define a new Priority
	- Core Priority logic
    - Unit tests
- [x] 6. Integration or(and) E2E tests - #80011
    - Integration tests on predicate (including preemption), priority
- [x] 7. Enhancements & Issus Fixes
	- [x] Use {tpPair: count} in topologySpreadMap to optimize the memory footprint and preemption logic. ([comment1](https://github.com/kubernetes/kubernetes/pull/77760#issuecomment-513126887), [comment2](https://github.com/kubernetes/kubernetes/pull/79062#discussion_r305470724)) - #81068
	- [TBD] How to deal with pods in tainted nodes? (Braimstorming issue #80921)
    - [TBD] Implement a slow-path meta calculation ([comment](https://github.com/kubernetes/kubernetes/pull/77828/files#r300830018)) - may engage autoscaler team to evaluate
	- [TBD] New admission plugin? If a pod's constraint.labelSelector is nil, apply labels from pod's controller.
- [x] 8. Documents - https://github.com/kubernetes/website/pull/15514
- ~~(optional for alpha) Benchmark tests~~

### Links

- KEP: [even-pods-spreading.md](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20190221-even-pods-spreading.md)
- Enhancement Issue: https://github.com/kubernetes/enhancements/issues/895

/sig scheduling
/assign

**Comment by draveness** [comment]
/close 

I think we have already solved this issue, and feel free to reopen if not.
