### ISSUE TITLE
Umbrella: Imporve volume expand e2e test

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/kubernetes#79445]
This holds a list of volume expand e2e test related improvements that are not covered in https://github.com/kubernetes/kubernetes/pull/78000

- [ ] Move mounted_volume_resize.go to framework
- [ ] Add actual volume size check for volume expand tests
- [ ] Merge volume expand tests for flex volume to framework (Move entire flex volume tests to framework?)
- [ ] Make binding mode tunable depending on drivers
- [ ] Enable VolumeExpandTestSuite for CSI drivers (Add `InitVolumeExpandTestSuite` in csi_volumes.go)
