### ISSUE TITLE
Refactor InterPodAffinity with the Scheduling Framework

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#80667]
**What would you like to be added**:

Most extension points of the scheduling framework have already been implemented, and we should use the Scheduling Framework to refactor original predicates and priorities function. According to the discussion with @ahg-g and @Huang-Wei in https://github.com/kubernetes/kubernetes/pull/80225#issuecomment-515422080 we could start with `InterPodAffinity` since it used a pattern which has already been deprecated.

**Why is this needed**:

`InterPodAffinity` used a pattern which has already been deprecated, and we could start with it to see which pieces are missing to support the current predicates and priorities.

Once the last priority function was converted to plugins with scheduling framework, we could remove the deprecated pattern with https://github.com/kubernetes/kubernetes/pull/80225

- [ ] Refactor the InterPodAffinity Priority function #80898
  - [x] Use an named array (or map) in the normalize score function #80901
  - [ ] ~Add a cleanup extension point to the scheduling framework https://github.com/kubernetes/kubernetes/issues/81438~
  - Figure out an approach to register framework plugins
- [ ] Refactor the InterPodAffinity Predicate function

/sig scheduling
/kind cleanup
cc/ @bsalamat @Huang-Wei @ahg-g

**Comment by alculquicondor** [comment]
Can you share a high level design on how do you plan to implement this? From a quick read, it sound like we should be using PostFilter + Score + NormalizeScore

/cc @Huang-Wei this is likely going to be very similar to EvenPodSpreading. The main issue with the current framework is that Score only cares about one Node at a time. But here we need to calculate some weights based on other nodes' contents. WDYT?

**Comment by draveness** [comment]
Per discussion in https://github.com/kubernetes/kubernetes/pull/80901#issuecomment-519316908, I could give an implementation of refactoring interpod-affinity for review after #80901 gets merged.

**Comment by alculquicondor** [comment]
Please consider drafting the proposal in a doc before starting the implementation, so that we can get to some level of agreement before getting any code done.

**Comment by tedyu** [comment]
Where can I find the proposal mentioned above ?
