### ISSUE TITLE
[e2e] Track TODOs in merged PRs

### ISSUE THREAD

**Issue by jiatongw** [kubernetes/kubernetes#80975]
This issue is to track TODOs in merged PRs of `test/e2e/framework`. Here is the checklist of potential following PRs.

- [ ] `e2e/framework/node/resource.go` (#78282): 
    - [ ] TODO for func `FirstAddress`
    - [ ] TODO for func `isNodeConditionSetAsExpected `

- [ ] `e2e/apps/daemon_restart.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/autoscaling/cluster_size_autoscaling.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/cloud/nodes.go `  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/network/service.go `  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/scalability/density.go  `  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/scheduling/equivalence_cache_predicates.go `  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/scheduling/predicates.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/scheduling/preemption.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/scheduling/priorities.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/storage/vsphere/vsphere_volume_vsan_policy.go`  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/windows/service.go `  (#79879):
    - Write a wrapper for `framework.ExpectNoErrorWithOffset`

- [ ] `e2e/framework/node/resource.go`, `e2e/framework/util.go`  (#79879):
    - TODO for func `GetReadySchedulableNodesOrDie `

**Comment by jiatongw** [comment]
/area/e2e-test-framework
/area/test
/assign
