### ISSUE TITLE
[Umbrella Issue] Rewrite tests which hit Stable API endpoints

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#80997]
Previous Umbrella Issues https://github.com/kubernetes/kubernetes/issues/78747 & https://github.com/kubernetes/kubernetes/issues/78748 encompassed PRs to promote tests which hit Stable endpoints. Some of these PRs have been able to be successfully merged, others require rewrites/changes in order to  be included in Conformance. This issue tracks the progress of those rewrites.

#### Merged

* [x]   [feat: add conformance tests for patchCoreV1NamespacedConfigMap #78924 - author: draveness](https://github.com/kubernetes/kubernetes/pull/78924)
> @draveness picked up one of the endpoints and created a test and attempted to promote it at the same time. If draveness does not resubmit it, then we will pick it up in a week.

- We picked up the test and updated to address @spiffxp's comments on the original PR. 
- Our PR: https://github.com/kubernetes/kubernetes/pull/80787 **MERGED**
- PR for Promoting to Conformance: https://github.com/kubernetes/kubernetes/pull/81205

#### In Progress

* [ ]   [Promote return chunks of results for list calls to conformance #79871](https://github.com/kubernetes/kubernetes/pull/79871)  
> [comment from @spiffxp](https://github.com/kubernetes/kubernetes/pull/79871#issuecomment-514854868)
- **PR:** https://github.com/kubernetes/kubernetes/pull/82297

* [ ]  [Promote LimitRange Tests to Conformance #78828](https://github.com/kubernetes/kubernetes/issues/78828)  
> PR #78921 was closed because the test [needs to be broken into multiple parts](https://github.com/kubernetes/kubernetes/pull/78921#discussion_r295536235), because it has too much going on. It was identified as a good candidate, and the discussion on refactoring it [is in progress](https://github.com/kubernetes/kubernetes/pull/78921#issuecomment-506985021)
> 

In [limit_range.go](https://github.com/kubernetes/kubernetes/blob/c38ae01f8e7509dec80fa0cc72846d3ffb6912f5/test/e2e/scheduling/limit_range.go) we are looking at splitting out the following lines:

- [56 - 131](https://github.com/kubernetes/kubernetes/blob/c38ae01f8e7509dec80fa0cc72846d3ffb6912f5/test/e2e/scheduling/limit_range.go#L56)
- [132 - 148](https://github.com/kubernetes/kubernetes/blob/c38ae01f8e7509dec80fa0cc72846d3ffb6912f5/test/e2e/scheduling/limit_range.go#L132)
- [149 - 193](https://github.com/kubernetes/kubernetes/blob/c38ae01f8e7509dec80fa0cc72846d3ffb6912f5/test/e2e/scheduling/limit_range.go#L149)
- [199 - 241](https://github.com/kubernetes/kubernetes/blob/c38ae01f8e7509dec80fa0cc72846d3ffb6912f5/test/e2e/scheduling/limit_range.go#L199)

- **PR:** https://github.com/kubernetes/kubernetes/pull/81311

* [ ]   [Promote 'Kubelet:Timed Pod Deletion' test to Conformance #79630](https://github.com/kubernetes/kubernetes/pull/79630)  
> This test could not be promoted as is due to test name being a non-literal string, and the conformance walker failing on non-literal strings. 
 
- Rewrote test and [created PR](https://github.com/kubernetes/kubernetes/pull/80731)

* [ ]  [Write Scale Tests for Conformance #78834](https://github.com/kubernetes/kubernetes/issues/78834)  
> [This test (#79122)](https://github.com/kubernetes/kubernetes/pull/79122) was closed because:
> 
> * It uses a deprecated annotation (`tolerate-unready-endpoints`)
> * It uses preStop hook that sleeps, instead of using agnhost netexec
> * It uses `wget`, which is Linux specific

- *Rewrite is in progress* in [this branch](https://github.com/ii/kubernetes/tree/wip-service-test-rewrite)
- **PR:** https://github.com/kubernetes/kubernetes/pull/81320

* [ ]   [Promote pod readiness gates #79875](https://github.com/kubernetes/kubernetes/pull/79875)  
> @jbelamaric asks for the test to be rewritten using better practices, including agnhost, and wait function instead of sleep.

- *Rewrite is in progress*

/sig testing
/area test
/area conformance

**Comment by hh** [comment]
/close
I think this kind of umbrella issue we can close.... the referenced PRs are on the board or closed.
