### ISSUE TITLE
Umbrella issue for RuntimeClass Scheduling

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#81016]
The issue works as an umbrella holding up all related items of implementing KEP "[RuntimeClass Scheduilng](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/runtime-class-scheduling.md)" in 1.16 as a beta feature.

## Work Items

+ [x] 1. API Changes https://github.com/kubernetes/kubernetes/pull/80825
    + Add Scheduling field to RuntimeClass
    + Add validation and conversation method
+ [x] 2. RuntimeClass Admission Plugins Updates #81072
    + Add validate and set scheduling
    + Add unit tests
+ [x] 3. Fix toleration comparison & merging logic #81732
+ [x] 4. Enable the RuntimeClass admission controller for scheduling #81862
+ [x] 5. Enable the RuntimeClass admission controller on GCE & CI #82094
+ [x] 6. Integration or(and) E2E tests #81915
+ [x] 7. Documents https://github.com/kubernetes/website/pull/15989

## Links

* KEP [RuntimeClass Scheduilng](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/runtime-class-scheduling.md)
* Enhancement issue https://github.com/kubernetes/enhancements/issues/894

/sig node
/sig scheduling
/assign
/cc @tallclair

**Comment by kacole2** [comment]
@tallclair @draveness I see https://github.com/kubernetes/kubernetes/pull/82094 currently in the tide merge pool. However, I do not see https://github.com/kubernetes/kubernetes/pull/81915 in the merge pool. Is https://github.com/kubernetes/kubernetes/pull/81915 critical to this being implemented in v1.16? Or since this missed code freeze should this be bumped to v1.17?

**Comment by draveness** [comment]
> @tallclair @draveness I see #82094 currently in the tide merge pool. However, I do not see #81915 in the merge pool. Is #81915 critical to this being implemented in v1.16? Or since this missed code freeze should this be bumped to v1.17?

#81815 is nice to have for 1.16 and it is so close to merge with one pending issue.

**Comment by tallclair** [comment]
https://github.com/kubernetes/kubernetes/pull/81915 is adding tests for functionality that is being added in v1.16. I'm sorry this didn't make code-freeze, but I'd like to see it merged in 1.16.

As a test-only PR, what's the exception request process for this?

**Comment by kacole2** [comment]
@tallclair [file an exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md) and tag @lachie83 and myself in the email.

**Comment by tallclair** [comment]
Exception request filed: https://groups.google.com/d/topic/kubernetes-sig-node/a4WdtrFU8U8/discussion

**Comment by draveness** [comment]
/close

All the PR in this issue have been merged.
