### ISSUE TITLE
[Umbrella] Graduate ResourceQuotaScopeSelectors from beta to GA

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#82480]
/sig scheduling
/kind feature

**What would you like to be added**:

Graduate ResourceQuotaScopeSelectors from beta to GA

- [x] Relax namespace restriction for critical pods #76310
- [x] Graduate ResourceQuotaScopeSelectors API to GA https://github.com/kubernetes/kubernetes/pull/82690
- [x] Update documents to reflect the changes

**Why is this needed**:

- [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20190409-resource-quota-ga.md)
- https://github.com/kubernetes/enhancements/issues/986
