### ISSUE TITLE
Improve scheduler observability

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#83356]
This is the master issue that tracks all enhancements to scheduler observability.

**What would you like to be added**:
Metrics/logs/events to improve the observability/debuggability of kube-scheduler.

**Why is this needed**:
Right now there are very few signals to tell if scheduling is working well. And there has been some requests to add more metrics such as #83298. 
Improving observability not only helps us monitor and operate scheduler, but also gives us more signals and confidence for big changes such as the migration to the new scheduler framework.

## Metrics
Please refer to this [Google Doc](https://docs.google.com/document/d/1R7GOzZBcv_uEEIPp0REvifk90Q6SE5b4WcFmMFWs4Kw/edit?usp=sharing) for a summary of metrics. Leave your comment there as well.

* ~~[ ] improve schedule_attempts_total metric #83411~~
* [x] per pod scheduling latency #83412
* [x] per pod scheduling attempts #83415
* [x] latency for framework extension point #83416
* [x] latency for framework plugins #83416

* [x] incoming pods to the queues #83410
* [x] cache size #83404
* [x] number of binding goroutines #83403
* [x] permit extension point "wait" behavior #83473
* ~~[ ] filter and score plugin specific metrics #82427~~
* [x] change preemption_victims to histogram #83464
* ~~[ ] deprecate old metrics #83782~~

## Logs/Events/Tracing
* [x] #83399
* ~~[ ] #83401~~

## User-facing changes
* `pod_preemption_victims` will be changed from Gauge to Histogram #83464
* Some metrics related to the old predicate/priority algorithms will be replaced by new framework metrics as we migrate to the new scheduler framework
  * `Scheduling_algorithm_predicate_evaluation_seconds` will be replaced by `framework_extension_point_duration_seconds[extension_point="Filter"]`
  * `Scheduling_algorithm_priority_evaluation_seconds` will be replaced by `framework_extension_point_duration_seconds[extension_point="Score"]`

## Reference
[Kubernetes Metrics Stability](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md)

/sig scheduling
/sig instrumentation

**Comment by hprateek43** [comment]
Should we also introduce some kind of verbosity level for scheduler metrics? This will allow development and non production clusters to run at a higher verbosity level, something that can be useful for certain organisations adopting kubernetes?

**Comment by liu-cong** [comment]
> Should we also introduce some kind of verbosity level for scheduler metrics? This will allow development and non production clusters to run at a higher verbosity level, something that can be useful for certain organisations adopting kubernetes?

Interesting idea. Is there an example where verbosity is used for metrics in k8s?

**Comment by hprateek43** [comment]
I am not yet aware of such a component. But I commonly see organisations struggling with the high verbosity of components like core-dns, networking overheads etc, that most of the time they fail to identify a metric that can lead to problems before the problem occurs. Idea is that if somehow we can give user control over the logging system of scheduler through an external flag, it can prove helpful.

**Comment by liu-cong** [comment]
@piosz, can you review the proposed changes to make sure it's aligned with instrumentation guide lines? Thanks!

**Comment by serathius** [comment]
Hey Cong, I can take a look.

**Comment by serathius** [comment]
@brancz
