### ISSUE TITLE
Allow show hidden metrics

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/kubernetes#85270]
**What would you like to be added**:
Add a flag `--show-hidden-metrics-for-version` to following binaries:
- [x] kube-apiserver https://github.com/kubernetes/kubernetes/pull/84292 by @RainbowMango 
- [x] kube-scheduler https://github.com/kubernetes/kubernetes/pull/84913 by @serathius 
- [x] kube-proxy #85279 by @RainbowMango 
- [x] kube-controller-manager #85281 by @RainbowMango 
- [x] kublet  #85282 by @serathius 

**Usage**:
Assume we are using v1.17,
`--show-hidden-metrics-for-version=1.16` will enable metrics that have been turned off in v1.16.

**Why is this needed**:
> On a subsequent release (when the metric's deprecatedVersion is equal to current_kubernetes_version - 1)), a deprecated metric will become a hidden metric. Unlike their deprecated counterparts, hidden metrics will no longer be automatically registered to the metrics endpoint (hence hidden). However, they can be explicitly enabled through a command line flag on the binary (i.e. '--show-hidden-metrics-for-version='). This is to provide cluster admins an escape hatch to properly migrate off of a deprecated metric, if they were not able to react to the earlier deprecation warnings. Hidden metrics should be deleted after one release.

More details please refer to [metrics stability framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md#show-hidden-metrics).

**Q&A**:
**1. Why Not Bool Flag? Or why we need to specify a version?**

First of all, this flag is an escape hatch, it intends to be used by admins if they were not able to react to the earlier deprecation warnings.

Second of all, we don't want admins to be excessive depend on this flag, otherwise, they may fail to notice deprecate message from the next release.

Here is an example: [why-not-bool-flag](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md#why-not-bool-flag)

/assign

**Comment by clarklee92** [comment]
/assign 
Could I deal this?   I want pick two task: kube-controller-manager and kubectl.
Thank you very much.

**Comment by RainbowMango** [comment]
@clarklee92 
All the implementation has been done at local. They will be fired soon after basic testing.

If you are interested in contributing to sig instrumentation in the future, I can get you support for that.  Please feel free to contact me.

**Comment by clarklee92** [comment]
@RainbowMango ok, thanks.

**Comment by serathius** [comment]
@RainbowMango Flag was added to kubelet.
All tasks for this Issue have been finished.

**Comment by RainbowMango** [comment]
Yeah, I see it. And thanks for your help!
I'll close this now.
