### ISSUE TITLE
Framework Migration Phase 2

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85822]
This is an umbrella issue to track Phase 2 of the migration plan as discussed in the [migration doc](https://docs.google.com/document/d/1P1eBaePxuko22B8LLOrPEonoj1awc1dCVBDefuRWUA4/edit#heading=h.u7jfy9wqpd2b). 

The main goal of Phase 2 is to deprecate predicates and priorities logic in the scheduler. We will keep supporting the Policy API (defines the scheduler behavior in terms of predicates and priorities), which will be supported through the policy-to-framework translation layer we built in Phase 1.

**Important:** please wait until a corresponding issue is created for each of the tasks below, we need to go through a careful evaluation of whether those tasks actually make sense and divide each one to perhaps a larger number of smaller tasks. 

The tasks are:
- [x] 1. Remove priorities execution path in schedule core (#85917). 
- [x] 2. Remove predicates execution path in scheduler core (#85918).
- [x] 3. Scheduler configuration 
  - [x] 3.1 Define algorithm providers in terms of plugins instead of predicates/priorities (#86162)
  - [x] 3.2 Disable scheduler plugins according to component config plugins disabled list (#86789)
  - [x] 3.3 Support mandatory plugins in the scheduling framework (#86909)
- [x] 4. Break priority metadata computation into post-filter plugins (#85924).
- [x] 5. Break predicate metadata computation into pre-filter plugins.
  - [x] 5.1 Move Affinity Predicate Metadata calculation to a pre-filter plugin (#85926)
  - [x] 5.2 Move EvenPodSpread Predicate Metadata calculation to a pre-filter plugin (#85925)
  - [x] 5.3 Move host ports predicate metadata to pre-filter plugin (#86227)
  - [x] 5.4 Move node resources predicate metadata to pre-filter plugin (#86248)
  - [x] 5.5 Move service affinity metadata to pre-filter plugin (#86263)
  - [x] 5.6 Deprecate PredicateMetadata and its producers (#86290)
- [x] 6. Move all predicates logic to their corresponding plugins.
  - [x] 6.1 Move Service affinity logic into its plugin (#86263)
  - [x] 6.2 Move VolumeBinding predicate to its filter plugin (#86442)
  - [x] 6.3 Move VolumeZone predicate to its Filter plugin (#86444)
  - [x] 6.4 Move NoDiskConflict predicate to its Filter plugin (#86443)
  - [x] 6.5 Move Pod Affinity predicate logic to its Filter plugin (#86460)
  - [x] 6.6 Move volume limits predicates to their Filter plugins (#86613)
  - [x] 6.7 Move CheckNodeUnschedulable predicate to its filter plugin (#86622)
  - [x] 6.8 Move Pod Topology Spread predicate logic to its Filter plugin (#86658)
  - [x] 6.9 Move volume limits predicates to their Filter plugins (#86613)
  - [x] 6.10 Move node Affinity predicate logic to its Filter plugin (#86717)
  - [x] 6.11 Move taint toleration predicate logic to its Filter plugin (#86979)
- [x] 7. Move all priorities logic to their corresponding plugins.
  - [x] 7.1 Move Pod Affinity priority logic to its Score plugin (#86398)
  - [x] 7.2 Move ImageLocality priority logic to its Score plugin (#86404)
  - [x] 7.3 Move NodeAffinity priority logic to its Score plugin (#86405)
  - [x] 7.4 Move NodePreferAvoidPods priority logic to its Score plugin (#86407)
  - [x] 7.5 Move SelectorSpread priority logic to its Score plugin (#86435)
  - [x] 7.6 Move Taint and toleration predicate to its Score plugin (#86439)
  - [x] 7.7 Move Pod Spread priority logic to its Score plugin (#86440)
  - [x] 7.8 Move NodeLabelPriority to its Score plugin (#86437)
  - [x] 7.9 Move resource-based priority functions (Most/Least/Balanced and RequestedToCapacityRatio) to their Score plugins (#86445)
  - [x] 7.10 Move ServiceAntiAffinityPriority to its Score plugin (#86447)
  - [x] 7.11 Move ResourceLimitsPriority to its Score plugin (#86571)
- [x] 8. Remove ```scheduler/algorithms``` package
  - [x] 8.1 Break DS controller dependency on predicates package (#86729) 
  - [x] 8.2 Break Filter plugins dependency on predicates package (#86712) 
  - [x] 8.3 Break Filter plugins dependency on PredicateFailureReason (#86711)
  - [x] 8.4 Cleanup unused predicate error types (#86988)
  - [x] 8.5 Remove scheduler/algorithm/priorities/util package (#86993)
  - [x] 8.6 Move GeneralPredicates logic to kubelet (#87342)
- [x] 9. Move pod binding logic to run as a default binding plugin (#87157)
- [x] 10. Move the default queue sort logic to a QueueSort framework plugin (#87160)

/cc @alculquicondor @liu-cong @Huang-Wei @ravisantoshgudimetla @damemi

**Comment by Huang-Wei** [comment]
> Break priority metadata computation into post-filter plugins.
> Break predicate metadata computation into pre-filter plugins.

I will send PRs on EvenPodsSpread to resolve part of the above items.

**Comment by clarklee92** [comment]
> Move all predicates logic to their corresponding plugins.
> Move all priorities logic to their corresponding plugins.

I will do this two.  /assgin

**Comment by ahg-g** [comment]
/cc @wgliang 

Thanks all for the interest, we will first do the perp work (tasks 1 - 5), and then I will create sub tasks for items 6 and 7 for anyone to contribute.

**Comment by hprateek43** [comment]
@ahg-g Is any activity pending around this? I am relatively free and can pick some tasks.

**Comment by ahg-g** [comment]
Thanks all for your interest helping with the migration. I created a bunch of issues and assigned them to all cc-ed themselves on this issue. Please confirm on the assigned issue that you will be able to work on it.

**Comment by yuxiaobo96** [comment]
/cc
I want to join it too.

**Comment by ahg-g** [comment]
Congrats all, we are done with phase 2 of the migration.
