### ISSUE TITLE
Promote TaintBasedEvictions to GA in 1.18

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#87161]
/kind feature
/sig scheduling

TaintBasedEvictions has been in beta since 1.13 (see https://github.com/kubernetes/enhancements/issues/166) and should be ready to be promoted to GA for 1.18

**Tasks**
- [x] need a merged KEP, in an implementable state and with test plans and graduation criteria. (https://github.com/kubernetes/enhancements/pull/1450)
- [x] ensure test coverage is complete and up-to-date (https://github.com/kubernetes/kubernetes/issues/87427) PR https://github.com/kubernetes/kubernetes/pull/88152
- [x] clean up featuregate logic (https://github.com/kubernetes/kubernetes/issues/87428) PR https://github.com/kubernetes/kubernetes/pull/87487
- [x] update docs (https://github.com/kubernetes/kubernetes/issues/87429) PR https://github.com/kubernetes/website/pull/19302

**Comment by Huang-Wei** [comment]
One gentle reminder/tip :)

If you only want to be subscribed without giving any **real** comments, please restrain of leaving `/cc` because it would generate useless (email) notifications. There is a **"Subscribe" button** to ensure you get subscribed without triggering (email) notifications to others.

**Comment by damemi** [comment]
I've submitted an exception request for this and the 3 open PRs waiting approval

**Comment by damemi** [comment]
All PRs have now merged so I think we can offically close this tracking issue!

Thank you to everyone who contributed to getting this done in 1.18!

/close
