### ISSUE TITLE
Scheduler Component Config v1alpha2

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87617]
This is a tracking issue for the changes we plan to have in `kubescheduler.config.k8s.io/v1alpha2`

- [x] Blocking: new `pkg/scheduler/apis/config/v1alpha2` folder
- [x] Deprecate AlgorithmSource #87526
- [x] Move HardPodAffinitySymmetricWeight to PluginConfig #87657
- [x] Multi Scheduling Profiles #85737
- [x] Rename PostFilter to PreScore #87523
- [x] Update docs in kubernetes/website kubernetes/website#19172

/sig scheduling
/kind feature

**Comment by ahg-g** [comment]
/milestone v1.18

https://github.com/kubernetes/enhancements/issues/785#issuecomment-581469848

"If so, just a friendly reminder we're looking for a PR against k/website (branch dev-1.18) due by Friday,"

**Comment by smourapina** [comment]
Hello @ahg-g, @alculquicondor !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is a few weeks from now. Is this issue still intended for milestone 1.18? Thanks in advance!

**Comment by alculquicondor** [comment]
It is :)
All implementation PRs are out for review.

**Comment by smourapina** [comment]
Hello again @alculquicondor,
Just leaving a reminder that code freeze is coming in about 1 week (5 March)!

**Comment by alculquicondor** [comment]
Other than documentation, we only have one PR left in review :)

**Comment by alculquicondor** [comment]
We are done with the initial implementation items. However, we will be discussing #88529 in today's SIG meeting.

**Comment by smourapina** [comment]
Thanks for getting back on this @alculquicondor. We are now 2 days away from code freeze (5 March), so please keep this in mind.

**Comment by smourapina** [comment]
As we are now in code freeze for 1.18, and since you have [#19172](https://github.com/kubernetes/website/pull/19172) as WIP, I am moving this to the next milestone.

/milestone v1.19

**Comment by alculquicondor** [comment]
Sorry, we have finalized the implementation of this issue. We haven't
reached the docs freeze. And I'm already working on it.

**Comment by smourapina** [comment]
Thanks for getting back on this @alculquicondor. You are correct, the for docs you need to have a PR ready by EOD Mon March 9! 
It makes sense in that case to reassign the milestone to 1.18. 
/milestone v1.18

**Comment by alculquicondor** [comment]
Thanks @smourapina, the docs PR is now out for review :)

**Comment by alculquicondor** [comment]
Done 😃 

/close
