### ISSUE TITLE
Tracking PodOverhead graduation to beta for 1.18 release

### ISSUE THREAD

**Issue by egernst** [kubernetes/kubernetes#88339]
This issue is used to track the enhancements we plan to make to PodOverhead in the 1.18 timeframe. As part of the 1.18 release, we plan to graduate `PodOverhead` feature to beta.

 - [x] - update KEP beta criteria: https://github.com/kubernetes/enhancements/pull/1526
 - [x] - scheduler e2e test: https://github.com/kubernetes/kubernetes/pull/87215
 - [x] - feature observability: https://github.com/kubernetes/kube-state-metrics/pull/1053, https://github.com/kubernetes/kubernetes/issues/87259
 - [x] - node e2e test: https://github.com/kubernetes/kubernetes/pull/88558
 - [x] - move to beta https://github.com/kubernetes/kubernetes/pull/88338

 - [x] - updated documentation: https://github.com/kubernetes/website/pull/19059
