### ISSUE TITLE
[Umbrella] scheduler PostFilter extension point

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#91038]
## Background

Per discussion in the [draft design doc](https://docs.google.com/document/d/1lBZOA-vjo2m52242q4dZ1L1W-RrNyr14F63PfQ5YUr8/view) and [brainstorming issue](https://github.com/kubernetes/kubernetes/issues/90025), we've come out with a good shape on how scheduler preemption logic can be refactored into.

I've done some evaluation work and decided to go with the option that introducing a PostFilter extension point, which is called after Filter phase when there is no node can fit in the incoming Pod. And the old preemption logic will be moved as a PostFilter plugin implementation.

Generally we will introduce a `PreemptHandle` interface which embed all needed operations during preemption logic, specifically a `PreemptHandle` interface will include several sub-interfaces/functions:

- `PluginRunner` interface. It's for abstracting calling RunXYZPlugins during plugin runtime
- `PodNominater` interface with internal nominatedMap (which is related with setting/clearing `.spec.NominatedNodeName` as well as managing internal scheduler status
- `Extenders()` function. It's for interacting with registered extenders.

And then the `PreemptHandle` will be instantiated properly, and passed as an arg to `PostFilter()` function.

Below are the items going forward. Hope they can be finished in this (1.19) release cycle.

### Part 1 - prefactor current code to make PostFilter extension point possible

- [x] Refactor preemption extender logic and move SchedulerExtender interface to framework pkg #91037
- [x] Extract logic related with scheduler nominatedPods to an interface #90356
- [x] Add function NominatedPodsForNode to PodNominator interface #90415
- [x] Add Extender and PluginsRunner to PreemptHandle #90711

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblx0QTFbIzkxMDM3XSAtLT4gQ1sjOTA3MTFdXG4gIEEyWyM5MDM1Nl0gLS0-IEJbIzkwNDE1XVxuXHRCIC0tPiBDWyM5MDcxMV1cblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0QTFbIzkxMDM3XSAtLT4gQ1sjOTA3MTFdXG4gIEEyWyM5MDM1Nl0gLS0-IEJbIzkwNDE1XVxuXHRCIC0tPiBDWyM5MDcxMV1cblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

### Part 2 - design and implementation of PostFilter

- [x] Scheduler PostFilter API #91547
- [x] Scheduler PostFilter definition #91314
- ~Default preemption plugin implementation #91426~
- [x] [postfilter-impl-1] Refactor scheduler preempt interface #92009
- [x] Expose EventRecorder to scheduler FrameworkHandle #92010
- [x] [postfilter-impl-2] Introduce a defaultpreemption PostFilter plugin #92012
- [x] [postfilter-impl-3] Register and enable the defaultpreemption plugin #92049
- [x] Move scheduler fake artifacts to pkg/scheduler/testing #92107
- [x] [postfilter-impl-4] Move Preempt() to defaultpreemption package. #92108
- [x] [postfilter-impl-5] Polish unit tests of defaultpreemptio plugin #92571
- [x] [postfilter-impl-6] Refactor and expose common preemption functions #92890
- [x] Remove `DisablePreemption` field from KubeSchedulerConfiguration #92892

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblx0QVsjOTE1NDddIC0tPiBCWyM5MTMxNF1cblx0IEJbIzkxMzE0XSAtLT4gQzFbIzkyMDA5IGltcGwtMV1cblx0IEJbIzkxMzE0XSAtLT4gQzJbIzkyMDEwXVxuXHQgQlsjOTEzMTRdIC0tPiBDM1sjOTIxMDddXG5cdCAgQzFbIzkyMDA5IGltcGwtMV0gLS0-IERbIzkyMDEyIGltcGwtMl1cblx0ICBDMlsjOTIwMTBdIC0tPiBEWyM5MjAxMiBpbXBsLTJdXG5cdCAgIERbIzkyMDEyIGltcGwtMl0gLS0-IEVbIzkyMDQ5IGltcGwtM11cblx0ICAgIEVbIzkyMDQ5IGltcGwtM10gLS0-IEZbIzkyMTA4IGltcGwtNF1cbiAgICAgIEMzWyM5MjEwN10gLS0-IEZbIzkyMTA4IGltcGwtNF0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0QVsjOTE1NDddIC0tPiBCWyM5MTMxNF1cblx0IEJbIzkxMzE0XSAtLT4gQzFbIzkyMDA5IGltcGwtMV1cblx0IEJbIzkxMzE0XSAtLT4gQzJbIzkyMDEwXVxuXHQgQlsjOTEzMTRdIC0tPiBDM1sjOTIxMDddXG5cdCAgQzFbIzkyMDA5IGltcGwtMV0gLS0-IERbIzkyMDEyIGltcGwtMl1cblx0ICBDMlsjOTIwMTBdIC0tPiBEWyM5MjAxMiBpbXBsLTJdXG5cdCAgIERbIzkyMDEyIGltcGwtMl0gLS0-IEVbIzkyMDQ5IGltcGwtM11cblx0ICAgIEVbIzkyMDQ5IGltcGwtM10gLS0-IEZbIzkyMTA4IGltcGwtNF1cbiAgICAgIEMzWyM5MjEwN10gLS0-IEZbIzkyMTA4IGltcGwtNF0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

### Part 3 - docs

- [x] Update KEP https://github.com/kubernetes/enhancements/pull/2054
- [x] Update k/website https://github.com/kubernetes/website/pull/22429

**Comment by zorro786** [comment]
@Huang-Wei Will `Extenders()` be ever marked deprecated?, since framework is the recommended way going forward.

**Comment by Huang-Wei** [comment]
@zorro786 not in the near future. You can even combine using framework and extenders.

If we decide to deprecate Extenders, we will for sure go through the official deprecation cycle - support it for one year or 3 releases before removing it.

**Comment by giovannifs** [comment]
Hi folks, 

I'm very interested in using the PostFilter extension point. In order to evaluate a new scheduling policy, in the past (k8s v1.9), I have developed a proof-of-concept customized scheduler by duplicating the code of the default-scheduler and customizing it according to the new policy. The preemption logic was one of the things that I have changed.

I'm trying to develop this new scheduling policy following the new Scheduling framework based on plugins. I've started working on k8s v1.18.3 (developing and testing a QueueSort plugin). As I understand, the PostFilter extension point is almost ready to be provided in the v1.19 release. I'd like to try to develop a PostFilter plugin using the current code, do you encourage me on that? Is there any specific release/commit that would be more appropriate to start developing on?

I'm not senior on go/Kubernetes, so could you point me some documentation (if it exists) that could help me to deploy the kube-scheduler configured with these new plugins?

Thank you in advance.

**Comment by damemi** [comment]
Hi @giovannifs, with the scheduling framework it is fairly simple now to write a custom scheduler with just a few lines. There is an example in the [framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#custom-scheduler-plugins-out-of-tree) as well as a working example of a scheduler (implementing a custom plugin) in this repo: https://github.com/hex108/coscheduling-plugin/blob/master/main.go

I think if you wanted to develop on the most recent code (master) that should be fine to vendor, though 1.19 code freeze is tomorrow so there should be 1.19 RC branches published soon after if you want something more consistent

**Comment by giovannifs** [comment]
Hi @damemi, thank you very much. I'll take a look on these.

**Comment by Huang-Wei** [comment]
In addition to @damemi 's comments, the SIG-Scheduling is sponsoring a sub-project called https://github.com/kubernetes-sigs/scheduler-plugins. Its primary goal is to gather 3rd party plugins and evolve in an open-source manner.

> As I understand, the PostFilter extension point is almost ready to be provided in the v1.19 release.

Yes, all work items have been completed. Once the official v1.19 release is cut, you can have the defaultpreemption plugin in place, as well as implementing your own preemption logic, such as [cross-node-preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#cross-node-preemption).

> I'd like to try to develop a PostFilter plugin using the current code, do you encourage me on that?

Sure, some companies are already proposing new plugins at https://github.com/kubernetes-sigs/scheduler-plugins. Feel free to raise an issue discussing what you like to do first, and design/implementation afterwards.

> Is there any specific release/commit that would be more appropriate to start developing on?

1.18 is a good start. And with 1.19, you will be able to implement PostFilter plugins (custom preemption for instance)

> I'm not senior on go/Kubernetes, so could you point me some documentation (if it exists) that could help me to deploy the kube-scheduler configured with these new plugins?

We have some documents here: https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/. But it may be a bit high-level. We're a bit overloaded to craft detailed step-by-step guides atm, but that's under our radar, and also any contribution is very welcome!

**Comment by giovannifs** [comment]
Hi @Huang-Wei, 

I'll read the documentation you pointed to and I'll engage in the discussions about the plugins.

Thanks.

**Comment by danielmitre** [comment]
> 1.18 is a good start. And with 1.19, you will be able to implement PostFilter plugins (custom preemption for instance)

The *defaultpreemption* was moved to **1.20.0-alpha.0** alongside with nice helpers. They will still be available on the **v1.19.0** release?

**Comment by Huang-Wei** [comment]
> The defaultpreemption was moved to 1.20.0-alpha.0 alongside with nice helpers.

That's because at some time of release `x.y` (earlier than code freeze), branch `x.y` is cut off from `master`. However, all code changes of release `x.y` still go to `master`, but they will be rebased back to branch `x.y` periodically by a script. So don't worry, all defaultpreemption logic will be available into official **1.19** release.
