### ISSUE TITLE
Update to etcd 3.4.9 in Kubernetes 1.19

### ISSUE THREAD

**Issue by jingyih** [kubernetes/kubernetes#91266]
Bump etcd version to 3.4.9 to pick up a few bug fixes, notably: 
 - Fix inconsistency between WAL and server snapshot. (https://github.com/etcd-io/etcd/pull/11888)
 - Fix a data corruption bug when etcd auth is enabled. (https://github.com/etcd-io/etcd/pull/11652)

Todo:
- [x] Update etcd client version (#92075)
- [x] Update etcd server version in Makefile under `cluster/images/etcd` (#92078)
- [x] Test and promote images from staging to prod repo (https://github.com/kubernetes/k8s.io/pull/973)
- [ ] Update default etcd server version everywhere in codebase (#92349)

/sig api-machinery
/kind feature

**Comment by jpbetz** [comment]
Thanks for doing this @jingyih. Be sure to coordinate with https://github.com/kubernetes/kubernetes/pull/91171 (cc @dims)

**Comment by dims** [comment]
+1 to get #91171 in first @jpbetz @jingyih

**Comment by tangcong** [comment]
@jingyih v3.4.8 introduces a [crash bug](https://github.com/etcd-io/etcd/pull/11924), we have to release a new version(v3.4.9) to fix it.

**Comment by jingyih** [comment]
> @jingyih v3.4.8 introduces a [crash bug](https://github.com/etcd-io/etcd/pull/11924), we have to release a new version(v3.4.9) to fix it.

Thanks! I just updated this PR to 3.4.9.

**Comment by warmchang** [comment]
Based on the series of optimizations and bug fixes, this upgrade would be cherry pick to v1.17 & v1.18 branches?

**Comment by BenTheElder** [comment]
I'm also very interested in the --unsafe-no-fsync functionality for some of our CI, but I believe that landed after the most recent release tag.
