### ISSUE TITLE
Port to the illumos Operating system (Master Issue)

### ISSUE THREAD

**Issue by Toasterson** [kubernetes/kubernetes#91570]
This is the master Issue to track my porting effort to the illumos operating system and to allow me to ask questions about things in kubernetes.

The following things are part of this effort:
- [ ] Modify build tags to allow compilation #91572
- [ ] Update Vendor with upstream fixes
  - [ ] github.com/moby/term
- [ ] Update build system to recognize illumos as build host. #91573
- [ ] Fix SO_REUSEPORT issue on illumos or check if we can leave that out on illumos

**Comment by Toasterson** [comment]
Unfortunately there is no porting sig so I have to guess which one. As most of these changes are to make it possible for illumos based nodes I'll contact the node sig. Please let me know if any other SIGs need to be added.

/sig node

**Comment by neolit123** [comment]
hi, before doing work we need an official stance from SIG Release whether this is a OS that the project wishes to support.

you can ask in #sig-release on k8s slack.

/remove-sig node
/sig release

**Comment by ehashman** [comment]
It looks like it was discussed in the [2020-06-16 Release](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#bookmark=id.gzcu39lyo36s) and [2021-07-02 Architecture](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#bookmark=kix.p4f81sc201dp)  meetings but there was no agreement to take on support for this.

This could change in the future, but for now, I'd like to close this issue since it's on our backlog and we don't have clear agreement to work on it.

/close

**Comment by Toasterson** [comment]
@ehashman It is only the 24.06.2021 so the Discussion on 2021-07-02 has not happened yet.

**Comment by imheresamir** [comment]
Please reopen this issue

**Comment by BenTheElder** [comment]
There's no 2021-07-02 meeting, that's a typo and won't ever be happening (SIG arch does not meet on fridays), the meeting happened on 2020-07-02, which is what the text links to.

**Comment by Toasterson** [comment]
Ah, ok Is the document limited access? I get the page to ask for access via Google drive. I sent the Request and included that the Document is linked on Github.

**Comment by BenTheElder** [comment]
Yeah it probably is limited access though, in general documents are at least supposed to be available to all members of kubernetes-dev@googlegroups.com (which is open to join without an invite) and any relevant SIGs' group mailinglists, some organizations set a gsuite policy to only allow sharing to specific groups and users instead of the entire internet unfortunately. Most likely if you join and try again you'll have access, FWIW.

**Comment by BenTheElder** [comment]
https://groups.google.com/g/kubernetes-dev

Meeting recordings are also on YouTube (public Access) 

https://youtu.be/GxGX98IuNHc

https://youtube.com/playlist?list=PL69nYSiGNLP2m6198LaLN6YahX7EEac5g

**Comment by mrbobbytables** [comment]
I flipped the doc so that anyone on the internet can view - as an FYI most of the kubernetes google docs require membership to the [kubernetes-dev](https://groups.google.com/g/kubernetes-dev) mailing list to be able to comment/edit.

**Comment by Toasterson** [comment]
Ok, so I was able to piece together some of the process. There was an effort by @dims to Standardize new platform porting and integration and that is still ongoing IIRC

For now I have very little time to look into this and do the work here. So I will keep not contest the closing and see to review revive Kubernetes on illumos with a strategy that works for me and which interface boundry that works. With Api server also getting an interface boundry that is much more interesting to me, as mostly I want compatibility with the toolset not doing things exactly the same way.
