### ISSUE TITLE
Remove generators from kubectl commands

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#93100]
As @soltysh suggests:
kubectl command are going to get rid of the dependency to the generators, and ultimately remove them entirely.
The main goal is to simplyfy the use of kubectl command.
This is already done in `kubectl run`, see https://github.com/kubernetes/kubernetes/pull/87077 and https://github.com/kubernetes/kubernetes/pull/68132.

Example PR that removes generators : https://github.com/kubernetes/kubernetes/pull/91127

Related files: 
- [x]  `pkg/cmd/create/create_rolebinding.go` (@zhouya0, #92956)
- [x]  `pkg/cmd/create/create_clusterrolebinding.go` (@aubm , #91127)
- [x]  `pkg/cmd/create/create_deployments.go` (@aubm, #90676)
- [ ]   `pkg/cmd/create/create_namespaces.go` (@CaiyuhangC, https://github.com/kubernetes/kubernetes/pull/96556)
- [x]   `pkg/cmd/create/create_priorityclass.go` (@aubm)
- [x]   ` pkg/cmd/create/create_pdb.go` (@sachinkumarsingh092, https://github.com/kubernetes/kubernetes/pull/97429)
- [x]   `pkg/cmd/create/create_quota.go` (@SaiHarshaK, https://github.com/kubernetes/kubernetes/pull/95265)
- [x]   `pkg/cmd/create/create_configmap.go` (@lauchokyip https://github.com/kubernetes/kubernetes/pull/97981)
- [ ]   `pkg/cmd/create/create_secret.go` (@lauchokyip, https://github.com/kubernetes/kubernetes/pull/98614)
- [x]   `pkg/cmd/create/create_service.go` (@Git-Jiro, https://github.com/kubernetes/kubernetes/pull/95256)
- [x]   `pkg/cmd/create/create_serviceaccount.go` (@ramnar, https://github.com/kubernetes/kubernetes/pull/96492)
 
- [x]   `pkg/cmd/autoscale/autoscale.go` (@SataQiu, #92998)
- [ ]   `pkg/cmd/expose/expose.go` (@lauchokyip)
- [ ]    `pkg/cmd/run/run.go` (@soltysh )

/cc @aubm @rahulkrishnanfs @SataQiu

**Comment by soltysh** [comment]
I'm going to assign this to myself, since I'm overlooking this entire effort and this will allow me easier to track it :) 
Thanks @zhouya0

**Comment by jay-owen** [comment]
Hi, can I help with this issue?

**Comment by kshitijcode** [comment]
@soltysh Can I assign this issue to me  if its not taken ?

**Comment by JeremyShih** [comment]
Can I take one of them if it's not finished yet?
Like `pkg/cmd/create/create_namespaces.go`

**Comment by surajrana93** [comment]
Need help on one of those?

**Comment by BarakStout** [comment]
> Need help on one of those?

I would like to help as well

**Comment by ramnar** [comment]
@zhouya0 - I would like to work on pkg/cmd/create/create_serviceaccount.go. Can you please assign me that

**Comment by zhouya0** [comment]
> @zhouya0 - I would like to work on pkg/cmd/create/create_serviceaccount.go. Can you please assign me that

Sure

**Comment by aubm** [comment]
@zhouya0 pkg/cmd/create/create_priorityclass.go done 🙂

**Comment by sachinkumarsingh092** [comment]
Hi @zhouya0.
I'm new to Kubernetes and would like to work on `pkg/cmd/create/create_secret.go`. Can you please assign me that?

**Comment by ramnar** [comment]
@zhouya0  - Can you review the above pull request? Also I would like to work on create_service. Can you please assign me that

**Comment by ramnar** [comment]
@zhouya0  - create_service was already done by this https://github.com/kubernetes/kubernetes/pull/95256 . I have spent lot of time to implement it and test it and finally realised that someone has already done it. Not sure how I was having such a stale master copy . Can you mark this as complete. I would like to work on expose feature

**Comment by ramnar** [comment]
@aubm - Can I work on configmap if you permit ? That will be relatively easy for me to get started

**Comment by aubm** [comment]
Sure @ramnar go ahead!

**Comment by zhouya0** [comment]
> @zhouya0 - create_service was already done by this #95256 . I have spent lot of time to implement it and test it and finally realised that someone has already done it. Not sure how I was having such a stale master copy . Can you mark this as complete. I would like to work on expose feature. Can you assign me that one

Sorry for that. And by the way, if you have done the PR, please ask for cli approvers to get it merged.

**Comment by sachinkumarsingh092** [comment]
@zhouya0 `pkg/cmd/create/create_secret.go` seems a little complex for a first issue since it has 3 parts for `secret docker-registry` , `secret generic` and `secret tls`. Can you instead assign me a simpler one? `pkg/cmd/create/create_pdb.go` seems to be relatively easier. Can I have a go @aubm?

**Comment by aubm** [comment]
No problem @sachinkumarsingh092 go ahead 🙂

**Comment by Aut0R3V** [comment]
Hey anything I can do here

**Comment by lauchokyip** [comment]
Hey @sachinkumarsingh092 can I work on `create_secrete.go`?

**Comment by lauchokyip** [comment]
Hey @ramnar , Can I work on `create_configmap.go`?

**Comment by sachinkumarsingh092** [comment]
@lauchokyip yeah, sure. Go ahead :)

**Comment by lauchokyip** [comment]
@sachinkumarsingh092 Thanks

**Comment by lauchokyip** [comment]
If anyone wanna on work `create_secret.go` please go ahead, I will work on `create_configmap.go` first

**Comment by rikatz** [comment]
@zhouya0 as @ramnar is out of bandwidth @lauchokyip will work on `pkg/cmd/create/create_configmap.go`

Also, `pkg/cmd/create/create_pdb.go` is also done with PR #97429

**Comment by lauchokyip** [comment]
Finished `create_configmap.go`, will take `create_secret.go` :)

**Comment by soltysh** [comment]
I'll take the run bits, since there's a few tricky bits there and I'm also cleaning deprecated flags there.

**Comment by lauchokyip** [comment]
`expose.go` is still available if anyone wanna tackle it :)

**Comment by Aut0R3V** [comment]
Sure I'd like to work on it

**Comment by lauchokyip** [comment]
will take `expose.go` next :)

**Comment by almas33** [comment]
Hi @lauchokyip are you working on `expose.go` ?

**Comment by lauchokyip** [comment]
@almas33 , you can take it if you want 👍🏼

**Comment by rikatz** [comment]
@almas33 thanks for taking this

Once ready please mark me in the PR for review :)

**Comment by lauchokyip** [comment]
@almas33 any progress :) ?

**Comment by almas33** [comment]
@lauchokyip ,sorry I was working on another issue and currently exams are going on.
Though I have planned this after exams but you can work if you want.

**Comment by rikatz** [comment]
@almas33 I guess we can wait until your exams are over :)

**Comment by lauchokyip** [comment]
yup @almas33 , take your time. 👍🏼

**Comment by BLasan** [comment]
@rikatz @lauchokyip Can I take up `run.go` ?

**Comment by rikatz** [comment]
@BLasan I need to take a look :) Right now I'm with a bunch of other things to verify and review, but hopefully we will have a process for the internalization PRs and I'll open a new issue with this set for new contributors.

Thanks for your interest in contributing

**Comment by BLasan** [comment]
@rikatz Can I work on `run.go` ?

**Comment by rikatz** [comment]
@BLasan I guess run.go is already done. Let me see where else do we have generators on the code base

**Comment by lauchokyip** [comment]
Since @almas33 is not getting back to me, if anyone is ready to work on it and submit a PR, please feel free to comment and do so! Thank You

**Comment by Git-Jiro** [comment]
Hi!
If i see this correctly then only expose.go needs some attention?

I can take a look at that one.

**Comment by lauchokyip** [comment]
Hi @Git-Jiro , yea @almas33  `expose.go` here (https://github.com/kubernetes/kubernetes/pull/99891) and he needs some. It would be great if you can help reviewing the PR and provide him some guidance

**Comment by lauchokyip** [comment]
Given the size of the PR for `expose.go`, I don't think this should be a good first issue.
