### ISSUE TITLE
1.19 Action Items Umbrella Issue

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/kubernetes#93430]
This is a rolling list of issues, topics and action items that come up through the end of the 1.19 cycle.

**WEEK OF July 20**

**In Progress**
- [ ] Vanity Domain Flip | rep: @justaugustus 
Will not merge until we have thumbs up from Linus Arver that all is healthy and this latest flip wont need rolled back.

**To do**
- [ ] get a test in place that would have caught [#93194](https://github.com/kubernetes/kubernetes/issues/93194) ("kube-scheduler and kube-controller-manager fails health checks on insecure port on 1.16.13") before 1.16.13 release

**Bundle of action items pitched by @liggitt** 
- [ ] _formalize in policy and enforce going forward_: require contact information / list email notifications for all jobs that are not on the informing/blocking dashboards the release team looks at
- [ ]  _formalize in policy and enforce going forward_: stop running jobs that are non-informing + non-blocking + 100% failing (for O(weeks)), and notify ^ contact/list
- [ ]  open issues with clear owners targeting improving some of our slowest tests ([e.g.](https://github.com/kubernetes/kubernetes/issues/87807#issuecomment-662532855) )
- [ ] open issues with clear owners targeting deduping some of our presubmits and/or moving some to postsubmit/periodic ([e.g.](https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662178519), see [also](https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662699230))

- [ ] **Related to previous item:** Given [CI Signal subproject](https://github.com/kubernetes/sig-release/issues/966) progress, and the need for SIGs to consistently fix the problems they have in place (testing flakes), draft a summary/planning doc based on comments on this topic to date. Include: Values, goals and priorities, Blockers/risks, unresolved questions, needs, what needs to be formalised (see :arrow_up:) vs. what is open to negotiation. | @LappleApple to draft
      - Note via @BenTheElder: "Items around changing what tests run and requirements for running are explicitly in scope for SIG Testing. We've already moved on some of this."

- [ ] Need interlock with sig-scalability regarding upgrade to new go versions: releng, sig-scalability AIs | reps: @justaugustus + @LappleApple 

- [ ] Decide how to present/promote Stephen's three hours of new content (videos) related to Go upgrades | @justaugustus 

- [ ] Decide how to present/promote Veronica's Bazel notes | @Verolop
