### ISSUE TITLE
Avoid moving pods out of unschedulable status unconditionally

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#94009]
Currently we unconditionally move pods out of unschedulable status when an event happens. However, we can optimize this by setting some conditions for each event to avoid unnecessarily doing that:

1) PV, PVC, StorageClass or CSINode add/update: move only pods with a PVC.
2) Service add/update: only if ServiceAffinity plugin is enabled in one of the profiles
3) Node add/update: test the pods against the [kubelet admission logic](https://github.com/kubernetes/kubernetes/blob/3b5aedcef43fa01538518ecbc7de369b27ecd191/pkg/kubelet/lifecycle/predicate.go#L224), this include: NodeAffinity, NodeName NodePorts, NodeResources and TaintsTolerations filters.
4) Pod delete: keep it as is (spreading or affinity constraints must be tested, which is expensive to do)

This is necessary to avoid wasting scheduling cycles.

Related proposal: https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit

/sig scheduling
/assign @adtac

**Comment by Huang-Wei** [comment]
/cc @denkensk 

I'm thinking of if we can amplify the scope: which is to say, not only enable/disable moving **(all)** pods, but also provides mechanics to let plugins notify the scheduler framework which **particular** pods should be moved.

This would benefits in @denkensk 's coscheduling implementation to move the preceding (N-1) pods back to activeQ when the Nth pod comes - which satisfies the "minAvaialbe" requirement. Moreover, this would help in getting rid of flushing 
 pods back to activeQ #87850.

**Comment by ahg-g** [comment]
The suggestion is not to enable/disable moving all pods in all events, this is only true for the Service events. For the other two, node and volumes, we will test each pod and move the ones that pass the condition.

I agree that our proposal of integrating this with filters/permit plugins is more generic, but it adds a lot of complexity and potential for bugs, so we need to be careful with that I think.

**Comment by ahg-g** [comment]
One approach could be to start simple, validate and establish a reference point in terms of perf improvements, and then migrate to something more generic. The more generic approach will not be more performant than what is proposed in this issue.

**Comment by Huang-Wei** [comment]
> I agree that our proposal of integrating this with filters/permit plugins is more generic, but it adds a lot of complexity and potential for bugs, so we need to be careful with that I think.

Yes, filters/permit runs in the critical path, and move Pods isn't a lock-free operation. What I want to say is during the design/implementation of this proposal, keep it in mind that plugins may need to actively "suggest" moving particular Pods back to activeQ.

> One approach could be to start simple, validate and establish a reference point in terms of perf improvements, and then migrate to something more generic.

Agree.

**Comment by ahg-g** [comment]
> Yes, filters/permit runs in the critical path, and move Pods isn't a lock-free operation. What I want to say is during the design/implementation of this proposal, keep it in mind that plugins may need to actively "suggest" moving particular Pods back to activeQ.

Right, we already designed the interface for such a potential eventuality: https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit.

**Comment by neolit123** [comment]
just fixing double "moving" in title:
/retitle Avoid moving pods out of unschedulable status unconditionally

**Comment by alculquicondor** [comment]
@Huang-Wei what is the current plan?
Is it to do the entire proposal in "Efficient Requeuing" doc or just the minimal checks proposed in the issue?

**Comment by Huang-Wei** [comment]
@alculquicondor I plan to fix the problems mentioned in this issue, but not entirely following the logic mentioned here. For example, it's inappropriate to move a Pod with PVC once a CSINode happens - the Pod may fail due to a reason irrelevant to its PVC.

What I'm proposing is more aligned with the Google doc, but there are 2 major distinctions:

- I'm not associating the interface to a particular extension point - the EventsToRegister is more a general hook instead of semantically associated with a particular scheduling phase.
- I'm not going to pass the changed event object to let users decide whether to move or not - that'd increase the latency, also impose an extra burden on plugin developers.

---

Fixing this issue is the minimum goal I can promise in 1.21, but in the future, we may provide other interfaces like enable users to proactively move Pods inside scheduling queue.

**Comment by ahg-g** [comment]
> it's inappropriate to move a Pod with PVC once a CSINode happens - the Pod may fail due to a reason irrelevant to its PVC.

That is true, but this is the case right now, not something new this issue is proposing to do. This issue is proposing to address the obvious moves that we can avoid with minimal complexity, which will also likely give us the most bang for the buck.

Do you have a more detailed proposal for what you are planning to do?

**Comment by Huang-Wei** [comment]
> Do you have a more detailed proposal for what you are planning to do?

Yes, the code is almost complete - PR1 (#98041) and PR2 (#98241), I will send out another PR later to use ServiceAffinity as an example to show case how it works in details.

Basically, the plugin can implement an optional interface called `EnqueueExtensions` and return a number of ClusterEvents that a Pod failed by that plugin can be made re-schedulable, and also upon a Pod's scheduling failure, we store the "failed plugin" into `PodInfo`, so that upon moving Pods in the internal queues, we're able to tell whether the Pod's failed plugins are associated/registered with the current event, and hence perform efficient enqueuing.

**Comment by Huang-Wei** [comment]
@ahg-g You can wait late today or tomorrow when the 3rd PoC PR will be ready, and it'd show you a whole picture.

**Comment by Huang-Wei** [comment]
FYI: the 3rd PR to showcase how it works: PoC: ServiceAffinity enqueue #98248.

**Comment by alculquicondor** [comment]
Do we have a benchmark we can use to prove that the changes are having a positive impact?

**Comment by alculquicondor** [comment]
Also, are we planning to keep the existing checks that some events have?

**Comment by Huang-Wei** [comment]
> Do we have a benchmark we can use to prove that the changes are having a positive impact?

Will do that.

> Also, are we planning to keep the existing checks that some events have?

Yes, they will be kept.

**Comment by alculquicondor** [comment]
I think we should still do 3:

> Node add/update: test the pods against the kubelet admission logic, this include: NodeAffinity, NodeName NodePorts, NodeResources and TaintsTolerations filters.

or even just NodeAffinity+TaintsTolerations

The problem is that just one node is being and potentially we are retrying all pending pods. And this means that we are testing all Nodes for each of those Pods.

**Comment by Huang-Wei** [comment]
> I think we should still do 3:

I think we can do sth. like this: upon a Node Add/Update, for each unschedulablePodInfo, only verify if the Pod can pass NodeAffinity/NodePorr/etc. filtering logic when the Pod failed by NodeAffinity/NodePort/etc. plugin.
In this way, we can save cycles for Pods not failed with NodeAffinity/NodePort.

**Comment by Huang-Wei** [comment]
Latest status of this issue:

- Interface and implementation in framework side
    - [x] Surface info of failed plugins during PerFilter, Filter and Permit [#98041]
    - [x] Store a cluster event to plugin map in SchedulerQueue [#98241]
- Plugin implementation and perf evaluation.
    > The goal is to implement `EventsToRegister()` for all in-tree PreFilter/Filter/Permit plugins (default [enabled plugins](https://github.com/kubernetes/kubernetes/blob/ed978f6549d258edc890b508e7a4c830800dd44c/pkg/scheduler/algorithmprovider/registry.go#L78-L106) + disabled plugins (like ServiceAffinity)).

    |            Plugin(s)           | Owner | PR | Status |      Comments      |
    |:------------------------------:|:-----:|:--:|:------:|:------------------:|
    | noderesources                  | @Huang-Wei      |    |        |                    |
    | nodeports                      |       |    |        |                    |
    | podtopologyspread              |       |    |        |                    |
    | interpodaffinity               |       |    |        |                    |
    | volumebinding                  |       |    |        |                    |
    | nodeaffinity                   |       |    |        |                    |
    | nodeunschedulable, nodename    |       |    |        |                    |
    | tainttoleration                |       |    |        |                    |
    | nodevolumelimits.*             |       |    |        |                    |
    | volumerestrictions, volumezone |       |    |        |                    |
    | serviceaffinity                |  @Huang-Wei      |    |        | non-default plugin |
    | nodelabel                      |       |    |        | non-default plugin |

**Comment by Huang-Wei** [comment]
/help

Some tips/notes for contributors who are interested:

- please dedicate some time to the item(s) you claimed as code freeze is around the corner, we'd like to finish the above items as early as possible
- #99922 works as a sample you can refer, basically you need to think about which events can make the unschedulabed Pods failed by the specified plugins schedulable, and specify the reasons. Also give a benchmark test result proving it.
- to design a desired benchmark test, you _may_ need to try the "churn operator", which means you need to rebase #98900 locally (unless they get merged)
- if you meet timeout issue frequently during running a 5000Nodes test, you can work it around by rebasing #96696

**Comment by pacoxu** [comment]
I would like to take ‘ tainttoleration’ to learn something about scheduling plugins.

**Comment by Huang-Wei** [comment]
> I would like to take ‘ tainttoleration’ to learn something about scheduling plugins.

@pacoxu Thanks! I updated the tips to include a [script](https://gist.github.com/Huang-Wei/1d1d16ec0de0d23ce8ed2a2448a44c4d) to automate running the benchmark tests multiple times.

**Comment by KofClubs** [comment]
I claim "nodeports" and shall learn about it firstly. 😊

**Comment by tanjing2020** [comment]
Can I try to deal with the "nodeaffinity" plugin？

**Comment by yuzhiquan** [comment]
I would like take "podtopologyspread" plugin.

**Comment by Jerry-Ge** [comment]
Can I take `nodeunschedulable, nodename` ?

**Comment by cofyc** [comment]
@Huang-Wei I can take `volumebinding` plugin.

**Comment by whypro** [comment]
Can I take `volumerestrictions, volumezone`?

**Comment by wzshiming** [comment]
Can i take `nodelabel`?

**Comment by pacoxu** [comment]
> > I would like to take ‘ tainttoleration’ to learn something about scheduling plugins.
> 
> @pacoxu Thanks! I updated the tips to include a [script](https://gist.github.com/Huang-Wei/1d1d16ec0de0d23ce8ed2a2448a44c4d) to automate running the benchmark tests multiple times.

@Huang-Wei 
I opened #99936 and will add testcase and test result tommorrow.

**Comment by pravarag** [comment]
I would like to take on `interPodAffinity` @Huang-Wei

**Comment by minbaev** [comment]
I would like to look at `nodelabel` @Huang-Wei

**Comment by Huang-Wei** [comment]
https://github.com/kubernetes/kubernetes/issues/94009#issuecomment-792354461 updated with proper owners. Thanks!

Please assign the reviewer to me when your PR is ready.

/remove-help

**Comment by ahg-g** [comment]
Wei, there were followups from https://github.com/kubernetes/kubernetes/pull/98241, are we tracking them somewhere?

**Comment by Huang-Wei** [comment]
> Wei, there were followups from #98241, are we tracking them somewhere?

@ahg-g the only followup is https://github.com/kubernetes/kubernetes/pull/98241#issuecomment-777100874. I will work on that. Let me know if any other followup I missed.

**Comment by ahg-g** [comment]
> > Wei, there were followups from #98241, are we tracking them somewhere?
> 
> @ahg-g the only followup is [#98241 (comment)](https://github.com/kubernetes/kubernetes/pull/98241#issuecomment-777100874). I will work on that. Let me know if any other followup I missed.

sg, can you open an issue to track that unless you have an open PR.

**Comment by Huang-Wei** [comment]
> sg, can you open an issue to track that unless you have an open PR.

Sure, create two issues tracking the follow-ups:

- [ ] sched: cleanup clusterEventReg from pkg/scheduler/internal/queue/events.go [#99966]
- [ ] sched: requeue optimization upon Node Add/Update [#99968]

**Comment by KofClubs** [comment]
I submitted a PR ( #100004 ) for NodePorts, not yet tested.
I shall test it this week.

**Comment by Huang-Wei** [comment]
After discussion with @ahg-g , due to 1.21 code freeze (today), we decided to postpone merging most of the opening PRs here. Apologize for that - we'd better not rush to avoid regressions. So priority your time on the on-going PRs, we will still review them, just take your time :)

**Comment by pacoxu** [comment]
Use https://github.com/Huang-Wei/k8s-sched-perf-stat to convert the json files to table. 👍

**Comment by adtac** [comment]
>https://github.com/Huang-Wei/k8s-sched-perf-stat

That's a really useful tool @Huang-Wei, thanks so much for writing that!

**Comment by alculquicondor** [comment]
oh bummer.
I would have liked at least serviceaffinity to go in.

**Comment by alculquicondor** [comment]
Actually, to get rid of the reaction to service changes... all plugins would have to opt-out, so nvm.

**Comment by alculquicondor** [comment]
That wouldn't qualify for codefreeze though.

**Comment by Huang-Wei** [comment]
> That wouldn't qualify for codefreeze though.

Nvm then :)

**Comment by ahg-g** [comment]
We should simply not register for service updates at all if ServiceAffinity is not configured, which is the default.

**Comment by Huang-Wei** [comment]
> We should simply not register for service updates at all if ServiceAffinity is not configured, which is the default.

Probably not a great idea to totally disable the registration, as an out-of-tree plugin may choose to respond to Service events.

**Comment by ahg-g** [comment]
We need to find a way for external plugins to register events because we will remove this registration once the plugin is deprecated.

**Comment by Huang-Wei** [comment]
> We need to find a way for external plugins to register events because we will remove this registration once the plugin is deprecated.

Yes, also should take CRD into consideration. _Probably_ dynamic informer.

**Comment by ahg-g** [comment]
I still think we should disabled services event handlers when the plugin is not registered. If an external plugin is using it, then they could enable the service affinity filter plugin with an empty affinity labels or patch event handlers until we figure out a way for external plugins to register extra events.

btw, do you know of any external plugins that actually rely on service events?

**Comment by Huang-Wei** [comment]
> I still think we should disabled Service event handlers when the plugin is not registered. If an external plugin is using it, then they could enable the service affinity filter plugin with an empty affinity labels or patch event handlers until we figure out a way for external plugins to register extra events.

That's fair, and I can work on this, adding some comments caveating this is a temporary workaround.

> btw, do you know of any external plugins that actually rely on service events?

I'm not aware so far.

**Comment by alculquicondor** [comment]
tbh, I would say plugins depending on services is an antipattern, given the existence of pod affinity.

Probably some CRDs might make sense for specialized plugins.

**Comment by ahg-g** [comment]
@Huang-Wei we should add a metrics to track the efficiency of the solution. The metric would track the number of pods that were not put back into the queue broken down by plugin and even type for example.

**Comment by Huang-Wei** [comment]
> we should add metrics to track the efficiency of the solution. The metric would track the number of pods that were not put back into the queue broken down by plugin and even type for example.

SG. I compiled a list to include on-going and to-do items here #100347.

**Comment by Huang-Wei** [comment]
> I would like take "podtopologyspread" plugin.

@yuzhiquan Are you still working on this?

**Comment by ahg-g** [comment]
@Huang-Wei did we have PRs for number 2 and number 3?

**Comment by yuzhiquan** [comment]
> @Huang-Wei did we have PRs for number 2 and number 3?

@ahg-g  Number3 `podtopologyspread` already merged in #100853

**Comment by ahg-g** [comment]
I am asking about the two points from the four mentioned in the description of this issue: https://github.com/kubernetes/kubernetes/issues/94009#issue-679258867

**Comment by yuzhiquan** [comment]
> I am asking about the two points from the four mentioned in the description of this issue: [#94009 (comment)](https://github.com/kubernetes/kubernetes/issues/94009#issue-679258867)

Oops, misunderstanding, ignore me.

**Comment by Huang-Wei** [comment]
> @Huang-Wei did we have PRs for number 2 and number 3?

- number 2: #100357 mitigated the problem. In short, what #100357 did includes two parts: one part is to remove Service event from default list so that **only Pods failed by a plugin** (e.g., ServiceAffinity) which explicitly are interested in Service events **can be moved**; the other part is to implement EventsToRegister() in ServcieAfffinity plugin. But that doesn't prevent the internal processing cycles like going through the unschedulabe pods and verify whether each is failed by that plugin, so it's a mitigation.
PR #101394 will fix this problem thoroughly.
- number 3: #100049

**Comment by ahg-g** [comment]
> number 3: #100049

ah, yeah, I knew we worked on that in the previous release, lol. Thanks.
