### ISSUE TITLE
scheduler_perf: meta issue to track multiple issues

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#94285]
/sig scheduler
/cc @ahg-g 
/kind feature
/assign
/milestone v1.20

The following features will only be added to the new framework (proposed in https://github.com/kubernetes/kubernetes/issues/93117, implemented in https://github.com/kubernetes/kubernetes/pull/93252), which will replace the old benchmarking framework in `test/integration/scheduler_perf`.

- [x] https://github.com/kubernetes/kubernetes/issues/93117 - the framework itself.

- [x] https://github.com/kubernetes/kubernetes/issues/89036 - benchmark preemption.

- [ ] https://github.com/kubernetes/kubernetes/issues/94009 - benchmark impact of unschedulableQ.

- [ ] https://github.com/kubernetes/kubernetes/issues/93760 - support multiple node labelling strategies. Currently, we support three labelling strategies, but no two strategies can be used together even though it makes sense to do so sometimes.

- [ ] https://github.com/kubernetes/kubernetes/issues/93793 - add a sleep timer op. This will be useful in simulating workloads that require some sort of time-based synchronisation.

- [ ] https://github.com/kubernetes/kubernetes/issues/94601 - add a delete nodes op. Useful in benchmarking autoscaler-like behaviour.

- [ ] https://github.com/kubernetes/kubernetes/issues/93792 - allow users to specify default pod and node specs. Reduces config toil.

- [x] https://github.com/kubernetes/kubernetes/issues/93795 - minor QoL improvement.

- [ ] https://github.com/kubernetes/kubernetes/issues/93794 - minor QoL improvement.

- [ ] https://github.com/kubernetes/kubernetes/issues/94404 - minor QoL improvement.

- [x] https://github.com/kubernetes/kubernetes/issues/94665 - minor QoL improvement.

Other places where the framework might help:

- [ ] https://github.com/kubernetes/kubernetes/pull/88389

- [ ] https://github.com/kubernetes/kubernetes/issues/93505#issuecomment-684892448

**Comment by adtac** [comment]
/sig scheduling

:)

**Comment by sanposhiho** [comment]
/remove-lifecycle rotten

I'm assined to most of issues listed here. So, I take this issue over. 

/assign

**Comment by sanposhiho** [comment]
Now, there are 4 PRs for scheduler_perf 

- [ ] https://github.com/kubernetes/kubernetes/pull/104716
- [ ] https://github.com/kubernetes/kubernetes/pull/101854
- [ ] https://github.com/kubernetes/kubernetes/pull/101835
- [ ] https://github.com/kubernetes/kubernetes/pull/101799
