### ISSUE TITLE
Umbrella: scheduler component config v1beta2

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95446]
/sig scheduling

- [ ] Deprecate some Plugins #94008
- [ ] Make Plugin names fully qualified #95445
- [ ] Remove backwards compatibility hacks:
  - [ ] Defaulting Type to List when non empty list (PodTopologySpread) from #95048

/assign

**Comment by alculquicondor** [comment]
cc @hprateek43

**Comment by adtac** [comment]
@alculquicondor could you mark the things from https://github.com/kubernetes/kubernetes/pull/99597 as completed (see PR description)

**Comment by alculquicondor** [comment]
Done, thanks for the heads up

**Comment by ahg-g** [comment]
Did we update the docs?

**Comment by alculquicondor** [comment]
I'll take that

**Comment by alculquicondor** [comment]
kubernetes/website#28839
