### ISSUE TITLE
API priority and fairness: beta graduation checklist

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#96119]
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness

- [x] types alpha -> beta: https://github.com/kubernetes/kubernetes/pull/96213
- [x] update docs to say APF is on by default + docs alpha -> beta: https://github.com/kubernetes/website/pull/24975
- [x] E2E test to make sure APF works under request drown-out: https://github.com/kubernetes/kubernetes/pull/96124 
- [x] fix data races in tests: https://github.com/kubernetes/kubernetes/pull/96244
- [x] metric labels snake_case in docs: https://github.com/kubernetes/website/pull/24905
- [x] switch to snake_case in metric labels: https://github.com/kubernetes/kubernetes/pull/96236
- [x] fix a different data race + don't leak goroutines in tests: https://github.com/kubernetes/kubernetes/pull/96229
- [x] mitigate wind-up problem: prevent queue virtualStart lag: https://github.com/kubernetes/kubernetes/pull/95986
- [x] production readiness review: https://github.com/kubernetes/enhancements/pull/2049
- [x] use PostStartHook to run background APF goroutines: https://github.com/kubernetes/kubernetes/pull/95371
- [x] add `apiserver_dropped_requests_total` metric: https://github.com/kubernetes/kubernetes/pull/93877
- [x] E2E test to test request categorisation: https://github.com/kubernetes/kubernetes/pull/94925

/cc @ahg-g @MikeSpreitzer @yue9944882 @lavalamp @deads2k @tkashem 
/sig api-machinery
/kind feature

**Comment by ahg-g** [comment]
lets get https://github.com/kubernetes/kubernetes/pull/94925 checked off the list :)

**Comment by ahg-g** [comment]
let get https://github.com/kubernetes/kubernetes/pull/93877 checked off as well

**Comment by MikeSpreitzer** [comment]
Bug fixes we need in beta:
- #96244 fix races recently introduced in test
- #96236 fix metric labels
- https://github.com/kubernetes/website/issues/24895 fix doc of metric labels

**Comment by adtac** [comment]
Closing as fixed :)
