### ISSUE TITLE
Umbrella issue: slow/timing-out unit tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#98486]
running `make test KUBE_RACE=-race` locally, several packages have very slow unit tests, and some timed-out entirely

The default per-package timeout for `make test` is 120 seconds (which is already much longer than I would expect).

The following packages had tests that ran longer than 30 seconds on my workstation. Running tests on CI machines regularly takes 2-3x as long. Anything longer than 60 seconds should be prioritized.

cluster-lifecycle
- [x] **k8s.io/kubernetes/cmd/kubeadm/app/cmd	86.056s** (`TestRunRenewCommands` looks to be the slowest test) - https://github.com/kubernetes/kubernetes/pull/98664
- [x] k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init	56.161s - https://github.com/kubernetes/kubernetes/pull/98664
- [x] **k8s.io/kubernetes/cmd/kubeadm/app/phases/certs	120.433s (timed out, TestCreatePKIAssetsWithSparseCerts, TestUsingExternalCA, TestCreateCertificateFilesMethods are the slowest)** - https://github.com/kubernetes/kubernetes/pull/98664
- [x] k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil	38.180s - https://github.com/kubernetes/kubernetes/pull/98682
- [x] **k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade	89.649s** - https://github.com/kubernetes/kubernetes/pull/98664

apps
- [x] **k8s.io/kubernetes/pkg/controller/cronjob	61.696s** - https://github.com/kubernetes/kubernetes/pull/98691

networking
- [x] k8s.io/kubernetes/pkg/controller/endpointslice	35.619s - #98793
- [x] **k8s.io/kubernetes/pkg/controller/nodeipam	112.441s** - https://github.com/kubernetes/kubernetes/pull/98756

node
- [x] k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler	52.778s - https://github.com/kubernetes/kubernetes/issues/98495, https://github.com/kubernetes/kubernetes/pull/98595

storage
- [x] k8s.io/kubernetes/pkg/controller/volume/persistentvolume	41.215s - https://github.com/kubernetes/kubernetes/pull/98792
- [x] **k8s.io/kubernetes/pkg/controller/volume/scheduling	109.515s** - https://github.com/kubernetes/kubernetes/pull/98912
- [x] **k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler	120.434s (timed out)** - https://github.com/kubernetes/kubernetes/issues/91834, https://github.com/kubernetes/kubernetes/pull/97955 or https://github.com/kubernetes/kubernetes/pull/98915, #99174
- [x] **k8s.io/kubernetes/pkg/volume/csi	62.449s** - https://github.com/kubernetes/kubernetes/pull/98762
- [x] k8s.io/kubernetes/pkg/volume/util/operationexecutor	56.046s - https://github.com/kubernetes/kubernetes/pull/98760

api-machinery
- [x] **k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver	109.590s** - https://github.com/kubernetes/kubernetes/pull/98694
- [x] k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2	56.254s - https://github.com/kubernetes/kubernetes/pull/98694
- [x] **k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation	74.794s** - https://github.com/kubernetes/kubernetes/pull/98496#issue-comment-box
- [ ] k8s.io/kubernetes/pkg/controlplane. 240s, timeout

/sig cluster-lifecycle apps network node storage api-machinery
/triage accepted
/help

**Comment by liggitt** [comment]
Tagging specific sigs/people

- @kubernetes/sig-cluster-lifecycle @neolit123 for cluster-lifecycle
- @kubernetes/sig-apps-bugs @soltysh for cronjob
- @kubernetes/sig-network-bugs @bowei for nodeipam
- @kubernetes/sig-node-bugs @kubernetes/sig-scheduling-bugs @ahg-g @SergeyKanzhelev for node lifecycle
- @kubernetes/sig-storage-bugs @msau42 for volumes
- @kubernetes/sig-api-machinery-bugs @lavalamp @deads2k for apiserver/connrotation

As specific issues are spawned for these packages or package trees, please link them back here

**Comment by neolit123** [comment]
> The following packages had tests that ran longer than 30 seconds on my workstation. Running tests on CI machines regularly takes 2-3x as long. Anything longer than 60 seconds should be prioritized.

some package just have a lot of code.
i'm sure there are things that can be optimized, but if not, does that mean we need to reduce coverage to be under 30 seconds for a package, or split the package to comply with this rule?

**Comment by liggitt** [comment]
multi-minute-long unit tests are typically a symptom of one of the following:
* running benchmark-style tests in a unit test (e.g. https://github.com/kubernetes/kubernetes/issues/98322)
* exercising operations that involve time delays and waiting real clock times instead of using a fake clock (https://github.com/kubernetes/kubernetes/pull/93839#discussion_r468936718)
* something actually running inappropriately slowly we should fix

we should at least look at these packages to see if those are the cause

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/issues/91834 was opened for k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler

**Comment by bowei** [comment]
@robscott looks like endpointslice tests are pretty slow

**Comment by bowei** [comment]
@rahulkjoshi nodeipamcontroller

**Comment by lavalamp** [comment]
connrotation probably has something else wrong with it, but I can explain 50s of the 74s, sent #98496

**Comment by pacoxu** [comment]
I’m working on the ‘kubeadm cert’ package. @neolit123

**Comment by pacoxu** [comment]
pkiutil: optimized in #98682 by @neolit123 (which is merged)
I opened #98691 for cronjob UT.

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/volume/util/operationexecutor 56s -> 6s #98760

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/volume/csi 62s -> 30s #98762

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/controller/volume/persistentvolume 41s -> 19s #98792

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/controller/endpointslice 35s -> 13s #98793

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/controller/volume/scheduling 109s -> 24s #98912

**Comment by wzshiming** [comment]
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler  120s (timeout) -> 38s #98915

**Comment by pacoxu** [comment]
UT running timeout in my PR test: 

- //pkg/controller/volume/scheduler PASSED in 109.6s
- //pkg/controlplane:go_default_test PASSED in 152.0s
- //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test TIMEOUT in 300.1s

And I find another 3 slow test cases.

**Comment by BenTheElder** [comment]
I also noticed `pkg/controlplane`, it took 240s and timed out in a CI job I'm working on (with a 240s limit currently).

**Comment by pacoxu** [comment]
It seems all slow test cases are fixed in the list, except the newly found `pkg/controlplane`.
@liggitt 

Related PRs:  #99344 is opened for the flake.

**Comment by liggitt** [comment]
hmm, I consistently get ~15 second runtimes testing that package with -race... do you have a pointer to slow/timeout failures?

**Comment by liggitt** [comment]
if we're down to 1-2 problematic packages, I think I'll close this in favor of specific targeted issues. If you have pointers to >100 second unit test runs of packages, please open an issue for the package and tag the appropriate sig

**Comment by BenTheElder** [comment]
+1 sgtm.

thank you all!

**Comment by pacoxu** [comment]
> hmm, I consistently get ~15 second runtimes testing that package with -race... do you have a pointer to slow/timeout failures?

@liggitt I find the reason would be #39649
https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/controlplane/instance_openapi_test.go#L21-L24


`go test -race -c ./pkg/controlplane` will ignore this test case.

**Comment by liggitt** [comment]
wow... I... didn't remember that was excluding itself that way. Opened https://github.com/kubernetes/kubernetes/pull/99782 to fix or remove unit tests that don't work in race mode.
