### ISSUE TITLE
Write Read, Replace and Patch ReplicaSetScale test +3 endpoints

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#98920]
# Progress <code>[5/6]</code>

-   [X] APISnoop org-flow : [ReplicaSetScaleTest.org](https://github.com/apisnoop/ticket-writing/blob/AppsEndpoints/ReplicaSetScaleMockTest.org)
-   [X] test approval issue : [kubernetes/kubernetes#98920](https://github.com/kubernetes/kubernetes/issues/98920)
-   [x] test pr : kuberenetes/kubernetes[#98987](https://github.com/kubernetes/kubernetes/pull/98987)
-   [X] two weeks soak start date : [testgrid-link](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&include-filter-by-regex=Replicaset%20should%20have%20a%20working%20scale%20subresource)
-   [ ] two weeks soak end date : 26 Feb 2021
-   [x] test promotion pr : kubernetes/kubernetes[#99282](https://github.com/kubernetes/kubernetes/pull/99282)

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still some remaining RESOURCENAME endpoints which are untested.

with this query you can filter untested endpoints by their category and eligiblity for conformance. e.g below shows a query to find all conformance eligible untested,stable,core endpoints

```sql-mode
SELECT
  endpoint,
  -- k8s_action,
  -- path,
  -- description,
  kind
  FROM testing.untested_stable_endpoint
  where eligible is true
  and endpoint like '%ReplicaSetScale%'
  --and category = 'core'
  order by kind, endpoint desc
  limit 25;
```

```example
                endpoint                | kind
----------------------------------------|-------
 replaceAppsV1NamespacedReplicaSetScale | Scale
 readAppsV1NamespacedReplicaSetScale    | Scale
 patchAppsV1NamespacedReplicaSetScale   | Scale
(3 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#read-scale-replicaset-v1-apps)
-   [client-go - ReplicaSet](https://pkg.go.dev/k8s.io/kubernetes/test/e2e/framework/replicaset)

# The mock test

## Test outline

1.  Create a ReplicaSet with a static label

2.  Read the ReplicaSetScale

3.  Update the ReplicaSetScale

4.  Get the ReplicaSetScale to ensure it is updated

5.  Patch the ReplicaSetScale

6.  Read the ReplicaSetScale to ensure it is Patch

7.  Delete the Namespace and ReplicaSet

### Test the functionality in Go

Due to the complexity of setting up the resources for APIService we have used the current e2e test as template. It has been extended in a [new ginkgo test](https://github.com/ii/kubernetes/commit/a157574c27e0efa55d3ce2b742fb45bb451a1ecf#diff-c4323b71233a6ca89375ef859d5757a50af9bbeb842d279cdd8f7f80fc0fd882R352-R420) for review.

# Verifying increase in coverage with APISnoop

```sql-mode
select distinct  endpoint, useragent
                 -- to_char(to_timestamp(release_date::bigint), ' HH:MI') as time
from testing.audit_event
where endpoint ilike '%ReplicaSetScale%'
  -- and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
-- and useragent like 'kubectl%'
order by endpoint
limit 100;

```

```example
                endpoint                |                                                          useragent
----------------------------------------|------------------------------------------------------------------------------------------------------------------------------
 patchAppsV1NamespacedReplicaSetScale   | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] ReplicaSet Replicaset should have a working scale subresource
 readAppsV1NamespacedReplicaSetScale    | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] ReplicaSet Replicaset should have a working scale subresource
 replaceAppsV1NamespacedReplicaSetScale | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] ReplicaSet Replicaset should have a working scale subresource
(3 rows)

```

# Final notes

If a test with these calls gets merged, ****test coverage will go up by 3 points****

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture

**Comment by Riaankl** [comment]
Presented in Conformance meeting of 9 Feb 2021 and it was agreed that that method see to achieve the purpose and a PR can be created. A similar approach would be taken for the DepoymentScale endpoints.

**Comment by Riaankl** [comment]
Issue [#98920](https://github.com/kubernetes/kubernetes/issues/98920) was presented in the Conformance meeting of 9 Feb 2021 and it was agreed that that method see to achieve the purpose and a PR can be created. A similar approach would be taken for the DepoymentScale endpoints, and this issue was created for that purpose.
