### ISSUE TITLE
Write Read, Replace and Patch DeploymentScale test +3 endpoints

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#98936]
# Progress <code>[5/6]</code>

-   [X] APISnoop org-flow : [DeploymentScaleTest.org](https://raw.githubusercontent.com/apisnoop/ticket-writing/AppsEndpoints/DeploymentScaleMockTest.org)
-   [X] test approval issue : [kubernetes/kubernetes#98936](https://github.com/kubernetes/kubernetes/issues/98936)
-   [x] test pr : [kuberenetes/kubernetes#98988](https://github.com/kubernetes/kubernetes/pull/98988)
-   [x] two weeks soak start date : [testgrid-link](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&include-filter-by-regex=Deployment%20should%20have%20a%20working%20scale%20subresource&graph-metrics=test-duration-minutes)
-   [ ] two weeks soak end date : 26 Feb 2021
-   [X] test promotion pr : kubernetes/kubernetes[#99281](https://github.com/kubernetes/kubernetes/pull/99281)

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still some remaining Deployment endpoints which are untested.

with this query you can filter untested endpoints by their category and eligibility for conformance. e.g below shows a query to find all conformance eligible untested,stable,core endpoints

```sql-mode
SELECT
  endpoint,
  -- k8s_action,
  -- path,
  -- description,
  kind
  FROM testing.untested_stable_endpoint
  where eligible is true
  and endpoint like '%DeploymentScale%'
  --and category = 'core'
  order by kind, endpoint desc
  limit 25;
```

```example
                endpoint                | kind
----------------------------------------|-------
 replaceAppsV1NamespacedDeploymentScale | Scale
 readAppsV1NamespacedDeploymentScale    | Scale
 patchAppsV1NamespacedDeploymentScale   | Scale
(3 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#read-scale-deployment-v1-apps)
-   [client-go - Deployment](https://pkg.go.dev/k8s.io/kubernetes/test/e2e/framework/deployment)

# The mock test

## Test outline

1.  Create a Deployment with a static label

2.  Read the Deployment

3.  Update the DeploymentScale

4.  Get the DeploymentScale to ensure it is updated

5.  Patch the DeploymentScale

6.  Read the DeploymentScale to ensure it is Patch

7.  Delete the Namespace and Deployment

### Test the functionality in Go

Due to the complexity of setting up the resources for APIService we have used the current e2e test as template. It has been extended in a [new ginkgo test](https://github.com/ii/kubernetes/blob/7e0d468f06cbee234bbafba3e40c18618b0fccfb/test/e2e/apps/deployment.go#L1484-L1554) for review.

# Verifying increase in coverage with APISnoop

```sql-mode
select distinct  endpoint, useragent
                 -- to_char(to_timestamp(release_date::bigint), ' HH:MI') as time
from testing.audit_event
where endpoint ilike '%DeploymentScale%'
  -- and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
-- and useragent like 'kubectl%'
order by endpoint
limit 100;

```

```example
                endpoint                |                                                          useragent
----------------------------------------|------------------------------------------------------------------------------------------------------------------------------
 patchAppsV1NamespacedDeploymentScale   | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] Deployment Deployment should have a working scale subresource
 readAppsV1NamespacedDeploymentScale    | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] Deployment Deployment should have a working scale subresource
 replaceAppsV1NamespacedDeploymentScale | e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-apps] Deployment Deployment should have a working scale subresource
(3 rows)

```

# Final notes

If a test with these calls gets merged, ****test coverage will go up by N points****

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture
/area conformance

**Comment by Riaankl** [comment]
Issue [#98920](https://github.com/kubernetes/kubernetes/issues/98920) was presented in the Conformance meeting of 9 Feb 2021 and it was agreed that that method see to achieve the purpose and a PR can be created. A similar approach would be taken for the DepoymentScale endpoints, and this issue was created for that purpose.
